### ISSUE TITLE
Generic naming for ONNX model objects

### ISSUE THREAD

**Issue by tduffy000** [kubeflow/kfserving#1004]
/kind feature

**Describe the solution you'd like**
Currently in order to turn an ONNX runtime model into a servable, the file must have the name `model.onnx`, [here](https://github.com/kubeflow/kfserving/blob/ff02ea49b399565a8abd4a556c75e1fbb003a6e2/pkg/apis/serving/v1alpha2/framework_onnx.go#L25). This poses restrictions when multiple models are stored in the same directory, or with the potential extension of a `storageUri` that exists as a path over the internet. For example, the models in the ONNX [model zoo](https://github.com/onnx/models) are not directly servable under the current structure.   

It would be good to extend the specification & downloading of ONNX models to have an arbitrary name. Whether this can be specified with another field in the CRD (like Pytorch does with `modelClassName`, or via some other mechanism is an open question.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by yuzisun** [comment]
@tduffy000 this sounds reasonable to me, would you like to make a small proposal ?

**Comment by tduffy000** [comment]
It seems like the two possibilities are:

1. Use a similar CRD structure to the Pytorch model (which has [modelClassName](https://github.com/kubeflow/kfserving/blob/master/docs/samples/pytorch/pytorch.yaml#L10)) by introducing another field like `modelFileName`, if we want the user to be explicit, otherwise splitting on `/` and taking the filename should work.
2. Do some invisible moving on storage initialization by renaming the pulled in model from `someModelFile.onnx` to `model.onnx`. 

The problem with number 2 is it's not really compatible with a multiple model serving architecture, so the first option seems somewhat more intrusive but avoids any potential collisions.

**Comment by tduffy000** [comment]
@yuzisun do you have thoughts on either option above, or perhaps alternatives solutions?

**Comment by rakelkar** [comment]
I like that fact that with (2) you just point to the model and boom it works - but I really dont like the magical renaming. The filename is fixed in the framework (that has access to the storage URI) - maybe that code can lookup the model name on the path and use it (if it finds xxx.onnx) or else default to model.onnx?

**Comment by rakelkar** [comment]
aka here: https://github.com/kubeflow/kfserving/blob/2037e9c6c0e09385852af15236e939bd5f25cf71/pkg/apis/serving/v1alpha2/framework_onnx.go#L40 

how about if did path.Base(s.StorageUri) and used that if it ends in .onnx?

**Comment by tduffy000** [comment]
Right that was my thinking, just split the filename off the end and validate it.
