### ISSUE TITLE
inference time is huge difference between standalone cpu and kubeflow based (kf-serving based ) deployment

### ISSUE THREAD

**Issue by tiru1930** [kubeflow/kfserving#1014]
I have successfully deployed  Detection model on cpu ( stand alone with tf-serving and frozen graph with fastapi ) and cacluated the inference time which is 0.15 sec (average)

Same model deployed on kubeflow with kf-serving now the average inference-time is 7 seconds 

both cpu and kubeflow deployments have same amount of resource.

Why there is higher inference time in kf-serving ( for first request understood pod has to be created but what about other requests) 

Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
Dashboard v2.0.0-beta8+0.g4275399
General-purpose web UI for Kubernetes clusters
kfctl version: (use kfctl version):
kfctl_k8s_istio.v1.0.2.yaml
Kubernetes platform: minikube
Kubernetes version: (use kubectl version):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

**Comment by tiru1930** [comment]
@yuzisun  Any thoughts on this issues ?

**Comment by ellistarn** [comment]
This shouldn't be the case. KFServing creates a deployment under the hood to serve your model. Can you take a look at that deployment, compare, and then share your results:

1. Resource Requests / Limits for each deployment
2. Container Image for each deployment

You're correct that the first request should be slow, but if you set minNodes, you shouldn't be seeing a cold start.

**Comment by tiru1930** [comment]
@ellistarn  how can we set the minNodes and how can we give the resource in deployment file, can you give the reference

**Comment by yuzisun** [comment]
@tiru1930 which KFS version you are on? If you are on KFS 0.3+ we default minReplicas to 1 so it won't scale to 0 when no requests are sent to the service.

**Comment by tiru1930** [comment]
Kfserving 0.2.2

**Comment by tiru1930** [comment]
@ellistarn @yuzisun  can i do the same configuration on kf 0.2.2

**Comment by ellistarn** [comment]
Is there any way you can upgrade from 0.2.2? That release is quite old and is missing a ton of improvements. It's a pre-beta product, so we have a difficult time supporting it.

**Comment by ellistarn** [comment]
Alternatively, if I'm remember 0.2.2 correctly, you should be able to set minReplicas in
```
spec:
  default:
    predictor:
      minReplicas: 1
```

**Comment by tiru1930** [comment]
Thank you I have upgraded to 0.3

**Comment by yuzisun** [comment]
@tiru1930 are you good now?

**Comment by tiru1930** [comment]
@yuzisun , yes looks fine, but still the latency issues is there , we figured it out port-forward is causing  some delay in response, planning to move it nodePort and check

**Comment by yuzisun** [comment]
@tiru1930 ye port forward is only for testing purpose definitely can not be used in serious use case.

**Comment by yuzisun** [comment]
@tiru1930 I am closing for now please help reopen if still an issue for you, thanks!

/close
