### ISSUE TITLE
Predict request neither returns nor there is a timeout

### ISSUE THREAD

**Issue by ShilpaGopal** [kubeflow/kfserving#1037]
/kind bug

**What steps did you take and what happened:**
I am implementing serving for CRNN model. This model uses TensorFlow predict method. Prediction works fine without kfserving. When I implement kfserving.KFmodel, predict request neither returns nor there is a time out. 
The payload is less than 1mb
```
{
"roi":'base64(bytearray(image.png))'
}
```
I also have a preprocess method implemented, which does the base 64 decode, converts the image byte array to tensor, resizing, grayscale and padding. 

**What did you expect to happen:**
Any suggestion to resolve this issue is appreciated. 
Is there a reason why there is no time out for the request?

**Anything else you would like to add:**

**Environment:**

- Istio Version: NA
- Knative Version: NA
- KFServing Version:0.4.0 python sdk
- Kubeflow version:NA
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]: NA
- Minikube version:NA
- Kubernetes version: (use `kubectl version`):NA
- OS (e.g. from `/etc/os-release`): os x

**Comment by ShilpaGopal** [comment]
@yuzisun I could resolve the issue. While initializing the KFServer, the number of workers was not set and the default value is 0. By setting the workers to 1 solved the issue. 
```
kfserving.KFServer(workers=1).start([model])
```

**Comment by yuzisun** [comment]
@ShilpaGopal Looks like it is some multi-process issue? Also looks like you are running KFServer locally not on kubernetes right?

**Comment by ShilpaGopal** [comment]
Yes, @yuzisun I am running kfserving locally for development purpose and the prediction was multithreaded.

**Comment by yuzisun** [comment]
@ShilpaGopal I wondering if multi-processing is causing some weirdness in your server, but if you deploy it on KFServing the timeout is enforced on sidecar regardless of how model server behaves. Regarding using transformer and tfserving, can you mock out the call to tfserving by overwriting `predict` on transformer?  in that way you can test transformer separately.

**Comment by ShilpaGopal** [comment]
@yuzisun Thanks for your response. That's a good option to mock predict to verify transformer. With respect to timeout, I will have to verify by deploying it, looks like it won't be a problem on k8s. Thanks once again for your input. In case of any finding on local server issue will share it across.

**Comment by yuzisun** [comment]
thanks @ShilpaGopal! let us know your findings. 

/close

**Comment by pencilerazzer** [comment]
> I could resolve the issue. While initializing the KFServer, the number of workers was not set and the default value is 0
I also had the same issue. But even after initializing 2 workers , the issue didn't got resolved.
