### ISSUE TITLE
KFServing CI cluster creation permission issue

### ISSUE THREAD

**Issue by yuzisun** [kubeflow/kfserving#1044]
/kind bug

**What steps did you take and what happened:**
```
Activating service-account ...
Activated service account credentials for: [kubeflow-testing@kubeflow-ci.iam.gserviceaccount.com]
Creating cluster zng-presubmit-e2e-1042-c1d4684-6048-fc7e ...
WARNING: Newly created clusters and node-pools will have node auto-upgrade enabled by default. This can be disabled using the `--no-enable-autoupgrade` flag.
WARNING: Starting with version 1.18, clusters will have shielded GKE nodes by default.
WARNING: The Pod address range limits the maximum size of the cluster. Please refer to https://cloud.google.com/kubernetes-engine/docs/how-to/flexible-pod-cidr to learn how to op
timize IP address allocation.
This will enable the autorepair feature for nodes. Please see https://cloud.google.com/kubernetes-engine/docs/node-auto-repair for more information on node autorepairs.
Machines with GPUs have certain limitations which may affect your workflow. Learn more at https://cloud.google.com/kubernetes-engine/docs/how-to/gpus
ERROR: (gcloud.beta.container.clusters.create) ResponseError: code=403, message=Required "container.clusters.create" permission(s) for "projects/kubeflow-ci".
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by ellistarn** [comment]
@jlewi what happened to the permissions here?

**Comment by jlewi** [comment]
See testing/issues#749 permissions to create test infra in kubeflow-ci were removed.

@kubeflow/kfserving-owners you should also take a look kubeflow/testing#737 and come up with a plan for ensuring CI for your projects.

**Comment by jlewi** [comment]
@yuzisun  See comments: https://github.com/kubeflow/community-infra/pull/10#issuecomment-679459497

It looks like the project kfserving already exists which is why it can't be created and why you don't have access; I think its owned by the google.com org; probably created by @ellistarn .

It looks like there's already a kfserving-test project in kubeflow.org so you might just be able to use that. I believe you have access to it.

**Comment by yuzisun** [comment]
thanks @jlewi ! I have the access to `kfserving-test` project, currently KFServing creates a test cluster under kubeflow-ci project https://github.com/kubeflow/kfserving/blob/master/test/scripts/create-cluster.sh#L29 for running e2e tests  and looks like we need to mount a service account secret for the new project on argo workflow if moving to the `kfserving-test` project. I guess I need to get the access to kubeflow-ci project and create the secret there?

**Comment by jlewi** [comment]
@yuzisun You shouldn't need to create any new secrets. The pods should be executing with some appropriate GSA. If you look at your original bug report they are using the GSA `kubeflow-testing@kubeflow-ci.iam.gserviceaccount.com`.

So if you want that GSA to be able to create resources in your project e.g. kfserving-test  you will need to modify the IAM policy of project kfserving-test to grant the GSA kubeflow-testing@ appropriate priveleges.

So you shouldn't need to modify the CI infrastructure.

That said if for some reason you do need to modify the shared infrastructure. You can reach out to the folks listed in
https://github.com/kubeflow/internal-acls/blob/master/ci-team.members.txt

As noted in kubeflow/testing#737 CI infrastructure is maintained by 20% and you should calibrate your expectations accordingly.

**Comment by yuzisun** [comment]
@jlewi looks like I need the permission to set IAMPolicy for `kfserving-test` project.

**Comment by yuzliu** [comment]
@jlewi same for me, don't have permission to change IAM.

**Comment by jlewi** [comment]
The best thing to do would be to manage this project using GitOps.
The project is already inside the community folder.

@yuzisun Please update https://github.com/kubeflow/community-infra/tree/master/prod/namespaces/kfserving  to manage this project. Change the project and namespace to kfserving-test.

You probably want to set the deletion policy to abandon.
https://github.com/kubeflow/manifests/blob/c429076246114eaaed2e4b2592aeb8dd3b269784/gcp/v2/cnrm/gcp-services.yaml#L7

Add IAMPolicyMembers to grant the appropriate service account permissions. Add IAMPolicyMembers to grant kfserving folks permissions as needed.

We should try to avoid granting individuals OWNER permissions. We should aim to use GitOps as much as possible to leave a paper trail. 

Attaching current IAM policy for reference.
[kfserving-iam-policy.txt](https://github.com/kubeflow/kfserving/files/5126235/kfserving-iam-policy.txt)

**Comment by yuzisun** [comment]
Thanks @jlewi for the instruction. I have granted the `kfserving-ci` service account with the edit role, can you help take a look? 
https://github.com/kubeflow/community-infra/pull/12/files

**Comment by yuzisun** [comment]
we are going to migrate KFServing CI to AWS https://github.com/kubeflow/kfserving/issues/1160
