### ISSUE TITLE
gcloud build issue in KFServing CI

### ISSUE THREAD

**Issue by yuzisun** [kubeflow/kfserving#1066]
/kind bug

**What steps did you take and what happened:**
The following error happens when doing image build step on the KFServing argo CI workflow, seems starting to happen recently.
```
Activating service-account
Activated service account credentials for: [kubeflow-testing@kubeflow-ci.iam.gserviceaccount.com]
Copy source to GOPATH
Creating temporary tarball archive of 168 file(s) totalling 1.4 MiB before compression.
Uploading tarball of [.] to [gs://kubeflow-ci_cloudbuild/source/1598927047.71441-106d5e9c40ff43119fbc7f1c8507080a.tgz]
Created [https://cloudbuild.googleapis.com/v1/projects/kubeflow-ci/builds/b375ed94-487c-4515-bf70-33cf579cc38d].
Logs are available at [https://console.cloud.google.com/cloud-build/builds/b375ed94-487c-4515-bf70-33cf579cc38d?project=593963025935].
ERROR: (gcloud.builds.submit) [Errno 104] Connection reset by peer
This may be due to network connectivity issues. Please check your network settings, and the status of the service you are trying to reach
```

After @jinchihe's investigation looks somehow if we split the 11 concurrent image builds into 3 steps the success rate increased a lot. Not sure if this is due to some networking bandwidth issue. Also according to https://cloud.google.com/sdk/gcloud/reference/builds/submit#--region it must be set to `us-central1` but we are on `us-east1-d`, so I guess global service is used instead?

**What did you expect to happen:**

**Anything else you would like to add:**

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by andreyvelich** [comment]
@yuzisun I tried to follow your approach (https://github.com/kubeflow/kfserving/pull/1063) in Katib: https://github.com/kubeflow/katib/pull/1316.
It helps with GCP networking issue for us.

Does the restarts help in your CI?

**Comment by yuzisun** [comment]
We have added the argo retries also.
