### ISSUE TITLE
ONNX example model is missing

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfserving#1067]
/kind bug

**What steps did you take and what happened:**
We are trying out the ONNX example today and found out we cannot connect to the sample ONNX model. Is the below URI still working or do we need some permission to gain access to it?
https://github.com/kubeflow/kfserving/blob/52451bd0397e76ec605ce7789b1f218b3742d99c/docs/samples/onnx/onnx.yaml#L9

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by ellistarn** [comment]
@rakelkar

**Comment by rakelkar** [comment]
aargh - appears to have gotten deleted... however the original model was from the onnx model zoo at https://github.com/onnx/models/tree/master/vision/style_transfer/fast_neural_style/model

Can you try this link instead (now that KF has raw URL support, it should work :) )?
https://github.com/rakelkar/kfserving/raw/rakelkar-patch-1/docs/samples/onnx/model.onnx

**Comment by Tomcli** [comment]
Thanks @rakelkar, URL support just merged yesterday. Where do you think is a good place to host this onnx model?

**Comment by yuzisun** [comment]
@tduffy000 I think for onnx the model name still has be model.onnx correct?

**Comment by tduffy000** [comment]
Yeah, I did not change that part of the spec so it should still be `model.onnx`. I opened this issue https://github.com/kubeflow/kfserving/issues/1004 in response to that requirement to make it more generic. Would be nice to pull from the onnx model zoo. If you need one with the proper uri right now, you can use one of the examples I created for testing at https://github.com/tduffy000/kfserving-uri-examples/tree/master/onnx/frozen.

**Comment by Tomcli** [comment]
Thanks @tduffy000, we are able to run the ONNX model now. We are wondering should we update the example now, or wait for you to fix #1004 then update the storageUri to pull from onnx model zoo?

**Comment by tduffy000** [comment]
I raised a PR to add support for the generic ONNX names: https://github.com/kubeflow/kfserving/pull/1078.

**Comment by tduffy000** [comment]
@Tomcli @rakelkar  looks like https://github.com/kubeflow/kfserving/pull/1078 got merged so we should be able to update the example to point at the ONNX model zoo now.

**Comment by rakelkar** [comment]
Sure, feel free to raise a PR to update the example!

**Comment by yuzisun** [comment]
I have uploaded the model to `gs://kfserving-examples/onnx/style` now, so it should work now.
