### ISSUE TITLE
kubectl apply -f pytorch.yaml spinning up infinite number of pods

### ISSUE THREAD

**Issue by neolunar7** [kubeflow/kfserving#1068]
/kind bug

I followed the README.md
`kubectl apply -f pytorch.yaml`
resulting in infinite number of pods, and causing the cluster to fail.

**What did you expect to happen:**
One InferenceService CRD to spin up.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.3
- Knative Version:
- KFServing Version: v0.4.0
- Kubeflow version: 1.0
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`): 1.17
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@neolunar7 Did you send a lot of requests to the inference service?

**Comment by neolunar7** [comment]
@yuzisun No I did not. I just created the inferenceservice and did not send any request to it.

**Comment by yuzisun** [comment]
> @yuzisun No I did not. I just created the inferenceservice and did not send any request to it.

that shouldn't happen if no requests are sent to the pods

**Comment by neolunar7** [comment]
@yuzisun Yes, that's the issue.

**Comment by yuzisun** [comment]
@neolunar7 Could you help provide more details? I do not quite understand how that could happen
