### ISSUE TITLE
Proposal: Collapse URI External/Internal to just URI

### ISSUE THREAD

**Issue by ellis-bigelow** [kubeflow/kfserving#107]
/kind feature

**Describe the solution you'd like**
We should just have:
```status.url```

**Anything else you would like to add:**
External URI should be delegated to the cloud provider. KFServing assumes an istio/knative fabric and will follow the domain provided. We don't need to reinvent the wheel here.

**Comment by ellis-bigelow** [comment]
@yuzisun @cliveseldon @animeshsingh 

See Knative's use of "url" in https://docs.google.com/presentation/d/10wuLMFXyol731WKuO5x7lalWrH0A6YVHa4exIERQaQ8

**Comment by ellis-bigelow** [comment]
We may also want to consider ducktyping some of our spec/status to match theirs (not the template, but maybe routing/traffic concepts).

**Comment by yuzisun** [comment]
that sounds good me. Part of my working PR for https://github.com/kubeflow/kfserving/issues/113, I start to ducktype the status object.

**Comment by rakelkar** [comment]
> @yuzisun @cliveseldon @animeshsingh
> 
> See Knative's use of "url" in https://docs.google.com/presentation/d/10wuLMFXyol731WKuO5x7lalWrH0A6YVHa4exIERQaQ8

How do I get perms to see this (have requested, but is there a specific group I need to join?)

**Comment by ellis-bigelow** [comment]
Oh crap. It may not be public. It says public on it. You might need to be in Cloud Run alpha program.
