### ISSUE TITLE
istio-proxy for inferenceservice deny access to inferenceservice

### ISSUE THREAD

**Issue by insoo67park** [kubeflow/kfserving#1076]
/kind bug

**What steps did you take and what happened:**
1. I installed kubeflow 1.1.0 with kubernetes 1.15.12
2. I created notebook server
3. I did serving example with guide (https://github.com/kubeflow/kfserving/tree/master/docs/samples/istio-dex)
4. when I executed below command finally
   -  curl -v -H "Host: ${SERVICE_HOSTNAME}" -H "Cookie: authservice_session=${SESSION}" http://${CLUSTER_IP}/v1/models/${MODEL_NAME}:predict -d ${INPUT_PATH}

   503 Unavaliable service error occurred.

    - so when I check inferenceservice pod's log (istio proxy container), I can see below log.

[2020-09-03 05:59:54.530][21][warning][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:81] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) 10.244.0.77_9090: Found header(name: "kubeflow-userid"
exact_match: "admin@kubeflow.org"
) rule,not supported by RBAC network filter, virtualInbound: Found header(name: "kubeflow-userid"
exact_match: "admin@kubeflow.org"
) rule,not supported by RBAC network filter

    - when I execute curl command, above log message was added.

5. How I can fix it?      

**What did you expect to happen:**
Inferenceservice should reponse 200 OK and the inference result

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

I installed kubeflow 1.1.0 with below command
- kfctl apply -f https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_istio_dex.v1.1.0.yaml

kubernetes version: 1.15.12
os: centos 7

**Comment by yuzisun** [comment]
@insoo67park What happens if you disable the istio proxy by adding following annotation? 
https://github.com/kubeflow/kfserving/blob/master/docs/samples/istio-dex/sklearn.yaml#L6

**Comment by insoo67park** [comment]
@yuzisun
It works after disabling istio injection at namespace level.
I think, with service level disabling istio injection would make it work.

I have one question. 
Do we always have to disable istio injection (namespace/service level) for inference service?
Or is there other solution for this problem?
(I think, envoy proxy is necessary in every inference service  for better service)

Thanks for your help.

**Comment by yuzisun** [comment]
@insoo67park it really depends on if you want to use service mesh features

The Istio service mesh provides a few benefits:
- Allows you to turn on mutual TLS, which secures service-to-service traffic within the cluster.
- Allows you to use the Istio authorization policy, controlling the access to each Knative service based on Istio service roles.

**Comment by yuzisun** [comment]
this is related to https://github.com/kubeflow/kfserving/issues/1032

**Comment by insoo67park** [comment]
Thanks for your comments.
Eventually it seems to depend on if developer want to make istio-injection disable or not.
I agree on your thought.

I will close this issue.
