### ISSUE TITLE
Should we upgrade the Knative version for KFServing?

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfserving#1089]
/kind feature
related https://github.com/kubeflow/kfserving/issues/1015
**Describe the solution you'd like**
Starting from KFServing 0.4 release, the logger API uses CloudEvents V1 which available on Knative Eventing 0.14.2+. Should we also consider updating the Knative serving version to something more recent?

**Anything else you would like to add:**
<del> I think Knative 0.16 is not working with KFServing, so we need to figure out a version that won't break our current implementation.

**Comment by yuzisun** [comment]
@Tomcli Why Knative 0.16 is not working with KFS ?

**Comment by Tomcli** [comment]
Thanks @yuzisun, For Knative 0.16 I'm deploying with
Istio 1.6.8
Knative 0.16
KFServing 0.4
Kubernetes 0.16.14

Here are the events for one of the inferenceservice
```
  Warning  UpdateFailed   63s                kfserving-controller  Failed to update status for InferenceService "flowers-sample": Operation cannot be fulfilled on inferenceservices.serving.kubeflow.org "flowers-sample": the object has been modified; please apply your changes to the latest version and try again
  Warning  InternalError  63s                kfserving-controller  Operation cannot be fulfilled on inferenceservices.serving.kubeflow.org "flowers-sample": the object has been modified; please apply your changes to the latest version and try again
  Normal   Updated        16s (x3 over 63s)  kfserving-controller  Updated InferenceService "flowers-sample"
```

**Comment by Tomcli** [comment]
Thanks @yuzisun, so Knative 0.16 is working when we install istio with istioctl with operator. But we have to pay attention when we leverage the istio 1.1.6 and istio 1.3.1 with Dex when upgrading it for kubeflow.

**Comment by ulrikpl** [comment]
I am new to KFserving so please excuse my most likely ignorant questions.

Following quote is from the KF serving docs themselves:

`If you are looking to use PodSpec fields such as nodeSelector, affinity or tolerations which are now supported in the KFServing v1beta1 API spec, this requires Knative v0.17.0+, and you need to turn on the corresponding feature flags in your Knative configuration.`

Q: Does serving without nodeSelectors force me to run my prediction service with KFserving on the same nodepool that KFServing and Kubeflow was installed on? And would that mean that for use cases with large memory intensive models and high throughput I would have to run Kubeflow 24/7 on a mega expensive nodepool strong enough for the occasional prediction jobs? I really liked the idea of scaling to zero.

I followed the KF/GKE installation guide which installs Knative v0.14.3 and KFServing v1alpha2. 

Q: Is it possible to upgrade to v1beta1 and if so is it a matter of editing a few upstream manifests or Kustomization.yaml files and redeploying or is it more akin to open heart surgery for us mere mortals and wouldn't it also require upgrading Knative to v017? Any hints are appreciated!

Q: How about upgrading Knative to v0.17? It seems rather daunting. Just checking how many upstream files are referencing Knative v0.14 yields 28 files

`$ find ./upstream -type f -exec grep -H 'release' {} \;  | grep v0.14  | cut -f 1 -d ':' | sort | uniq | wc -l
      28`

Sorry for the many questions. I have 200 more about setting up Ingress Gateway for a KFserving service, for which the docs made my head spin at 5000RPM.
