### ISSUE TITLE
Allow developer overrides for framework images via ConfigMap

### ISSUE THREAD

**Issue by ellis-bigelow** [kubeflow/kfserving#109]
/kind feature

**Describe the solution you'd like**
In addition to making all images configurable with a config map, we need a local developer story. We should have something along the lines of a kustomize patch that overrides a local configmap to point to the developers modified framework images.

**Comment by yuzisun** [comment]
@ellis-bigelow Are you working on this? I have a PR mostly ready to submit just to make sure we do not duplicate the effort.

**Comment by ellis-bigelow** [comment]
Not yet. It stuck me we needed a dev experience though. I'll reduce scope of this issue.
