### ISSUE TITLE
logs for inferenceservice 

### ISSUE THREAD

**Issue by narennadig** [kubeflow/kfserving#1092]
`* upload completely sent off: 42 out of 42 bytes
< HTTP/1.1 500 Internal Server Error
< content-length: 93
< content-type: text/html; charset=UTF-8
< date: Thu, 17 Sep 2020 06:14:59 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 4727
< 
* Connection #0 to host 169.46.83.189 left intact
<html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>

Hey, 
how do I see my logs for this?? I don't see any pods but just 1 deployment 

```
 kubectl get deployment -n kfserving
NAME                                                        READY   UP-TO-DATE   AVAILABLE   AGE
kfserving-custom-model-predictor-default-2c5nk-deployment   0/0     0            0           27m

```

How do I see the logs to fix the issue?
```

kubectl get inferenceservice -n kfserving
NAME                     URL                                                                                             READY   DEFAULT TRAFFIC   CANARY TRAFFIC   AGE
kfserving-custom-model   http://kfserving-custom-model.kfserving.169.33.33.111.xip.io/v1/models/kfserving-custom-model   True    100                                43d``
```

**Comment by Iamlovingit** [comment]
use `kubectl get pods -n kfserving` to get the pod name, then use the `kubectl logs -n kfserving $podname -c $containername` to get the log

**Comment by narennadig** [comment]
thanks @Iamlovingit :)
