### ISSUE TITLE
Encountering 404 Not Found while using sklearn example

### ISSUE THREAD

**Issue by mahsanaru** [kubeflow/kfserving#1096]
/kind bug

**What steps did you take and what happened:**
used sklearn example to run a predictor module.

After observing inferenceservices' READY become true, I was expecting to be able to use predictor module successfully.

 ` $ kubectl get inferenceservices sklearn-iris  -n admin`
`NAME           URL                                                            READY   DEFAULT TRAFFIC   CANARY TRAFFIC   AGE` 
`sklearn-iris   http://sklearn-iris.admin.example.com/v1/models/sklearn-iris   True    100                                33m`

`kubectl get ksvc   -n admin`
`NAME                             URL                                                       LATESTCREATED                          LATESTREADY                            READY   REASON`
`sklearn-iris-predictor-default   http://sklearn-iris-predictor-default.admin.example.com   sklearn-iris-predictor-default-qkssb   sklearn-iris-predictor-default-qkssb   True`
 
I used the `KFServing on Kubeflow with Istio-Dex` guide to use the predictor model but I get the following error:

HTTP/1.1 404 Not Found
Cannot POST /v1/models/sklearn-iris:predict

**Environment:**

- KFServing Version: 0.3.0
- Kubeflow version: 1.1 with Istio-Dex
- Kubernetes version: 1.15

**Comment by yuzisun** [comment]
@mahsanaru Can you provide more details or the command you can using to send the request to the service ?

**Comment by mahsanaru** [comment]
I used the following commands:
`kubectl port-forward --namespace istio-system $(kubectl get pod --namespace istio-system --selector="app=istio-ingressgateway" --output jsonpath='{.items[0].metadata.name}') 8080:80` 

`curl -v -H "Host: sklearn-iris.default.example.com"  -H "Cookie: authservice_session=${SESSION}" http://localhost:8080/v1/models/sklearn-iris:predict -d @./docs/samples/sklearn/iris-input.json`

I don't know if it's helpful or not but I don't have an external loadbalancer and without cookie I'm redirected to dex.

**Comment by yuzisun** [comment]
@adrian555 Any thoughts? this is using Kubeflow 1.1 with Dex

**Comment by mahsanaru** [comment]
Thank you for your time. 

I reinstalled kfserving in my cluster and after that the error changed from 404 to `HTTP/1.1 504 Gateway Timeout`. After that I found my solution here [#1076](https://github.com/kubeflow/kfserving/issues/1076)

I will close this issue.

**Comment by juangon** [comment]
@mahsanaru can you describe the fix you made? I am still reproducing the 404 errors. I've seen in pod logs there aren't any `Registering model: XXX` , the opposite as the sklearn-iris from docs/samples. Any ideas of why isn't registering the model @yuzisun ? Thanks very much!
