### ISSUE TITLE
Generate KFServing v1beta1 Python SDK

### ISSUE THREAD

**Issue by yuzisun** [kubeflow/kfserving#1098]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by yuzisun** [comment]
@jinchihe Would you be able to help generate the v1beta SDK?

**Comment by jinchihe** [comment]
@yuzisun just switched off from busy work, I'm starting to work on this.  Thanks
