### ISSUE TITLE
ModelSpec definition - thinking

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/kfserving#111]
For now https://github.com/kubeflow/kfserving/blob/master/pkg/apis/serving/v1alpha1/kfservice_types.go#L52-L54 has 3 fields for Tensorflow, XGBoost and SKLearn models, in fact TensorflowSpec, XGBoostSpec and SKLearnSpec share same structure. how about refactor the type as below to make ModelSpec thin:
```
type ModelSpec struct {
	// Service Account Name
	ServiceAccountName string `json:"serviceAccountName,omitempty"`
	// Minimum number of replicas, pods won't scale down to 0 in case of no traffic
	MinReplicas int `json:"minReplicas,omitempty"`
	// This is the up bound for autoscaler to scale to
	MaxReplicas int `json:"maxReplicas,omitempty"`
	// The following fields follow a "1-of" semantic. Users must specify exactly one spec.
	Custom     *CustomSpec     `json:"custom,omitempty"`
	ModelTemplate     * ModelTemplate     `json:"modelTemplate,omitempty"`
}

type ModelTemplate struct {
	FrameworkName string `json:"frameworkName"`
	ModelURI string `json:"modelUri"`
	// Defaults to latest Version.
	RuntimeVersion string `json:"runtimeVersion,omitempty"`
	// Defaults to requests and limits of 1CPU, 2Gb MEM.
	Resources v1.ResourceRequirements `json:"resources,omitempty"`
}
```

**Comment by ellis-bigelow** [comment]
Hi Hougang,
I can understand the rationale, but this is done intentionally. We explicitly expect to start surfacing extra parameters (tensorflow_session_parallelism, tensorflow_batch_size), etc.

I expect that the framework configuration parameters will drift over time, so we should avoid coalescing them now

**Comment by hougangliu** [comment]
@ellis-bigelow thanks for clarifying
/close
