### ISSUE TITLE
Model uri `file://` does not work for local files

### ISSUE THREAD

**Issue by panchul** [kubeflow/kfserving#1112]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Attempting to deploy the sample on Kubernetes cluster that has Kubeflow 1.1.

As far as I know, in `InferenceService` .yaml, `storageUri, must be one of: [gs://, s3://, pvc://, file://] or match https://{}.blob.core.windows.net/{}/{} or be an absolute or relative local path.`

However, local files do not seem to work:

```
$ ls -la model.onnx
-rw-r--r-- 1 azureuser azureuser 3465 Sep 30 01:54 model.onnx

$ cat onnx.yaml
apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  name: tensorflow-from-uri
spec:
  default:
    predictor:
      onnx:
        storageUri: file://model.onnx

$ kubectl logs -n  kfserving-test tensorflow-from-uri-predictor-default-xqm4h-deployment-f86mjjxn storage-initializer
[I 200930 18:39:24 initializer-entrypoint:13] Initializing, args: src_uri [file://model.onnx] dest_path[ [/mnt/models]
[I 200930 18:39:24 storage:35] Copying contents of file://model.onnx to local
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 54, in download
    return Storage._download_local(uri, out_dir)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 192, in _download_local
    raise RuntimeError("Local path %s does not exist." % (uri))
RuntimeError: Local path file://model.onnx does not exist.
```

**What did you expect to happen:**
The model should be loaded and inference service become 'ready'

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I also tried absolute paths, e.g. `file:///home/myuser/model.onnx`

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version: 
- Kubeflow version: Version 1.1
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):  v1.17.11, aks-engine v0.55.4
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04.7 LTS

**Comment by yuzisun** [comment]
@panchul we do not support local file, the model should be either on cloud storage like gcs/s3 or pvc.

**Comment by panchul** [comment]
@yuzisun , Thanks for clarifying that. I was misled by the error message kubectl prints for cases other than gcs/s3/pvc.

**Comment by pugangxa** [comment]
> @yuzisun , Thanks for clarifying that. I was misled by the error message kubectl prints for cases other than gcs/s3/pvc.

I once had a PR #622 to remove the "file://" type totally, but closed that since it's not important at that time. I think we should redo the task, or at least remove the misleading message included in that PR. I will do it.

**Comment by yuzisun** [comment]
thanks @pugangxa ! Totally agree, this is so confusing.

**Comment by panchul** [comment]
> > @yuzisun , Thanks for clarifying that. I was misled by the error message kubectl prints for cases other than gcs/s3/pvc.
> 
> I once had a PR #622 to remove the "file://" type totally, but closed that since it's not important at that time. I think we should redo the task, or at least remove the misleading message included in that PR. I will do it.

Thanks. I myself thought of contributing to this fine project by creating a PR with that fix. :-) But if it is already there, please let it go through - the folks who use Azure reach out for `file://` option often, because `gsc/s3` is not available.

**Comment by yuzisun** [comment]
@panchul how does `file://` work on Azure? we originally implemented it for local development purpose where you can load the model from your local machine.

**Comment by panchul** [comment]
> @panchul how does `file://` work on Azure? we originally implemented it for local development purpose where you can load the model from your local machine.

That's exactly what I wanted - to feed a local file from right there on the vm where I executed `kubectl`(even simpler, a master node). I thought if .yaml file could be read, there should not be a big stretch to ingest another file from the same location with none of cloud storage nuances(network access, permissions, etc.).

**Comment by pugangxa** [comment]
In my opinion, should use pvc for local file. In fact since we don't know which node the pod will finally run the local os file will not take effect, the only use case I can imagine is to pack local file to your docker image during dockerfile building, the "file://"  prefix indicate the location for the model.

**Comment by panchul** [comment]
> In my opinion, should use pvc for local file. In fact since we don't know which node the pod will finally run the local os file will not take effect, the only use case I can imagine is to pack local file to your docker image during dockerfile building, the "file://" prefix indicate the location for the model.

I think there is a huge usability value in system being able to pick up `file://`. The whole operation is just so atomic and obvious, it has to be made simple. Under the hood, and unbeknown to the non-infrastructure-savvy data scientist, there could be an automatically-created pvc, or some ephemeral distributed read-only blob storage that makes the magic happen.

**Comment by panchul** [comment]
We can close this issue, pvc on local file work, and it is an adequate alternative to `file://` on a cloud.
