### ISSUE TITLE
PyTorch sample fails with 'File exists' error

### ISSUE THREAD

**Issue by panchul** [kubeflow/kfserving#1116]
/kind bug

**What steps did you take and what happened:**

Following the steps from the `Readme.md` in `/src/kfserving/docs/samples/pytorch`:
```
$ python3 cifar10.py
Files already downloaded and verified
Files already downloaded and verified
[1,  2000] loss: 2.205
[1,  4000] loss: 1.856
[1,  6000] loss: 1.686
[1,  8000] loss: 1.605
[1, 10000] loss: 1.540
[1, 12000] loss: 1.475
[2,  2000] loss: 1.401
[2,  4000] loss: 1.367
[2,  6000] loss: 1.361
[2,  8000] loss: 1.335
[2, 10000] loss: 1.309
[2, 12000] loss: 1.297
Finished Training

$ python3 -m pytorchserver --model_dir ./ --model_name pytorchmodel --model_class_name Net
[I 201007 17:02:36 storage:35] Copying contents of ./ to local
[I 201007 17:02:36 storage:205] Linking: ./pytorch.yaml to pytorchmodel/pytorch.yaml
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/azureuser/src/kfserving/python/pytorchserver/pytorchserver/__main__.py", line 35, in <module>
    model.load()
  File "/home/azureuser/src/kfserving/python/pytorchserver/pytorchserver/model.py", line 36, in load
    model_file_dir = kfserving.Storage.download(self.model_dir, self.name)
  File "/home/azureuser/.local/lib/python3.8/site-packages/kfserving/storage.py", line 54, in download
    return Storage._download_local(uri, out_dir)
  File "/home/azureuser/.local/lib/python3.8/site-packages/kfserving/storage.py", line 206, in _download_local
    os.symlink(src, dest_path)
FileExistsError: [Errno 17] File exists: './pytorch.yaml' -> 'pytorchmodel/pytorch.yaml'
```

**What did you expect to happen:**
I expected it to confirm that the model was successfully created and is ready to be used by KFServing 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Python 3.8.2, torch-1.6.0, torchvision-0.7.0

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04 LTS

**Comment by theofpa** [comment]
Hello @panchul, `kfserving` passes the `/mnt/models` path to the `--model_dir` parameter, which works because it's an absolute path. When the `--model_dir` is relative, the symlink doesn't work. So with #1118 I've updated the sample instructions to use the full path of the model instead. Also, make sure you'll remove the temp `example_model/model/pytorchmodel` directory before calling it again!

**Comment by panchul** [comment]
> Hello @panchul, `kfserving` passes the `/mnt/models` path to the `--model_dir` parameter, which works because it's an absolute path. When the `--model_dir` is relative, the symlink doesn't work. So with #1118 I've updated the sample instructions to use the full path of the model instead. Also, make sure you'll remove the temp `example_model/model/pytorchmodel` directory before calling it again!

Thanks. And, yes, I did noticed that additional problems with symlinks pop up if the directory already has a model. Some files create symlinks on themselves, and luckily it has a more action-able error message.
