### ISSUE TITLE
KFServing behind corporate proxy

### ISSUE THREAD

**Issue by kd303** [kubeflow/kfserving#1138]
/kind bug

**What steps did you take and what happened:**
Deploying skLearn example without Dex, fail to load images.
In activator logs  "failed to fetch image information: Get https://gcr.io/v2/"
kubectl -n mmskubeflow get ksvc returns 
Service returns ready=False and reason is "RevisionMissing"

kubectl logs -l model=sklearn-iris-v1 -c storage-initializer -n mmskubeflow

[I 201016 16:21:55 initializer-entrypoint:13] Initializing, args: src_uri [s3://mms-objects/models/sklearn/iris] dest_path[ [/mnt/models]
[I 201016 16:21:55 storage:35] Copying content
s of s3://mms-objects/models/sklearn/iris to local
[I 201016 16:21:55 storage:60] Successfully copied s3://mms-objects/models/sklearn/iris to /mnt/models

kubectl get pod -l model=sklearn-iris-v1 -n mmskubeflow
NAME                                                                                                READY   STATUS    RESTARTS   AGE
sklearn-iris-v1-predictor-default-j4b68-deployment-c69dc74tntzk   3/3     Running   0          3h36m

[123.txt](https://github.com/kubeflow/kfserving/files/5393891/123.txt)

**What did you expect to happen:**
Example sklearn-iris should deploy successfully

**Anything else you would like to add:**
Service returns ready=False and reason is "RevisionMissing"
In activator logs  "failed to fetch image information: Get https://gcr.io/v2/"
Tried setting http_proxy, https_proxy, no_proxy env. variables on controller
**Environment:**

- Istio Version:1.3.1
- Knative Version: serving.knative.dev/release=v0.11.2
- KFServing Version:
- Kubeflow version:1.1.0
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm] kfctl_k8s_istio.v1.1.0.yaml
- Minikube version: NA
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:11:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`):CentOS

**Comment by kd303** [comment]
Out put of 
kubectl get configuration sklearn-iris-v3-predictor-default --output json 

"status": {
        "conditions": [
            {
                "lastTransitionTime": "2020-10-16T23:58:57Z",
                "message": "Revision \"sklearn-iris-v3-predictor-default-j95hk\" failed with message: Unable to fetch image \"gcr.io/kfserving/sklearnserver:v0.3.0\": failed to resolve image to digest: failed to fetch image information: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 10.96.0.10:53: server misbehaving.",
                "reason": "RevisionFailed",
                "status": "False",
                "type": "Ready"
            }
        ],

Is this because I am behind because of I am not deploying on GCP or any other cloud provider does not have imagePullSecrets created? Like mentioned in Knative documentation? Cause it may be doing something like verifying digest for which dockerhub credentials are required?

https://knative.dev/docs/serving/deploying/private-registry/

**Comment by yuzisun** [comment]
@kd303 are you able to pull the above image behind your corporate proxy?

**Comment by kd303** [comment]
Closing this issue and opening a new one. as the original issue is resolved by adding http_proxy settings in controller.

**Comment by kd303** [comment]
Yes Dan. You can set http_proxy, https_proxy and no_proxy env. Variables on
kfserving contoller logs.

**Comment by chinmay22897** [comment]
@kd303 Can u please tell me how you have set this proxy details, is it that before deploying the whole kubeflow cluster you changed the manifest for kfserving or is there any other way there to set the environment on running kubeflow cluster? Will be highly grateful for any pointers from your side.
