### ISSUE TITLE
aggressive probe error:  dial tcp 127.0.0.1:8080: connect: connection refused

### ISSUE THREAD

**Issue by iavinas** [kubeflow/kfserving#1151]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I am getting this error when seeing the logs in the Pytorch server gpu example model in kfserving v0.4.

aggressive probe error:  dial tcp 127.0.0.1:8080: connect: connection refused
aggressive probe error:  dial tcp 127.0.0.1:8080: connect: connection refused
....

{"level":"error","ts":"2020-10-21T08:15:01.782Z","logger":"queueproxy","caller":"network/error_handler.go:33","msg":"error reverse proxying request; sockstat: sockets: used 16\nTCP: inuse 5 orphan 1 tw 12 alloc 51 mem 5\nUDP: inuse 0 mem 2\nUDPLITE: inuse 0\nRAW: inuse 0\nFRAG: inuse 0 memory 0\n","commit":"3372d58","knative.dev/key":{"knative.dev/key":"default/pytorch-cifar10-gpu-predictor-default-2zprm"},"knative.dev/pod":"pytorch-cifar10-gpu-predictor-default-2zprm-deployment-858m8cs5","error":"context canceled","stacktrace":"knative.dev/pkg/network.ErrorHandler.func1\n\tknative.dev/pkg@v0.0.0-20200812224206-44c860147a87/network/error_handler.go:33\nnet/http/httputil.(*ReverseProxy).ServeHTTP\n\tnet/http/httputil/reverseproxy.go:259\nknative.dev/serving/pkg/queue.(*appRequestMetricsHandler).ServeHTTP\n\tknative.dev/serving/pkg/queue/request_metric.go:205\nmain.proxyHandler.func1\n\tknative.dev/serving/cmd/queue/main.go:149\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2041\nknative.dev/serving/pkg/queue.ForwardedShimHandler.func1\n\tknative.dev/serving/pkg/queue/forwarded_shim.go:54\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2041\nknative.dev/serving/pkg/http/handler.(*timeToFirstByteTimeoutHandler).ServeHTTP.func1\n\tknative.dev/serving/pkg/http/handler/timeout.go:86"}

**What did you expect to happen:**
I am suspecting if multiple GPU nodes are serving requests or not. It is taking almost the same time for 1 replica vs 3 replica  

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.7
- Knative Version: v0.17.1
- KFServing Version: 0.4
- Kubeflow version: Usning only KFServing
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

**Comment by averagua** [comment]
I have a similar issue, my main problem is that i cant request to the service. I'm trying to request it from jupyter notebook in the same namespace and avoid de IAP but doest not works. I think that is the same issue, my details are:

- Latest Kubeflow deployment on GCP, v1.12
- Custom KFServing model for simple SKlearn model
- Server run locally


`!kubectl logs covid-server-53e4be7e-predictor-default-whn5l-deployment-8bklfh queue-proxy`
results in
{"level":"info","ts":"2020-12-16T07:07:20.577Z","caller":"logging/config.go:108","msg":"Successfully created the logger."}
{"level":"info","ts":"2020-12-16T07:07:20.577Z","caller":"logging/config.go:109","msg":"Logging level set to info"}
{"level":"info","ts":"2020-12-16T07:07:20.578Z","logger":"queueproxy","caller":"metrics/exporter.go:142","msg":"Flushing the existing exporter before setting up the new exporter.","commit":"bcda051","knative.dev/key":"default-profile/covid-server-53e4be7e-predictor-default-whn5l","knative.dev/pod":"covid-server-53e4be7e-predictor-default-whn5l-deployment-8bklfh"}
{"level":"info","ts":"2020-12-16T07:07:20.578Z","logger":"queueproxy","caller":"metrics/prometheus_exporter.go:37","msg":"Created Opencensus Prometheus exporter with config: &{knative.dev/internal/serving revision prometheus 5000000000 <nil> <nil>  false 9091 false   {   false}}. Start the server for Prometheus exporter.","commit":"bcda051","knative.dev/key":"default-profile/covid-server-53e4be7e-predictor-default-whn5l","knative.dev/pod":"covid-server-53e4be7e-predictor-default-whn5l-deployment-8bklfh"}
{"level":"info","ts":"2020-12-16T07:07:20.578Z","logger":"queueproxy","caller":"metrics/exporter.go:151","msg":"Successfully updated the metrics exporter; old config: <nil>; new config &{knative.dev/internal/serving revision prometheus 5000000000 <nil> <nil>  false 9091 false   {   false}}","commit":"bcda051","knative.dev/key":"default-profile/covid-server-53e4be7e-predictor-default-whn5l","knative.dev/pod":"covid-server-53e4be7e-predictor-default-whn5l-deployment-8bklfh"}
aggressive probe error:  dial tcp 127.0.0.1:8080: connect: connection refused

`!kubectl get inferenceservices -n default-profile`

NAME                     URL                                                         READY   DEFAULT TRAFFIC   CANARY TRAFFIC   AGE
covid-server-53e4be7e    http://covid-server-53e4be7e.default-profile.example.com    True    100                                4h33m
covid-server-592407c43   http://covid-server-592407c43.default-profile.example.com   True    100                                172m
covid-server-fe8b3e4c3   http://covid-server-fe8b3e4c3.default-profile.example.com   True    100                                117m

**Comment by yuzisun** [comment]
> I have a similar issue, my main problem is that i cant request to the service. I'm trying to request it from jupyter notebook in the same namespace and avoid de IAP but doest not works. I think that is the same issue, my details are:
> 
> * Latest Kubeflow deployment on GCP, v1.12
> * Custom KFServing model for simple SKlearn model
> * Server run locally
> 
> `!kubectl logs covid-server-53e4be7e-predictor-default-whn5l-deployment-8bklfh queue-proxy`
> results in
> {"level":"info","ts":"2020-12-16T07:07:20.577Z","caller":"logging/config.go:108","msg":"Successfully created the logger."}
> {"level":"info","ts":"2020-12-16T07:07:20.577Z","caller":"logging/config.go:109","msg":"Logging level set to info"}
> {"level":"info","ts":"2020-12-16T07:07:20.578Z","logger":"queueproxy","caller":"metrics/exporter.go:142","msg":"Flushing the existing exporter before setting up the new exporter.","commit":"bcda051","knative.dev/key":"default-profile/covid-server-53e4be7e-predictor-default-whn5l","knative.dev/pod":"covid-server-53e4be7e-predictor-default-whn5l-deployment-8bklfh"}
> {"level":"info","ts":"2020-12-16T07:07:20.578Z","logger":"queueproxy","caller":"metrics/prometheus_exporter.go:37","msg":"Created Opencensus Prometheus exporter with config: &{knative.dev/internal/serving revision prometheus [5000000000](tel:5000000000) false 9091 false { false}}. Start the server for Prometheus exporter.","commit":"bcda051","knative.dev/key":"default-profile/covid-server-53e4be7e-predictor-default-whn5l","knative.dev/pod":"covid-server-53e4be7e-predictor-default-whn5l-deployment-8bklfh"}
> {"level":"info","ts":"2020-12-16T07:07:20.578Z","logger":"queueproxy","caller":"metrics/exporter.go:151","msg":"Successfully updated the metrics exporter; old config: ; new config &{knative.dev/internal/serving revision prometheus [5000000000](tel:5000000000) false 9091 false { false}}","commit":"bcda051","knative.dev/key":"default-profile/covid-server-53e4be7e-predictor-default-whn5l","knative.dev/pod":"covid-server-53e4be7e-predictor-default-whn5l-deployment-8bklfh"}
> aggressive probe error: dial tcp 127.0.0.1:8080: connect: connection refused
> 
> `!kubectl get inferenceservices -n default-profile`
> 
> NAME URL READY DEFAULT TRAFFIC CANARY TRAFFIC AGE
> covid-server-53e4be7e http://covid-server-53e4be7e.default-profile.example.com True 100 4h33m
> covid-server-592407c43 http://covid-server-592407c43.default-profile.example.com True 100 172m
> covid-server-fe8b3e4c3 http://covid-server-fe8b3e4c3.default-profile.example.com True 100

@averagua can you get the logs from the main model server container ?

**Comment by HassaanAkbar** [comment]
I am having the exact same issue with KF 1.2 on AKS deployed using [this](https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_azure.v1.2.0.yaml) manifest. queue-proxy gives error connection refused. Main serving container has no error. Calling inference endpoint gives 503 service unavailable error. Any workaround for this issue?

**Comment by arya-oss** [comment]
Any updates on this issue? I'm facing similar issue.

**Comment by diazidabagus** [comment]
I got the same error in GKE, this is a snapshot of the logs from the pod of the model

```
{
  "textPayload": "[I 210219 23:24:18 kfserver:88] Registering model: continuum-bcbert\n",
  "insertId": "1fwi7i7g431xr53",
  "resource": {
    "type": "k8s_container",
    "labels": {
      "namespace_name": "default",
      "project_id": "keping-ai-text",
      "cluster_name": "cluster-1",
      "container_name": "kfserving-container",
      "pod_name": "continuum-bcbert-predictor-default-kvbx8-deployment-8b6f94jcwqw",
      "location": "us-central1-a"
    }
  },
  "timestamp": "2021-02-19T23:24:18.314406585Z",
  "severity": "ERROR",
  "labels": {
    "k8s-pod/serving_knative_dev/revision": "continuum-bcbert-predictor-default-kvbx8",
    "compute.googleapis.com/resource_name": "gke-cluster-1-serving-pool-0a037079-qxtl",
    "k8s-pod/serving_kubeflow_org/inferenceservice": "continuum-bcbert",
    "k8s-pod/service_istio_io/canonical-name": "continuum-bcbert-predictor-default",
    "k8s-pod/serving_knative_dev/configurationGeneration": "1",
    "k8s-pod/serving_knative_dev/service": "continuum-bcbert-predictor-default",
    "k8s-pod/serving_knative_dev/revisionUID": "ff03ada6-a148-4ba0-a2ec-5fb7e2ebc51e",
    "k8s-pod/component": "predictor",
    "k8s-pod/app": "continuum-bcbert-predictor-default-kvbx8",
    "k8s-pod/service_istio_io/canonical-revision": "continuum-bcbert-predictor-default-kvbx8",
    "k8s-pod/controller-tools_k8s_io": "1.0",
    "k8s-pod/serving_knative_dev/configuration": "continuum-bcbert-predictor-default",
    "k8s-pod/pod-template-hash": "8b6f94cd9"
  },
  "logName": "projects/keping-ai-text/logs/stderr",
  "receiveTimestamp": "2021-02-19T23:24:22.014627039Z"
}
```

**Comment by marcjimz** [comment]
We had this issue come up with one of our deployments as well. Redeploying the pod seems to fix it but I'm not sure what is causing it. Would love some more insights or resolution on the core issue.

**Comment by molejnik-mergebit** [comment]
Same issue here. It started happening after `kubectl rollout restart deployment/sklearn-xxxx-predictor-default-gvhxf-deployment `. Only once I deleted and re-created `inferenceservice` all worked fine.

**Comment by daganida88** [comment]
any updates? experiencing the same issue with KFServing 0.5.

**Comment by yuzisun** [comment]
> any updates? experiencing the same issue with KFServing 0.5.

Can you help elaborate the issue? the following error is quite normal when queue proxy is still waiting for the model server to be up.
 `aggressive probe error: dial tcp 127.0.0.1:8080: connect: connection refused`

**Comment by yuzisun** [comment]
as above the error logging is from knative probes failures while waiting for the model server to be up serving requests. 

The other related error reported in the original issue is due to request timeout, I'd recommend tuning the timeout setting if needed.
```
{"level":"error","ts":"2020-10-21T08:15:01.782Z","logger":"queueproxy","caller":"network/error_handler.go:33","msg":"error reverse proxying request; sockstat: sockets: used 16\nTCP: inuse 5 orphan 1 tw 12 alloc 51 mem 5\nUDP: inuse 0 mem 2\nUDPLITE: inuse 0\nRAW: inuse 0\nFRAG: inuse 0 memory 0\n","commit":"3372d58","knative.dev/key":{"knative.dev/key":"default/pytorch-cifar10-gpu-predictor-default-2zprm"},"knative.dev/pod":"pytorch-cifar10-gpu-predictor-default-2zprm-deployment-858m8cs5","error":"context canceled
```

**Comment by edwardzjl** [comment]
Same issue here.

We are using kubeflow v1.4.1 with kfserving v0.6.1

Logs of `kfserving-container`:
```
INFO:     Started server process [7]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
```

Logs of `queue-proxy`:
```
{"level":"info","ts":"2022-01-07T01:55:10.998Z","caller":"logging/config.go:110","msg":"Successfully created the logger."}
{"level":"info","ts":"2022-01-07T01:55:10.998Z","caller":"logging/config.go:111","msg":"Logging level set to info"}
{"level":"info","ts":"2022-01-07T01:55:10.998Z","logger":"queueproxy","caller":"metrics/exporter.go:152","msg":"Flushing the existing exporter before setting up the new exporter.","commit":"4ed85f3","knative.dev/key":{"knative.dev/key":"kubeflow-jlzhou/xgboost-iris-predictor-default-w7xwq"},"knative.dev/pod":"xgboost-iris-predictor-default-w7xwq-deployment-6f5898bc9cjjlz2"}
{"level":"info","ts":"2022-01-07T01:55:10.998Z","logger":"queueproxy","caller":"metrics/prometheus_exporter.go:50","msg":"Created Opencensus Prometheus exporter with config: &{knative.dev/internal/serving revision prometheus 5000000000 <nil> <nil>  false 9091 false   {   false}}. Start the server for Prometheus exporter.","commit":"4ed85f3","knative.dev/key":{"knative.dev/key":"kubeflow-jlzhou/xgboost-iris-predictor-default-w7xwq"},"knative.dev/pod":"xgboost-iris-predictor-default-w7xwq-deployment-6f5898bc9cjjlz2"}
{"level":"info","ts":"2022-01-07T01:55:10.998Z","logger":"queueproxy","caller":"metrics/exporter.go:165","msg":"Successfully updated the metrics exporter; old config: <nil>; new config &{knative.dev/internal/serving revision prometheus 5000000000 <nil> <nil>  false 9091 false   {   false}}","commit":"4ed85f3","knative.dev/key":{"knative.dev/key":"kubeflow-jlzhou/xgboost-iris-predictor-default-w7xwq"},"knative.dev/pod":"xgboost-iris-predictor-default-w7xwq-deployment-6f5898bc9cjjlz2"}
aggressive probe error:  dial tcp 127.0.0.1:8080: connect: connection refused
aggressive probe error:  dial tcp 127.0.0.1:8080: connect: connection refused
```

**Comment by himanshumps** [comment]
I am also facing the same issue

**Comment by pszzz** [comment]
I have a similiar issue when deploying knative service.  I have a http service in a pod and alone with a queue-proxy.
The problem for me is that my http service does not listen on localhost by default, which cause the queue-proxy can not connct to it.
So when I force my service to listion on localhost, like localhost:8080 ,the error disappears.

**Comment by phutaneVinayak** [comment]
> I have a similiar issue when deploying knative service. I have a http service in a pod and alone with a queue-proxy. The problem for me is that my http service does not listen on localhost by default, which cause the queue-proxy can not connct to it. So when I force my service to listion on localhost, like localhost:8080 ,the error disappears.

Hey @pszzz  How to do you force your service to listen in localhost ? can you elaborate more on the way you solve the issue?

I understand you have ans it in 2022 but, I still feel your detail explanation might help me and others. who are still around this issue and stuck on it like forever. :(

**Comment by jokerwyt** [comment]
I solved this problem by setting a containerPort in the template. My server runs on 31000.
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mlpipe-stage0
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: my-container
          image: ...
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args: ...
          ports:
          - containerPort: 31000
```
