### ISSUE TITLE
Moving presubmit jobs to Shared Test-infra (AWS CI)

### ISSUE THREAD

**Issue by PatrickXYS** [kubeflow/kfserving#1160]
Community is asking different WG to own their infra and community won't provide a GCP common shared testing infra anymore. Sees kubeflow/testing#752 for more details.

Katib and Pytorch migration works well and here's the PR to update test case to work on AWS Prow+ Argo cluster.
kubeflow/pytorch-operator#305

As we discussed offline, creating this issue to keep track migration work for kfserving. 

/cc @kubeflow/wg-serving-leads

**Comment by yuzisun** [comment]
thanks @PatrickXYS !

/cc @jinchihe
