### ISSUE TITLE
Support for TensorRT as a first class framework

### ISSUE THREAD

**Issue by ellis-bigelow** [kubeflow/kfserving#117]
/kind feature

**Describe the solution you'd like**
# What is TensorRT?
TensorRT is a ML Serving framework for DL supporting multiple frontends (TF, ONNX, etc), multi-model serving, GCS/NFS integration (needs S3, etc), Metrics.

They also have a protocol: https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/core/api.proto

# How does it relate to KFServing?
It might make sense to support TensorRT as a top level framework. We may eventually wish to support multiple frontends (i.e., user submits a saved model.pb, we transform it to a tensorrt model in an init container, and then serve).

We may also want to consider adopting/modifying the TensorRT protocol.

# Thoughts?

**Comment by tripti-singhal** [comment]
I wanted to clarify some of the terminology in this issue.
[TensorRT Inference Server ](https://github.com/NVIDIA/tensorrt-inference-server) is an inference solution that allows you to deploy deep learning models while maximizing the utilization of your underlying hardware. It has features such as concurrent model executiono n a single GPU, dynamic batching, custom backend, HTTP or gRPC endpoints to interface with the client, etc.

**Comment by WangAllen851018** [comment]
@ellis-bigelow  Can you show me an example, how to modify the /etc/hosts, because i have
tried several methods, but the predict still do not work......
