### ISSUE TITLE
Add TorchServe Model Archive creating support

### ISSUE THREAD

**Issue by chauhang** [kubeflow/kfserving#1181]
/kind feature

**Describe the solution you'd like**
This feature will add support for creating the [TorchServe Model Archiver file](https://github.com/pytorch/serve/tree/master/model-archiver) for serving PyTorch models. It will include detailed steps for generating the MAR file using a mechanisms provided by K8s/KFServing.

**Comment by yuzisun** [comment]
thanks @chauhang ! Can we setup a meeting with you to go over these issues?
