### ISSUE TITLE
Generate deployable resource yamls as release artifacts

### ISSUE THREAD

**Issue by krabhishek8260** [kubeflow/kfserving#119]
Generate deployable resource yamls for kfserving deployment. This will simplify the kfserving deployments for people wanting to try this out.
Something like here: https://knative.dev/docs/install/knative-custom-install/
https://github.com/knative/serving/releases/download/v0.6.0/serving.yaml

**Comment by ellis-bigelow** [comment]
Are you planning on taking this on Kumar?

**Comment by krabhishek8260** [comment]
@ellis-bigelow 
I can take this up and probably would need some help from you as I am new to this world. So some stupid questions is on the way.
I was looking into this and the current triggers are setup very differently then using Makefile. 
Can we use our Makefile and ko to build push image and then generate the yamls on Google Cloud Build?

**Comment by ellis-bigelow** [comment]
I actually don't know the best way to do this.

We could definitely build YAMLs on GCB, but I'm not sure where we'd publish them. We could consider making them public on GCS, which could be kind of cool.

You could then kubectl apply -f URI.

I know the knative and istio use helm for their installations, and they put them in a /install folder. It might be worth reaching out to those teams and finding someone to chat with.

Alternatively, the Kubeflow community does this as well for other modules (though I don't trust it's as mature as Istio, for example), and they might have some ideas.

**Comment by krabhishek8260** [comment]
I can take a stab at doing it through GCB using Makefile through build config. Can I get permissions to edit triggers? Also storing it on publicly readable GCS sounds good for now. I am not sure where to provision the GCS. Can you do that please and let me know?

**Comment by ellis-bigelow** [comment]
I think we should probably do a bit of research on existing approaches
before gcb. Is that something you're interested in or are you looking for
more concrete things 😉?

**Comment by krabhishek8260** [comment]
I was planning to make it work with gcb as that would be a quick path for now to enable release CRDs and image for people to try without enlisting.

**Comment by ellis-bigelow** [comment]
Alright, well in that case feel free to make a GCP project and use Cloud Build and GCS to test the solution. Once you've got it all working, I can wire it up with the kfserving project. For now, I don't have Google's permission to open the permissions on this project given that there's a direct billing impact. Sound good?

**Comment by krabhishek8260** [comment]
That sounds good.

**Comment by ellis-bigelow** [comment]
Implemented
/close

**Comment by rakelkar** [comment]
resolved via https://github.com/kubeflow/kfserving/pull/210
