### ISSUE TITLE
Move to 'One' yaml semantic for Model deployments

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/kfserving#121]
/kind feature

**Describe the solution you'd like**
User needs to provide only "one" yaml file for model deployment. KFserving takes care of the rest. Possibly align with MLSpec

**Comment by ellis-bigelow** [comment]
Can you elaborate a little bit here? We already have a "one" yaml semantic. Do you mean for things like secrets, service accounts, and ingress? These will inevitably need to be driven outside the kfservice.yaml file.

**Comment by ellis-bigelow** [comment]
Closing due to lack of response.
/close
