### ISSUE TITLE
Multiple Worker on Pytorch GPU models

### ISSUE THREAD

**Issue by iavinas** [kubeflow/kfserving#1212]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I want more GPU utilization for my Pytorch inference models using kfserving's Pytorchserver. I hardcoded workers=2 in KFServing's code and built docker again but it is not working. I am getting an error message

**TypeError: Failed to initialize Torch Tensor from inputs: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method, []**

Is there any workaround to use to get more workers in Pytorchserver?
Currently, the model is using 1GB out of 16 GB GPU. The model is also using very less CPU.

**What did you expect to happen:**

More workers and better performance.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version: 0.4
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@iavinas KFServing is deprecating the existing pytorchserver, we prefer using torchserve instead and here are [custom examples](https://github.com/kubeflow/kfserving/tree/master/docs/samples/custom/torchserve) which I think should work with 0.4 as well, the native integration is still working in progress. @jagadeeshi2i Do you have an example for pytorch GPU with multi workers?

**Comment by jagadeeshi2i** [comment]
@iavinas Please refer https://github.com/pytorch/serve/blob/master/docs/configuration.md for adding workers to config.properties `default_workers_per_model`. Refer [worker scaling](https://github.com/pytorch/serve/blob/master/README.md#start-torchserve-to-serve-the-model) on how the workers are scaled.
