### ISSUE TITLE
Unable to change default subdomain from name.namespace.domain.com to name-namespace.domain.com

### ISSUE THREAD

**Issue by karlschriek** [kubeflow/kfserving#1216]
By default, KNative rolls out to the subdomain  `{{.Name}}.{{.Namespace}}.{{.Domain}}`. This can be seen under "domainTemplate" in the following config map:

`kubectl -n knative-serving get configmap/config-network`

This causes difficulties with certification. When we roll out KF on EKS, we attach a certificate to it (which gets attached to the ELB that sits behind the Istio Ingress). We typically would configure the certifcate with multipiple names, such as:

```
domain.com
*.domain.com
```

This would allow routing **one level down** from the domain. However, the construct `{{.Name}}.{{.Namespace}}.{{.Domain}}` results in two levels. What this means is that we have to have the following in the certificate:

```
domain.com
*.domain.com
*.somenamespace.domain.com
*.anothernamespace.domain.com
etc.

```
However, certificates cannot be altered once issued. So every time we add a namespace, the cert must be detached from the loadbalancer, destroyed, recreated and reattached. That is a fairly error-prone process.

What we would like instead would be to set the subdomain to `name-namespace` since this would then be covered by `*.domain.com` in the cert. This can be done in KNative by setting the following in `configmap/config-network`:

`domainTemplate: '{{.Name}}-{{.Namespace}}.{{.Domain}}'`

(In the configmap example it describes this exact situation and the above domainTemplate is exactly what they propose as solution)

This however does not appear to work. In this case the `InferenceService` results in `name.domain.com`. I would have expected it to become `name-namespace.domain.com`. I suppose there is some translation between KNative and KFServing that is not working correctly.

This is on Kubeflow 1.0.2

**Comment by karlschriek** [comment]
@theofpa FYI, relates to what you and I were discussing recently

**Comment by yuzisun** [comment]
@karlschriek this has been working for us with the exactly same use case, I think it is fixed with https://github.com/kubeflow/kfserving/issues/715 in KFS 0.3 so Kubeflow 1.1 should work.

**Comment by theofpa** [comment]
thanks @yuzisun!

@karlschriek , I've just confirmed it works in `v0.3`
```
❯ kubectl -n knative-serving get configmap/config-network -o yaml|grep "^  domainTemplate"
  domainTemplate: '{{.Name}}.{{.Namespace}}.{{.Domain}}'
❯ k get inferenceservice
NAME              URL                                                READY   AGE
flowers-sample    http://flowers-sample.default.homelab.pydata.nl    True    5m48s
pytorch-cifar10   http://pytorch-cifar10.default.homelab.pydata.nl   True    5m55s
```
changed dot to hyphen
```
❯ kubectl -n knative-serving edit configmap/config-network
configmap/config-network edited
```
```
❯ kubectl -n knative-serving get configmap/config-network -o yaml|grep "^  domainTemplate"
  domainTemplate: '{{.Name}}-{{.Namespace}}.{{.Domain}}'
❯ k get inferenceservice
NAME              URL                                                READY   AGE
flowers-sample    http://flowers-sample-default.homelab.pydata.nl    True    6m19s
pytorch-cifar10   http://pytorch-cifar10-default.homelab.pydata.nl   True    6m26s
```

**Comment by ofey404** [comment]
@theofpa Thank you! Very useful!
