### ISSUE TITLE
Ability to configure the "domain"

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/kfserving#122]
/kind feature

**Describe the solution you'd like**
Ability to configure the "domain" configmap 

"myorg.mycluster.com" is the prefix of all serving uris
people need a wildcard domain and a cert to match
Knative is planning on autoprovisioning certs in Beta

**Comment by ellis-bigelow** [comment]
Should we just point to this https://knative.dev/v0.4-docs/serving/using-a-custom-domain?

We could also consider shimming, but I'd rather now.

**Comment by ellis-bigelow** [comment]
We need to document this
/area project-health

**Comment by rakelkar** [comment]
Just FYI - we merged a change to knative that allows the cluster operator to override the namespace part of the hostname (to decouple the hostname from cluster details)... https://github.com/knative/serving/issues/4141

**Comment by rakelkar** [comment]
@animeshsingh can you point me to discussion/design around cert autoprovisioining in knative?

**Comment by yuzisun** [comment]
We have tested KFServing with https with certs, this should now work with KFServing 0.3 and Knative 0.11+. For details you can check [knative docs](https://knative.dev/docs/serving/using-a-tls-cert/)

/close
