### ISSUE TITLE
Support cluster-local-gateway in higher istio versions

### ISSUE THREAD

**Issue by larssuanet** [kubeflow/kfserving#1237]
/kind feature

**Describe the solution you'd like**

I would like KFServing to support the use of the cluster-local-gateway at higher Istio & Knative versions. 

Currently, the official support for Istio ends at 1.3.1. When I test higher versions of Istio and Knative (i.e. istio 1.6.13 & knative 0.18) the ingress gateway option seems to work. However, the moment I change the knative `config-domain` to `svc.cluster.local`, KFServing breaks and Inferences never become ready.

**Comment by yuzisun** [comment]
@larssuanet this has been fixed inn https://github.com/kubeflow/kfserving/pull/1224

**Comment by larssuanet** [comment]
@yuzisun thanks! Looking forward to the release
