### ISSUE TITLE
Failed to build kubeflow v1.1.0/v1.2.0 due to kustomization.yaml file not found

### ISSUE THREAD

**Issue by chinmay22897** [kubeflow/kfserving#1248]
/kind bug

**What steps did you take and what happened:**
I am trying to install kubeflow on minikube single node using official guide, so for first I failed in both v1.1.0 and v1.2.0 so tried with older v0.7.0 which got successfully deployed on my minikube cluster so I tried again to deploy the newer versions. First of all I am not able to connect with CONFIG_URI and the manifest uri present in the CONFIG_URI .yaml file which i faced in v0.7 as well for that I did wget both the yaml file and the repo tar.gz file and changed the uri's manually which worked for me in v0.7.0 so I did same thing for v1.1.0 as well, so now the error that I am getting is pointing me to believe that there is something wrong with .yaml files that setup is trying to lookup into, the error log that I am getting for following uri's are:
CONFIG_URI - "https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_k8s_istio.v1.2.0.yaml"
repo uri - "https://github.com/kubeflow/manifests/archive/v1.2.0.tar.gz"

Log for `kfctl build -V -f ${CONFIG_URI}` where CONFIG_URI is pointing to local directory where yaml file is downloaded
INFO[0000] No name specified in KfDef.Metadata.Name; defaulting to my-kubeflow_n based on location of config file: /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kfctl_k8s_istio.v1.2.0.yaml.  filename="coordinator/coordinator.go:202"
INFO[0000]
****************************************************************
Notice anonymous usage reporting enabled using spartakus
To disable it
If you have already deployed it run the following commands:
  cd $(pwd)
  kubectl -n ${K8S_NAMESPACE} delete deploy -l app=spartakus

For more info: https://www.kubeflow.org/docs/other-guides/usage-reporting/
****************************************************************
  filename="coordinator/coordinator.go:120"
INFO[0000] Creating directory /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/.cache  filename="kfconfig/types.go:445"
INFO[0000] Fetching file:/scratch/users/ofsaa/kubeflow/v1.2/v1.2.0.tar.gz to /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/.cache/manifests  filename="kfconfig/types.go:493"
INFO[0000] probing file path: /scratch/users/ofsaa/kubeflow/v1.2/v1.2.0.tar.gz  filename="kfconfig/types.go:543"
INFO[0000] updating localPath to /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/.cache/manifests/manifests-1.2.0  filename="kfconfig/types.go:552"
INFO[0000] Fetch succeeded; LocalPath /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/.cache/manifests/manifests-1.2.0  filename="kfconfig/types.go:561"
INFO[0000] Processing application: namespaces            filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/namespaces/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/namespaces/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: application           filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/application/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/application/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: istio-stack           filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/istio-stack/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/istio-stack/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: cluster-local-gateway  filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/cluster-local-gateway/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/cluster-local-gateway/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: istio                 filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/istio/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/istio/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: cert-manager-crds     filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/cert-manager-crds/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/cert-manager-crds/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: cert-manager-kube-system-resources  filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/cert-manager-kube-system-resources/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/cert-manager-kube-system-resources/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: cert-manager          filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/cert-manager/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/cert-manager/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: add-anonymous-user-filter  filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/add-anonymous-user-filter/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/add-anonymous-user-filter/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: metacontroller        filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/metacontroller/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/metacontroller/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: bootstrap             filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/bootstrap/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/bootstrap/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: spark-operator        filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/spark-operator/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/spark-operator/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: kubeflow-apps         filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/kubeflow-apps/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/kubeflow-apps/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: knative               filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/knative/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/knative/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: kfserving             filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/kfserving/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/kfserving/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
Error: failed to build kfApp from URI /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kfctl_k8s_istio.v1.2.0.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't generate kustomization file for component kfserving
Usage:
  kfctl build [flags]

Flags:
  -f, --file string   Static config file to use. Can be either a local path:
                                export CONFIG=./kfctl_gcp_iap.yaml
                        or a URL:
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml
                        kfctl build -V --file=${CONFIG}
  -h, --help          help for build
  -V, --verbose       verbose output default is false

failed to build kfApp from URI /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kfctl_k8s_istio.v1.2.0.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't generate kustomization file for component kfserving
**********************************************************************************************************************************
**********************************************************************************************************************************
Log for 'kfctl apply -V -f ${CONFIG_URI}'
INFO[0000] No name specified in KfDef.Metadata.Name; defaulting to my-kubeflow_n based on location of config file: /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kfctl_k8s_istio.v1.2.0.yaml.  filename="coordinator/coordinator.go:202"
INFO[0000]
****************************************************************
Notice anonymous usage reporting enabled using spartakus
To disable it
If you have already deployed it run the following commands:
  cd $(pwd)
  kubectl -n ${K8S_NAMESPACE} delete deploy -l app=spartakus

For more info: https://www.kubeflow.org/docs/other-guides/usage-reporting/
****************************************************************
  filename="coordinator/coordinator.go:120"
INFO[0000] Creating directory /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/.cache  filename="kfconfig/types.go:445"
INFO[0000] Fetching file:/scratch/users/ofsaa/kubeflow/v1.2/v1.2.0.tar.gz to /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/.cache/manifests  filename="kfconfig/types.go:493"
INFO[0000] probing file path: /scratch/users/ofsaa/kubeflow/v1.2/v1.2.0.tar.gz  filename="kfconfig/types.go:543"
INFO[0000] updating localPath to /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/.cache/manifests/manifests-1.2.0  filename="kfconfig/types.go:552"
INFO[0000] Fetch succeeded; LocalPath /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/.cache/manifests/manifests-1.2.0  filename="kfconfig/types.go:561"
INFO[0000] Processing application: namespaces            filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/namespaces/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/namespaces/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: application           filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/application/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/application/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: istio-stack           filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/istio-stack/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/istio-stack/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: cluster-local-gateway  filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/cluster-local-gateway/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/cluster-local-gateway/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: istio                 filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/istio/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/istio/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: cert-manager-crds     filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/cert-manager-crds/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/cert-manager-crds/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: cert-manager-kube-system-resources  filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/cert-manager-kube-system-resources/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/cert-manager-kube-system-resources/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: cert-manager          filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/cert-manager/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/cert-manager/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: add-anonymous-user-filter  filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/add-anonymous-user-filter/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/add-anonymous-user-filter/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: metacontroller        filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/metacontroller/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/metacontroller/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: bootstrap             filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/bootstrap/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/bootstrap/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: spark-operator        filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/spark-operator/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/spark-operator/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: kubeflow-apps         filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/kubeflow-apps/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/kubeflow-apps/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: knative               filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/knative/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/knative/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0000] Processing application: kfserving             filename="kustomize/kustomize.go:408"
WARN[0000] Cannot get kustomization from /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/kfserving/base: error open /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kustomize/kfserving/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
Error: failed to build kfApp from URI /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kfctl_k8s_istio.v1.2.0.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't generate kustomization file for component kfserving
Usage:
  kfctl apply -f ${CONFIG} [flags]

Flags:
  -f, --file string   Static config file to use. Can be either a local path:
                                export CONFIG=./kfctl_gcp_iap.yaml
                        or a URL:
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml
                        kfctl apply -V --file=${CONFIG}
  -h, --help          help for apply
  -V, --verbose       verbose output default is false

failed to build kfApp from URI /scratch/users/ofsaa/kubeflow/v1.2/my-kubeflow_n/kfctl_k8s_istio.v1.2.0.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't generate kustomization file for component kfserving

**What did you expect to happen:**
Successfully using kfctl apply to deploy the kubeflow on minikube k8s cluster with working pods and services

**Anything else you would like to add:**
Tried the same thing with both v1.1.0 and v.1.2.0 and getting the same error of files and directories not present, I was able to deploy v0.7.0 successfully using same approach of manually setting the uri files which is really not a big change from official guide- https://www.kubeflow.org/docs/started/workstation/minikube-linux/

**Environment:**

- Istio Version: Deploying through setup only
- Knative Version: Deploying through setup (default)
- KFServing Version: Deploying through setup (default)
- Kubeflow version: v1.1.0/v1.2.0
- Kfdef: k8s_istio
- Minikube version: v1.15.1
- Kubernetes version: (use `kubectl version`): server version- 1.14.0 and client version- 1.15.0
(compatible with v1.1)
- OS (e.g. from `/etc/os-release`): Oracle Linux Server 7.6

**Comment by yuzisun** [comment]
@chinmay22897 Can you help move this issue to `kubeflow/manifests` ?

**Comment by chinmay22897** [comment]
> @chinmay22897 Can you help move this issue to `kubeflow/manifests` ?

Done.
