### ISSUE TITLE
How many modelUri are supported right now?

### ISSUE THREAD

**Issue by benjaminhuo** [kubeflow/kfserving#127]
Just wondering how many kinds of modelUrl are supported ?

I can see from the example that google cloud storage is supported ： gs://

what about hdfs path like : "hdfs://192.168.11.4:9000/testdata/saved_model_half_plus_two_cpu" ?

Any others?

Thanks
Ben

**Comment by ellis-bigelow** [comment]
We currently support 
gs://
s3://

We're looking to support mounted volumes. hdfs is interesting. Would love to hear your thoughts on it either in this issue or at the KFServing weekly meeting.

**Comment by benjaminhuo** [comment]
Great to hear that mounted volumes is going to be supported.
Seems that hdfs support is a bit complex, I'll see what I can do 

Ben

**Comment by yuzisun** [comment]
Yes it is a little complex if your hdfs is kerberized. We need ConfigMap for core/hdfs site xml and a secret mount for delegation token, also another process to monitor the delegation token expiration time and refresh the token.

**Comment by ellis-bigelow** [comment]
Closing due to question answered. Feel free to open an issue for any actionable followups
