### ISSUE TITLE
kfserving in kubeflow not work

### ISSUE THREAD

**Issue by JoinHands** [kubeflow/kfserving#1273]
/kind bug
when I exec "kubectl get inferenceservices -n kubeflow“， get message "Unable to connect to the server: stream error: stream ID 1; INTERNAL_ERROR”

kubeflow version: 1.2.0
install from kfctl -V -f kfctl_istio_dex.v1.2.0.yaml
**What did you expect to happen:**

logs from "kubectl logs kfserving-controller-manager-0 -n kubeflow manager"
`https://10.96.0.1:443/apis/serving.kubeflow.org/v1alpha2/inferenceservices?limit=500&resourceVersion=0: stream error: stream ID 2101; INTERNAL_ERROR E1230 05:49:56.976954 1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1alpha2.InferenceService: Get https://10.96.0.1:443/apis/serving.kubeflow.org/v1alpha2/inferenceservices?limit=500&resourceVersion=0: stream error: stream ID 2103; INTERNAL_ERROR E1230 05:49:58.002730 1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1alpha2.InferenceService: Get https://10.96.0.1:443/apis/serving.kubeflow.org/v1alpha2/inferenceservices?limit=500&resourceVersion=0: stream error: stream ID 2105; INTERNAL_ERROR E1230 05:49:59.009870 1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1alpha2.InferenceService: Get https://10.96.0.1:443/apis/serving.kubeflow.org/v1alpha2/inferenceservices?limit=500&resourceVersion=0: stream error: stream ID 2107; INTERNAL_ERROR E1230 05:50:00.018486 1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1alpha2.InferenceService: Get https://10.96.0.1:443/apis/serving.kubeflow.org/v1alpha2/inferenceservices?limit=500&resourceVersion=0: stream error: stream ID 2109; INTERNAL_ERROR E1230 05:50:01.027432 1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1alpha2.InferenceService: Get https://10.96.0.1:443/apis/serving.kubeflow.org/v1alpha2/inferenceservices?limit=500&resourceVersion=0: stream error: stream ID 2111; INTERNAL_ERROR E1230 05:50:02.036551 1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1alpha2.InferenceService: Get https://10.96.0.1:443/apis/serving.kubeflow.org/v1alpha2/inferenceservices?limit=500&resourceVersion=0: stream error: stream ID 2113; INTERNAL_ERROR`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:1.3.0
- Knative Version:0.14.3
- KFServing Version: 0.4.1
- Kubeflow version:1.2.0
- Kfdef:[istio_dex]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@JoinHands looks like kfserving controller is not able to connect to api server, is there any network policy enforced ?

**Comment by yuzisun** [comment]
this looks like cluster setup issue.
