### ISSUE TITLE
Istio-gateway config in standalone KFserving install

### ISSUE THREAD

**Issue by ontheway16** [kubeflow/kfserving#1275]
Hello, I have followed the standalone KFserving route to get a fully local kfserving setup, and tested the sklearn-iris sample provided down below the install page.
https://github.com/kubeflow/kfserving#standalone-kfserving-installation

But after finalizing sklearn samples install, I realized its working only locally since _Curl from local cluster gateway_ is working (with some modifications), but _Curl from ingress gateway_ is failing with 503. So there seems a istio-gateway configuration missing in sample descriptions or I missed some steps (may be it gets installed with _KFserving with Kubeflow installation_ route?). Do we have to setup a istio-ingress gateway and a virtual service, individually? Since, When I check the other samples within docs/samples folder, There is always a step saying:
_Your cluster's Istio Ingress gateway must be network accessible._

But I think its setup is not available in standalone install, I am new and slowly setting things in mind, so it would be very helpful if someone can direct me, on what files needs to be modified to have external IP start working. I am planning to use triton server pods and hoping to get knative autoscaler, function as intended at the end.

Lastly, as advised, I am using metalLB and have an IP assigned to load balancer. 

Thanks !

**Comment by cliveseldon** [comment]
The ingress gateway to use is defined in the configmap for kfserving : e.g., https://github.com/kubeflow/kfserving/blob/a370b7ccee2cacaf7480d2d03f2660703888c896/install/v0.4.1/kfserving.yaml#L4289-L4293

Do these default setting match your use case?

**Comment by ontheway16** [comment]
@cliveseldon Thanks for the reply.
I have applied the following;
```
TAG=v0.5.0-rc1
kubectl apply -f ./install/$TAG/kfserving.yaml
```
So, yes, I have it in yaml. May be I just do not know how to connect things.
Meanwhile, I have these, if it helps;

![Screenshot01](https://user-images.githubusercontent.com/23200711/103528382-edff7400-4e94-11eb-9d35-11040203da0a.png)
![Screenshot02](https://user-images.githubusercontent.com/23200711/103528391-f192fb00-4e94-11eb-9917-bed7e941ea56.png)
![kiali_ss](https://user-images.githubusercontent.com/23200711/103528409-f5bf1880-4e94-11eb-8a51-8156daaab3a5.jpg)

**Comment by ontheway16** [comment]
Another attempt with Bert;

```
$ kubectl get inferenceservice --all-namespaces
NAMESPACE        NAME           URL                                                       READY   AGE
default          bert-v2        http://bert-v2.default.192.168.1.235.xip.io               True    16h
kfserving-test   sklearn-iris   http://sklearn-iris.kfserving-test.192.168.1.235.xip.io   True    4d17h
```
```
$ echo $INGRESS_PORT
80
$ echo $INGRESS_HOST
192.168.1.235
$ echo $SERVICE_HOSTNAME
bert-v2.default.192.168.1.235.xip.io
```
```
$ curl -v -H "Host: ${SERVICE_HOSTNAME}" -d $INPUT_PATH http://${INGRESS_HOST}:${INGRESS_PORT}/v2/models/$MODEL_NAME/infer
*   Trying 192.168.1.235...
* TCP_NODELAY set
* Connected to 192.168.1.235 (192.168.1.235) port 80 (#0)
> POST /v2/models/bert-v2/infer HTTP/1.1
> Host: bert-v2.default.192.168.1.235.xip.io
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 110
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 110 out of 110 bytes
< HTTP/1.1 503 Service Unavailable
< date: Mon, 04 Jan 2021 15:51:13 GMT
< server: istio-envoy
< connection: close
< content-length: 0
< 
* Closing connection 0
```
