### ISSUE TITLE
Support loading model from local storage

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/kfserving#129]
/kind feature

**Describe the solution you'd like**
kfserving should support onprem cluster, since there are some user cases which are privisioned for on-premise cluster, and the trained model is stored in local storgae. That's better to have a easy way to configure local storage such as PV/PVC and then allow `modelUri` point to local path that's mounted by PVC.

**Comment by rakelkar** [comment]
The subject seems to broad.. maybe update it to support loading from
mounted PVC or something like that?

**Comment by jinchihe** [comment]
> The subject seems to broad.. maybe update it to support loading from mounted PVC or something like that?

Agree, updated, thanks.

**Comment by jinchihe** [comment]
Seems the knative does not support mounts PVCs for container. See tickets https://github.com/knative/serving/issues/2025 and beflow logs for details.

```
{"level":"error","ts":1559532065.8891385,"logger":"kfserving-controller","msg":"Failed to reconcile default model spec","name":"flowers-sample-default","error":"Internal error occurred: admission webhook \"webhook.serving.knative.dev\" denied the request: mutation failed: expected exactly one, got neither: spec.revisionTemplate.spec.volumes[0].configMap, spec.revisionTemplate.spec.volumes[0].secret\nmust not set the field(s): spec.revisionTemplate.spec.volumes[0].persistentVolumeClaim"
```

Seems need knative support the cases firstly. Thanks.

**Comment by ellis-bigelow** [comment]
Keep in mind we can always work around these with MutatingWebhooks. A Knative interface limitation is annoying but not a blocker for us.

**Comment by jinchihe** [comment]
@ellis-bigelow Thanks for your comments.  Yes, I think that's a work around solution, seems the `kanative` side has no action for this recently.  I'm going to have a investigation for the way and create RP then. 

/cc @hougangliu @gyliu513

**Comment by rakelkar** [comment]
@jinchihe Would your scenario be solved by a combination of Minio and #148?

**Comment by jinchihe** [comment]
@rakelkar  We have a trying case that's used Minio for our trained mode that's stored locally on premise cluster. But I think we should support some easy way like PVC mounting to let kfservice get mode.

Personally we can use`Webhook` way to get our purpose, but seems it's impure :-) We can enhance later once knative` supported.

**Comment by rakelkar** [comment]
In general I prefer we first try to push for the right solution. From a KNative perspective mounting a PVC itself is impure and I doubt that they will ever support that directly.

I would advocate starting with something simple like the INIT container approach and then learn and try to incrementally optimize. I dont think it makes sense to build out this webhook workaround at this time. 

@ellis-bigelow  thoughts?

**Comment by jinchihe** [comment]
@rakelkar Thanks. We have real `Pipeline` case for on-premise cluster, the model is trained in the upstream steps of Kubeflow Pipeline, and stored local storage (such as NFS), and just want using kfserving to start service. You know, not all user have policy for access clould storage.

I strongly suggest to implement this. I thinlk this is a common way to resolve similar problems.  And I had a trying webhook way, it works as expected. Will create a PR once finishing tests. Thanks.

**Comment by johnugeorge** [comment]
@rakelkar
In our on-prem cluster, we have similar pipelines where serving component loads from mounted PVCs backed by NFS.  This is a likely scenario in on-prem KF environments(though underlying storage can be different)

**Comment by jinchihe** [comment]
I’m not sure I can join meeting for discussion, but I tried to summarize the pros/cons for supporting pvc, please discuss that. Great thanks!

### Pros for pvc supporting:
1. PVC is generic storage for k8s, and import storage, especially for on prem cluster.
2. For Pipeline cases, downloading source and training model in the upstream steps of Pipeline, and start service using KFServing, that’s a easy way of use the PVC directly.
3. Kubeflow Fairing may use kfserving, and Fairing is going to support on-prem cluster, if so, pvc will be better way.
4. PVC performance is volume plugin related, saying if volume plugin is GCEPersistentDisk, PVC performance should keep same as gs.
5. May use minio to work around, personally seems extra walk for this, PVC is directly way. And how get model if use monio from storage? seems cannot skill pvc or local storage, and minio need one more pod from my understanding.

### Cons for pvc supporting:
1. Knative does not support PVC (recheck knative ticket, I did not get real reasons), so if we support this, need use webhook method.
2. Not sure if have performance issue if mount multiple pods for autoscaling.

**Comment by ellis-bigelow** [comment]
This is now supported! /close
