### ISSUE TITLE
Make MutatingWebhook  have object selector by default

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/kfserving#1300]
/kind feature

Is there any particular reason why the [troubleshooting step described in the docs](https://github.com/kubeflow/kfserving/blob/master/docs/DEVELOPER_GUIDE.md#troubleshooting) (adding object selector on kfserving pod mutating webhook) is not applied in the default in `kubeflow/manifests` YAML?

See here for the relevant manfiets: https://github.com/kubeflow/manifests/blob/master/kfserving/kfserving-install/base/webhook.yaml

**Comment by thesuperzapper** [comment]
@kubeflow/kfserving-owners

**Comment by yuzisun** [comment]
@thesuperzapper we did not change kubeflow manifest only because kubeflow min requirement was kube 1.14 while object selector is introduced in 1.15. Kfserving stand-alone already requires min 1.15 so object selector is set by default, let us know if we can do the same for kubeflow manifest now.

**Comment by thesuperzapper** [comment]
@yuzisun I don't think we explicitly state anywhere what the minimum supported K8S is. (If this is true, we should put this somewhere on kubeflow.org)

But given 1.14 (and 1.15, 1.16 for that matter) [are EOL](https://en.wikipedia.org/wiki/Kubernetes#History), I don't see a reason to continue supporting them.

**Comment by thesuperzapper** [comment]
@kubeflow/kfserving-owners any movement on this for Kubeflow 1.3?

**Comment by yuzisun** [comment]
@pvaneck We can make the object selector by default for KF 1.3?

**Comment by yuzisun** [comment]
@thesuperzapper I'd suggest moving this issue to kubeflow manifest repo

**Comment by thesuperzapper** [comment]
@yuzisun manifests are going to be moved into the component repos (out of kubeflow/manifests) soon, so that's probably not a good idea.

**Comment by thesuperzapper** [comment]
@kubeflow/wg-serving-leads can you please add this as an item on your next meeting?

**Comment by yuzisun** [comment]
@thesuperzapper We are working on to integrate KFS 0.5 to Kubeflow 1.3, will make sure this is turned on by default.
/cc @pvaneck @animeshsingh

**Comment by pvaneck** [comment]
Yea, looks the KFDef you were using was still using the old KFServing YAMLs (I think v0.3.0). The kustomize path for KFServing v0.4.1 is supposed to be `kfserving/installs/generic`. In any case, the manifests repo is undergoing a refactoring where this will be cleared up.

**Comment by yuzisun** [comment]
@pvaneck Just want to confirm, this should be fixed already with Kubeflow 1.3 right?

**Comment by pvaneck** [comment]
@yuzisun Yes, this can be closed. The v0.5.1  release is in the manifests repo currently, and that has the objectSelector.
