### ISSUE TITLE
transformer without domain of predictor

### ISSUE THREAD

**Issue by jiaqianjing** [kubeflow/kfserving#1308]
![image](https://user-images.githubusercontent.com/16071449/105164744-76963980-5b50-11eb-89a5-1214aa495175.png)
![image](https://user-images.githubusercontent.com/16071449/105165336-2bc8f180-5b51-11eb-9f3d-a265dfb7cda9.png)

https://github.com/kubeflow/kfserving/blob/659b2c43841ea98bcfab5411b05964e49b34811c/pkg/constants/constants.go#L307:6

**Comment by yuzisun** [comment]
@jiaqianjing the predictor host is correct here as transformer to predictor is via local gateway which uses the in cluster service name.
