### ISSUE TITLE
knative networking-istio unmarshalerDecoder: unknown field error

### ISSUE THREAD

**Issue by prgawade** [kubeflow/kfserving#1314]
/kind bug

**What steps did you take and what happened:**

1. Created a new inference service yaml as below:

apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "pytorch-cifar-test6"
spec:
  default:
    predictor:
      logger:
        mode: all
      pytorch:
        storageUri: "s3://internalrepo/Internal_Artifacts/3333/model/2341/"
        runtimeVersion: "1.7.0"
        modelClassName: "Net"
      serviceAccountName: miniosa

2: Virtualservices are not created
3: On analyzing found the following error occurring repeatedly on istio-networking deployment

Failed to list *v1alpha3.VirtualService: v1alpha3.VirtualServiceList.Items: []v1alpha3.VirtualService: v1alpha3.VirtualService.v1alpha3.VirtualService.Spec: unmarshalerDecoder: unknown field "match" in v1alpha3.StringMatch, error found in #10 byte of ...|:"300s"}]}},{"apiVer|..., bigger context ...|local","port":{"number":80}}}],"timeout":"300s"}]}},{"apiVersion":"networking.istio.io/v1alpha3","ki|... 

4. Analyzed all the virtual services and could not find any issues as "match" is valid in VirtualService spec. 

[A clear and concise description of what the bug is.]

There are two issues:

1. Even though all the Virtualservices are using match in a valid way, we still see the error
2. One error in any virtualservice should not fail the entire knative serving 

**What did you expect to happen:**
Creation of valid inferenceservice with all the Knative virtualservices

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.3
- Knative Version: 0.11
- KFServing Version:
- Kubeflow version: 1.1
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`): 1.16
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
Could be some invalid virtual service resource living in your cluster?

**Comment by prgawade** [comment]
closed. Issue was found with one of the virtual service

**Comment by HassanOuda** [comment]
@prgawade Hi , im getting something similar in that the virtualservice is not being created. What was your issue exactly with your virtualservice?
