### ISSUE TITLE
Unable to invoke grpc endpoint inside my tensorflow ML model.

### ISSUE THREAD

**Issue by daganida88** [kubeflow/kfserving#1321]
/kind feature

Unable to access my grpc endpoint when creating tensorflow InferenceService, there is no way to invoke it.
When you create an inference service, you will receive a host domain, which then you will add to the headers when invoking a rest call, using -H "HOST:<example.com". I don't have these header options when trying to invoke it using a grpc stub, what should I do? There are no samples for this also (In case it is even possible).

When I used pure TFServing, I created a kubernetes Service with a LoadBalancer that mapped to the grpc port so everything is working as expected.. how can I do it with KFServing??

**Comment by yuzisun** [comment]
@daganida88 We are still working on the docs, but this is the example yaml for tensorflow gRPC
https://github.com/kubeflow/kfserving/blob/master/docs/samples/v1beta1/tensorflow/grpc.yaml

**Comment by yuzisun** [comment]
you can check [this example](https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/tensorflow#create-the-inferenceservice-with-grpc) now
