### ISSUE TITLE
imcompatible with tensorrtserver with version 19.xx

### ISSUE THREAD

**Issue by hsinhoyeh** [kubeflow/kfserving#1347]
/kind bug

In triton predictor, it seems that only version 20.xx are allowed and 19.xx are not.

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

As nvidia rename the inference service executable name to `tritonserver` since version 20.03 (whereas `tensorrtserver` previously) (https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel_20-03.html#rel_20-03)
and the executed name from predictor was changed in the commit `(https://github.com/kubeflow/kfserving/commit/deba8df15)

although users can use custom predictors for this, I think it is better to get support from triton predictor, isn't it?
or it is expected behavior?

**What did you expect to happen:**

triton predictor can work for both 19.xx and 20.xx

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
kfserving: 0.5.0-rc2

**Comment by yuzisun** [comment]
@deadeyegoodwin 19.xx are no long supported right ?

**Comment by deadeyegoodwin** [comment]
Triton's older than 20.06 only support the original V1 protocol and that protocol is no longer supported.

**Comment by yuzisun** [comment]
@hsinhoyeh KFS have no plan to support triton versions older than 20.06.
