### ISSUE TITLE
renewed certificate not reflecting in mutatingwebhookconfigurations inferenceservice.serving.kubeflow.org

### ISSUE THREAD

**Issue by prgawade** [kubeflow/kfserving#1359]
/kind bug

**What steps did you take and what happened:**

We have a cluster up and running since 3 months, last week, kfserving-webhook-server-cert certificate was updated

Certificate: kfserving-webhook-server-cert
Valid Beginning:
01/29/2021 (7 days ago)
Expires:
04/29/2021 (in 3 months)
Algorithm:
RSA - 256 bits
Issuer:
kfserving-webhook-server-service.kubeflow.svc

Since then, we were getting the following when we try to create a kfserving inferenceservice

kubectl --kubeconfig=cloudconfig apply -f pytorch-transformer.yml -n ainadel-ns
Error from server (InternalError): error when creating "pytorch-transformer.yml": Internal error occurred: failed calling webhook "inferenceservice.kfserving-webhook-server.defaulter": Post https://kfserving-webhook-server-service.kubeflow.svc:443/mutate-inferenceservices?timeout=30s: x509: certificate signed by unknown authority (possibly because of "x509: invalid signature: parent certificate cannot sign this kind of certificate" while trying to verify candidate authority certificate "kfserving-webhook-server-service.kubeflow.svc")

We deleted the inferenceservice.serving.kubeflow.org and validation webhook and deleted the kfserving-controller-manager-0 pod

The kfserving-controller-manager-pod-0 came up but the inferenceservice.serving.kubeflow.org and validation webhooks were not recreated.

After a bit of reading on https://cert-manager.io/docs/concepts/ca-injector/

cabundle on the mutating webhooks was updated with the  ca.crt from the “kfserving-webhook-server-cert” and mutating webhooks were recreated from backup. Then the inferenceservice was deployed successfully.

**What did you expect to happen:**

After  kfserving-webhook-server-cert certificate is updated , the cabundle should automatically get updated in the webhooks and kfserving controller should create those webhooks

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.3
- Knative Version: 0.11
- KFServing Version: 0.4.0
- Kubeflow version: 1.1
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`): 1.16
- OS (e.g. from `/etc/os-release`):

**Comment by dejangolubovic** [comment]
Thank you @prgawade for raising the issue. It helped me solve this issue.

Environment: 

- Istio Version: 1.5
- Knative Version: 0.15
- KFServing Version: 0.3.0
- Kubeflow version: 1.1

In case anybody has the same issue, this is what worked for us:

As written here https://cert-manager.io/docs/concepts/ca-injector/, we need to make sure that caBundle if the mutatingwebhookconfiguration (and validatingwebhookconfigurations) is the same as the ca.crt field of the secret. In this case, for kfserving, the resources are:

```
mutatingwebhookconfiguration: inferenceservice.serving.kubeflow.org
validatingwebhookconfigurations: inferenceservice.serving.kubeflow.org
certificate: serving-cert
secret: kfserving-webhook-server-cert
```

These should be equal:

```
kubectl get mutatingwebhookconfiguration inferenceservice.serving.kubeflow.org -o yaml | grep caBundle
kubectl -n kubeflow get secret kfserving-webhook-server-cert -o yaml | grep ca.crt
```

These also should be equal:

```
kubectl get validatingwebhookconfiguration inferenceservice.serving.kubeflow.org -o yaml | grep caBundle
kubectl -n kubeflow get secret kfserving-webhook-server-cert -o yaml | grep ca.crt 
```

The solution was to recreate mutatingwebhookconfiguration and validatingwebhookconfiguration.

First delete them:

```
kubectl delete mutatingwebhookconfiguration inferenceservice.serving.kubeflow.org
kubectl delete validatingwebhookconfiguration inferenceservice.serving.kubeflow.org
```

Find the template here: [webhooks.yaml](https://github.com/kubeflow/kfserving/files/6754333/webhooks.yaml.txt)

Get the ca.crt value from the certificate secret:

`kubectl -n kubeflow get secret kfserving-webhook-server-cert -o yaml | grep ca.crt`

Copy the value to the caBundle fields of webhooks.yaml.

Apply the changes (create webhooks):

`kubectl apply webhooks.yaml`

**Comment by edwardzjl** [comment]
For others who encounter the same problem, @d-gol 's solution was correct.
However I recommend use `kubectl edit` to change the caBundle value, instead of a template `webhooks.yaml`, as the template may be incompatible with your version.
