### ISSUE TITLE
Multimodel serving error when downloading models - unsupported protocol GS

### ISSUE THREAD

**Issue by molejnik-mergebit** [kubeflow/kfserving#1364]
/kind bug

**What steps did you take and what happened:**

I followed instructions for multimodel serving from here: 
https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/sklearn/multimodel

According to the logs model files cannot be downloaded from the Google cloud storage (gs:// prefix). I checked the source code pointed to by the log message (kfserving/pkg/agent/puller.go:134) but it seems gs prefix should be supported.

**What did you expect to happen:**

The example for multimodel serving should work - models from GCP storage (gs:// prefix) should be downloaded and served.

Logs from the predictor pod:

> kubectl logs sklearn-iris-example-predictor-default-vzlzt-deployment-787s9tv -c agent
> {"level":"info","ts":"2021-02-08T08:57:37.023Z","caller":"logging/config.go:110","msg":"Successfully created the logger."}
> {"level":"info","ts":"2021-02-08T08:57:37.023Z","caller":"logging/config.go:111","msg":"Logging level set to: info"}
> {"level":"info","ts":"2021-02-08T08:57:37.023Z","caller":"logging/config.go:78","msg":"Fetch GitHub commit ID from kodata failed","error":"\"KO_DATA_PATH\" does not exist or is empty"}
> {"level":"info","ts":"2021-02-08T08:57:37.023Z","caller":"agent/main.go:268","msg":"Initializing model agent with config-dir /mnt/configs, model-dir /mnt/models"}
> {"level":"info","ts":"2021-02-08T08:57:37.027Z","caller":"agent/main.go:301","msg":"Starting puller"}
> {"level":"info","ts":"2021-02-08T08:57:37.027Z","caller":"agent/main.go:303","msg":"Starting watcher"}
> {"level":"info","ts":"2021-02-08T08:57:37.027Z","caller":"agent/watcher.go:89","msg":"Start to watch model config event"}
> {"level":"info","ts":"2021-02-08T08:57:37.027Z","caller":"agent/watcher.go:127","msg":"Watching /mnt/data/models.json"}
> {"level":"info","ts":"2021-02-08T10:24:43.358Z","caller":"agent/watcher.go:103","msg":"Processing event \"/mnt/configs/..data\": CREATE"}
> {"level":"info","ts":"2021-02-08T10:24:43.565Z","caller":"agent/watcher.go:173","msg":"adding model model1-sklearn"}
> {"level":"info","ts":"2021-02-08T10:24:43.566Z","caller":"agent/watcher.go:173","msg":"adding model model2-sklearn"}
> {"level":"info","ts":"2021-02-08T10:24:43.599Z","caller":"agent/puller.go:121","msg":"Worker is started for model2-sklearn"}
> {"level":"info","ts":"2021-02-08T10:24:43.599Z","caller":"agent/puller.go:121","msg":"Worker is started for model1-sklearn"}
> {"level":"info","ts":"2021-02-08T10:24:43.652Z","caller":"agent/puller.go:129","msg":"Downloading model from gs://kfserving-samples/models/sklearn/iris"}
> {"level":"info","ts":"2021-02-08T10:24:43.652Z","caller":"agent/puller.go:129","msg":"Downloading model from gs://kfserving-samples/models/sklearn/iris"}
> {"level":"info","ts":"2021-02-08T10:24:43.656Z","caller":"agent/downloader.go:47","msg":"Downloading gs://kfserving-samples/models/sklearn/iris to model dir /mnt/models"}
> {"level":"info","ts":"2021-02-08T10:24:43.656Z","caller":"agent/downloader.go:47","msg":"Downloading gs://kfserving-samples/models/sklearn/iris to model dir /mnt/models"}
> {"level":"error","ts":"2021-02-08T10:24:43.724Z","caller":"agent/puller.go:134","msg":"Failed to download model model1-sklearn with err failed to download model: unsupported protocol: protocol not supported for storageUri","stacktrace":"github.com/kubeflow/kfserving/pkg/agent.(*Puller).modelProcessor\n\t/go/src/github.com/kubeflow/kfserving/pkg/agent/puller.go:134"}
> {"level":"error","ts":"2021-02-08T10:24:43.724Z","caller":"agent/puller.go:134","msg":"Failed to download model model2-sklearn with err failed to download model: unsupported protocol: protocol not supported for storageUri","stacktrace":"github.com/kubeflow/kfserving/pkg/agent.(*Puller).modelProcessor\n\t/go/src/github.com/kubeflow/kfserving/pkg/agent/puller.go:134"}
> {"level":"info","ts":"2021-02-08T10:24:43.728Z","caller":"agent/puller.go:114","msg":"completion event for model model1-sklearn, in flight ops 0"}
> {"level":"info","ts":"2021-02-08T10:24:43.728Z","caller":"agent/puller.go:114","msg":"completion event for model model2-sklearn, in flight ops 0"}

**Environment:**

- KFServing Version: latest (master branch commit b63544fde68b0b1423df99ac7dfa2a01a367e0d0)
- Minikube version: v1.17.1
- Kubernetes version: (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`): Debian GNU/Linux 9 (stretch)

**Comment by yuzliu** [comment]
gs protocol is supported and that's what used in the [e2e test](https://github.com/kubeflow/kfserving/blob/master/test/e2e/predictor/test_multi_model_serving.py#L45). Could you please double check you are on the latest master branch?

**Comment by yuzliu** [comment]
You could also try using our nightly built model agent image: `kfserving/agent:latest`

**Comment by yuzliu** [comment]
@molejnik-mergebit I think I know why it doesn't work for you. The quick_install.sh installs from a release candidate and the gcs support is not released yet. If you are familiar with the dev workflow you can run `make deploy-dev` to build and deploy the master branch into your cluster. Or change all the `kfserving/agent:v0.5.0-rc2` image in your inferenceservice.yaml such as [this line ](https://github.com/kubeflow/kfserving/blob/master/config/configmap/inferenceservice.yaml#L174) to `kfserving/agent:latest`

We also plan to cut another release candidate, so you should have gcs support soon from our released candidate soon.

**Comment by molejnik-mergebit** [comment]
@yuzliu thank you for these hints, I'm not familiar with the development process of this project, so I'll try changing the line to `kfserving/agent:latest` as you proposed and get back to you

**Comment by molejnik-mergebit** [comment]
After using `kfserving/agent:latest` it seems to work

```
kubectl logs sklearn-iris-example-predictor-default-h9lzb-deployment-85p62rp -c agent
{"level":"info","ts":"2021-02-09T15:34:09.946Z","caller":"logging/config.go:110","msg":"Successfully created the logger."}
{"level":"info","ts":"2021-02-09T15:34:09.946Z","caller":"logging/config.go:111","msg":"Logging level set to: info"}
{"level":"info","ts":"2021-02-09T15:34:09.946Z","caller":"logging/config.go:78","msg":"Fetch GitHub commit ID from kodata failed","error":"\"KO_DATA_PATH\" does not exist or is empty"}
{"level":"info","ts":"2021-02-09T15:34:09.946Z","caller":"agent/main.go:262","msg":"Initializing model agent with config-dir /mnt/configs, model-dir /mnt/models"}
{"level":"info","ts":"2021-02-09T15:34:09.946Z","caller":"agent/syncer.go:36","msg":"Syncing from model dir /mnt/models"}
{"level":"info","ts":"2021-02-09T15:34:09.946Z","caller":"agent/main.go:271","msg":"Starting puller"}
{"level":"info","ts":"2021-02-09T15:34:09.946Z","caller":"agent/watcher.go:89","msg":"Start to watch model config event"}
{"level":"info","ts":"2021-02-09T15:34:09.946Z","caller":"agent/watcher.go:127","msg":"Watching /mnt/data/models.json"}
{"level":"info","ts":"2021-02-09T15:59:17.742Z","caller":"agent/watcher.go:103","msg":"Processing event \"/mnt/configs/..data\": CREATE"}
{"level":"info","ts":"2021-02-09T15:59:17.743Z","caller":"agent/watcher.go:173","msg":"adding model model1-sklearn"}
{"level":"info","ts":"2021-02-09T15:59:17.743Z","caller":"agent/watcher.go:173","msg":"adding model model2-sklearn"}
{"level":"info","ts":"2021-02-09T15:59:17.743Z","caller":"agent/puller.go:121","msg":"Worker is started for model2-sklearn"}
{"level":"info","ts":"2021-02-09T15:59:17.743Z","caller":"agent/puller.go:121","msg":"Worker is started for model1-sklearn"}
{"level":"info","ts":"2021-02-09T15:59:17.743Z","caller":"agent/puller.go:129","msg":"Downloading model from gs://kfserving-samples/models/sklearn/iris"}
{"level":"info","ts":"2021-02-09T15:59:17.743Z","caller":"agent/puller.go:129","msg":"Downloading model from gs://kfserving-samples/models/sklearn/iris"}
{"level":"info","ts":"2021-02-09T15:59:17.743Z","caller":"agent/downloader.go:47","msg":"Downloading gs://kfserving-samples/models/sklearn/iris to model dir /mnt/models"}
{"level":"info","ts":"2021-02-09T15:59:17.743Z","caller":"agent/downloader.go:47","msg":"Downloading gs://kfserving-samples/models/sklearn/iris to model dir /mnt/models"}
{"level":"info","ts":"2021-02-09T15:59:17.838Z","caller":"agent/downloader.go:67","msg":"Creating successFile /mnt/models/model2-sklearn/SUCCESS.66a3b6130a51a4de6f899f4e464e76d3d3f945f49aa7344af05e69d29ff4b7c8"}
{"level":"info","ts":"2021-02-09T15:59:17.849Z","caller":"agent/downloader.go:67","msg":"Creating successFile /mnt/models/model1-sklearn/SUCCESS.66a3b6130a51a4de6f899f4e464e76d3d3f945f49aa7344af05e69d29ff4b7c8"}
{"level":"info","ts":"2021-02-09T15:59:22.667Z","caller":"agent/puller.go:146","msg":"Successfully loaded model model2-sklearn"}
{"level":"info","ts":"2021-02-09T15:59:22.667Z","caller":"agent/puller.go:114","msg":"completion event for model model2-sklearn, in flight ops 0"}
{"level":"info","ts":"2021-02-09T15:59:22.760Z","caller":"agent/puller.go:146","msg":"Successfully loaded model model1-sklearn"}
{"level":"info","ts":"2021-02-09T15:59:22.760Z","caller":"agent/puller.go:114","msg":"completion event for model model1-sklearn, in flight ops 0"}
```

I think you can close the issue

**Comment by yuzliu** [comment]
Thanks!
