### ISSUE TITLE
KFServing-controller: admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: 1 error occurred:  * attempts must be positive

### ISSUE THREAD

**Issue by crmne** [kubeflow/kfserving#1369]
/kind bug

duplicate of https://github.com/kubeflow/kubeflow/issues/5598 since I'm not sure which component is at fault

**What steps did you take and what happened:**
1. Installed Kubeflow 1.2 on EKS with Cognito using [the manifest on Kubeflow's website](https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_aws_cognito.v1.2.0.yaml)
2. Tried to deploy the `pytorch`, `sklearn`, and `tensorflow` models from [the samples directory](https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1alpha2)
3. Checked health:

        $ kubectl get inferenceservices -n kfserving-test
        NAME           URL   READY   DEFAULT TRAFFIC   CANARY TRAFFIC   AGE
        sklearn-iris         False                                      15m

        $ kubectl describe inferenceservices sklearn-iris -n kfserving-test
        [...]
        Events:
          Type     Reason         Age                     From                  Message
          ----     ------         ----                    ----                  -------
          Warning  InternalError  4m5s                    kfserving-controller  Operation cannot be fulfilled on services.serving.knative.dev "sklearn-iris-predictor-default": the object has been modified; please apply your changes to the latest version and try again
          Normal   Updated        3m59s (x5 over 4m6s)    kfserving-controller  Updated InferenceService "sklearn-iris"
          Warning  InternalError  3m31s (x19 over 3m49s)  kfserving-controller  admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: 1 error occurred:
        
        * attempts must be positive

(ignore the difference in time, the `get inference services` was done way after the `describe`)

**What did you expect to happen:**
Have a prediction endpoint.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.9.0
- Knative Version: v0.14.3
- KFServing Version: v0.4.1
- Kubeflow version: 1.2
- Kfdef: aws_cognito
- Minikube version:
- Kubernetes version: (use `kubectl version`):

        Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.2-dirty", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"dirty", BuildDate:"2021-02-08T10:30:25Z", GoVersion:"go1.16rc1", Compiler:"gc", Platform:"darwin/arm64"}
        Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`): macOS 11.2 arm64

**Comment by yuzisun** [comment]
this is same as https://github.com/kubeflow/kfserving/issues/1065, I think you are on Istio 1.1 which is already EOL, please upgrade to higher istio version.

**Comment by crmne** [comment]
thank you @yuzisun! should this manifest be updated then? https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_aws_cognito.v1.2.0.yaml

**Comment by yuzisun** [comment]
@PatrickXYS what’s the story for istio version for AWS cognito?
