### ISSUE TITLE
KFServing: Move manifests development upstream

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kfserving#1376]
### Background

Umbrella-Issue: https://github.com/kubeflow/manifests/issues/1740

As part of the work of wg-manifests for 1.3
(https://github.com/kubeflow/manifests/issues/1735), we are moving manifests
development to upstream repos. This gives the application developers full
ownership of their manifests, tracked in a single place.

To give an example from the `notebook-controller`, the diagram shows the current
situation. Manifests are in two repos, blurring separation of responsibilities
and making things harder for application developers.

![diagram_1](https://user-images.githubusercontent.com/6123106/107092187-c9881600-680b-11eb-9993-fc04c5e5b6dd.PNG)

Instead, we will copy all manifests from the manifests repo back to each
upstream's repo. From there, they will be imported in the manifests repo. The
following diagram presents the desired state:

![diagram_2](https://user-images.githubusercontent.com/6123106/107092197-cd1b9d00-680b-11eb-8123-7fa5424c5cb2.PNG)

### Current State

KFServing has manifests:
- In the manifests repo, under folder `apps/kfserving/upstream`.
- In upstream repo (https://github.com/kubeflow/kfserving) under folder `config`.

### Desired State

The proposed folder in the upstream repo to receive the manifests is:
`config`.

The goal is to consolidate all manifests development in the upstream repo.
The manifests repo will include a copy of the manifests under `apps/kfserving/upstream`.
This copy will be synced periodically.

KFServing in particular already follows a similar pattern in `kubeflow/manifests`, but keeps the following extra folders:
- `kfserving-crds` and `kfserving-install`: Are these folders maintained? Should they be transferred here or thrown out?
- The `installs/generic` kustomization. This looks like it should be consolidated with `overlays/kubeflow` upstream.

What do you think?

### Success Criteria

The manifests in `apps/kfserving/upstream` should be a copy of the upstream manifests
folder. To do that, the application manifests in `kubeflow/manifests` should be
moved to the upstream application repo.

/assign @yanniszark
cc @kubeflow/wg-serving-leads

**Comment by yanniszark** [comment]
@drewbutlerbb4 @animeshsingh while preparing the KFServing manifests for a PR, I noticed that `overlays` no longer install CRDs.
In addition, I noticed there are two crd kustomizations:
- `config/crd`
- `config/default/crd` which includes some extra patches and a namespace

It seems they were introduced in this PR: https://github.com/kubeflow/kfserving/pull/1244
Could you help me understand the purpose of this change?

**Comment by Tomcli** [comment]
The generated CRD size is too big to store in annotations, so we need to separate it into another kustomization.yaml and run `kubectl create` for that config. 

I think one way to work around this is to manually prune the crd spec with `x-kubernetes-preserve-unknown-fields: true` . Many Knative CRDs use this on their [openAPIV3Schema](https://github.com/knative/serving/blob/ccbfdaddeaafc3141a9f1b5b190fad9c19a6623e/config/core/300-resources/podautoscaler.yaml#L31-L37).

**Comment by Tomcli** [comment]
@yuzisun do you know where we should use `x-kubernetes-preserve-unknown-fields: true` on KFServing?

**Comment by yanniszark** [comment]
> The generated CRD size is too big to store in annotations, so we need to separate it into another kustomization.yaml and run kubectl create for that config.

@Tomcli I tried to reproduce the issue by applying this file in a minikube cluster:
https://github.com/kubeflow/kfserving/blob/5569670250ed068df904774cdbdd7a2d7ca98a58/install/v0.5.0/kfserving_crds.yaml

I could not reproduce. Should the issue be happening with this file?

**Comment by Tomcli** [comment]
oh the KFServing 0.5 release yesterday removed the `initContainers` spec so it can fit into the annotations now. 

@yanniszark so the goal here is to have the same pattern for both kubeflow/manifests and this repo?

**Comment by yanniszark** [comment]
> oh the KFServing 0.5 release yesterday removed the initContainers spec so it can fit into the annotations now.

Was that a workaround? I think we should continue the discussion in issue https://github.com/kubeflow/kfserving/issues/1296 and update it with this new development.

> @yanniszark so the goal here is to have the same pattern for both kubeflow/manifests and this repo?

The goal is to move kfserving manifests development in this repo (the upstream repo). Right now, there are two sources of truth for KFServing (this repo and kubeflow/manifests). We want to only have 1 source of truth (this repo) and kubeflow/manifests should simply copy a subfolder of this repo at a specific commit. You can see a longer explanation in this issue:
https://github.com/kubeflow/manifests/issues/1740

So I'm trying to make a PR to bring the kfserving manifests that are currently at kubeflow/manifests in this repo.
But I'm having some trouble figuring out the newly changed structure.

**Comment by pvaneck** [comment]
The `kfserving-crds` and `kfserving-install` directories that were in the manifests repo can be removed as those were YAMLs corresponding to an older version of KFServing. In regards to the kubeflow overlay, `application.yaml`, `cluster-role.yaml` and `statefulset-patch.yaml` are likely the only things from manifests repo `kfserving/installs/generic` directory that should be carried over. 

The yaml here will also recreate the kubeflow namespace, so if there is no easy way to omit this, then I'm thinking that the kubeflow overlay will also need a namespace patch to reset the labels on the kubeflow namespace to what they were set to in `kubeflow/manifests` (i.e. `control-plane: kubeflow` and `istio-injection: enabled`). Otherwise applying the overlay will overwrite the initial kubeflow namespace labels. 

And, yea. The new CRD structure makes things a bit tricky as I found that just adding `../../default/crd` as a base to the kubeflow overlay does not work. If the CRD size is no longer an issue, perhaps going back to the old structure should be fine? It would certainly  simplify things here.

If not, then can just add `../../crd` as a base in `overlays/kubeflow/kustomize.yaml` and copy over the two patches that are applied in `../../default/crd` (i.e. `inferenceservice_conversion_webhook.yaml` and `cainjection_conversion_webhook.yaml`).

**Comment by yanniszark** [comment]
> It would certainly simplify things here.

@pvaneck I'm all for simplifying and I believe the old structure was simpler, while the new one has certain peculiarities:
- `crd` kustomization defined in two places, only one of which is valid (the `config/default/crd` one).
- The kustomizations containing the crd resources (`config/default/crd`) and the installation resources (`config/default/crd`) can't be combined, as they both contain a namespace.

It also seems that the original reason for moving to this structure is gone:

> oh the KFServing 0.5 release yesterday removed the initContainers spec so it can fit into the annotations now.

Given this information, should we revert to the previous configuration or at least fix some of the problems outlined above? 
cc @Tomcli @yuzisun @animeshsingh @drewbutlerbb4

**Comment by Tomcli** [comment]
We can revert it back to the old ways since we no longer has the blocker issue.

**Comment by pvaneck** [comment]
PR for updating the kubeflow overlay to better match what we have in manifests:  #1424. 

One concern is the matter of image tags for various images. In the config directory, most kfserving image tags are set to `latest`, but when the `install/kfserving.yaml` file is generated, these latest image tags are replaced with the release version (i.e. `v0.5.1`) through some automated (and also maybe manual) post-processing. So if we copy over the config directory at a specific release/commit, the image tags would probably need to be changed from `latest` on the manifests side as well. 

One alternative is that KFServing generates a `kfserving_kubeflow.yaml` per release in the install directory (i.e. install/$TAG/kfserving_kubeflow.yaml) and we just keep syncing that. This would be generated using the kubeflow overlay and looks to be something that has already been explored (e.g https://github.com/kubeflow/kfserving/blob/master/install/v0.5.0/kfserving_kubeflow.yaml)

**Comment by yanniszark** [comment]
Resolved in https://github.com/kubeflow/kfserving/pull/1424
