### ISSUE TITLE
What is the kfserving_endpoint for a remote KFServing installation? Using http://$INGRESS_HOST:$INGRESS_PORT/deploy-model returns 404

### ISSUE THREAD

**Issue by PatrickGhosn** [kubeflow/kfserving#1379]
/kind question

I have a standalone/remote KFServing installation running. When I put the ingress host (public IP) and the ingress port as the kfserving_endpoint ` $INGRESS_HOST:$INGRESS_PORT`, the pipeline calls `http://$INGRESS_HOST:$INGRESS_PORT/deploy-model` but that returns a 404 not found error.

I even tried it manually from the command line and got the same result.

What should I call to reach the deploy-model api?

```
export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].port}')
curl http://$INGRESS_HOST:$INGRESS_PORT/deploy-model -v
```

**Comment by yuzisun** [comment]
@PatrickGhosn you will need to pass the host header if you are using public ip not dns

**Comment by yuzisun** [comment]
https://github.com/kubeflow/kfserving#curl-the-inferenceservice

**Comment by PatrickGhosn** [comment]
> @PatrickGhosn you will need to pass the host header if you are using public ip not dns

I'm trying to call the API to create the inference service, not curling the service itself. It's in the code here: 
https://github.com/kubeflow/pipelines/blob/1.4.0/components/kubeflow/kfserving/src/kfservingdeployer.py

Line 367.

**Comment by PatrickGhosn** [comment]
For those interested in a follow up. Apparently the sample in kfdeployer needs to be run as a seperate pod, and use flask for the  the deploy-model API that communicates with the kf-serving deployment.
