### ISSUE TITLE
Transformer Timeout

### ISSUE THREAD

**Issue by crmne** [kubeflow/kfserving#1386]
/kind bug

**What steps did you take and what happened:**
1. Install Kubeflow 1.2 on EKS with Cognito
2. Set up custom domain `kubectl edit configmap config-domain -n knative-serving`
3. Deploy [transformer](https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1alpha2/transformer/image_transformer) or [this one on 0.5.0](https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/transformer/torchserve_image_transformer)
4. Send prediction request to transformer
5. Prediction request takes forever and eventually times out returning:

        <html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>* Closing connection 0

6. Logs of transformer show:

        [E 210217 10:50:35 web:1793] Uncaught exception POST /v1/models/mnist:predict (127.0.0.1)
            HTTPServerRequest(protocol='http', host='localhost:8004', method='POST', uri='/v1/models/mnist:predict', version='HTTP/1.1', remote_ip='127.0.0.1')
            Traceback (most recent call last):
            File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
                result = await result
            File "/usr/local/lib/python3.7/site-packages/kfserving/handlers/http.py", line 59, in post
                response = (await model.predict(request)) if inspect.iscoroutinefunction(model.predict) else model.predict(request)
            File "/usr/local/lib/python3.7/site-packages/kfserving/kfmodel.py", line 69, in predict
                body=json.dumps(request)
            tornado.simple_httpclient.HTTPTimeoutError: Timeout during request

Same thing happens in KFServing 0.4.1 as in 0.5.0

**What did you expect to happen:**
Step 4 returning predictions

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.3.1
- Knative Version: 0.14.3
- KFServing Version: 0.4.1 and 0.5.0
- Kubeflow version: 1.2
- Kfdef: aws_cognito
- Kubernetes version: (use `kubectl version`): v1.18.9-eks-d1db3c
- OS (e.g. from `/etc/os-release`): macOS Big Sur arm64

**Comment by 4vik** [comment]
Have you tried turning it off and back on again?

**Comment by crmne** [comment]
stopped using EKS

**Comment by BrandonLiang** [comment]
what was the resolution? I am running into the same issue
