### ISSUE TITLE
No matches for kind "InferenceService" in version "serving.kubeflow.org/v1beta1"

### ISSUE THREAD

**Issue by OfTheThorn** [kubeflow/kfserving#1390]
/kind bug
**What steps did you take and what happened:**

I installed KFServing and Kubeflow, have tried with a v1alpha2 inference service which worked. However, I would like to use certain features made available in the v1beta1 version, mainly with regard to the V1beta1PredictorSpec and V1Volume. I always end up with the No matches for kind "InferenceService" in version "serving.kubeflow.org/v1beta1" error though.

**What did you expect to happen**

I expect the model to be deployed successfully

**Environment**:

Istio Version: 1.6.0
Knative Version: 0.14.3
KFServing Version: 0.4.1
Kubeflow version:1.2.0
Kubernetes version: (use kubectl version): client:1.19.3, server:1.18.14
OS (e.g. from /etc/os-release): macOS Catalina

/kind bug

**Comment by yuzisun** [comment]
@OfTheThorn v1beta1 version is not integration in kubeflow yet, we are expecting to install it in Kubeflow 1.3
