### ISSUE TITLE
Failed to execute code samples - https://github.com/kubeflow/kfserving/pull/1330

### ISSUE THREAD

**Issue by daganida88** [kubeflow/kfserving#1392]
Hey, I am using KF serving and I asked for an example on how to create an inference service that is using grpc.
After installing kubeflow from here: https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/ using kfctl to install version
https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_k8s_istio.v1.2.0.yaml I get the following error:
no matches for kind "InferenceService" in version "serving.kubeflow.org/v1beta1"
Seems like the examples does not work. Am I missing something? 
kfctl version: kfctl v1.2.0-0-gbc038f9
Kubernetes master version: 1.18
Also, using v1alpha2 api does not work, it gives me:
Error from server: error when creating "test.yaml": admission webhook "inferenceservice.kfserving-webhook-server.validator" denied the request: Exactly one of [Custom, ONNX, Tensorflow, Triton, SKLearn, XGBoost] must be specified in PredictorSpec

**Comment by yuzisun** [comment]
@daganida88 kubeflow 1.2 does not support KFServing v1beta1.

**Comment by daganida88** [comment]
I managed to do it using a custom model.

**Comment by daganida88** [comment]
spec:
  default:
    predictor:
      custom:
        container:
          name: grpc
          args:
          - --port=9000
          - --rest_api_port=8500
          - --model_config_file=gs://tensorflow_serving_poc/model_config
          image: tensorflow/serving
          ports:
          - protocol: TCP
            name: h2c
            containerPort: 9000

**Comment by daganida88** [comment]
I tried your example, but the part of the port did not work. my example worked.

**Comment by yuzisun** [comment]
@daganida88 ye this is only supported in v1beta1 for prepackaged tensorflow which allows you specifying container field, in v1alpha2 the only possible way is to use custom.

**Comment by daganida88** [comment]
Ok cool. thanks, bro, waiting for v1beta1 ;)

**Comment by yuzisun** [comment]
> Ok cool. thanks, bro, waiting for v1beta1 ;)

v1beta1 is always released in KFServing 0.5, it will be integrated to kubeflow 1.3.
