### ISSUE TITLE
503 Service Unavailable error on the kfserving inferences service

### ISSUE THREAD

**Issue by prgawade** [kubeflow/kfserving#1393]
/kind bug

**What steps did you take and what happened:**

 Kfserving service was created succesfully

NAME                   URL                                                                                         READY   DEFAULT TRAFFIC   CANARY TRAFFIC   AGE
pytorch-cifar-63       http://pytorch-cifar-63.kubeflow.example.com/v1/models/pytorch-cifar-62           True    100                                8h

all vs, routes, revisions and pods are up and in TRUE status

But, we get error while invoking the API

curl -v -H "Host: pytorch-cifar-63.kubeflow.example.com" -d @./input.json http://10.66.102.66:31380/v1/models/pytorch-cifar-63:predict 

> POST /v1/models/pytorch-cifar-63:predict HTTP/1.1
> Host: pytorch-cifar-63.kubeflow.example.com
> User-Agent: curl/7.55.1
> Accept: */*
> Content-Length: 110681
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
>
< HTTP/1.1 100 Continue
< HTTP/1.1 **503 Service Unavailable**
< content-length: 19
< content-type: text/plain
< date: Thu, 18 Feb 2021 14:07:31 GMT
< server: istio-envoy
< connection: close

However, when we invoked the API by passing authority header as  pytorch-cifar-63**-predictor-default**.kubeflow.example.com
 as follows, it works just fine

_curl -v -H "Host: pytorch-cifar-63.kubeflow-predictor-default.example.com" -d @./input.json http://10.66.102.66:31380/v1/models/pytorch-cifar-63:predict_ 

Somehow the virtualservice pytorch-cifar-63 is unable to route the request to cluster-local-gateway and gets http 503 error 

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"serving.kubeflow.org/v1alpha2","kind":"kubeflow","metadata":{"annotations":{},"name":"pytorch-cifar-63","namespace":"kubeflow"},"spec":{"default":{"predictor":{"logger":{"mode":"all"},"pytorch":{"modelClassName":"Net","runtimeVersion":"1.7.0","storageUri":"s3://testrepo/test_Artifacts/95/model/93/"},"serviceAccountName":"miniosa"}}}}
  creationTimestamp: "2021-02-18T14:07:03Z"
  generation: 1
  managedFields:
  - apiVersion: networking.istio.io/v1alpha3
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:ownerReferences: {}
      f:spec:
        .: {}
        f:gateways: {}
        f:hosts: {}
        f:http: {}
    manager: manager
    operation: Update
    time: "2021-02-18T14:07:03Z"
  name: pytorch-cifar-63
  namespace: kubeflow
  ownerReferences:
  - apiVersion: serving.kubeflow.org/v1alpha2
    blockOwnerDeletion: true
    controller: true
    kind: InferenceService
    name: pytorch-cifar-63
    uid: 0213a916-0f93-4ecc-83c9-a4c2aaf24378
  resourceVersion: "229314209"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/kubeflow/virtualservices/pytorch-cifar-63
  uid: c388c061-f102-4353-8baa-1c9b7095b860
spec:
  gateways:
  - kubeflow-gateway.kubeflow
  - knative-serving/cluster-local-gateway
  hosts:
  - pytorch-cifar-63.kubeflow.example.com
  - pytorch-cifar-63.kubeflow.svc.cluster.local
  http:
  - match:
    - authority:
        regex: ^pytorch-cifar-63\.kubeflow\.example\.com(?::\d{1,5})?$
      gateways:
      - kubeflow-gateway.kubeflow
      uri:
        prefix: /v1/models/pytorch-cifar-63:predict
    - authority:
        regex: ^pytorch-cifar-63\.kubeflow(\.svc(\.cluster\.local)?)?(?::\d{1,5})?$
      gateways:
      - knative-serving/cluster-local-gateway
      uri:
        prefix: /v1/models/pytorch-cifar-63:predict
    retries:
      attempts: 3
      perTryTimeout: 600s
    route:
    - destination:
        host: cluster-local-gateway.istio-system.svc.cluster.local
        port:
          number: 80
      headers:
        request:
          set:
            Host: pytorch-cifar-63-predictor-default.kubeflow.svc.cluster.local
      weight: 100

**What did you expect to happen:**

Get the API response with the authority header as pytorch-cifar-63.kubeflow.example.com

**Anything else you would like to add:**
Recently we upgraded Knative from v0.11 to v0.15.

**Environment:**

- Istio Version: 1.3.1
- Knative Version: v0.15
- KFServing Version: 0.3.0
- Kubeflow version: 1.1
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`): 1.18
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@prgawade Do you have cluster local gateway installed?

**Comment by prgawade** [comment]
yes cluster gateway is up and runing and also resolved as the ipaddress of the kubernetes service when we curl using the port and hostname but we get connection refused error but when curl with locahost on shell of cluster local gateway , we do not get any error

**Comment by jal06** [comment]
@prgawade , I had the same problem a few months ago.

This problrem happens because the Istio local gataway is missing in GCP : see issue [176](https://github.com/kubeflow/gcp-blueprints/issues/176) 

The status for this issue is that 2 actions are needed  [see comment](https://github.com/kubeflow/gcp-blueprints/pull/177#issuecomment-759234498) :
- Upgrade Istio version (asm in GCP) . This is planned for the next version Kubeflow 1.3 
- Set the idiomatic way to install cluster-local-gatreway : this will be solved after the upgrade of istio (or hopefully simultaneously  than the upgrade of Istio)

**Comment by prgawade** [comment]
@jal06 , we are using private Kubernetes cluster

**Comment by daganida88** [comment]
I had the same issue,
this installation solved it for me:
https://deploy.seldon.io/docs/getting-started/production-installation/standalone-kfserving/

**Comment by yuzisun** [comment]
see #1660
