### ISSUE TITLE
Validate KFServing with Istio 1.9

### ISSUE THREAD

**Issue by pvaneck** [kubeflow/kfserving#1408]
As noted in the KF mailing list (https://groups.google.com/g/kubeflow-discuss/c/qhK-CMz3N5g), Istio 1.9 is targeted to be included in the manifests for the KubeFlow 1.3 release. 

This is an issue to track the validation of KFServing installation and usage with Istio 1.9, potentially in conjunction with newer  versions of Knative (as Knative could probably use an upgrade on the KF manifests side if newer features are desired: https://github.com/kubeflow/manifests/issues/1754). Target for Knative will be at least 0.16.x, as I think some functionality related to explainers/loggers required a newer version of Knative-eventing then the one provided in kubeflow/manifests (v0.14.3)

I do not foresee there being any issues with the new Istio, but I will use this issue to post any findings validating on various platforms.

/cc @animeshsingh @Tomcli 
/assign @pvaneck

**Comment by Tomcli** [comment]
Right now many of my tests are running on Knative 0.18. The alibi is also using Knative eventing 0.18+. Maybe we should update the Knative to 0.18 if possible?

Knative 0.19 is where we start seeing problem #1333

**Comment by yuzisun** [comment]
Just a note we are currently running istio 1.7.2 and knative serving/eventing 0.17 as we are on kubernetes 1.16, knative 0.18 requires kubernetes 1.17.

**Comment by theofpa** [comment]
tested combinations:
* k8s-1.17, istio-1.7.1, knative-0.20.0, #1334
* k8s-1.19, istio-1.8.2, knative-0.21.0, #1482
