### ISSUE TITLE
Missing v0.5.1 tag for alibi-explainer

### ISSUE THREAD

**Issue by pvaneck** [kubeflow/kfserving#1426]
The latest release has a [default image version of  v0.5.1 for alibi-explainer](https://github.com/kubeflow/kfserving/blob/master/install/v0.5.1/kfserving.yaml#L15982). That tag doesn't seem to exist yet: https://console.cloud.google.com/gcr/images/kfserving/GLOBAL/alibi-explainer?gcrImageListsize=30

**Comment by yuzisun** [comment]
hmm looks like the build for some reason failed
https://console.cloud.google.com/cloud-build/builds;region=global/04ddc7db-24af-474f-8f65-1eb1bcee4c99?authuser=1&project=kfserving

**Comment by yuzisun** [comment]
it actually timed out possibly related to https://github.com/kubeflow/kfserving/pull/1395
