### ISSUE TITLE
multi-model-serving support for custom container in predictorSpec

### ISSUE THREAD

**Issue by sreddybr3** [kubeflow/kfserving#1427]
/kind feature

**Describe the solution you'd like**
multimodel feature support currently depends on "multiModelServer" : true in config/configmap/inferenceservice.yaml
this feature works for standard supported predictors such as sklearn, triton and NOT for a custom container-based preditor spec. 

**Anything else you would like to add:**
- ASsumption is that custom container is a model server exposing predict endpoint along with load, unload endpoints (defined in v2 protocol). If not, then agent will not be able to call load/unload endpoints. a mutlimodel server like AWS MMS can load models by polling /mnt/models/ directory without the need for load/unload endpoints.

Proposed solution:
- can we add new field "multiModelServer" under CoponentExtensionSpec struct (pkg/apis/serving/v1beta1/component.go)
this field in predictorSpec will also be useful to override default config behaviour

- further (c *CustomPredictor) IsMMS(config *InferenceServicesConfig) under pkg/apis/serving/v1beta1/predictor_custom.go  can be adjusted to use the multiModelServer flag to return if inferenceService is multi-model-server

- if MMS, then agent will be injected as sidecar along the custom container, agent watches for configMap changes and downloads models to mnt/models shared directory and call /load and /unload endpoints of model server

**Comment by yuzisun** [comment]
@sreddybr3 Great proposal! We prefer load/unload instead of polling model directory for performance concerns on model server container. We want model server resource are dedicated for inference and let model agent handle the model downloading and watching.

/cc @abchoo @yuzliu

**Comment by shydefoo** [comment]
Can I raise a PR for this?

**Comment by yuzisun** [comment]
@shydefoo that would be great!
