### ISSUE TITLE
Homepage link on PyPi incorrect

### ISSUE THREAD

**Issue by DavidSpek** [kubeflow/kfserving#1430]
/kind bug

Looking on https://pypi.org/project/kfserving/ and clicking on the homepage button on the left under project links goes to a page that does not exist (https://github.com/kubeflow/kfserving/python/kfserving). It should probably be changed to https://github.com/kubeflow/kfserving/tree/master/python/kfserving.

**Comment by yuzisun** [comment]
Good catch @DavidSpek ! Can you help fix [here](https://github.com/kubeflow/kfserving/blob/master/python/kfserving/setup.py#L32) ?

**Comment by DavidSpek** [comment]
@yuzisun Fixed it in https://github.com/kubeflow/kfserving/pull/1431
