### ISSUE TITLE
How to  upgrade kfserving in kubeflow1.2

### ISSUE THREAD

**Issue by jidemoski** [kubeflow/kfserving#1437]
/kind bug

I try to upgrade kfserving from **v0.4.0 to 0.5.0**
1. I delete kfserving configure from kfctl_istio_dex.v1.2.0.yaml and update 
2. I deploy  kfserving0.5 by wget kfserving yaml
3. I entry my notebook and install kfserving==0.5.0
4. I execute this code 
```
from kfserving import KFServingClient
kf = KFServingClient()
kf.get()
```
5. this code return error:
```
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"inferenceservices.serving.kubeflow.org is forbidden: User \"system:serviceaccount:test:default-editor\" cannot list resource \"inferenceservices\" in API group \"serving.kubeflow.org\" in the namespace \"test\"","reason":"Forbidden","details":{"group":"serving.kubeflow.org","kind":"inferenceservices"},"code":403}
```
**but I can use it deploy my inferenceservice before I upgrade.**

How to upgrade kfserving that is no error?

**Environment:**

- Istio Version: 1.3.0
- Knative Version: v0.14.3
- KFServing Version: v0.5.0
- Kubeflow version: v1.12
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm] k8s_istio_dex
- Kubernetes version: (use `kubectl version`): 1.18.0

**Comment by yuzisun** [comment]
@pvaneck

**Comment by pvaneck** [comment]
Something may be missing in your install for KFServing depending on which YAML you used. The KFServing install for integration with Kubeflow is a bit different than the standalone KFServing install. There is currently a PR (https://github.com/kubeflow/kfserving/pull/1424) for fleshing out the kubeflow overlay. With this PR, you could do `kustomize build config/overlays/kubeflow | kubectl apply -f -` but this would always give you the latest in terms of KFServing config and images. I hope to soon generate a stable install yaml file (`kfserving_kubeflow.yaml`) corresponding to v0.5.1 to be placed here: https://github.com/kubeflow/kfserving/tree/master/install/v0.5.1

**Comment by jidemoski** [comment]
> 您安装的KFServing可能缺少某些内容，具体取决于您所使用的YAML。与Kubeflow集成的KFServing安装与独立的KFServing安装略有不同。当前有一个PR（[＃1424](https://github.com/kubeflow/kfserving/pull/1424)）用于充实kubeflow叠加层。使用此PR，您可以执行`kustomize build config/overlays/kubeflow | kubectl apply -f -`此操作，但这始终可以为您提供有关KFServing配置和图像的最新信息。我希望很快生成一个`kfserving_kubeflow.yaml`与v0.5.1相对应的稳定的安装yaml文件（），以放置在此处：[https](https://github.com/kubeflow/kfserving/tree/master/install/v0.5.1) : [//github.com/kubeflow/kfserving/tree/master/install/v0.5.1](https://github.com/kubeflow/kfserving/tree/master/install/v0.5.1)

@pvaneck You are right, I try to apply the some kfserving file in  kubeflow 1.2, it can run.  
but have a new problem, when I describe the inferenceserving, it can't Ready, the tip is   
craft         Unknown          100                              craft-predictor-default-zstwg   12h

**Comment by pvaneck** [comment]
FYI,  https://github.com/kubeflow/kfserving/blob/master/install/v0.5.1/kfserving_kubeflow.yaml was added recently and should be applied when installing with Kubeflow. I am wondering if you applied the `kfserving.yaml` file which has the kfserving ingress gateway configured to the Knative gateway instead of the Kubeflow gateway.
