### ISSUE TITLE
CommandException: No URLs matched: gs://kfserving-examples/models/mnist

### ISSUE THREAD

**Issue by julianmack** [kubeflow/kfserving#1439]
/kind bug 

I would like to run the kafka mnist example but when I run:
```bash
gsutil cp gs://kfserving-examples/models/mnist .
```
As per the readme, I get
```
CommandException: No URLs matched: gs://kfserving-examples/models/mnist
```

**What did you expect to happen:**
I expected to be able to download the model checkpoint.

**Comment by yuzisun** [comment]
@julianmack it should be `gs://kfserving-examples/models/tensorflow/mnist`

**Comment by kmarquardsen** [comment]
I've updated the doc in the ^ PR to correct the command
