### ISSUE TITLE
KFServing release process

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kfserving#1461]
/kind feature

Opening this issue to figure out the release process for KFServing manifests.
Related: https://github.com/kubeflow/katib/issues/1466

KFServing wants to release manifests, in its various releases. Now that manifests live inside upstream app repos, the final result should be committed in this repo, not kubeflow/manifests. In this issue, I will describe a procedure to release manifests, same as what Katib is implementing: https://github.com/kubeflow/katib/issues/1466

**Describe the solution you'd like**

Here is the proposed procedure:
Suppose we have a repo with kustomizations under `manifests`.
Here are the steps that the upstream repository must take:
1. Create a new release branch:
```sh
VERSION="1.0"
git checkout -b release-$VERSION origin/master
```
2. Edit files under manifests (e.g., Deployments) to the release image tag. This can be done manually or with a `sed` command:
```sh
TAG=$VERSION
# Example with sed or manually
find manifests -type f | sed -i "s/<old_image_tag>/$TAG/g"
```
3. Commit changes to the release branch and tag commit as version:
```sh
git commit -s -a -m "Release $VERSION"
git tag $VERSION
git push -u origin release-$VERSION
git push $VERSION
```

4. Create GitHub release from existing tag and add desired release notes.

@pvaneck @animeshsingh what do you think?

**Comment by pvaneck** [comment]
I think this should work fine. I believe KFServing already follows a similar process for making release branches and tags. The only thing we need to do in each release branch before doing a git tag is updating the necessary image tags in https://github.com/kubeflow/kfserving/blob/master/config/configmap/inferenceservice.yaml and https://github.com/kubeflow/kfserving/blob/master/config/default/manager_image_patch.yaml
