### ISSUE TITLE
KFServing should have a consistent way of supporting model download across inference server implementations

### ISSUE THREAD

**Issue by rakelkar** [kubeflow/kfserving#148]
/kind feature

**Describe the solution you'd like**
KFServing should expose a consistent way to download models across inference servers and clouds. The current implementation depends on the features of individual inference servers expose. E.g. see #137 

**Anything else you would like to add:**
Proposed solution design is documented here: https://docs.google.com/document/d/1xqBOkoQ6Vzc5gv4O5MgVVNE3qILbKuMkC-DN5zp5w28/edit?usp=sharing

**Comment by rakelkar** [comment]
@krabhishek8260 @ellis-bigelow @cliveseldon @yuzisun

**Comment by cliveseldon** [comment]
Apart from the needed knative workarounds, the init container solution looks best to me and can be tied into a separate caching layer easily.

**Comment by ellis-bigelow** [comment]
Cool! Can you share this with the kubeflow community?

**Comment by ellis-bigelow** [comment]
Also, i'd title this as model caching or something about unified storage layer instead of "referring to models"

**Comment by rakelkar** [comment]
> model caching

I was hoping to keep the scope to a minimum aka tackle caching once the download part is figured out. Made an attempt to update the title, if you have a better suggestion let me know...

**Comment by ellis-bigelow** [comment]
Sounds good now
