### ISSUE TITLE
Broken link to documentation on using Triton in KFServing

### ISSUE THREAD

**Issue by msalehiNV** [kubeflow/kfserving#1515]
We have a few organizations asking how to use Triton Inference Server within KFServing, but I can't find any documentation to refer them to

I noticed the hyper link on the Kubeflow-Triton docs is broken: https://github.com/kubeflow/kfserving/tree/master/docs/samples/triton

Can you please refer to me where we can find the latest docs / instructions?

**Comment by yuzisun** [comment]
@msalehiNV it is https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/triton
