### ISSUE TITLE
All traffic goes to one gpu pod while other pods stay idle

### ISSUE THREAD

**Issue by daganida88** [kubeflow/kfserving#1520]
/kind bug

**What steps did you take and what happened:**

1. I ran 2 pods, each one requesting 1 gpu that are related to the same inference service and sent a lot of requests.

**What did you expect to happen:**
1. I expected to see the load spread to both of my pods, but instead it all traffic goes to one pod.

**Anything else you would like to add:**
Running kfserving 0.5 installation without kubeflow on kubernets version 1.18 on gke.

Why does it happen?

**Comment by yuzisun** [comment]
@daganida88 Can you provide more details? It is very unlikely it is only hitting one pod if both pods are in ready state.

**Comment by daganida88** [comment]
Hi @yuzisun what can of details do you want? 
Basically what happens is that in the first 10 seconds I am sending messages I see that both gpu are working. Afterwards I see the gpu utilization decreases to 0 and the other gpu is working on 99%.
![image](https://user-images.githubusercontent.com/22128504/114413081-578acf00-9bb6-11eb-8648-19eebfe0afa2.png)

**Comment by daganida88** [comment]
It works.. Not sure what has changed.
