### ISSUE TITLE
terminationGracePeriodSeconds fails in v1Beta1 InferenceService

### ISSUE THREAD

**Issue by danishsamad** [kubeflow/kfserving#1546]
I get a validation error (shown below) when I specify terminationGracePeriodSeconds in the InferenceService yaml. It works fine if I remove this setting. 

 **Warning  InternalError  16m (x22 over 87m)  v1beta1Controllers  fails to reconcile predictor: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: must not set the field(s): spec.template.spec.terminationGracePeriodSeconds**

I tried enabling the feature in the config-features configmap but it did not have any effect

  **kubernetes.podspec-terminationGracePeriodSeconds: enabled**

I expect if the setting is available in the [v1Beta1PredictorSpec]
(https://github.com/kubeflow/kfserving/blob/v0.5.0/python/kfserving/docs/V1beta1PredictorSpec.md) API it should also be configurable through the yaml ?

The Yaml I use is as follows

apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "svcname"
spec:
  predictor:
    serviceAccountName: saacct
    containerConcurrency: 1
    terminationGracePeriodSeconds: 20
    minReplicas: 0
    maxReplicas: 3
    nodeSelector:
      nodekey: nodeval
    tolerations:
    - key: tolerationkey
      operator: Equal
      value: tolerationval
      effect: NoSchedule           
    containers:
    - image: _imageurl_

    
KFServing version: 0.5
KNative version: 0.17.4
K8s version: 1.18.14

**Comment by yuzisun** [comment]
it is not supported as it is not listed [here](https://knative.dev/docs/serving/feature-flags/), but  if you set the `timeout` field then `terminationGracePeriodSeconds` is set accordingly.
