### ISSUE TITLE
## :pill: CI failures summary and remediations

### ISSUE THREAD

**Issue by Sifat1998** [kubeflow/kfserving#1548]
## :pill: CI failures summary and remediations
As of commit 63fd50ff36 (more details [on the Dr. CI page](https://our.intern.facebook.com/intern/opensource/dr_ci/commit/167825833786582/63fd50ff36348975020ef14e7671988aff6c366c/)):

---
* **1/2** failures possibly[\*](https://code.facebook.com/ci/dr-ci-info/ "Currently, only CircleCI and GitHub Actions failures are distinguished as upstream failures") introduced in this PR
    * **1/1** non-scanned failure(s)
* **1/2** [broken upstream](https://our.intern.facebook.com/intern/opensource/ci/regressions/167825833786582/) at merge base fe3f6f2da2 on Apr 19 from  4:34pm to  8:04pm

---
### :construction: 1 fixed upstream failure:
These were probably **caused by upstream breakages** that were **already fixed**.
<details>
<summary>
Please rebase on the <code>viable/strict</code> branch (expand for instructions)
</summary>

If your commit is older than `viable/strict`, run these commands:
```
git fetch https://github.com/pytorch/pytorch viable/strict
git rebase FETCH_HEAD
```
</details>

* [pytorch_linux_xenial_py3_clang5_asan_test2](https://our.intern.facebook.com/intern/opensource/ci/job/195995628825900/) on Apr 19 from  4:34pm to  8:04pm (fe3f6f2da2 - 0d94c04247)
    * [:repeat: rerun](https://our.intern.facebook.com/intern/opensource/ci/restart/195995628825900/)

---
<details><summary>This comment was automatically generated by <a href="https://code.facebook.com/ci/dr-ci-info/">Dr. CI</a> (expand for details).</summary>Follow <a href="https://code.facebook.com/ci/settings/">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions to the (internal) <a href="https://fburl.com/ujo0mikv">Dr. CI Users group</a>.
</details>

__Originally posted by @facebook-github-bot in https://github.com/pytorch/pytorch/pull/56409#issuecomment-822774013__

**Comment by yuzisun** [comment]
this looks like possible spam
