### ISSUE TITLE
Upgrade knative serving vendor

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/kfserving#158]
knative serving 0.6.0 has [released](https://github.com/knative/serving/releases/tag/v0.6.1), but kfserving now cannot work with knative serving 0.6.0

**Comment by yuzisun** [comment]
Why it can not work with knative 0.6 ? We are still using the v1alpha1 I do not think there are breaking changes. I'd prefer waiting for 0.7 release which is for official v1beta1 serving API and then we update vendor to use beta API.

**Comment by hougangliu** [comment]
ok, make sense.
/close
