### ISSUE TITLE
Anonymous credentials for single model serving with s3

### ISSUE THREAD

**Issue by Aaronchoo** [kubeflow/kfserving#1581]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Update [download from s3](https://github.com/kubeflow/kfserving/blob/4fd401e348174f954fee7596dc3d54f197f4aa8c/python/kfserving/kfserving/storage.py#L86) to configure boto3 to use anon credentials if anonymous credentials env is set to true.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Would be nice if anon e2e test were also added.

**Comment by mkbhanda** [comment]
May I be assigned this issue?

**Comment by Aaronchoo** [comment]
> May I be assigned this issue?

I don't believe anyone is working on this issue so by all means go for it! :)

**Comment by mkbhanda** [comment]
Thanks @Aaronchoo!
1)  is there already an environment variable defined for Anon?
The only ones I found with grep are: "AZ_TENANT_ID", "AZ_CLIENT_ID", "AZ_CLIENT_SECRET", AZ_SUBSCRIPTION_ID",
python/kfserving/kfserving/storage.py:        headers_json = os.getenv(host_uri + _HEADERS_SUFFIX, "{}")
2) If the Anon environment variable is set and credentials as above, my guess is to use the credentials? Is that the desired behavior?
3) With rest to additional test cases: no anon or credentials set, anon set, anon & credentials set.

**Comment by mkbhanda** [comment]
@Aaronchoo you will have to do the assign

**Comment by Aaronchoo** [comment]
Hi @mkbhanda!

To answer your questions:
1. The environment variable is [defined in s3_secret.go](https://github.com/kubeflow/kfserving/blob/master/pkg/credentials/s3/s3_secret.go#L35). You will need to redefine the variable in `storage.py`. The environmental variable is [appended on this line](https://github.com/kubeflow/kfserving/blob/master/pkg/credentials/s3/s3_secret.go#L137).
2. The current desired behaviour is to use anonymous credentials when the annotation is define AND set to `True`.
3. There is a comment that sorta explained it in the [s3 storage documentation](https://github.com/kubeflow/kfserving/blob/master/docs/samples/storage/s3/README.md#create-s3-secret-and-attach-to-service-account)  (If this is not clear enough feel free to update the documentation) but to be clear I will write out the cases!
- Credentials set + anon set to True: Use anonymous credentials instead
- Credentials set + anon set to False: Use credentials
- Credentials set + anon not defined: Use credentials
- Credentials not set + anon set to True: Use anonymous credentials
- Credentials not set + anon set to False: Use credentials [boto3 searches for it](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials)
- Credentials not set + anon not defined: Use credentials [boto3 searches for it](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials)

Essentially always try to use credentials unless the anon env var is defined and set to `True`.

Hopefully this helps! Thanks :smile:

**Comment by mkbhanda** [comment]
Thank you for the detailed desired behavior and assigning @Aaronchoo !

**Comment by mkbhanda** [comment]
@matty-rose and @mttcnnff on examining test_storage.py and test_s3_storage.py my understanding is that credentials are not considered as part of mocking. Am I missing something?

Moto is a popular library to interact with AWS infrastructure: https://github.com/spulec/moto and been around since 2014.

Based on @Aaronchoo careful explanation of scenarios,  there are 4 cases, env-with-anon-true (disregards secrets in env/config file etc), env-with-secret-credentials, env-clear (boto searches).  Would need to in addition create an S3 object each of type public and private to flex the access options. Can use a python fixture here. We may have some test case bloat!

The essence of my changes in storage.py are:
@staticmethod
    def _download_s3(uri, temp_dir: str):
        # anon environment variable defined in s3_secret.go 
        anon = ("True" == os.getenv("awsAnonymousCredential", "false").capitalize())
        config = None
        if anon:
            config = Config(signature_version=UNSIGNED)
        s3 = boto3.resource('s3', 
                            endpoint_url=os.getenv("AWS_ENDPOINT_URL", "http://s3.amazonaws.com"),
                            config=config)
