### ISSUE TITLE
sklearn.Dockerfile is not presented

### ISSUE THREAD

**Issue by gaodan-fang** [kubeflow/kfserving#1600]
Trying to build my own sklearn server image with `scikit-learn==0.23.2`, following the docs https://github.com/kubeflow/kfserving/tree/master/python/sklearnserver#building-your-own-scikit-learn-server-docker-image

The `sklearn.Dockerfile ` file is not presented in the directory.

**Comment by yuzisun** [comment]
it is here https://github.com/kubeflow/kfserving/blob/master/python/sklearn.Dockerfile, you need to navigate up one directory level to the python directory.

**Comment by gaodan-fang** [comment]
@yuzisun ah thanks for point out!
