### ISSUE TITLE
Proposal: Add Go Client Libraries fo KFservice

### ISSUE THREAD

**Issue by cliveseldon** [kubeflow/kfserving#161]
/kind feature

Should we autogen client libraries for our types in Go?
This will allow users of KfServing to easily manipulate kfservices.

There seems to be an open issue for this on kubebuilder https://github.com/kubernetes-sigs/kubebuilder/issues/403 which suggests as the k8s Go client has dynamic-client then this is not required. 

It still seems to me to have static exposed client informers etc would still be useful and easy to add/update as per other libraries such as knative do.

**Comment by ellis-bigelow** [comment]
Would love to hear more about the knative approach here. Generally, I'm supportive of this type of thing :).

**Comment by yuzisun** [comment]
everything was generated pre-kubebuilder time, it is gone since kubebuilder switches to use dynamic-client, but we can still use the codegen script to generate those static client library.

**Comment by yuzisun** [comment]
I added this https://github.com/kubeflow/kfserving/issues/160, I guess for user python makes more sense ?
