### ISSUE TITLE
Concerns on default KFSERVING_VERSION in python SDK 

### ISSUE THREAD

**Issue by Peilun-Li** [kubeflow/kfserving#1612]
/kind bug

Curious what's the considerations in our python SDK https://github.com/kubeflow/kfserving/blob/master/python/kfserving/kfserving/constants/constants.py#L23 that we default KFSERVING_VERSION to v1alpha2 instead of v1beta1? The mismatch between the default value and the cluster KFServing version can create pitfalls sometimes.

**Comment by yuzisun** [comment]
@Peilun-Li this constant is only used in e2e tests looks, in the KFS client API we are defaulting to v1beta1 https://github.com/kubeflow/kfserving/blob/42007c532286a1e43893ef2be03b15e104bfd7a4/python/kfserving/kfserving/api/kf_serving_client.py#L310
