### ISSUE TITLE
TorchServe & Tornado conflict return

### ISSUE THREAD

**Issue by MatthiasVDDooren** [kubeflow/kfserving#1617]
/kind bug

**What steps did you take and what happened:**
I'm trying to deploy a HuggingFace layoutlm model using torchserve and a custom handler. 
In order to be able to use the layoutlm model, I supply a custom requirements.txt file with transformers 4.5.0 in it.

I can successfully predict using the model, but I cannot return the output due to the following reason:
TorchServe expects to return a `list`, however, this conflicts with Tornado resulting in: 
`TypeError: write() only accepts bytes, unicode, and dict objects. Lists not accepted for security reasons; see http://www.tornadoweb.org/en/stable/web.html#tornado.web.RequestHandler.write`

When trying to return a dict, or any other format, TorchServe throws the following error:
`Invalid return type: <type>`

**What did you expect to happen:**
To be able to return a prediction

**Anything else you would like to add:**
LayoutLM model by HuggingFace
requirements.txt with transformers 4.5.0

**Environment:**

- Istio Version: 1.7.3
- Knative Version: 0.14.3
- KFServing Version: 0.6.0
- Kubeflow version: 1.2.0
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Kubernetes version: (use `kubectl version`): v1.18.14

**Comment by yuzisun** [comment]
@MatthiasVDDooren Are you using the kfserving/torchserve wrapper(kfs pytorch spec) from v1beta1 API?

**Comment by MatthiasVDDooren** [comment]
@yuzisun I am using the V1beta1 pytorch predictor spec, if that is what you mean. The following code is used to generate the isvc:
`api_version = constants.KFSERVING_GROUP + '/' + constants.KFSERVING_V1BETA1_VERSION

    isvc = V1beta1InferenceService(api_version=api_version,
                                   kind=constants.KFSERVING_KIND,
                                   metadata=V1ObjectMeta(
                                       name='layout-lm-pytorch',
                                       namespace='development',
                                       deletion_grace_period_seconds=60,

                                   ),
                                   spec=V1beta1InferenceServiceSpec(predictor=V1beta1PredictorSpec(min_replicas=1,
                                                                                                   max_replicas=1,
                                                                                                   pytorch=V1beta1TorchServeSpec(
                                                                                                       resources=V1ResourceRequirements(
                                                                                                           requests={
                                                                                                               'memory': "400Mi",
                                                                                                               'cpu': '200m'
                                                                                                           }
                                                                                                       ),
                                                                                                       storage_uri=model_path))
                                                                    ))
    return isvc`

**Comment by yuzisun** [comment]
I do not think torchserve enforces the type to be a list according to their [doc](https://pytorch.org/serve/custom_service.html#custom-handlers) and torchserve/kfs [wrapper](https://github.com/pytorch/serve/blob/master/kubernetes/kfserving/kfserving_wrapper/TorchserveModel.py) always expects dict, would you be able to return the dict from your custom handler?

**Comment by MatthiasVDDooren** [comment]
@yuzisun I have already tried to return a dict and got the following error:
`[INFO ] W-9000-layout-lm-pytorch_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - model: layout-lm-pytorch, Invalid return type: <class 'dict'>.`

**Comment by yuzisun** [comment]
> @yuzisun I have already tried to return a dict and got the following error:
> `[INFO ] W-9000-layout-lm-pytorch_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - model: layout-lm-pytorch, Invalid return type: <class 'dict'>.`

@MatthiasVDDooren I wonder how this [example](https://github.com/pytorch/serve/blob/master/examples/image_classifier/mnist/mnist_handler.py) works, maybe you are returning numpy list instead of python list?

**Comment by MatthiasVDDooren** [comment]
@yuzisun That seems to have done it. Now I'm only getting 507 errors, but that's solvable.

I presume I was returning a numpy list instead of a python list. Thanks!
