### ISSUE TITLE
Several Issues with the KFServing MMS Triton README

### ISSUE THREAD

**Issue by shashank3959** [kubeflow/kfserving#1621]
/kind bug

**What steps did you take and what happened:**
Following the steps in the README is not a seamless experience. It seems like several commands/instructions are outdated.

1) README mentions “ You must set Triton's multiModelServer flag in inferenceservice.yaml to true to enable multi-model serving for Triton” -- but MMS only worked for me when the multimodelserver flag was set in the kfserving.yaml file used in installation (eg. install/v0.5.1/kfserving.yaml).

2) The README mentions “Setup Minio for storing the models as currently model agent sidecar only supports S3 protocol.”, but it looks like gs:// protocol is also supported now as I was able to specify model location in a GCS bucket.

3) In minio.yaml, the apiVersion is specified as extensions/v1beta1. However, that gives an error:
"**error: unable to recognize "minio.yaml": no matches for kind "Deployment" in version "extensions/v1beta1**"

From https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ :
“Deployment in the extensions/v1beta1, apps/v1beta1, and apps/v1beta2 API versions is no longer served. Migrate to use the apps/v1 API version, available since v1.9.”
So, in minio.yaml the apiVersion should be updated 
`apiVersion: extensions/v1beta1 → apiVersion: apps/v1`

4) The README mentions “**Setup Minio for storing the models as currently model agent sidecar only supports S3 protocol.**”, but it looks like gs:// protocol is also supported now as I was able to specify model location in a gcs bucket

5) Copying cifar10 model to minio gives the following error:
`mc cp -r cifar10 myminio/triton/torchscript`
**mc: <ERROR> Failed to copy `cifar10/1/model.pt`. Bucket `triton` does not exist.**
**mc: <ERROR> Failed to copy `cifar10/config.pbtxt`. Bucket `triton` does not exist.**
We may need to create a Triton bucket before copying

6) The command to copy the simple_string model to mc is missing the destination argument.
`gsutil cp -r gs://kfserving-samples/models/triton/simple_string`

7) It looks like the model “gs://kfserving-samples/models/triton/simple_string” has moved, or does not exist at that path.
There is a simple_string model at "gs://kfserving-samples/models/tensorrt/simple_string/” -- is this the one to use in this example?

8) In the section to Deploy the "Cifar10 Torchscript Model", the command provided is the one to start the InferenceService, instead of specifying a TrainedModel:
`kubectl apply -f multi_model_triton.yaml` 
should be
`kubectl apply -f trained_model.yaml`

9) For the simple_string Tensorflow model, the framework specified in it's trained_model2.yaml is "pytorch"

Other Suggestions:
1) It would be great to indicate that the following command should be run from another terminal.
**kubectl port-forward $(kubectl get pod --selector="app=minio" --output jsonpath='{.items[0].metadata.name}') 9000:9000**

2) To make the example simpler, is it possible to directly use gs:// instead of minio s3?

**What did you expect to happen:**
The list of steps provided for the examples should execute without any errors to provide a seamless experience to new users.

**Environment:**
- Istio Version: 1.9.0
- Knative Version: 0.18.0
- KFServing Version: 0.5.1
- Kubeflow version: -
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version: 1.17.1
- Kubernetes version: (use `kubectl version`): Client: v1.20.4, Server: v1.20.2
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.2 LTS (Focal Fossa)

**Comment by yuzisun** [comment]
Thanks @shashank3959! Will update the doc to use gcs which is much easier for the example.
