### ISSUE TITLE
Invalid Header Host when creating example Model

### ISSUE THREAD

**Issue by GetOn4** [kubeflow/kfserving#1638]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I installed kubeflow 1.3 with kfserving v0.6.0-rc0 on an eks cluster and tried to deploy an example model from the samples 
After debugging TLS for Knative I've got the message that  
Ingress reconciliation failed
on the kubeflow dashboard, models tab.

The logs from the kfserving-controller pod showing the following error:
`"controller-runtime.manager.controller.inferenceservice","msg":"Reconciler error","reconciler group":"serving.kubeflow.org","reconciler kind":"InferenceService","name":"torchserve","namespace":"lars","error":"fails to reconcile ingress: fails to create or update ingress: admission webhook \"validation.istio.io\" denied the request: configuration is invalid: invalid header \"Host\": cannot set Host header","errorVerbose":"admission webhook \"validation.istio.io\" denied the request: configuration is invalid: invalid header \"Host\": cannot set Host header\nfails to create or update ingress\ngithub.com/kubeflow/kfserving/pkg/controller/v1beta1/i`

**What did you expect to happen:**
I expect that I get an endpoint to ping the model for predictions

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 
- Knative Version: 0.22
- KFServing Version: v0.6.0-rc0
- Kubeflow version: 1.3
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
`
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-eks-7737de", GitCommit:"7737de131e58a68dda49cdd0ad821b4cb3665ae8", GitTreeState:"clean", BuildDate:"2021-03-10T21:33:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
`
- OS (e.g. from `/etc/os-release`):

**Comment by beyersito** [comment]
I'm having the same issue

**Comment by GetOn4** [comment]
Did you get any information or know the reason?

**Comment by GetOn4** [comment]
Shoule be fixed with 
https://github.com/kubeflow/kfserving/pull/1646
