### ISSUE TITLE
try to create an InferenceService but meet this

### ISSUE THREAD

**Issue by chengsky-NTU** [kubeflow/kfserving#1642]
/kind bug
try to create an InferenceService, but meet this:'V1beta1InferenceService' object has no attribute 'swagger_types'
![图片](https://user-images.githubusercontent.com/73595772/120431174-b5fc4e80-c3aa-11eb-8587-1e1bce804850.png)

**Environment:**

- Istio Version:
- Knative Version:0.11.0
- KFServing Version:0.5.1
- Kubeflow version:1.0.2
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):1.15.2
- OS (e.g. from `/etc/os-release`):ubuntu

**Comment by yuzisun** [comment]
@chengsky-NTU What's the kubernetes-python version you are using, v1beta1 is already migrated from swagger to openapi.

**Comment by yuzisun** [comment]
I think you are on the older version of python kubernetes client which still uses swagger_types.
