### ISSUE TITLE
different InferenceService name and model_name returns 404 [torch serve]

### ISSUE THREAD

**Issue by AntPeixe** [kubeflow/kfserving#1656]
/kind bug

**What steps did you take and what happened:**
Trying to serve a torch model for which I only have available the TAR file with the config folder and model-store/mar file.
Because of this it may happen that the `model_name` value is not the same as the name of the Inference Service is being created.
When trying to make a prediction the inference is routed to  `v1/models/<InferenceServiceName>:predict`
which then results in `404: Model with name <InferenceServiceName> does not exist` since the registered model has the name defined in the config file.

Is it possible to work around this or am I really locked at having to match the two names? Is there a way to make a map between the names? Maybe in the `initialize` function of the handler?

**Environment:**

- Istio Version: 1.6.0
- Knative Version: (from kubeflow)
- KFServing Version: (from kubeflow)
- Kubeflow version: 1.2.0
- Kfdef: kfctl_azure.v1.2.0.yaml 
- Kubernetes version: 1.21.0

**Comment by yuzisun** [comment]
@AntPeixe check the [torchserve example](https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/torchserve), I do not think we require the model name to be the same as the inference service name. Can you provide your inference service yaml? When you make the prediction call the path should be `v1/models/<ModelName>:predict`

**Comment by AntPeixe** [comment]
I figured out what I was doing wrong with the names and you are correct.

**Comment by tongtaott** [comment]
@AntPeixe I also encountered this problem. Can you tell me how you solved it？
