### ISSUE TITLE
Improvements to self-signed-ca.sh

### ISSUE THREAD

**Issue by elukey** [kubeflow/kfserving#1657]
/kind bug

**What steps did you take and what happened:**
Hi! I am trying to deploy kfserving 0.5 on minikube for testing (k8s 1.20, istio 1.6.14, knative 0.18.1 and go 1.15) and I am using the `self-signed-ca.sh` script instead of cert-manager. The script works fine, but I end up getting two separate errors when deploying a simple `InferenceService` resource:

* `x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching` - this one seems to be due to how the TLS certificate is created in https://github.com/kubeflow/kfserving/blob/master/hack/self-signed-ca.sh#L97, since from what I can see the `.csr` contains SANs but the `.crt` does not. I ended up fixing it adding `-extensions v3_req` to the cmd line, to force the .crt to pick up the SANs. After applying this fix the error went away, and I got the next one.
* `Error from server: error when creating "service.yaml": conversion webhook for serving.kubeflow.org/v1alpha2, 
Kind=InferenceService failed: Post "https://kfserving-webhook-server-service.kfserving-system.svc:443/convert?timeout=30s": 
x509: certificate signed by unknown authority` - in this case it seems that the webhook responsible to convert APIs versions is not patched by the `self-signed-ca.sh` script, so its CABundle remains empty ending up in the above error. This happens if I use the `v1alpha2` API, meanwhile if I use the `v1beta1` everything works as expected.

Thanks in advance!

**What did you expect to happen:**
The script should run, patch the various webhooks with custom CA + TLS cert and it should be possible to deploy an InferenceService without errors.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.6.14
- Knative Version: 0.18.1
- KFServing Version: 0.5
- Kubeflow version: (kfserving standalone)
- Minikube version: v1.19.0
- Kubernetes version: (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): Debian 11 (Bullseye)

**Comment by haijohn** [comment]
Maybe this [PR ](https://github.com/kubeflow/kfserving/pull/1603)can solve your issue

**Comment by elukey** [comment]
> Maybe this [PR ](https://github.com/kubeflow/kfserving/pull/1603)can solve your issue， you can try the latest scripts in master branch

Hi @haijohn! The errors reported above are related to the master version of the script, I am aware of the patches to mutating and validating webhooks. What it is missing, in my opinion, is the patch to the conversion webhook that's missing (the caBundle doesn't get updated by the script). In my case, when a conversion between versions needed to happen, the unable to validate etc.. error popped up.

**Comment by haijohn** [comment]
> > Maybe this [PR ](https://github.com/kubeflow/kfserving/pull/1603)can solve your issue， you can try the latest scripts in master branch
> 
> Hi @haijohn! The errors reported above are related to the master version of the script, I am aware of the patches to mutating and validating webhooks. What it is missing, in my opinion, is the patch to the conversion webhook that's missing (the caBundle doesn't get updated by the script). In my case, when a conversion between versions needed to happen, the unable to validate etc.. error popped up.

I see, so we also need to patch the conversion webhook caBundle in the inferenceservice CRD

**Comment by elukey** [comment]
> > > Maybe this [PR ](https://github.com/kubeflow/kfserving/pull/1603)can solve your issue， you can try the latest scripts in master branch
> > 
> > 
> > Hi @haijohn! The errors reported above are related to the master version of the script, I am aware of the patches to mutating and validating webhooks. What it is missing, in my opinion, is the patch to the conversion webhook that's missing (the caBundle doesn't get updated by the script). In my case, when a conversion between versions needed to happen, the unable to validate etc.. error popped up.
> 
> I see, so we also need to patch the conversion webhook caBundle in the inferenceservice CRD

Yep this is my idea as well, but I didn't find a way to patch the CRD yet :D

**Comment by haijohn** [comment]
the caBundle resides in this patch file: https://github.com/kubeflow/kfserving/blob/595186347aad89218c8e8866b77052f59de68417/config/default/inferenceservice_conversion_webhook.yaml#L3-L19
so, you can replace the caBundle with a patch as follows:
```bash
conversionPatchString='[{"op": "replace", "path": "/spec/conversion/webhook/clientConfig/caBundle", "value":"{{CA_BUNDLE}}"}]'
conversionPatchString=$(echo ${conversionPatchString} | sed "s|{{CA_BUNDLE}}|${caBundle}|g")
kubectl patch CustomResourceDefinition inferenceservices.serving.kubeflow.org \
    --type='json' -p="${conversionPatchString}"
```

**Comment by elukey** [comment]
@haijohn worked nicely, just tested it on minikube. I updated my pull request to include your fix (added you as co-author, lemme know if it is ok).

**Comment by haijohn** [comment]
> @haijohn worked nicely, just tested it on minikube. I updated my pull request to include your fix (added you as co-author, lemme know if it is ok).

Hi，@elukey, It's ok.  According to this https://github.com/kubeflow/kfserving/issues/1618 issue，v1alpha2 will be deprecated in the future release，so the conversion webhook may no longer needed or maybe there will be a v1/v1beta conversion.  To be future compatible,  I think some error check (caBundle not exists) may also needed.

**Comment by elukey** [comment]
@haijohn good point, but I think that we could simply report this note to the other issue and let future changes to lead the next step (should be easier to fix when it will be clear how the conversion webhook will be used in the future, maybe it will be needed for a lot of next releases). Let me know what you think, if you feel strongly about adding a check I'll work on it.

**Comment by yuzisun** [comment]
fixed in https://github.com/kubeflow/kfserving/pull/1661
