### ISSUE TITLE
Unable to deploy with TorchServe

### ISSUE THREAD

**Issue by AahanSingh** [kubeflow/kfserving#1704]
/kind bug

Any help is appreciated. 

**What steps did you take and what happened:**

1. Installed Kubeflow on AWs via the AWS deployment [guide](https://www.kubeflow.org/docs/distributions/aws/deploy/install-kubeflow/).
2. Tested KFserving installation via this [guide](https://github.com/kubeflow/kfserving#test-kfserving-installation) 
3. Tried running a pytorch server via this [guide](https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/torchserve) . Ran `kubectl apply -f gpu.yaml`
4. Changed `APIVersion` in the gpu.yaml spec to `serving.kubeflow.org/v1alpha2` and reran `kubectl apply -f gpu.yaml` 

**What did you expect to happen:**

1. InferenceService should have been deployed. It wasn't. I got the error : `error: unable to recognize "gpu.yaml": no matches for kind "InferenceService" in version "serving.kubeflow.org/v1beta1"`. 
2. On changing the APIVersion and rerunning `kubectl apply -f gpu.yaml` got this error: `Error from server: error when creating "gpu.yaml": admission webhook "inferenceservice.kfserving-webhook-server.validator" denied the request: Exactly one of [Custom, ONNX, Tensorflow, Triton, SKLearn, XGBoost] must be specified in PredictorSpec`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

- `kfserving-controller-manager-0` exists in the `kubeflow` namespace. 
- Documentation for KFServing installation has broken links [here](https://github.com/kubeflow/kfserving#standalone-kfserving-installation) `kubectl apply -f https://github.com/kubeflow/kfserving/releases/download/$TAG/kfserving.yaml` doesnt work because the url is invalid. 

**Environment:**

- Istio Version: 13.1
- Knative Version: 
- KFServing Version:
- Kubeflow version: 1.2.0
- Kfdef: istio_dex
- Kubernetes version: (use `kubectl version`): 1.2
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by yuzisun** [comment]
@AahanSingh TorchServe is not supported in kubeflow 1.2, please help upgrade to kubeflow 1.3

**Comment by AahanSingh** [comment]
Is there a guide available to upgrade Kubeflow versions? I am unable to find this.

**Comment by AahanSingh** [comment]
@yuzisun Could you point me to the document that helps upgrade Kubeflow on aws. I have been unsuccessful in finding this.
