### ISSUE TITLE
After deleting isvc, the corresponding Pod will stay in Terminating state for a long time

### ISSUE THREAD

**Issue by SeibertronSS** [kubeflow/kfserving#1706]
Why after deleting isvc, the corresponding Pod will stay in Terminating state for a long time instead of being deleted immediately？

**Comment by yuzisun** [comment]
@SeibertronSS The `TerminationGracePeriod` is set to equal to the request timeout value which is by default 300s, the reason is that inference service pod needs to wait for the possible in flight requests to drain before fully terminating.

**Comment by ben-omji** [comment]
@yuzisun  I have a same issue and my model's inference time is just few seconds. In this situation, how can I change the `TerminationGracePeriod` value?

**Comment by ben-omji** [comment]
@yuzisun Hi, I have a question. How can I change the `TerminationGracePeriod` value in isvc config file?
