### ISSUE TITLE
How to use the pytorchserver image built by myself

### ISSUE THREAD

**Issue by SeibertronSS** [kubeflow/kfserving#1709]
Hello everyone,
Because I want to add some customized functions to the existing pytrochserver, I create a customized docker image. But I don't know how to use this customized image to deploy an isvc.

**Comment by iavinas** [comment]
Just mention it as custom inference service. Examples are here https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/custom

**Comment by SeibertronSS** [comment]
> Just mention it as custom inference service. Examples are here https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/custom

Thank you very much for your suggestion.

**Comment by SeibertronSS** [comment]
> Just mention it as custom inference service. Examples are here https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/custom

I follow the suggestions you give, but I get some problems. 

I build my own docker image according to the [tutorial](https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/custom) and test it locally. It works. 

The following is the abnormal situation.
I publish the inferenceservice through the `custom.yaml` , but the status of the inferenceservice will always become "False". Through the `kubectl describe` command, it is found that inferenceservice can't find the corresponding image. I have pushed the built image to the remote docker repository. At the same time, I find that after the inferenceservice is deplyed, no corresponding pod appears. 

Do you know why this happens?

**Comment by yuzisun** [comment]
@SeibertronSS This is related to https://github.com/kubeflow/kfserving/issues/1719 right? Can we close this issue?

**Comment by SeibertronSS** [comment]
> @SeibertronSS This is related to #1719 right? Can we close this issue?

Yes, we can close this.
