### ISSUE TITLE
MountVolume.SetUp failed for volume "cert" : secret "kfserving-webhook-server-cert" not found

### ISSUE THREAD

**Issue by DineshkumarElumalai** [kubeflow/kfserving#1710]
/kind bug

**What steps did you take and what happened:**
I have installed kfserving as mentioned here https://github.com/kubeflow/kfserving#install-kfserving. But kfserving-controller-manager pod is stuck in container creating state with an error `MountVolume.SetUp failed for volume "cert" : secret "kfserving-webhook-server-cert" not found`

```
$ kubectl get pod -n kfserving-system
NAME                                        READY   STATUS              RESTARTS   AGE
kfserving-controller-manager-0              0/2     ContainerCreating   0          131m
kfserving-models-web-app-84d5d66954-cckfc   1/1     Running             0          131m
```

```
$ kubectl get secret -n kfserving-system
NAME                                   TYPE                                  DATA   AGE
default-token-bvcxz                    kubernetes.io/service-account-token   3      139m
kfserving-models-web-app-token-gfzrc   kubernetes.io/service-account-token   3      139m
kfserving-webhook-server-secret        Opaque                                0      139m
```
**What did you expect to happen:**

Expected `kfserving-controller-manager-0`  to be in running state. 

**Environment:**

- Istio Version: 1.9.3
- Knative Version: v0.23.0
- KFServing Version: v0.6.0
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Kubernetes version: v1.19.6
- OS (e.g. from `/etc/os-release`):  Amazon Linux 2

**Comment by sriharan16** [comment]
Facing a similar issue. Using similar latest versions.
@yuzisun - tagging for better visibility

**Comment by yuzisun** [comment]
@DineshkumarElumalai Do you have cert manager installed?

**Comment by DineshkumarElumalai** [comment]
@yuzisun Yes. It's installed already
```
$ kubectl get pods -n cert-manager
NAME                                      READY   STATUS    RESTARTS   AGE
cert-manager-856445ccb6-67jff             1/1     Running   0          25h
cert-manager-cainjector-ccbd4b457-vjgg5   1/1     Running   0          25h
cert-manager-webhook-74c9955776-tz9wj     1/1     Running   0          25h
```

```
$ kubectl get secrets -n cert-manager
NAME                                  TYPE                                  DATA   AGE
cert-manager-cainjector-token-b6dpj   kubernetes.io/service-account-token   3      59d
cert-manager-token-tfk5p              kubernetes.io/service-account-token   3      59d
cert-manager-webhook-ca               Opaque                                3      59d
cert-manager-webhook-token-m7svf      kubernetes.io/service-account-token   3      59d
default-token-gd76v                   kubernetes.io/service-account-token   3      59d
```

**Comment by yuzisun** [comment]
@DineshkumarElumalai Could not replicate this, can you help get the following output?
`kubectl get certificate -n kfserving-system -oyaml`

**Comment by DineshkumarElumalai** [comment]
@yuzisun I have reinstalled the cert-manager and it worked now. Thank you so much

**Comment by fooozhe** [comment]
Hi @yuzisun, I encounter the same issue, and the `kubectl get certificate -n kfserving-system -oyaml` outputs as follows:
```
apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

Is it normal? And how did reinstall the cert-manager? @DineshkumarElumalai

**Comment by SeibertronSS** [comment]
Hi @DineshkumarElumalai, 
How did you reinstall cert-manager? I have the same problem as you.  I would be very grateful if you could reply.

**Comment by DineshkumarElumalai** [comment]
Hi @SeibertronSS 
To reinstall cert-manager, refer to this document https://cert-manager.io/docs/installation/#default-static-install

> kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.5.4/cert-manager.yaml

**Comment by silverlining21** [comment]
> Hi @SeibertronSS To reinstall cert-manager, refer to this document https://cert-manager.io/docs/installation/#default-static-install
> 
> > kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.5.4/cert-manager.yaml

I got the same issue, tried your solution, bug still exitsts
