### ISSUE TITLE
Unable to install kf-serving standalone v0.6.0 - artifact missing from release. 

### ISSUE THREAD

**Issue by plainenough** [kubeflow/kfserving#1712]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

kubectl apply -f https://github.com/kubeflow/kfserving/releases/download/v0.6.0/kfserving.yaml
error: unable to read URL "https://github.com/kubeflow/kfserving/releases/download/v0.6.0/kfserving.yaml", server reported 404 Not Found, status code=404

**What did you expect to happen:**

kfserving to install based on instructions located in readme. here: https://github.com/kubeflow/kfserving/blob/master/README.md

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Looks like the file doesn't exist in the release.

**Comment by mohakamg** [comment]
> /kind bug
> 
> **What steps did you take and what happened:**
> [A clear and concise description of what the bug is.]
> 
> kubectl apply -f https://github.com/kubeflow/kfserving/releases/download/v0.6.0/kfserving.yaml
> error: unable to read URL "https://github.com/kubeflow/kfserving/releases/download/v0.6.0/kfserving.yaml", server reported 404 Not Found, status code=404
> 
> **What did you expect to happen:**
> 
> kfserving to install based on instructions located in readme. here: https://github.com/kubeflow/kfserving/blob/master/README.md
> 
> **Anything else you would like to add:**
> [Miscellaneous information that will assist in solving the issue.]
> Looks like the file doesn't exist in the release.

Agreed, facing the same bug. Looks like the yaml file was never uploaded to the release 0.6.0

**Comment by yuzisun** [comment]
fixed.
