### ISSUE TITLE
Alibi explainer example times out

### ISSUE THREAD

**Issue by karlschriek** [kubeflow/kfserving#1713]
/kind bug

**What steps did you take and what happened:**

I am rolling out the Alibi Explainer example (as explained here https://github.com/kubeflow/kfserving/tree/v0.6.0/docs/samples/explanation/alibi/imagenet), although I have had to slightly adapt the InferenceService spec (see https://github.com/kubeflow/kfserving/issues/1707) as follows:

```
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: imagenet
  namespace: karl-schriek
spec:
  predictor:
    tensorflow:
      storageUri: "gs://seldon-models/tfserving/imagenet/model"
      resources:
        requests:
          cpu: 0.1
          memory: 5Gi                        
        limits:
          memory: 10Gi
  explainer:
    alibi:
      type: AnchorImages
      storageUri: "gs://seldon-models/tfserving/imagenet/explainer"
      config:
        batch_size: "1" # reduced from 25 in attempt to prevent timeout
        stop_on_first: "True"
        min_samples_start: "1"  # added in attempt to prevent timeout
      resources:
        requests:
          cpu: 0.5
          memory: 5Gi            
        limits:
          memory: 10Gi    
```

Predictor and explainer both roll out successfully. Requesting predictions work fine. Requesting an explaination on a single image results in an eventual timeout. The explainer Pod reports the following:

```
[I 210709 11:10:54 anchor_images:47] Calling explain on image of shape ((1, 299, 299, 3),)
[I 210709 11:10:54 anchor_images:48] anchor image call with {'batch_size': 1, 'stop_on_first': True}
```

After about 20  minutes it eventually also says the following:

```
skimage.measure.label's indexing starts from 0. In future version it will start from 1. To disable this warning, explicitely set the `start_label` parameter to 1.
[E 210709 11:30:11 web:1793] Uncaught exception POST /v1/models/imagenet:explain (127.0.0.1)
    HTTPServerRequest(protocol='http', host='imagenet-explainer-default.karl-schriek.svc.cluster.local', method='POST', uri='/v1/models/imagenet:explain', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/kfserving/kfserving/handlers/http.py", line 105, in post
        response = await model(body, model_type=ModelType.EXPLAINER)
      File "/kfserving/kfserving/kfmodel.py", line 58, in __call__
        else self.explain(request)
      File "/alibiexplainer/alibiexplainer/explainer.py", line 84, in explain
        explanation = self.wrapper.explain(request["instances"])
      File "/alibiexplainer/alibiexplainer/anchor_images.py", line 49, in explain
        anchor_exp = self.anchors_image.explain(arr[0], **self.kwargs)
      File "/usr/local/lib/python3.7/site-packages/alibi/explainers/anchor_image.py", line 409, in explain
        return self.build_explanation(image, result, self.instance_label, params)
      File "/usr/local/lib/python3.7/site-packages/alibi/explainers/anchor_image.py", line 447, in build_explanation
        explanation = Explanation(meta=copy.deepcopy(self.meta), data=data)
    AttributeError: 'AnchorImage' object has no attribute 'meta'
[E 210709 11:30:11 web:2243] 500 POST /v1/models/imagenet:explain (127.0.0.1) 1157265.30ms
```

The documentation states that the explanation may take a while, but surely it shouldn't time out with just a single image? This looks like a timeout, but I am not really sure if the `AttributeError: 'AnchorImage' object has no attribute 'meta'` suggests otherwise.

**What did you expect to happen:**

I would expect the request to succeed within a reasonable space of time.

- Istio Version: 1.10.2
- Knative Version: 0.24
- KFServing Version: 0.6.0
- Kubeflow version: 1.3+
- Kubernetes version: 1.20

**Comment by cliveseldon** [comment]
@karlschriek Which version of Alibi-Explain did you use to train your imagenet explainer?

**Comment by karlschriek** [comment]
@cliveseldon I didn't train my own explainer, the above describes what happens when attempt to roll out an example explainer from "gs://seldon-models/tfserving/imagenet/explainer".

**Comment by cliveseldon** [comment]
ok but the example has `storageUri: "gs://seldon-models/tfserving/imagenet/alibi/0.4.0"`

Not ` "gs://seldon-models/tfserving/imagenet/explainer"`

We need to update the kfserving integration to the latest version of Alibi - as its presently has examples based on 0.4.0

**Comment by karlschriek** [comment]
`gs://seldon-models/tfserving/imagenet/alibi/0.4.0` also gave me trouble, see https://github.com/kubeflow/kfserving/issues/1707. I found the reference to `gs://seldon-models/tfserving/imagenet/explainer` here: https://docs.seldon.io/projects/seldon-core/en/v0.4.1/examples/explainer_examples.html

**Comment by cliveseldon** [comment]
I think the issue may be the Alibi version build in the image is not tied to a particular version but a minimum version

https://github.com/kubeflow/kfserving/blob/v0.6.0/docs/samples/explanation/alibi/imagenet/requirements.txt

So I assume its running the latest Alibi. This may be incompatible with saved explainers from an older Alibi.

I think we need to fix the Alibi version and recreate some of the examples with that version.

**Comment by karlschriek** [comment]
That would be great. The example documentation at the moment is a bit inconsistent as well, so it is a bit hard to figure out what to use. The README refers to 0.4.0 while https://github.com/kubeflow/kfserving/blob/v0.6.0/docs/samples/explanation/alibi/imagenet/imagenet.yaml refers to 0.5.2.
