### ISSUE TITLE
sklearn sample not accessible through postman

### ISSUE THREAD

**Issue by swapkh91** [kubeflow/kfserving#1717]
I tried running the sklearn irirs sample on Kfserving standalone installation.

I installed kfserving using the `/hack/quick_install.sh` script on a GKE cluster.

Now, I am able to get the predictions from the cloud shell by executing:

`SERVICE_HOSTNAME=$(kubectl get inferenceservice sklearn-iris -n kfserving-test -o jsonpath='{.status.url}' | cut -d "/" -f 3)`

`curl -v -H "Host: ${SERVICE_HOSTNAME}" http://${INGRESS_HOST}:${INGRESS_PORT}/v1/models/sklearn-iris:predict -d @./docs/samples/${API_VERSION}/sklearn/v1/iris-input.json`

Result:

>   Trying <INGRESS_HOST>:80...
> TCP_NODELAY set
> Connected to <INGRESS_HOST> (<INGRESS_HOST>) port 80 (#0)
> POST /v1/models/sklearn-iris:predict HTTP/1.1
> Host: sklearn-iris.kfserving-test.example.com
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Length: 76
> Content-Type: application/x-www-form-urlencoded
> 
> upload completely sent off: 76 out of 76 bytes
> Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-length: 23
< content-type: application/json; charset=UTF-8
< date: Mon, 12 Jul 2021 09:02:17 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 5
< 
> Connection #0 to host <INGRESS_HOST> left intact
> {"predictions": [1, 1]}

**INGRESS_HOST** is the external ip of load balancer, I'm hiding the actual value here

But if I try to send a POST request through Postman on the above URL with `INGRESS_HOST` and `INGRESS_PORT` values, I get a 404 error. Below is the log in gcp for that call on `istio-ingressgateway` load balancer service:

`POST /v1/models/sklearn-iris:predict HTTP/1.1" 404 NR route_not_found - "-" 0 0 0 - "10.52.0.1" "PostmanRuntime/7.28.0" "0a70e35c-24db-413d-a5a5-027e5c1e0a6b" "<INGRESS_HOST ip>"-" - - 10.52.0.11:8080 10.52.0.1:63935 - -`

PS - I'm pretty new to this stuff so I might be missing some steps

**Comment by yuzisun** [comment]
@swapkh91 Did you set the host header in postman ?

**Comment by swapkh91** [comment]
> @swapkh91 Did you set the host header in postman ?

Yeah it works!

I never had to change that so didn't even click.

Thanks a lot
