### ISSUE TITLE
Make model files available across Pods on a Node

### ISSUE THREAD

**Issue by swapkh91** [kubeflow/kfserving#1741]
Is there some way to make the model files downloaded from a gcs link to `/mnt/models` be available across Pods on a Node?

I created a service and while load testing I noticed in logs that for every new Pod being created to handle load (mostly during Knative Panic mode) was downloading the model files again from the gcs path. For my usecase that downloading takes time due to multiple files being downloaded.

So what I notice is that new Pods remain in initialization phase beacuse of downloading and the requests get queued.

![Screenshot from 2021-07-28 17-12-57](https://user-images.githubusercontent.com/5755405/127316811-4edd95b8-c78d-4ad4-8fd4-f5852a7c4bfd.png)

The 3rd log shows that during creation of new pod all model files are again being downloaded, while the pending requests are being processed and the last log shows that it took around 10s for service to respond.

Would appreciate any help on this.

**Comment by bartgras** [comment]
I don't think storing data on Nodes is a good Kubernetes practice.
What you could try instead is to have models in the same cluster e.g. in MinIO or setup MinIO as a gateway to GCS [with caching mode enabled](https://docs.min.io/docs/minio-disk-cache-guide.html).

**Comment by swapkh91** [comment]
> I don't think storing data on Nodes is a good Kubernetes practice.
> What you could try instead is to have models in the same cluster e.g. in MinIO or setup MinIO as a gateway to GCS [with caching mode enabled](https://docs.min.io/docs/minio-disk-cache-guide.html).
@bartgras thanks for the reply, I'll try that. I think I need to have a persistent storage for the models
