### ISSUE TITLE
`domain-mapping` and `domainmapping-webhook` stuck in CrashLoopBackoff due to `version check failed`

### ISSUE THREAD

**Issue by dboshardy** [kubeflow/kfserving#1743]
Apologies in advance as this is likely a user error of some kind, but I'm having trouble finding help online on existing questions.

I'm trying to test out getting kfserving working on a private GKE cluster. I set it up using the recommended `kubectl apply` 

```bash
$ TAG=v0.6.0
$ kubectl apply -f https://github.com/kubeflow/kfserving/releases/download/$TAG/kfserving.yaml
``` 

Everything starts fine except for the aforementioned deployments.  Error logs for each look like this:

```
2021-07-29 16:11:03.515 CDT2021/07/29 21:11:03 Registering 4 clients
2021-07-29 16:11:03.515 CDT2021/07/29 21:11:03 Registering 3 informer factories
2021-07-29 16:11:03.515 CDT2021/07/29 21:11:03 Registering 4 informers
2021-07-29 16:11:03.515 CDT2021/07/29 21:11:03 Registering 1 controllers
2021-07-29 16:11:03.527 CDTVersion check failed
```

I've tried rebuilding the cluster and installing things in different orders. Most recently, I started getting this error as well when installing, but functionality remains the same:
```
error: unable to recognize "https://github.com/kubeflow/kfserving/releases/download/v0.6.0/kfserving.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1beta1"
```

I've tried running the sklearn iris example and it runs fine and returns results (once I remembered to enable sidecar injection in that namespace).  But these deployments remain in a failed state.

What is going on here, and how can I make these deployments green?

**Comment by yuzisun** [comment]
@dboshardy looks like you did not install the dependencies https://github.com/kubeflow/kfserving#prerequisites
