### ISSUE TITLE
Helm 3 lint reports deprecated resources

### ISSUE THREAD

**Issue by elukey** [kubeflow/kfserving#1744]
/kind bug

**What steps did you take and what happened:**
Hi! I am trying to create a simple Helm chart for Kfserving using the yaml config file provided, but the linter tells me:

[ERROR] templates/kfserving.yaml: the kind "apiextensions.k8s.io/v1beta1 CustomResourceDefinition" is deprecated in favor of "apiextensions.k8s.io/v1 CustomResourceDefinition"
[ERROR] templates/kfserving.yaml: the kind "apiextensions.k8s.io/v1beta1 CustomResourceDefinition" is deprecated in favor of "apiextensions.k8s.io/v1 CustomResourceDefinition"

I am wondering if there is a reason for using v1beta1 or if we could move to v1 instead.

**What did you expect to happen:**
No lint errors.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.9.5
- Knative Version: 0.18.1
- KFServing Version: 0.6.0
- Kubeflow version: none
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version: 
- Kubernetes version: (use `kubectl version`): 1.16
- OS (e.g. from `/etc/os-release`): Debian Bullseye

**Comment by markwinter** [comment]
`apiextensions.k8s.io/v1` is available from K8S v1.16

The KFServing README suggests using v1.17+ 

So I think it should be okay to upgrade this.

I can make the change if KFServing members agree

**Comment by yuzisun** [comment]
@markwinter Thanks! that will be great! we already have https://github.com/kubeflow/kfserving/issues/1591 to track the issue

**Comment by elukey** [comment]
@yuzisun should we close this and follow up only on #1591?
