### ISSUE TITLE
How to limit the number of revisions for an inference service?

### ISSUE THREAD

**Issue by daganida88** [kubeflow/kfserving#1746]
/kind feature

**Describe the solution you'd like**
I'm not sure if there is a configmap where I can define the number of max revisions per inference service.
[A clear and concise description of what you want to happen.]
I would want to set a number, e.g 5, and this will be the total number of revisions per inference service.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by markwinter** [comment]
I think there isn't a global config but you can set it per service in the YAML with `maxReplicas`

```YAML
spec:
  predictor:
    maxReplicas: 5
```

**Comment by yuzisun** [comment]
@daganida88 Not sure if you meant for `maxReplicas` or max revision, @markwinter answered the for the former, for max revision you can configure `min-non-active-revisions` setting in [config-gc](https://github.com/knative/serving/blob/main/config/core/configmaps/gc.yaml#L94) configmap under `knative-serving` namespace

**Comment by daganida88** [comment]
I meant min-non-active-revisions
