### ISSUE TITLE
kfserving==0.6.0 python package doesn't work with Python 3.9

### ISSUE THREAD

**Issue by elukey** [kubeflow/kfserving#1753]
/kind bug

**What steps did you take and what happened:**
pip3 install kfserving==0.6.0 leads to a ray[serve] install failure, probably due to:
https://github.com/ray-project/tune-sklearn/issues/169

This happens only with Python 3.9

**What did you expect to happen:**
pip3 packages installed correctly without errors

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version: 0.6.0
- Kubeflow version: 
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by rakshithvsk** [comment]
Hi, Facing same issue with Python 3.8.2

Collecting ray[serve]==1.3.0 (from kfserving)
  Could not find a version that satisfies the requirement ray[serve]==1.3.0 (from kfserving) (from versions: )
No matching distribution found for ray[serve]==1.3.0 (from kfserving)
