### ISSUE TITLE
storage-initializer: support AWS_CA_BUNDLE 

### ISSUE THREAD

**Issue by elukey** [kubeflow/kfserving#1766]
/kind feature

**Describe the solution you'd like**
While following [this tutorial](https://github.com/kubeflow/kfserving/blob/master/docs/samples/storage/s3/README.md#create-s3-secret-and-attach-to-service-account) about how to configure the storage-initializer to fetch from an S3 endpoint I found it difficult to find how to add a custom value to the `AWS_CA_BUNDLE` environment variable. The main motivation for me is to avoid TLS validation issues while trying to contact an internal S3 endpoint (we have Openstack Swift exposing an S3 API internally, that uses a TLS certificate signed by our internal CA). I tried first via standard container ENV variables but due to how the storage-initializer is configured (via a ConfigMap IIUC) I didn't find a way to do it easily, so I had to add it to the Docker image itself (we have our own images in our internal registry, very close to official kfserving ones). This worked nicely but it would be way better if there was a more friendly way, maybe adding an annotation to [s3_secret.go](https://github.com/kubeflow/kfserving/blob/master/pkg/credentials/s3/s3_secret.go)? Something like `s3-ca-bundle` or similar, that in turn adds the AWS_CA_BUNDLE environment variable to storage-initializer.

If there is another way please let me know!

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by DontStopMeNow** [comment]
@elukey Hi, did you try setting `serving.kubeflow.org/s3-verifyssl: "0"` in your secrets? Or do you have to verify the connection?

**Comment by elukey** [comment]
@DontStopMeNow I tried as test (and it didn't work), but yes I have to verify the connection :)

**Comment by umka1332** [comment]
For anyone, who will try to use
`    serving.kubeflow.org/s3-verifyssl: "0"`
It doesn't work, but this helps me to disable SSL verification - just set serving.kserve.io/s3-cabundle to an empty string in the same secret annotation:
`    serving.kserve.io/s3-cabundle: ""`
