### ISSUE TITLE
Can the kfserving v1beta1 version be set to deploy isvc in the kubeflow namespace?

### ISSUE THREAD

**Issue by SeibertronSS** [kubeflow/kfserving#1771]
Can the kfserving v1beta1 version be set to deploy isvc in the kubeflow namespace? I know that deploying isvc in the `kubeflow` namespace is not recommended, but is there such a way to accomplish this task?

**Comment by yuzisun** [comment]
The KFS pod mutator has a namespace selector requiring the namespaces not having the `control-plane` label,  you could choose to remove this selector but in general we do not recommend deploying user workload to control plane namespace.

https://github.com/kubeflow/kfserving/blob/master/config/webhook/manifests.yaml#L52
