### ISSUE TITLE
What are the benefits of using Transformer

### ISSUE THREAD

**Issue by SeibertronSS** [kubeflow/kfserving#1783]
What are the benefits of using `Tromsformer` for data pre-processing and post-processing than directly overwriting `preprocess` and `postprocess` in `KFModel`

**Comment by SeibertronSS** [comment]
@swapkh91 Thanks for your suggestion. Is the working method of Transformer interpreted as the following form? The client's data will be sent to the `Transformer` container, where it will call the prediction function in `predictor` through gRPC to get the inference result of the model. And kfserving will automatically configure gRPC related files for me?

**Comment by markwinter** [comment]
The Transformer only handles HTTP predictions.

You will need to override the `predict` to implement gRPC

Like this

```PYTHON
class Transformer(kfserving.KFModel):
    def __init__(self, name: str, predictor_host: str):
        super().__init__(name)

        self.channel = grpc.insecure_channel(f"{predictor_host}:80")
        self.stub = your_service_grpc.PredictServiceStub(self.channel)

    def preprocess(self, inputs: Dict) -> Dict:
        ...

    def predict(self, features: Dict) -> list:
        ...

        response = self.stub.Predict(request, timeout=10.0)

        ...

    def postprocess(self, result: list) -> Dict:
        ...
```

**Comment by SeibertronSS** [comment]
@markwinter Thank you very much for your suggestion.
