### ISSUE TITLE
Model specific custom python requirements for V1beta1TorchServeSpec not woks

### ISSUE THREAD

**Issue by yurkoff-mv** [kubeflow/kfserving#1804]
I have a model, I created a mar-file with option `-requirements-file "./requirements_model.txt"`
I specify a line `install_py_dep_per_model=true`  in the file **config.properties**.

File requirements_model.txt contains:
`transformers==4.10.1`

My code:
```
pytorch_predictor=V1beta1PredictorSpec(
    pytorch=V1beta1TorchServeSpec(
        storage_uri='pvc://torchserve-pv-claim/torchserve',
        resources=V1ResourceRequirements(requests={'cpu':'1000m', 'memory':'4Gi', 'nvidia.com/gpu': '1'},
                                         limits={'cpu':'1000m', 'memory':'8Gi', 'nvidia.com/gpu': '1'}),
    )
)

isvc = V1beta1InferenceService(api_version=constants.KFSERVING_V1BETA1,
                               kind=constants.KFSERVING_KIND,
                               metadata=client.V1ObjectMeta(name=model_name, namespace=namespace),
                               spec=V1beta1InferenceServiceSpec(predictor=pytorch_predictor))

KFServing = KFServingClient()
KFServing.create(isvc)
```

`!kubectl exec {POD} -n default -c kfserving-container -- python -c "import transformers; print(transformers.__version__)"`
`2.3.0`

Why version transformers in contaiter if pod is 2.3.0 and not 4.10.1?

`!kubectl logs -n default {POD} -c kfserving-container`
```
Torchserve version: 0.3.0
...
```
How can I update the version of the Torchserve?

**Comment by yuzisun** [comment]
@yurkoff-mv  please see https://github.com/kubeflow/kfserving/issues/1560, the default torchserve version is still 0.3.0, but you can add `runtime_version=v0.4.0` on your `V1beta1TorchServeSpec`.

**Comment by yurkoff-mv** [comment]
Hello, last version torchserve is 0.4.0
https://hub.docker.com/r/kfserving/torchserve-kfs/tags?page=1&ordering=last_updated
Please add GPU support.

**Comment by yurkoff-mv** [comment]
Without waiting for an answer to my request, I solved the problem in the following way:
```
microk8s kubectl edit configmap inferenceservice-config -n kubeflow
```
Edit lines according to:
```
"pytorch": {
            "v1": {
                "image": "gcr.io/kfserving/pytorchserver",
                "defaultImageVersion": "v0.5.1",
                "defaultGpuImageVersion": "v0.5.1-gpu",
                "supportedFrameworks": [
                    "pytorch"
                ],
                "multiModelServer": false
            },
            "v2": {
                "image": "pytorch/torchserve-kfs",
                "defaultImageVersion": "0.4.1",
                "defaultGpuImageVersion": "0.4.1-gpu",
                "supportedFrameworks": [
                    "pytorch"
                ],
                "multiModelServer": false
            }
        },
```
