### ISSUE TITLE
User install guide for 0.1

### ISSUE THREAD

**Issue by rakelkar** [kubeflow/kfserving#192]
/kind feature

**Describe the solution you'd like**
A simple user guide that links to KNative setup and a set of YAMLs for KFServing 0.1
Possibly a /install folder with said YAMLs

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by ellis-bigelow** [comment]
This is addressed. Front page readme include instructions. More detailed instructions to follow in future releases as the product becomes more complex.
/close
