### ISSUE TITLE
question: The scope of the repo

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/kfserving#2]
Hi, I am working on Model Serving these days and interested in contributing to this repo. Do we have any doc or design proposal of this repo? Are we trying to implement a Serving CRD?

**Comment by abhi-g** [comment]
@ellis-bigelow is working on a ROADMAP document that will be available in next couple days

**Comment by ellis-bigelow** [comment]
Hi Ce,
We're hoping to implement a CRD for a "unit of model serving". We're limiting our scope to just this for now, but eventually we may shift towards model server standardization, explainability, payload logging.

We hope to cover 80% of use cases. See my PR for more details.

If you're curious about the origin of this, see https://github.com/kubeflow/kubeflow/issues/2306
