### ISSUE TITLE
[feature request] request-response logging

### ISSUE THREAD

**Issue by ryandawsonuk** [kubeflow/kfserving#201]
This is to have an issue to track the discussion we've already started.

kf-serving's use of knative makes the [knative observability stack](https://knative.dev/docs/serving/samples/telemetry-go/) available to use in a straightforward way. This includes a lot of telemetry out of the box but request-response logging can be a bit more subtle, especially for machine learning. The simplest case is if one just wants an audit trail of traffic. This can be handled by getting raw payloads (possibly via an istio configuration) and outputting to stdout for fluentd/fluentbit collection. Where complexity grows is if one wants to make the data searchable, say to make it easy to link the request-response pairs, search by a business-relevant identifier (say customerId or orderId), search by a particular feature value, distinguish individual requests vs batch requests or handle image/binary data differently (e.g. send images to different storage and perhaps label them for retrieval).

This has been [discussed with the knative team](https://github.com/knative/observability/issues/41). In the [seldon-core project we faced the same challenge](https://github.com/knative/observability/issues/41#issuecomment-503756376) and decided to use a sidecar that sends the request-response pairs to a configurable request logging step which sits behind a knative broker (using knative eventing).

@animeshsingh put together https://docs.google.com/document/d/1MBl5frM9l_wyQkYEaDeHOP6Mrsuz9YOob7276AAN9_c/edit to summarise research on what could be done for kf-serving. The discussion is on-going - raising this issue to track the on-going work.

**Comment by animeshsingh** [comment]
Thanks @ryandawsonuk. @ellis-bigelow fyi - we intend to revisit this post v0.1
https://docs.google.com/document/d/1MBl5frM9l_wyQkYEaDeHOP6Mrsuz9YOob7276AAN9_c/edit to s

**Comment by ryandawsonuk** [comment]
Should this be added to https://github.com/kubeflow/kfserving/blob/master/ROADMAP.md ?

**Comment by animeshsingh** [comment]
Thanks @ryandawsonuk. I have added it in the PR as one of the items
https://github.com/kubeflow/kfserving/pull/230

**Comment by ryandawsonuk** [comment]
@animeshsingh I remember some work was done to log from a custom lua filter in the istio sidecar. Is that work or a snippet from it available anywhere to look at?

**Comment by ryandawsonuk** [comment]
Implemented by https://github.com/kubeflow/kfserving/pull/467
