### ISSUE TITLE
Proposal: support model initialization for CustomSpec via a well known env var

### ISSUE THREAD

**Issue by rakelkar** [kubeflow/kfserving#219]
/kind feature

**Describe the solution you'd like**
Support model initialization for CustomSpec by adding a well known environment variable KFSERVING_CUSTOMSPEC_MODEL_URI that gets mutated by the model initialization injector.

A custom spec user would be required to:
1. set KFSERVING_CUSTOMSPEC_MODEL_URI env var
2. use the KFSERVING_CUSTOMSPEC_MODEL_URI env var in custom container code or as a command line arg

Custom spec framework would:
1. look for env var and return its value as ModelUri for injection
2. replace the env var value with the default path

**Anything else you would like to add:**
Also need an example so users know how to use this

**Comment by rakelkar** [comment]
good first issue

**Comment by ellis-bigelow** [comment]
We should contrast this with other options:

1. Include ModelURI or MountURI as part of custom spec
2. Provide a PodTemplate like spec instead of Custom

**Comment by rakelkar** [comment]
implemented by #222
