### ISSUE TITLE
Updates needed for KNative 0.7

### ISSUE THREAD

**Issue by cliveseldon** [kubeflow/kfserving#221]
/kind bug

Knative 0.7 has changed the [route status to have URL and not Domain](https://github.com/knative/serving/commit/15ec3a3d144657d4676cac8b66864f50a2c0de53#diff-17cfcfa333468946627364581e2c7c53). We need to change our status update to use this otherwise samples are broken.

We should specify we need Knative 0.6 for current release.

**Environment:**

- Istio Version:
- Knative Version: 0.7
- KFServing Version: 0.1

**Comment by ellis-bigelow** [comment]
Related to #190

**Comment by ryandawsonuk** [comment]
Is this still valid (as the project is now using 0.8)?

**Comment by rakelkar** [comment]
Yes it is no longer relevant
