### ISSUE TITLE
KFservice status missing replicas

### ISSUE THREAD

**Issue by SachinVarghese** [kubeflow/kfserving#226]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Installed kfserving v0.1.0 on a GKE cluster and smoke tested the sklearm example at `docs/samples/sklearn` I have got a kfservice created with a pod running. The status of the kfservice has a url created but no replicas section under the `default` object.

```
"status": {
        "canary": {},
        "conditions": [
            {
                "lastTransitionTime": "2019-07-08T18:52:11Z",
                "status": "True",
                "type": "DefaultPredictorReady"
            },
            {
                "lastTransitionTime": "2019-07-08T18:52:13Z",
                "status": "True",
                "type": "Ready"
            },
            {
                "lastTransitionTime": "2019-07-08T18:52:13Z",
                "status": "True",
                "type": "RoutesReady"
            }
        ],
        "default": {
            "name": "sklearn-iris-default-g4bgl",
            "traffic": 100
        },
        "url": "sklearn-iris.default.example.com"
    }
```

**What did you expect to happen:**
The status from the kfservice should have had a replicas number for the default serving.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: Installation From kubeflow master branch
- Knative Version: v0.6.0
- KFServing Version: v0.1.0
- Kubeflow version: Installation From kubeflow master branch
- Minikube version: NA (GKE Cluster)
- Kubernetes version: (use `kubectl version`): v1.14.1
- OS (e.g. from `/etc/os-release`): Ubuntu 19.04

**Comment by ellis-bigelow** [comment]
Thanks!

/area project-health

**Comment by yuzisun** [comment]
The number of replicas changes during autoscaling and knative has scaling dashboard which already records the metrics for number of pods. @ellis-bigelow Do you think we need this field on status ?

**Comment by rakelkar** [comment]
+1 to removing replica count from status

**Comment by SachinVarghese** [comment]
I believe the KFservice status could provide vital information on if the pods are scaled down to zero (which means service is in a dormant state) or if the number of pods has already reached the maximum threshold specified. This data is very closely tied to the status of the service itself and hence in my opinion having replica count itself in the KFservice status could be really useful.
@yuzisun can you give some info on how I can utilize the knative scaling dashboard to monitor the number of pods? Do we have a demo?

**Comment by yuzisun** [comment]
@SachinVarghese this is the example https://github.com/kubeflow/kfserving/pull/203, hopefully can be merged soon. I am not sure how useful this field is since you won't be constantly  monitoring the replica count from status object while it is much easier on a dashboard.

**Comment by ellis-bigelow** [comment]
Just as Knative feels the need to surface its deployment's pod count, I think KFServices (regardless of our dependency on Knative), should also surface the pod count.

When asking questions about our interface, anything referring to "just check Knative" should smell funny. This of course, isn't always possible, but it's a good rule of thumb.

I think it's pretty trivial to setup a watch on pods with our label and keep our replicas up to date.

**Comment by rakelkar** [comment]
Does this mean we keep updating our spec as pods scale up and down? That seems like extra unessential load on the API server.. that could get prohibitive as # of kfservices scales... Am I mistaken in how this would get implemented?

**Comment by ellis-bigelow** [comment]
Updating status, not spec.

It's honestly pretty trivial. Especially when compared to what HPAs or KPAs
are doing.

This is also exactly what the deployment controller and knative controllers
are doing. This is triggered via watch anyways, so it's pretty cheap.
Google around, and I'm sure you can find the 100k qps kubernetes masters
article.

**Comment by cliveseldon** [comment]
I think it would be very useful for users to see a clear indication of the serverless scaling/hibernation via replica count on the kfserving status. If it can be done without must cost then i'm +1 for having it rather than the need to dig into prometheus metrics or decode the underlying revision ID to find the pods etc.
