### ISSUE TITLE
support calling services with curl when kubeflow auth is enabled

### ISSUE THREAD

**Issue by ryandawsonuk** [kubeflow/kfserving#234]
Lets say you have authentication enabled on your kubeflow installation and so your istio gateway can only be accessed with a valid token. We discussed this scenario on [another issue](https://github.com/kubeflow/kfserving/issues/196) and it was [noted that you can open the browser and go to kubeflow and get the token out from the browser's debugger](https://github.com/kubeflow/kfserving/issues/196). It would be nice to either have this officially documented or provide an easier way.

**Comment by ellis-bigelow** [comment]
I'm not sure familiar with how Kubeflow does auth. Our only dependency is on Istio's auth, as we haven't integrated with Kubeflow fully yet (slated for v0.2 release). One of the tasks we should look at is authn/z.

Can you modify this issue to reflect that feature request to integrate with kubeflow auth?

/area infrastructure-feature

**Comment by johnugeorge** [comment]
We can wait till KF 0.6 version is out. And then add instructions for using with KF 0.6. Currently, there are some open issues that have to be resolved in Kfctl

**Comment by ryandawsonuk** [comment]
A short-term workaround for anyone trying it might be to find the route and get the service name from the route's yaml and then port-forward to that.

**Comment by ryandawsonuk** [comment]
Actually I don't seem to be able to port-forward to that service, presumably because it's an ExternalName service.

The best workaround I've so far been able to find is to port-forward to a deployment. So [for the tensorflow flowers example](https://github.com/kubeflow/kfserving/tree/57335e7b175efd2250ab34e1261dbaed5d8821b0/docs/samples/tensorflow#run-a-prediction) this is:

`kubectl port-forward deployment/$(kubectl get deployment -l serving.knative.dev/configuration=flowers-sample-default -o jsonpath='{.items[0].metadata.name}') 8080:8080`

And then I can call it with:
```
curl https://raw.githubusercontent.com/kubeflow/kfserving/57335e7b175efd2250ab34e1261dbaed5d8821b0/docs/samples/tensorflow/input.json --output input.json

MODEL_NAME=flowers-sample
INPUT_PATH=@./input.json

curl -v http://localhost:8080/v1/models/$MODEL_NAME:predict -d $INPUT_PATH
```
But it doesn't go through the ingress gateway or the knative level so these requests don't show up in the knative observability dashboards.

**Comment by ryandawsonuk** [comment]
Closing in favour of https://github.com/kubeflow/kfserving/issues/371 , which explains more clearly
