### ISSUE TITLE
Develop python pip package for KFServing SDK

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/kfserving#246]
/kind feature

**Describe the solution you'd like**

Develop python pip package for KFServing SDK, user can directly install kfserving sdk using `pip install kfserving`, and then call kfserving sdk apis to create/check/patch/delete kfservice.

**Comment by animeshsingh** [comment]
@jinchihe any chance we can keep these SDKs aligned? Had a discussion today with some end users, and proliferation of SDKs (kfp, kfs, arena..) isn't helping the story. Something to think for future, if not immediately
@jinchihe @ellis-bigelow

**Comment by jinchihe** [comment]
@animeshsingh Thanks for the propose. Yes, that's better we should have a aligned Python SDK for Kubeflow whole projects. But I searched and did not get any plans for this in Kubeflow, I just logged ticket in kubeflow area https://github.com/kubeflow/kubeflow/issues/3683.

So for now, I think we can do that meanwhile, and just merging or something later once whole kubeflow SDK planed.
