### ISSUE TITLE
Upgrade openapi and python sdk once knative upgraded to v1beta1

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/kfserving#249]
/kind feature

**Describe the solution you'd like**
We need to upgrade openapi and python sdk once knative upgraded to v1beta1 (after the PR merged #238 ), since there are some changes in the `kfservice_types.go `

**Comment by jinchihe** [comment]
Just suspend the ticket more time, since we may has also update the knative/pkg recently, refer to two PRs in the knative which are made by kfserving team: https://github.com/knative/pkg/pull/538 and https://github.com/knative/pkg/pull/510

We may pin our commits to include the changes, seems we need to also upgrade knative/serving, I thonk the master breach is not stable, see more in #260 

@johnugeorge is going to have more investigration on this, so just suspend this more time to refresh openapi and swagger file. Thanks.

FYI @rakelkar @yuzisun

**Comment by johnugeorge** [comment]
i don't see any other way than manually committing these PRs in our repo.  we need to decide if we have to temporarily use that hack.  Or we have to wait till knative 0.8 to get these fixes
