### ISSUE TITLE
SDK Issues

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/kfserving#263]
/kind bug

1. The SDK assumes your certificates are under `~/.kube/config` to work remotely. Is there a way to set the location for certificate?

2. The SDK package name is `kfserving` which has the same package name as the kfserving python server - confusing a bit.

3.  SDK doesn’t have any function to customize storage secrets.

via @Tomcli 

/assign @jinchihe 
cc @yuzisun @ellis-bigelow

**Comment by yuzisun** [comment]
@animeshsingh I raised same concern here https://github.com/kubeflow/kfserving/pull/250. Maybe we can call it kfserving-sdk ?

**Comment by jinchihe** [comment]
@animeshsingh Thanks for the raising. 

For problem 2, we are discussing more details in the #268 
For problem 3, I think we can set the `service_account_name` for storage secrets, is that satify your requirement?

For exmple:
```
default_model_spec = V1alpha1ModelSpec(service_account_name='sa',
                                       tensorflow=V1alpha1TensorflowSpec(
                                       model_uri='gs://kfserving-samples/models/tensorflow/flowers'))
```
Of course the service_account_name need to be ready before this. see more in the related [sdk doc](https://github.com/kubeflow/kfserving/blob/master/sdk/docs/V1alpha1ModelSpec.md).

**Comment by animeshsingh** [comment]
For #3 
Maybe a map of key/value pairs with corresponding creds for gcs/s3/ibm cos etc...

cc @ellis-bigelow

**Comment by ellis-bigelow** [comment]
IMO Service accounts should drive the creds. KFServing can recognize special service accounts to pull and mount creds of each type.

The SDK should be capable of *creating* these service accounts. @jinchihe , what do you think about a helper for this?

**Comment by jinchihe** [comment]
@ellis-bigelow Make sense, so SDK can get the key/value pairs from user inputs/spefications, and then create the secrects/service accounts, and then mounting. Will do that later. Thanks.
