### ISSUE TITLE
Discussion for bundling backend and client together for kfserving pypi

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/kfserving#268]
/kind feature

As we made the decision to bundle backend and client together in the same pypi, I would like to discussing details here before implement that. I think there are two ways to implement this:

**Option A**,  move the [sdk](https://github.com/kubeflow/kfserving/tree/master/sdk) into the [python/kfserving/kfserving](https://github.com/kubeflow/kfserving/tree/master/python/kfserving/kfserving). The details are as following.

1. Move the `sdk/sample` to `docs/samples/python_client/`
2. Move the `sdk/tests` to `test/python_client/tests`
3. Move the `sdk/kfserving` to `python/kfserving/kfserving/client`
4. Move the `sdk/docs` to `python/kfserving/kfserving/client/docs`
5. Remove useless files under `sdk` such as `sdk/.swagger-codegen` and `sdk/test-requirements.txt`
6. Merge two setup.py file to build pypi poacakge, and rename the pkg name to `kfserving` in [python/kfserving/setup.py](https://github.com/kubeflow/kfserving/blob/ecb9b0d068505b4f7636ada5dbf127c48ee393d9/python/kfserving/setup.py#L24)

**Option B**, Make a script (like `_updatepypi_package.sh`) for this to do:
1. Create a tmp directory, for example`tmp_dir`.
2. Copy the `python/kfserving/kfserving` to `tmp_dir`.
3. Copy the `sdk/kfserving` to `tmp_dir/kfserving/client(or sdk?)`
4. Genereate the setup.py (or copy from somewhere).
5. And the upload the pkg to pypi (need to configure the .pypirc before do this).

After the updates, the python client sdk importing will be as following:
```
from kfserving.client.api.kf_serving_api import KFServingApi
from kfserving.client.constants import constants
from kfserving.client.models.v1alpha1_model_spec import V1alpha1ModelSpec
```

Personally, I perfer to Option B, as there is a problem for option A, the python client sdk will not easy to maintain, since the sdk is genereated by `swagger-codegen`, if so, we break the directory structure. in the future, if we want to upgrade, we need to do that as above oprations, but if we take option A, I need to update docu to record this for future maintainer. But seems Option B also has a problem that there are some difference between from local installation and from pypi, unless change the directory structure.

Please let me know if any better idea for this, Thanks.

**Comment by jinchihe** [comment]
@yuzisun @ellis-bigelow @animeshsingh Please let me know if you have any comments for the propose. Thanks a lot!

**Comment by ellis-bigelow** [comment]
I like most of your suggestions. The format:  `kfserving.client.api.kf_serving_api` is a little verbose. Is this because it's autogenerated? I'd prefer something like `kfserving.client`

setup.py should be flexible enough to allow you any folder structure. If it doesn't, I like option b.

**Comment by animeshsingh** [comment]
@ellis-bigelow are we asking for trouble by coupling the backend and client in terms of maintainability costs?

**Comment by jinchihe** [comment]
> I like most of your suggestions. The format: `kfserving.client.api.kf_serving_api` is a little verbose. Is this because it's autogenerated? I'd prefer something like `kfserving.client`
> 
Thanks @ellis-bigelow Yes, your are right, that's because it's autogenereated, and if we change that, we need change that every uprading in the future.

**Comment by jinchihe** [comment]
Personally I strongly suggest to take out the `client` word from apis , just merge the service and client directory, for reasons:
1. If we remove the `client`, so the kserving client api will be as `kfserving.api.kf_serving_api` , instead of `kfserving.client.api.kf_serving_api` which is verbose as @ellis-bigelow mentioned above.
2. If so we will not break `swagger-codegen` directory structure, easy for maintaining, both for two proposes.
3. We can do that, since no directory or class conflicts, only need to merge same name files such as `__init__.py` and `setup.py` .

**Comment by ellis-bigelow** [comment]
> @ellis-bigelow are we asking for more trouble by coupling the backend and client in terms of maintainability costs?

Honestly, locking thee versions may make compatibility easier. I'd hear your concerns though. Would you like to elaborate further on the scenario you're envisioning?

**Comment by jinchihe** [comment]
The bundling has been finished in the #250 , close the ticket.
