### ISSUE TITLE
The overall status should be shown for `kubectl get kfservice`

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/kfserving#306]
/kind feature

**Describe the solution you'd like**
While I'm doing the #305 , I think the overall status will be shown for `kubectl get kfservice`. User want to know if the KFService is ready or not.

For now:
```
(python36) [root@jinchi1 kfserving]# kubectl get kfservice
NAME             URL                                          DEFAULT TRAFFIC   CANARY TRAFFIC   AGE
flowers-sample   http://flowers-sample.kubeflow.example.com                                      23m
```

Should be like below I think (added READY):
```
(python36) [root@jinchi1 kfserving]# kubectl get kfservice
NAME            READY   URL                                          DEFAULT TRAFFIC   CANARY TRAFFIC   AGE
flowers-sample  True       http://flowers-sample.kubeflow.example.com                                      23m
```

Checked the knative, there is a READY,  I suggest we add one metric READY for kfservice.

```
kubectl get knative
......
NAME                           SERVICE NAME                   GENERATION   READY     REASON
flowers-sample-canary-mbcjq    flowers-sample-canary-mbcjq    1            True
flowers-sample-default-zmfbh   flowers-sample-default-zmfbh   1            True
helloworld-go-5bs95            helloworld-go-5bs95            2            True
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jinchihe** [comment]
@ellis-bigelow @yuzisun comments? Thanks.

**Comment by yuzisun** [comment]
@jinchihe good suggestion! Can you try add this annotation `+kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"` to `KFService` type see if that works?

**Comment by jinchihe** [comment]
> @jinchihe good suggestion! Can you try add this annotation `+kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"` to `KFService` type see if that works?

@yuzisun OK, thanks, I'm going to do that :-)

/assign @jinchihe
