### ISSUE TITLE
Discuss: Rename KFService to MLService

### ISSUE THREAD

**Issue by rakelkar** [kubeflow/kfserving#317]
We've discussed this idea before, opening an issue to discuss in the context of v1alpha2.

### Rationale:
KFServing as it currently stands defines an API spec and an implementation for serving. The spec models the ML domain but is not dependent on Kubeflow in any way. MLServing is a clearer name that reinforces the loose coupling of the API. 

wdyt?

**Comment by cliveseldon** [comment]
+1 if we push to be standalone component used by but not dependant on Kubeflow. But for this to be a reality we would need to have looser ties to kubeflow releases which brings up wider questions. 

Also, would help make clear the spec could have alternative implementations or extensions that are not kubeflow focused and definitely help promote it wider.

**Comment by aronchick** [comment]
the latter please 🙂

KFServing should stay in KFServing as an implemenation of MLService 🙂 (maybe we change the name to KFService?)
________________________________

**Comment by abhi-g** [comment]
thanks for that clarification. this is making more sense now.

**Comment by ellis-bigelow** [comment]
Any thoughts on InferenceService instead?
