### ISSUE TITLE
 V1Alpha2: Transformer/Explainer validation for KFService spec

### ISSUE THREAD

**Issue by yuzisun** [kubeflow/kfserving#324]
**Describe the solution you'd like**
Validate the spec for newly added transformer/explainer and some of the existing validation functions may need to be refactored.

**Anything else you would like to add:**
Open questions are that whether we should allow adding/removing transformer/explainer in canary.
- It may not make sense to add/remove transformer in canary, so if default has transformer then canary should have it too, vice versa when default does not have transformer.
- It may make sense to add/remove explainer in canary, is that case 100% traffic routes to explainer which in turn route to canary predictor which is no longer subjected to the traffic split.

**Comment by rakelkar** [comment]
We discussed this in the weekly meeting and we agreed to start simple and not allow graph changes between canary and default, this means the user can only modify components but cannot add/remove components in canary.

This means the following should fail validation:
1. Add a transformer as canary, where default does not have a transformer - not possible
2. Remove a transformer in canary, where default has a transformer - not possible
3. Same for explainer

However the following paths are available to users:
1. Create a new service that includes (or removes) a transformer or explainer
2. Update a service to include a new default spec (that is completely different from the old default spec) - as long as the service does *not* include a canary spec

FYI @hougangliu @cliveseldon @yuzisun @animeshsingh @ellis-bigelow

**Comment by ellis-bigelow** [comment]
I'm a little hesitant about this approach. Isn't this the whole value of a canary, in that you can add a transformer to a canary and try it out with the new traffic. As long as there's no data plane interface change, there shouldn't be a problem. This means that the canaried model may need to support a new interface if a transformer is introduced. 

Happy to discuss further in the weekly.

**Comment by hougangliu** [comment]
For me as https://github.com/kubeflow/kfserving/pull/336#issuecomment-530418650, I think we shouldn't limit that default and canary part must keep same structure, and they only need keep same data interface. w'd better free the user to do more experiments about how its model looks like.
Happy to discuss it. More comment is welcome. Thanks
