### ISSUE TITLE
add runtime image to configmap

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/kfserving#334]
/kind feature

**Describe the solution you'd like**
We need to add runtime image to configmap, and for now, we added in the pkg/apis/serving/v1alpha2/framework_*.go file, that's not good for user to update that, if in the configmap, user can update that or add old ones.

See more in the https://github.com/kubeflow/kfserving/pull/319

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by yuzisun** [comment]
this is done.

/close
