### ISSUE TITLE
Allow specification of concurrency

### ISSUE THREAD

**Issue by rakelkar** [kubeflow/kfserving#338]
/kind feature

KNative allows specification of container concurrency on models. Would be nice to be able to set this on a KFService. Python models often have a concurrency of 1 - setting this value correctly is important to get request based autoscaling to work correctly.

**Comment by yuzisun** [comment]
This is already supported via passing exactly same knative target concurrency annotation on kfservice.

**Comment by rakelkar** [comment]
Can you point me to the annotation? The only thing I saw is a configuration..

```
      # +optional max request concurrency per instance.
      # Defaults to `0` (system decides) when unspecified.
      containerConcurrency: ...
```

**Comment by yuzisun** [comment]
@rakelkar the above is for max allowed concurrency which is only used to limit how many requests(hard limit) can reach the pod at a given time. `autoscaling.knative.dev/target` annotation is the soft limit for how many requests you want at a given time(target concurrency) which we currently default to 1 in KFService and autoscaler is based off target concurrency and observed concurrency. You can always overwrite the annotation on KFService with a proper value you want.

**Comment by rakelkar** [comment]
I see thanks for the clarification!
