### ISSUE TITLE
Predict route appears to conflict with Predictor route

### ISSUE THREAD

**Issue by rakelkar** [kubeflow/kfserving#343]
/kind bug

**What steps did you take and what happened:**
We currently create a predictor and a predict route. The predict route points to the transformer if one is configured, else to the predictor. I configured a KFService without a predictor and found that the knative label reconciler keeps failing with the following message:
```
{"level":"error","ts":"2019-09-17T17:40:41.692Z","logger":"controller.labeler-controller","caller":"controller/controller.go:345","msg":"Reconcile error",

"knative.dev/controller":"labeler-controller","error":"configuration \"style-sample-predictor-default\" is already in use by \"style-sample-predictor-default\", and cannot be used by \"style-sample-predict\"",

"stacktrace":"knative.dev/serving/vendor/knative.dev/pkg/controller.(*Impl).handleErr\n\t/home/rakelkar/go/src/knative.dev/serving/vendor/knative.dev/pkg/controller/controller.go:345\nknative.dev/serving/vendor/knative.dev/pkg/controller.(*Impl).processNextWorkItem\n\t/home/rakelkar/go/src/knative.dev/serving/vendor/knative.dev/pkg/controller/controller.go:331\nknative.dev/serving/vendor/knative.dev/pkg/controller.(*Impl).Run.func1\n\t/home/rakelkar/go/src/knative.dev/serving/vendor/knative.dev/pkg/controller/controller.go:282"}
```

**What did you expect to happen:**
All logs should be happy

**Anything else you would like to add:**
the predict route seems to work, however it doesn't seem right to have made a knative controller sad as this could lead to unexpected issues down the line?

/assign @yuzisun

**Comment by yuzisun** [comment]
hmm, predictor is mandatory per KFService specification, thought webhook should reject if predictor is not specified.

**Comment by yuzisun** [comment]
Ah I see, it is going through the mutating webhook first and then validating webhook and it crashes the controller in mutating webhook.

**Comment by yuzisun** [comment]
we are using virtual service for single host routing now.
/close
