### ISSUE TITLE
Update DEVELOPER_GUIDE.md

### ISSUE THREAD

**Issue by yuzisun** [kubeflow/kfserving#35]
- Document prerequisites for development
- Instructions for how to run and test code

**Comment by ellis-bigelow** [comment]
Any update on this? Should I pick it up?

**Comment by yuzisun** [comment]
I have it half way will work on tomorrow and send a PR.

**Comment by yuzisun** [comment]
This is added in https://github.com/kubeflow/kfserving/pull/67.
