### ISSUE TITLE
Suggest defining Initializer image in configmap

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/kfserving#360]
/kind feature

**Describe the solution you'd like**

We defined the `StorageInitializerContainerImage` in the go `storage_initializer_injector.go`

https://github.com/kubeflow/kfserving/blob/1dabdb06f525ff9d784334337bea103f36ceb299/pkg/webhook/admission/deployment/storage_initializer_injector.go#L31

I think that's better to define that in the config file.

For this case, user want to run the kfserving on other than x86_64 platform such as POWER, may need to rebuild and update the image (edit deployment), but that does not work since the image is replaced by the webhook even if user updated deployment. If we defined in the configmap, so user just need to update configmap I think.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by yuzisun** [comment]
This is already supported, check the configmap here. I guess we need to document it.

https://github.com/kubeflow/kfserving/blob/master/config/default/configmap/kfservice.yaml#L30

**Comment by jinchihe** [comment]
@yuzisun Oh...Great! Thanks!
