### ISSUE TITLE
Empty host KFService

### ISSUE THREAD

**Issue by pradithya** [kubeflow/kfserving#363]
/kind bug

**What steps did you take and what happened:**
Install any sample
```
kubectl apply -f docs/samples/tensorflow/tensorflow.yaml
```
get kfservice info
```
kubectl get kfservice flowers-sample
```
Output
```
NAME             URL   DEFAULT TRAFFIC   CANARY TRAFFIC   AGE
flowers-sample         100                                29m
```
But `kubectl get knative` show me the route is set up correctly and accessible
```
NAME                                       URL                                         READY   REASON
route.serving.knative.dev/flowers-sample   http://flowers-sample.default.example.org   True
route.serving.knative.dev/helloworld-go    http://helloworld-go.default.example.org    True
```

**What did you expect to happen:**
URL is not empty

**Environment:**

- Istio Version: 1.1.7 - `istio-ingress` is modified to have internal load balancer
- Knative Version: 0.9.0
- KFServing Version: 0.1.0
- Kubeflow version: NA
- Minikube version: NA
- Kubernetes version: (use `kubectl version`): Server: v1.13.7-gke.8, Client: v1.14.2
- OS (e.g. from `/etc/os-release`): MacOS

**Comment by yuzisun** [comment]
We have not tested kfserving 0.1 with knative 0.9, likely they are not compatible. We are releasing 0.2 soon, stay tuned !

**Comment by pradithya** [comment]
Cool. I am looking forward to it!

**Comment by yuzisun** [comment]
this should be resolved now.
/close
