### ISSUE TITLE
shared auth with kubeflow

### ISSUE THREAD

**Issue by ryandawsonuk** [kubeflow/kfserving#371]
I've installed kubeflow from kfctl with a setup that [includes auth on the single external entrypoint for istio](https://www.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto/).

But KFServices are available without any security on port 80. This is because knative and kubeflow both create an istio [Gateway resource](https://istio.io/docs/reference/config/networking/v1alpha3/gateway/) and the kubeflow entry doesn't include port 80 whereas knative does. So port 80 traffic is unsecured (and still open because not covered by the kubeflow auth envoyfilter) and is routed by istio to the knative services as it matches the knative gateway record.

I can move the knative gateway to the default https port but then there's a conflict with the kubeflow gateway and requests do not get routed to the services. The only configuration I've able to get working with auth is putting the knative gateway on a different port entirely (e.g. 15443). I suspect it would also work if I were to create [a distinct entrypoint IP for knative](https://knative.dev/docs/serving/setting-up-custom-ingress-gateway/), though that would require additional changes to the auth setup (to allow that redirectUri).

@yanniszark [has suggested](https://github.com/kubeflow/kfserving/issues/196#issuecomment-506827346) this could be addressed by getting knative to use the kubeflow gateway. But I've tried to do that without success. Knative lets you [repoint to a different external gateway service](https://knative.dev/docs/serving/setting-up-custom-ingress-gateway/) but I've not been able to point to a different isitio Gateway (changing the config-istio configmap didn't work for me).

I've also considered changing kubeflow to use the knative-gateway but that would be a big change.

**Comment by ryandawsonuk** [comment]
Advice on the related knative-serving issue is that knative-serving can [currently only be switched to another gateway in the knative-serving namespace](https://github.com/knative/serving/issues/5700) but there is a plan to change that in future.

**Comment by rakelkar** [comment]
Also vaguely related (to enable custom per service auth): https://github.com/knative/serving/issues/5706

**Comment by yuzisun** [comment]
This should be fixed now

/close
