### ISSUE TITLE
kubectl get kfservices doesn't show values while reconciling (or unknown)

### ISSUE THREAD

**Issue by ellistarn** [kubeflow/kfserving#384]
/kind bug
```
NAME             READY     URL                                                 DEFAULT TRAFFIC   CANARY TRAFFIC   AGE
flowers-sample   True      http://flowers-sample-predict.default.example.com   100                                8m
xgboost-iris     Unknown   http://xgboost-iris-predict.default.example.com                                        5s
```
Canary and Default are both blank. Ready is Unknown. These values are deterministic and should be displayed immediately.

**Comment by yuzisun** [comment]
Istio virtual service is not created until revision pods are ready, I am not sure if we should show the traffic split percent when routes are not in ready state yet.

**Comment by ellis-bigelow** [comment]
How do you feel about simply returning False instead of unknown? We explicitly know it's not ready.
