### ISSUE TITLE
Migrate to go modules

### ISSUE THREAD

**Issue by zhilingc** [kubeflow/kfserving#404]
/kind feature

**Describe the solution you'd like**
Migrate from `dep` to `go modules` for dependency management. It would help greatly in creating more reproducible builds without vendoring (although we can continue vendoring, which seems to be the canon regardless), and also the flexibility to work with the code (1) outside the GOPATH and (2) without dep.

**Comment by cliveseldon** [comment]
This should be part of migrating to Kubebuilder V2 which uses modules.
