### ISSUE TITLE
Model service returns non 2XX during autoscaling

### ISSUE THREAD

**Issue by pradithya** [kubeflow/kfserving#407]
/kind bug

**What steps did you take and what happened:**
1. Deploy tensorflow model example (https://github.com/kubeflow/kfserving/tree/master/docs/samples/tensorflow)
2. Run load test when there is no pod available 

I am using vegeta to generate load 

```
cat cfg | vegeta attack -rate=100 -duration=60s | vegeta report -type=text
```

content of cfg
```
POST http://10.203.167.197/v1/models/flowers-sample:predict
Host: flowers-sample-predict.default.example.com
@input.json
```
Result: (notice that there are almost 20% errors returned)

```
Requests      [total, rate, throughput]  6000, 100.02, 54.54
Duration      [total, attack, wait]      1m29.460251217s, 59.989969451s, 29.470281766s
Latencies     [mean, 50, 95, 99, max]    11.688754397s, 6.504079498s, 30.000249363s, 30.000386688s, 30.009459504s
Bytes In      [total, mean]              1094281, 182.38
Bytes Out     [total, mean]              83773280, 13962.21
Success       [ratio]                    81.32%
Status Codes  [code:count]               0:832  200:4879  503:289
Error Set:
503 Service Unavailable
Post http://10.203.167.197/v1/models/flowers-sample:predict: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**What did you expect to happen:**

No error returned altough slower response time is expected

**Environment:**

- Istio Version: 1.1.7
- Knative Version: 0.8.1
- KFServing Version: master branch 
- Kubeflow version: -
- Minikube version: -
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
this should not be an issue anymore.
/close
