### ISSUE TITLE
Default ONNX runtime server version doesnt work with v1 virtual service

### ISSUE THREAD

**Issue by rakelkar** [kubeflow/kfserving#415]
/kind bug

#339 introduces path based routing. The default version of ORT server needs to be updated to a version that supports the required path. This has been fixed in the underlying server with https://github.com/microsoft/onnxruntime/pull/1995

**Comment by rakelkar** [comment]
@csteez feel like updating the version?

**Comment by rakelkar** [comment]
a patch release is on its way: https://github.com/microsoft/onnxruntime/pull/2087

**Comment by csteegz** [comment]
the 0.5.1 branch has had this cherry picked in and the 1.0 version will support this.
