### ISSUE TITLE
KFServing examples hardcode the namespace as "kubeflow"

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kfserving#429]
/kind feature

**Describe the solution you'd like**
This notebook hardcodes the namespace as kubeflow.
https://github.com/kubeflow/kfserving/blob/master/docs/samples/client/kfserving_sdk_sample.ipynb

I suspect others do as well.

This prevents the notebook from just running when people launch it in kubeflow.

It would be better if the code could try to test if the notebooks is running under K8s and default to the current namespace.

The fairing library has a routine to do this.
https://github.com/kubeflow/fairing/blob/ffebbe6529441f38ebcb13db9bb4c34883eb3b7c/kubeflow/fairing/utils.py#L23

The code is simple enough that you could either copy it over or just install and use fairing.

**Comment by jinchihe** [comment]
/assign 
I will take a look, thanks.
