### ISSUE TITLE
Storage initializer container succeeded even with invalid storage uri

### ISSUE THREAD

**Issue by yuzisun** [kubeflow/kfserving#440]
/kind bug

**What steps did you take and what happened:**
Set `storageUri` with an invalid uri `s3://platform-test/s3/moviesentiment` (s3 subdir does not exist)

The storage initializer container succeeded,
```
kubectl logs moviesentiment-predictor-default-xh8c8-deployment-5955bbccxfnfc -c storage-initializer
INFO:root:Initializing, args: src_uri [s3://platform-test/s3/moviesentiment] dest_path[ [/mnt/models]
INFO:root:Copying contents of s3://platform-test/s3/moviesentiment to local
INFO:root:Successfully copied s3://platform-test/s3/moviesentiment to /mnt/models
```
But main container failed
```
kubectl logs moviesentiment-predictor-default-xh8c8-deployment-5955bbccxfnfc -c user-container
INFO:root:Copying contents of /mnt/models to local
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/sklearnserver/sklearnserver/__main__.py", line 33, in <module>
    model.load()
  File "/sklearnserver/sklearnserver/model.py", line 32, in load
    self._joblib = joblib.load(model_file) #pylint:disable=attribute-defined-outside-init
  File "/usr/local/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 597, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/models/model.joblib'
```

**What did you expect to happen:**
It should fail in storage initializer container instead.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.1.7
- Knative Version: 0.8.0
- KFServing Version: 0.2.0
- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by pugangxa** [comment]
This confuse me too. When I first apply the tensorflow example, I'm not sure where the model is from and changed to my own in local but seems it's just failed. I think we should report error in a consistent way.

**Comment by pugangxa** [comment]
Take a look and if the object does not exist(if the path does not exist some will return error, if just object does not exist it will return successfully), only the local path will return error from code in storage.py:
```
        if blobs.
            raise Exception("Local path %s does not exist." % (uri))
```

For other types there's no chance to get in the for loop, take gcs for example(others are the same), in the code below the for loop will return directly since there's nothing in blobs.
```
        blobs = bucket.list_blobs(prefix=prefix)
        for blob in blobs:
```
I will fix this issue by checking whether it's empty for the iterator returned.
