### ISSUE TITLE
manager_image_patch.yaml: no such file or directory

### ISSUE THREAD

**Issue by 14sudharsan** [kubeflow/kfserving#447]
Following this [link](https://github.com/kubeflow/kfserving/blob/master/docs/DEVELOPER_GUIDE.md#deploy-kfserving) to deploy KF Serving

**Getting an below error for this step "make deploy-dev"**

root@ip-172-31-31-235:~/go/src/github.com/kubeflow/kfserving# make deploy-dev
go run vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go crd --output-dir=config/default/crds

[debug] name="URL"
[debug] type="string"
[debug] JSONPath=".status.url"
[debug] name="Ready"
[debug] type="string"
[debug] JSONPath=".status.conditions[?(@.type=='Ready')].status"
[debug] name="Default Traffic"
[debug] type="integer"
[debug] JSONPath=".status.traffic"
[debug] name="Canary Traffic"
[debug] type="integer"
[debug] JSONPath=".status.canaryTraffic"
[debug] name="Age"
[debug] type="date"
[debug] JSONPath=".metadata.creationTimestamp"CRD files generated, files can be found under path config/default/crds.
kustomize build config/default/crds -o config/default/crds/serving_v1alpha2_inferenceservice.yaml
go run vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go rbac --output-dir=config/default/rbac
RBAC manifests generated under 'config/default/rbac' directory
./hack/image_patch_dev.sh
2019/10/15 08:55:24 No matching credentials were found, falling back on anonymous
2019/10/15 08:55:24 Using base gcr.io/distroless/static:latest for github.com/kubeflow/kfserving/cmd/manager
2019/10/15 08:55:24 Building github.com/kubeflow/kfserving/cmd/manager
2019/10/15 08:55:32 Publishing docker.io/14sudharsan/manager-74c72c260668d14fbfb2548007233c7f:latest
2019/10/15 08:55:34 error processing import paths in "config/default/manager/manager.yaml": unsupported status code 401
kustomize build config/overlays/development | kubectl apply -f -
Error: builtin PatchStrategicMergeTransformer config: [112 97 116 104 115 58 10 45 32 109 97 110 97 103 101 114 95 105 109 97 103 101 95 112 97 116 99 104 46 121 97 109 108 10]: evalsymlink failure on '/root/go/src/github.com/kubeflow/kfserving/config/overlays/development/manager_image_patch.yaml' : lstat /root/go/src/github.com/kubeflow/kfserving/config/overlays/development/manager_image_patch.yaml: no such file or directory
error: no objects passed to apply
Makefile:31: recipe for target 'deploy-dev' failed
make: *** [deploy-dev] Error 1

**Comment by yuzisun** [comment]
this should be fixed now.
/close
