### ISSUE TITLE
unable to consume definitions from master

### ISSUE THREAD

**Issue by ryandawsonuk** [kubeflow/kfserving#453]
Working with a project that watches for and deploys KFServices in golang. Am trying to update it to use the latest master to work against the latest CRD.

It's a modules project so I do:

`go get github.com/kubeflow/kfserving@master`

It updates my project dependencies but when I try to build I then get:

`/home/ryan/go/pkg/mod/github.com/kubeflow/kfserving@v0.1.4-0.20191016145342-d33aee11696d/pkg/constants/constants.go:198:21: undefined: network.GetServiceHostname`

The project naturally does build from master using the makefile. I guess this is related to modules vs dep? Or my go version (go1.12.9 linux/amd64) somehow?

**Comment by yuzisun** [comment]
can you check if you have `knative.dev/serving/pkg/network` under your vendor?

**Comment by ryandawsonuk** [comment]
Aha, it's the knative version! 

My go.mod gets knative indirectly
```
	github.com/kubeflow/kfserving v0.1.4-0.20191016145342-d33aee11696d
	knative.dev/pkg v0.0.0-20191016060315-3f11504864ae // indirect
	knative.dev/serving v0.9.0 // indirect
```
When I switch that to knative serving 0.8.0 then it works.

Thanks @yuzisun !
