### ISSUE TITLE
Not all python tests run on presubmits.

### ISSUE THREAD

**Issue by ellistarn** [kubeflow/kfserving#493]
/kind bug
Only the SDK tests are running during presubmits.
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
fixed now
/close
