### ISSUE TITLE
KFserving explanations fail when used with authenticated kubeflow

### ISSUE THREAD

**Issue by SachinVarghese** [kubeflow/kfserving#504]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I am using kfserving deployments in a kubeflow cluster with an authentication specified by the arrikto config. https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_existing_arrikto.yaml. When I make explanation requests with relevant headers(for auth) I get a 404 response, but the prediction works. I am using this sample from the docs https://github.com/kubeflow/kfserving/tree/master/docs/samples/explanation/alibi/income
After some debugging, we found that the explainer is unable to get an output from the predictors as the istio-ingress gateway redirects these requests to a Dex URL for login. (Even the requests internal to the cluster). 

**What did you expect to happen:**
The explainer should have responded with the relevant explanation. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The service type for the default predictor is ExternalName instead of ClusterIP.

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
I suspect this should be fixed by Knative 0.9, since internal call should go through Istio local gateway not the ingress gateway

**Comment by cliveseldon** [comment]
When do we plan to have Knative 0.9 as the required install for kfserving? Are there any kubeflow blockers to moving to 0.9?

**Comment by pugangxa** [comment]
I used knative 0.9 from beginning and now even use knative v0.10.0, so far so good.

**Comment by ChanYiLin** [comment]
I am using [Kubeflow Deployment with kfctl_k8s_istio](https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/)
I get the same error when doing [tensorflow example](https://github.com/kubeflow/kfserving/tree/master/docs/samples/tensorflow)

```sh
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> POST /v1/models/flowers-sample:predict HTTP/1.1
> Host: flowers-sample.default.example.com
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Length: 16201
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
>
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
< HTTP/1.1 302 Found
< location: /dex/auth?client_id=kubeflow-oidc-authservice&redirect_uri=%2Flogin%2Foidc&response_type=code&scope=profile+email+groups+openid&state=MTU3NjMxMTIxMHxFd3dBRUdWWE1XZGtaMVZXUkhORlYwbzNOMkU9fF5YgT2Qxe7W3PdcmhpqI5ug9CwGBTxwTd1c9FARs9Br
< date: Sat, 14 Dec 2019 08:13:29 GMT
< content-length: 0
< x-envoy-upstream-service-time: 20
< server: istio-envoy
< connection: close
<
* Closing connection 0
```
the request is redirected to the dex/auth

**Comment by ChanYiLin** [comment]
@pugangxa Hi, may I know how do you deploy your kubeflow? like which version of kfctl you are using? Thanks!

**Comment by pugangxa** [comment]
> @pugangxa Hi, may I know how do you deploy your kubeflow? like which version of kfctl you are using? Thanks!

I did not use this kind of auth but for knative 0.9+ it do use cluster local gateway. Please refer to PR #561 to install cluster local gateway and have a try.

**Comment by yuzisun** [comment]
Please check https://github.com/kubeflow/kfserving/blob/master/docs/samples/istio-dex/README.md

/close
