### ISSUE TITLE
manager_image_patch.yaml deleted

### ISSUE THREAD

**Issue by cliveseldon** [kubeflow/kfserving#52]
Any reason why this [commit](https://github.com/kubeflow/kfserving/commit/a3df96228211ca6c3dac77333d7b0e7ba85d9c5f#diff-b044399460ea0f6be013b6ca31f3596c) deleted the manager_image_patch.yaml? Master seems broken now.

**Comment by ellis-bigelow** [comment]
Total accident. I kept accidentally updating it. I mustve removed the file without re-checking it out.
