### ISSUE TITLE
All the examples inference service status stays at False

### ISSUE THREAD

**Issue by capt2101akash** [kubeflow/kfserving#527]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Followed the steps to reproduce the sklearn/tensorflow examples to run a predictor module.

**What did you expect to happen:**
The predictor inference service to be at True/Ready state.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The deployment has been done on kubeflow k8s cluster v0.7

**Environment:**

- Istio Version: 1.1.7+
- Knative Version: 0.8.0+
- KFServing Version:
- Kubeflow version: 0.7+
- Minikube version:
- Kubernetes version: (use `kubectl version`): 1.13.1+
- OS (e.g. from `/etc/os-release`): Linux

**Comment by yuzisun** [comment]
Can you help provide more information ? An output of full inference service status yaml would be helpful.

**Comment by capt2101akash** [comment]
Here is what you requested:-
`apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"serving.kubeflow.org/v1alpha2","kind":"InferenceService","metadata":{"annotations":{},"name":"sklearn-iris","namespace":"kubeflow"},"spec":{"default":{"predictor":{"sklearn":{"storageUri":"gs://kfserving-samples/models/sklearn/iris"}}}}}
  creationTimestamp: "2019-11-05T11:47:36Z"
  generation: 5
  name: sklearn-iris
  namespace: kubeflow
  resourceVersion: "2006722"
  selfLink: /apis/serving.kubeflow.org/v1alpha2/namespaces/kubeflow/inferenceservices/sklearn-iris
  uid: 0fc8b83d-ffc2-11e9-b867-42010af00102
spec:
  default:
    predictor:
      sklearn:
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
        runtimeVersion: 0.2.0
        storageUri: gs://kfserving-samples/models/sklearn/iris
status:
  canary: {}
  conditions:
  - lastTransitionTime: "2019-11-05T11:47:45Z"
    message: Waiting for VirtualService to be ready
    reason: Uninitialized
    status: Unknown
    type: DefaultPredictorReady
  - lastTransitionTime: "2019-11-05T11:47:36Z"
    message: Failed to reconcile predictor
    reason: PredictorHostnameUnknown
    status: "False"
    type: Ready
  - lastTransitionTime: "2019-11-05T11:47:36Z"
    message: Failed to reconcile predictor
    reason: PredictorHostnameUnknown
    status: "False"
    type: RoutesReady
  default:
    predictor:
      name: sklearn-iris-predictor-default-2pn7z`

**Comment by hougangliu** [comment]
#469 may be the root cause

**Comment by pugangxa** [comment]
If that is the case, I encountered it before too. You can try to add "minReplicas: 1" under predictor like below and have a try.
```
  default:
    predictor:
      minReplicas: 1
      sklearn:
......
```

**Comment by hougangliu** [comment]
> If that is the case, I encountered it before too. You can try to add "minReplicas: 1" under predictor like below and have a try.
> 
> ```
>   default:
>     predictor:
>       minReplicas: 1
>       sklearn:
> ......
> ```

right, making `minReplicas` to greater than 0 can also be a workaround

**Comment by capt2101akash** [comment]
Tried that but with no success.
```Name:         sklearn-iris
Namespace:    kubeflow
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"serving.kubeflow.org/v1alpha2","kind":"InferenceService","metadata":{"annotations":{},"name":"sklearn-iris","namespace":"ku...
API Version:  serving.kubeflow.org/v1alpha2
Kind:         InferenceService
Metadata:
  Creation Timestamp:  2019-11-08T07:00:04Z
  Generation:          5
  Resource Version:    3350082
  Self Link:           /apis/serving.kubeflow.org/v1alpha2/namespaces/kubeflow/inferenceservices/sklearn-iris
  UID:                 63d2227e-01f5-11ea-b867-42010af00102
Spec:
  Default:
    Predictor:
      Min Replicas:  1
      Sklearn:
        Resources:
          Limits:
            Cpu:     1
            Memory:  2Gi
          Requests:
            Cpu:          1
            Memory:       2Gi
        Runtime Version:  0.2.0
        Storage Uri:      gs://kfserving-samples/models/sklearn/iris
Status:
  Canary:
  Conditions:
    Last Transition Time:  2019-11-08T07:00:13Z
    Message:               Waiting for VirtualService to be ready
    Reason:                Uninitialized
    Status:                Unknown
    Type:                  DefaultPredictorReady
    Last Transition Time:  2019-11-08T07:00:04Z
    Message:               Failed to reconcile predictor
    Reason:                PredictorHostnameUnknown
    Status:                False
    Type:                  Ready
    Last Transition Time:  2019-11-08T07:00:04Z
    Message:               Failed to reconcile predictor
    Reason:                PredictorHostnameUnknown
    Status:                False
    Type:                  RoutesReady
  Default:
    Predictor:
      Name:  sklearn-iris-predictor-default-jsxsg
Events:      <none>```

**Comment by yuzisun** [comment]
something related to this issue https://github.com/knative/serving/issues/5163?

**Comment by ellis-bigelow** [comment]
hey @capt2101akash ,
There are a bunch of incompatibilities with different istio versions and knative versions. It's a *huge* PITA, but almost certainly your problem. I recommend installing the latest knative, and following instructions there on how to install a compatible istio.

I'd read here: https://knative.dev/docs/install/, and come back if you get stuck. We hope to address this soon with better guidance on versions, but as is stands, we're seeing issues like you do related to dependencies more often than we'd prefer.

**Comment by capt2101akash** [comment]
@ellis-bigelow what to do if I am installing knative on a kubeflow cluster on gke for which istio comes as a package out of the box. Would you recommend me to delete the existing istio-ecosystem and reinstall it again, it might then break some things such as the ingress service that comes with gke kubeflow.

**Comment by capt2101akash** [comment]
@all Here are my inputs in solving the case that I faced. As I was installing the knative on top of kubeflow on top of GKE, there has been a lot of dependency issues in between istio, knative and k8s cluster as such. I had to create a k8s cluster with istio enabled and not with kubeflow, the guide for kubeflow e2e in GKE will install kubeflow with the k8s cluster, which in turn also installs istio and other components. Hence, I used [this](https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/) method here which is customised installation of the components and commented out the istio, knative and kfserving components as by default what it installs are not compatible with each other hence resulting in the above mentioned error. Try this out if someone else faces this kind of error please feel free to ask.
Thanks @ellis-bigelow I really missed out that part about compatibility issues.

**Comment by wronk** [comment]
@capt2101akash, can you give any hints on which versions were compatible with each other? We're also hitting this issue on [default CLI guide](https://www.kubeflow.org/docs/gke/deploy/deploy-cli/) for running KF 0.7 on GKE. The config we used was `kfctl_gcp_iap.0.7.0.yaml`

**Comment by alexwennerberg** [comment]
I'm encountering this issue as well. Interested in the response to @wronk 's question @capt2101akash

**Comment by wronk** [comment]
@alexwennerberg, this is tracked in a newer ticket here:
https://github.com/kubeflow/kfserving/issues/629

**Comment by alexwennerberg** [comment]
@wronk Thank you :)
