### ISSUE TITLE
Python crash when kfserving creates minio client

### ISSUE THREAD

**Issue by jeffgriffith** [kubeflow/kfserving#530]
/kind bug

I'm unable to successfully deploy my own model deployed in the local minio service in kubeflow. I finally managed to capture the logs before the failed initialization disappeared. It looks like an index out of bounds on the hostname (note: kc is aliased to kubectl in the snippets):

```
~/git/kfserving/docs/samples/s3 💡 kc logs dpe2e-s3-predictor-default-c8mn4-deployment-678947b495-tjh28 --container=storage-initializer
INFO:root:Initializing, args: src_uri [s3://models/dpe2e/v1] dest_path[ [/mnt/models]
INFO:root:Copying contents of s3://models/dpe2e/v1 to local
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 51, in download
    Storage._download_s3(uri, out_dir)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 66, in _download_s3
    client = Storage._create_minio_client()
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 204, in _create_minio_client
    secure=use_ssl)
  File "/usr/local/lib/python3.7/site-packages/minio/api.py", line 150, in __init__
    is_valid_endpoint(endpoint)
  File "/usr/local/lib/python3.7/site-packages/minio/helpers.py", line 301, in is_valid_endpoint
    if hostname[-1] == '.':
IndexError: string index out of range
```

**What steps did you take and what happened:**
- Uploaded (and browsed) a saved_model.pbtxt file and variables to the minio instance in KF (/models/dpe2e/v1 with the .pbtxt, etc under v1)
- applied the s3_secret.yml file from docs/samples/s3
- kubectl create -f for this file:
```
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "dpe2e-s3"
spec:
  default:
    predictor:
      serviceAccountName: sa
      tensorflow:
        storageUri: "s3://models/dpe2e/v1"

```
kn service list yields
```
~/git/kfserving/docs/samples/s3 💡 kn service list
NAME                               URL                                                           GENERATION   AGE   CONDITIONS   READY     REASON
dpe2e-s3-predictor-default         http://dpe2e-s3-predictor-default.default.example.com         1            8s    0 OK / 3     Unknown   RevisionMissing : Configuration "dpe2e-s3-predictor-default" is waiting for a Revision to become ready.
flowers-sample-predictor-default   http://flowers-sample-predictor-default.default.example.com   1            27h   3 OK / 3     True
~
```

and kubectl get pods shows it with an initialization error. If i quickly grab the logs on this with --container=storage-initializer i can see the python stack trace above. Also the secure=use_ssl in the stack trace seems surprising since s3-usehttps: "0" is in the annotations for the secret.

```
~/git/kfserving/docs/samples/s3 💡 kc get pods
NAME                                                           READY   STATUS       RESTARTS   AGE
dpe2e-s3-predictor-default-qvfjx-deployment-646cd848df-64628   0/2     Init:Error   1          20s
```

**What did you expect to happen:**
The service deployed.

**Anything else you would like to add:**
Seems related to a missing hostname but I'm unable to guess what that might mean. The s3_secret.yaml sample specifies minio-service.kubeflow:9000 as the endpoint. 

**Environment:**

Entire cluster created with RC8 on azure AKS (1.16).

**Comment by yuzisun** [comment]
I believe it is the issue fixed in https://github.com/kubeflow/kfserving/pull/430, if you try kfserving 0.2.1 it should work.

**Comment by yuzisun** [comment]
https://github.com/kubeflow/kfserving/issues/427, you can confirm the issue if you see the same error.
