### ISSUE TITLE
[Help wanted] Add e2e test for canary rollout

### ISSUE THREAD

**Issue by yuzisun** [kubeflow/kfserving#538]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by janeman98** [comment]
@yuzisun 
I can help to add e2e test for this issue (as well as https://github.com/kubeflow/kfserving/issues/539) 

May I know what e2e test environment is? What is setup? I don't get much  info from the following site:
https://github.com/kubeflow/kfserving/tree/master/test
_To run the e2e tests, you need to have a running environment that meets the e2e test environment requirements. (@TODO)_

**Comment by yuzisun** [comment]
@janeman98 sorry just saw this, thanks for taking this issue!  Currently e2e tests run in our CI after PR is created or merged to the master, we will need to update the doc there.
- This is the e2e script which runs in the CI https://github.com/kubeflow/kfserving/blob/master/test/scripts/run-e2e-tests.sh
- All the e2e tests(https://github.com/kubeflow/kfserving/tree/master/test/e2e) are written with pytest, you should be able to run that locally as well if you have the KFServing installation.

Let me know if you have further question! Really appreciate your help!
