### ISSUE TITLE
Python package kfserving 0.2.4 is missing

### ISSUE THREAD

**Issue by pradithya** [kubeflow/kfserving#541]
/kind bug

**What steps did you take and what happened:**
Run
```
pip install kfserving==0.2.4
```

returns
```
ERROR: No matching distribution found for kfserving==0.2.4
```

**What did you expect to happen:**
Able to install version 0.2.4

**Anything else you would like to add:**
It was working a couple of day ago and my internal package depends on this version.

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@pradithya we fixed sdk to match up with kfserving core release number, so try 0.2.1.

**Comment by ellis-bigelow** [comment]
0.2.4 was never supposed to exist! Sorry for the backwards incompat!

**Comment by ellis-bigelow** [comment]
If this is a hard blocker for you, we can look into restoring it.

**Comment by pradithya** [comment]
@ellis-bigelow @yuzisun That make sense. Thanks for clarifying. 

I changed it to 0.2.1.1 and it is ok now. I will close the issue.
