### ISSUE TITLE
gcr.io/kfserving/alibi-explainer:0.2.1 missing

### ISSUE THREAD

**Issue by cliveseldon** [kubeflow/kfserving#542]
/kind bug

**Comment by cliveseldon** [comment]
Are there any public logs on a release that show how this failed/succeeded ?

**Comment by yuzisun** [comment]
the build failed with conn reset
https://pantheon.corp.google.com/cloud-build/builds/ac44ed8a-da36-4f0f-ae2c-17f3e90dc9ac?project=kfserving

**Comment by ellis-bigelow** [comment]
Fixed! /close

**Comment by ellis-bigelow** [comment]
Oh -- looks like this failed again. Something deeper?

**Comment by ellis-bigelow** [comment]
docker pull gcr.io/kfserving/alibi-explainer:0.2.1
0.2.1: Pulling from kfserving/alibi-explainer
c7b7d16361e0: Already exists 
b7a128769df1: Already exists 
1128949d0793: Already exists 
667692510b70: Already exists 
bed4ecf88e6a: Already exists 
8a8c75f3996a: Already exists 
8c90ed29fb66: Already exists 
984b0e9d1433: Already exists 
d930e1ce5d4a: Already exists 
a775af47b7b5: Pull complete 
72907440595c: Extracting  34.54MB/68.09MB
f1b85e673806: Downloading  109.2MB/1.089GB
8890b3fac213: Download complete
