### ISSUE TITLE
XGBoost Model Perfomance Issue

### ISSUE THREAD

**Issue by pradithya** [kubeflow/kfserving#548]
/kind bug
XGboost model server perform poorly after deployed to k8s.

**What steps did you take and what happened:**
I did performance test for xgbserver using provided sample model.

`load.cfg`:
```
POST http://<target>/v1/models/default:predict
@request.json
```

`req.json`:
```
{"instances": [[1,2,3,4]]}
```
Running locally (on Mac OS, 8 core machine) with vegeta
```
cat load.cfg | vegeta attack -duration 1m -rate 1000 | vegeta report -type=text
```

I am able to hit 1000 RPS with good latencies result.

```
Requests      [total, rate, throughput]    60000, 1000.02, 1000.00
Duration      [total, attack, wait]        1m0.000012024s, 59.999069988s, 942.036µs
Latencies     [mean, 50, 90, 95, 99, max]  1.070524ms, 946.443µs, 1.414653ms, 1.520775ms, 2.401196ms, 17.650717ms
Bytes In      [total, mean]                1320000, 22.00
Bytes Out     [total, mean]                1560000, 26.00
Success       [ratio]                      100.00%
Status Codes  [code:count]                 200:60000  
```

But after deployed to K8S (with 4 core as CPU request and limit)

The performance deteriorates at 100 RPS
```
cat load-1.cfg | vegeta attack -rate 100 -duration 60s | vegeta report
```

```
Requests      [total, rate, throughput]    6000, 100.02, 89.47
Duration      [total, attack, wait]        1m7.064629048s, 59.989775627s, 7.074853421s
Latencies     [mean, 50, 90, 95, 99, max]  1.524605151s, 3.683733ms, 5.575147148s, 7.007148666s, 7.789309456s, 8.606190814s
Bytes In      [total, mean]                132000, 22.00
Bytes Out     [total, mean]                192000, 32.00
Success       [ratio]                      100.00%
Status Codes  [code:count]                 200:6000
```

**What did you expect to happen:**

The performance should not be affected too much after deployed to K8S.

**Anything else you would like to add:**
I suspected the issue come from `nthread` in xgbserver are left to default (i.e. 0). 
In: 
https://github.com/kubeflow/kfserving/blob/c46a0da8c0cf168dccfcee3b79f306fea135faf4/python/xgbserver/xgbserver/model.py#L36
and
https://github.com/kubeflow/kfserving/blob/c46a0da8c0cf168dccfcee3b79f306fea135faf4/python/xgbserver/xgbserver/model.py#L42

Which will leave the decision of number of thread to use to xgboost by detecting number of cpu. However, possibly due to this https://bugs.python.org/issue36054, the `nthread` is incorrect and causing the performance issues.

I did a test with setting `nthread=1` :
```
class XGBoostModel(kfserving.KFModel):
    def __init__(self, name: str, model_dir: str, booster: XGBModel = None):
        super().__init__(name)
        self.name = name
        self.model_dir = model_dir
        if not booster is None:
            self._booster = booster
            self.ready = True

    def load(self):
        model_file = os.path.join(
            kfserving.Storage.download(self.model_dir), BOOSTER_FILE)
        self._booster = xgb.Booster(params={"nthread" = 1},model_file=model_file)
        self.ready = True

    def predict(self, request: Dict) -> Dict:
        try:
            # Use of list as input is deprecated see https://github.com/dmlc/xgboost/pull/3970
            dmatrix = xgb.DMatrix(request["instances"], nthread=1)
            result: xgb.DMatrix = self._booster.predict(dmatrix)
            return { "predictions": result.tolist() }
        except Exception as e:
            raise Exception("Failed to predict %s" % e)
```

```
cat load.cfg | vegeta attack -rate 1000 -duration 60s | vegeta report
```

and it performed much better:

```
Requests      [total, rate, throughput]    60000, 1000.02, 999.99
Duration      [total, attack, wait]        1m0.00064503s, 59.9988685s, 1.77653ms
Latencies     [mean, 50, 90, 95, 99, max]  1.927362ms, 1.73989ms, 1.941139ms, 2.490536ms, 5.660895ms, 56.707145ms
Bytes In      [total, mean]                1320000, 22.00
Bytes Out     [total, mean]                1920000, 32.00
Success       [ratio]                      100.00%
Status Codes  [code:count]                 200:60000
```

The question here is:
1. Is setting `nthread=1` a good idea for other kind of workload?
2. Should this be configurable?

**Environment:**

- Istio Version: 1.1.7
- Knative Version: 0.8.1
- KFServing Version: 0.2.1
- Kubeflow version: NA
- Minikube version: NA
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by ellis-bigelow** [comment]
Great find! Let me find someone who can look into this with you. Agreed that we need to find a good value for this. May also need to pass a config param.

**Comment by pradithya** [comment]
Sure, I'll amend the PR if configuration is needed
