### ISSUE TITLE
Strangeness with top level spec fields applying to canary/default

### ISSUE THREAD

**Issue by ellis-bigelow** [kubeflow/kfserving#55]
Currently, min/maxreplicas are set outside of the default/canary specification. This for strange scenarios where replicas changes are not able to be rolled out cleanly. 

Should we move this into the canary/default specs? More generally, given that our CRD is responsible for two backend configurations, does it make sense to. by default, add new fields to canary or default instead of at the top level (e.g. auth).

This is also somewhat challenging for any features triggered based off of annotations, as the annotations would need to specify default/canary as well, or be subject to the same weirdness.

Along these same lines, I've been thinking that it might make sense to move trafficPercent up a level. Our 3 top level keys are then corresponding the to underlying 3 knative resources.

**Comment by ellis-bigelow** [comment]
Any thoughts @cliveseldon , @yuzisun

**Comment by cliveseldon** [comment]
Can you clarify what are the "strange scenarios" you refer to?

I suppose we need to clear there are user stories where people want differing values for min/max replicas for their canary as opposed to default. If so then yes definitely.

What annotations do you think would modify min/max replicas as opposed to the user specifying them in the resource directly?

What the semantics of trafficPercent at the top level? Does it mean this percent goes to the `default`? I thought we discussed the possibility of in future having 3-way splits or am I wrong?

**Comment by ellis-bigelow** [comment]
# spec-level config vs canary/default-level config
Agreed about mapping to user stories. However, I'm proposing that by default, it probably makes sense to put things at the canary/default level unless there is a clear case for something global. 

Upcoming features we've discussed for this are:

1. AWS/GCP/Azure Credentials for model pulling
2. min/max replicas 
3. annotations for GCP Accelerator selector

Credentials: Our original discussion about this suggested using annotations, but this is weird when canarying credential changes.

Replicas: This one is more challenging, as we might be able to do some math on trafficpercent to make this sane. That said, it adds cognitive load to the user to be aware of how this feature works.

Accelerator: There may not be a use case for canarying a different type of accelerator. 

I want to both avoid stuffing platform specific things into the spec itself (i.e. accelerator/credentials), but also avoid over-specifying annotations with `"serving.kubeflow.org/myfeature-default"` and `"serving.kubeflow.org/myfeature-canary"`

# Top level trafficPercent 3 way splits
I don't know the use case for this. The original discussion and design doc posited that 3-way traffic splits should be architected at a higher level resource. I'm happy to hear arguments to the contrary though.

**Comment by rakelkar** [comment]
I think it makes sense to move them in. If I want to rollout a canary to manually test for instance, I would want that to have minInstances=0 or 1 and not be subject to a potentially higher minInstance set on default.
