### ISSUE TITLE
change storage-initializer.Dockerfile and initializer-entrypoint  not work

### ISSUE THREAD

**Issue by Iamlovingit** [kubeflow/kfserving#551]
/kind bug
I want to use my local model file.  I have changed the storage-initializer.Dockerfile and add some logging in initializer-entrypoint.  Then i run `make deploy-dev`, but it seems like not work. Where is wrong?
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
### change Dockerfile, copy cifar10
```
RUN mkdir /cifar10
WORKDIR /cifar10
COPY ./cifar10 .
```
### change initializer-entrypoint
```
logging.info("test...")
logging.info("test over")

logging.info("Initializing, args: src_uri [%s] dest_path[ [%s]" % (src_uri, dest_path))
kfserving.Storage.download(src_uri, dest_path) 
```
### change yaml
```
apiVersion: serving.kubeflow.org/v1alpha2
#apiVersion: "serving.kubeflow.org/v1alpha2"
kind: InferenceService
# kind: "KFService"
metadata:
  name: "pytorch-cifar10"
spec:
  default:
    predictor:
      pytorch:
        #storageUri: "gs://kfserving-samples/models/pytorch/cifar10/"
        storageUri: "file:///cifar10/"
        modelClassName: "Net"
```
### run result
there is no `test ...` and `test over`
```
INFO:root:Initializing, args: src_uri [file:///cifar10/] dest_path[ [/mnt/models]
INFO:root:Copying contents of file:///cifar10/ to local
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 54, in download
    return Storage._download_local(uri, out_dir)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 192, in _download_local
    raise RuntimeError("Local path %s does not exist." % (uri))
```
**What did you expect to happen:**
`kubectl logs` changes.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:1.3.4
- Knative Version:v0.10.0
- KFServing Version:0.21
- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):1.14.3
- OS (e.g. from `/etc/os-release`):ubuntu16.04

**Comment by ellis-bigelow** [comment]
We need a better developer story for this. The problem is make deploy-dev only updates the kubernetes controller. You need to rebuild the storage-initializer and then edit here: https://github.com/kubeflow/kfserving/blob/master/config/default/configmap/inferenceservice.yaml#L75

We want to make a better deploy-dev story, but we're not there yet. Does that help unblock you?

**Comment by Iamlovingit** [comment]
@ellis-bigelow thanks a lot, that helps me. Now i can run my code. I wish newer developer story coming soon.
