### ISSUE TITLE
Default and Allowed Image Version for Explainer and Predictor, KFServing 0.2.1

### ISSUE THREAD

**Issue by ariefrahmansyah** [kubeflow/kfserving#552]
On [install/0.2.1/kfserving.yaml](https://github.com/kubeflow/kfserving/blob/master/install/0.2.1/kfserving.yaml), default and allowed image version for alibi explainer and some predictors are still `0.2.0`.

Is it expected? Should it be updated to `0.2.1` too?

**Comment by ellis-bigelow** [comment]
Ah! We need to regenerate these. Thanks!

**Comment by ariefrahmansyah** [comment]
Thanks, @ellis-bigelow!
