### ISSUE TITLE
change the pytorch server code, but it is not work

### ISSUE THREAD

**Issue by Iamlovingit** [kubeflow/kfserving#557]
/kind bug
i want to add some more informations to log, and have changed python/pytorchserver/pytorchserver/model.py, but it seems not work. how can i run my local pytorchserver code. thanks!
**What steps did you take and what happened:**
1. modify the `python/pytorchserver/pytorchserver/model.py`, add `logging.info`
```
        # Load the python class into memory
        sys.path.append(os.path.dirname(model_class_file))
        modulename = os.path.basename(model_class_file).split('.')[0].replace('-', '_')
        logging.info("test modulename : %s", modulename) #add
        logging.info("test model_class_file : %s", model_class_file) #add
        model_class = getattr(importlib.import_module(modulename), model_class_name)
```
2. build the pytorchserver image, and push:
`docker build -t my-pytorchserver:test0 -f pytorchserver.Dockerfile .`
`docker tag my-pytorchserver:test0  192.168.1.10:5000/gcr.io/kfserving/pytorchserver:test0`
`docker push 192.168.1.10:5000/gcr.io/kfserving/pytorchserver:test0`
3. modify the `configmap/inferenceservice.yaml`
```
"pytorch": {
            "image": "192.168.1.10:5000/gcr.io/kfserving/pytorchserver",
            "defaultImageVersion": "test0",
            "allowedImageVersions": [
               "test0",
               "0.2.1",
               "0.2.0"
            ]
        },
```
4. `make manifest & make deploy-dev`
5. run pytorch sample `kubectl apply -f pytorch.yaml`
6. `kubectl logs`
**the result is not change, where is the problem?**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**
i want see my print in `kubectl logs`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:1.3.4
- Knative Version:v0.10.0
- KFServing Version:0.21
- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):1.14.3
- OS (e.g. from `/etc/os-release`):ubuntu16.04

**Comment by pugangxa** [comment]
Can you describe the configmap directly and check whether the value's get changed? If not you can also kubectl edit it directly. 
I'm afraid it's not updated by your steps.

**Comment by Iamlovingit** [comment]
> 
> 
> Can you describe the configmap directly and check whether the value's get changed? If not you can also kubectl edit it directly.
> I'm afraid it's not updated by your steps.

Could you tell me how to describe the configmap directly? 
`kubectl describe configmap` ?

**Comment by Iamlovingit** [comment]
i run the command `kubectl describe cm inferenceservice-config -n kfserving-system`, the result is:
```
"pytorch": {
        "image": "192.168.1.10:5000/gcr.io/kfserving/pytorchserver",
        "defaultImageVersion": "test1",
        "allowedImageVersions": [
           "test1",
           "0.2.1",
           "0.2.0"
        ]
    },
```
the config map is change.

**Comment by yuzisun** [comment]
this looks good to me, can you check the pod if it is running the expected image?

**Comment by Iamlovingit** [comment]
> 
> 
> this looks good to me, can you check the pod if it is running the expected image?

run  `kubectl descirbe pod`, the result is:
```
Containers:
  kfserving-container:
    Container ID:  docker://df2b3f5e7f090390358a9193d6b31a4b765f334979558002ac0e90939bd7ce87
    Image:         192.168.1.10:5000/gcr.io/kfserving/pytorchserver@sha256:01a59c865f9f6ec8ab4ce6727bda338b6ee6724b33ea3f976df36fdf8dced8fe
    Image ID:      docker-pullable://192.168.1.10:5000/gcr.io/kfserving/pytorchserver@sha256:01a59c865f9f6ec8ab4ce6727bda338b6ee6724b33ea3f976df36fdf8dced8fe
```
can you show me your model.py code? i am not sure my logging statments are right.

**Comment by Iamlovingit** [comment]
> 
> 
> > this looks good to me, can you check the pod if it is running the expected image?
> 
> run `kubectl descirbe pod`, the result is:
> 
> ```
> Containers:
>   kfserving-container:
>     Container ID:  docker://df2b3f5e7f090390358a9193d6b31a4b765f334979558002ac0e90939bd7ce87
>     Image:         192.168.1.10:5000/gcr.io/kfserving/pytorchserver@sha256:01a59c865f9f6ec8ab4ce6727bda338b6ee6724b33ea3f976df36fdf8dced8fe
>     Image ID:      docker-pullable://192.168.1.10:5000/gcr.io/kfserving/pytorchserver@sha256:01a59c865f9f6ec8ab4ce6727bda338b6ee6724b33ea3f976df36fdf8dced8fe
> ```
> 
> can you show me your model.py code? i am not sure my logging statments are right.

i run it again this morning, the test code is worked. confusing!

**Comment by Iamlovingit** [comment]
close it.
