### ISSUE TITLE
tensorflow sample fails to run

### ISSUE THREAD

**Issue by Iamlovingit** [kubeflow/kfserving#562]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
when i run tensorflow-canary sample, `kubectl apply -f tensorflow-canary.yaml`, the pod's status is 
```
NAME                                                              READY   STATUS     RESTARTS   AGE
flowers-sample-predictor-canary-f2fx9-deployment-6c549449fdbhhr   0/2     Init:0/1   0          2s
flowers-sample-predictor-default-x6pt6-deployment-595d9d994ccs7   0/2     Init:0/1   0          2s
```
and about 3m after, the pod's status is 
```
NAME                                                              READY   STATUS        RESTARTS   AGE
flowers-sample-predictor-canary-f2fx9-deployment-6c549449fdbhhr   0/2     Terminating   0   3m6s
flowers-sample-predictor-default-x6pt6-deployment-595d9d994ccs7   0/2     Init:0/1      0       3m6s
```
it seems like downloading the model files form gcs is too slow.
how can i slove this problem? thanks !
**What did you expect to happen:**
pod is run ok.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
`kubectl logs `
```
INFO:root:Initializing, args: src_uri [gs://kfserving-samples/models/tensorflow/flowers-2] dest_path[ [/mnt/models]
INFO:root:Copying contents of gs://kfserving-samples/models/tensorflow/flowers-2 to local
INFO:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable onattempt 1 of 3
INFO:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable onattempt 2 of 3
INFO:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable onattempt 3 of 3
INFO:root:Downloading: /mnt/models/0001/saved_model.pb
INFO:root:Downloading: /mnt/models/0001/variables/variables.data-00000-of-00001
```
**Environment:**

- Istio Version:1.3.4
- Knative Version:0.10.0
- KFServing Version:0.21
- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):1.14.3
- OS (e.g. from `/etc/os-release`):ubuntu16

**Comment by ellis-bigelow** [comment]
Can you try setting min nodes to 1 and see if this resolves for you? It should load even if it takes a long time. How big is your model?

**Comment by yuzisun** [comment]
Seems there is network issue which takes long time to download model and after sometime it scales down to 0.

**Comment by koenmtb1** [comment]
Just came across this issue, I see you're located in Beijing. Are you using a VPN? Because Google Storage might be blocked.

**Comment by ryandawsonuk** [comment]
It seems like https://github.com/googleapis/google-auth-library-python/issues/211#issuecomment-345048835 never got fully resolved. I've hit this today when downloading models from a public bucket (so no auth is actually needed). The file did seem to download successfully (at least it logs that) but the problem connecting to the metadata server seemed to prevent the init from completing. In my case the Pod got stuck in PodInitializing status (so not entirely sure if it's the same issue). I'd never seen this before today. Eventually (seemed like maybe 30mins) it just resolved itself so maybe there was a temporary outage.
