### ISSUE TITLE
unable to work with pvc

### ISSUE THREAD

**Issue by ryandawsonuk** [kubeflow/kfserving#563]
Am trying to follow https://github.com/kubeflow/kfserving/tree/master/docs/samples/pvc

I find that the storage-initializer does run and download the files. I see

```
INFO:root:Initializing, args: src_uri [/mnt/pvc/] dest_path[ [/mnt/models]
INFO:root:Copying contents of /mnt/pvc/ to local
INFO:root:Linking: /mnt/pvc/lost+found to /mnt/models/lost+found
INFO:root:Linking: /mnt/pvc/deep_mnist_model.index to /mnt/models/deep_mnist_model.index
INFO:root:Linking: /mnt/pvc/deep_mnist_model.data-00000-of-00001 to /mnt/models/deep_mnist_model.data-00000-of-00001
INFO:root:Linking: /mnt/pvc/deep_mnist_model.meta to /mnt/models/deep_mnist_model.meta
INFO:root:Linking: /mnt/pvc/checkpoint to /mnt/models/checkpoint
```
But the service never becomes available. The kfserving-container logs:
```
2019-11-20 15:34:09.816670: I tensorflow_serving/model_servers/server.cc:82] Building single TensorFlow model file config:  model_name: tfservingkf model_base_path: /mnt/models
2019-11-20 15:34:09.817218: I tensorflow_serving/model_servers/server_core.cc:462] Adding/updating models.
2019-11-20 15:34:09.817245: I tensorflow_serving/model_servers/server_core.cc:561]  (Re-)adding model: tfservingkf
2019-11-20 15:34:09.824384: W tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:267] No versions of servable tfservingkf found under base path /mnt/models
```
But the model is there in a sense as I can `kubectl exec` into the container. An `ls -ltr` reveals that a symlink is there:
![image](https://user-images.githubusercontent.com/22754674/69253177-1d2d2600-0bac-11ea-8798-77ba3c8c9e5b.png)

Not sure why but the file doesn't seem to be visible to the server in kfserving-container. The symlinking might be relevant as when I use a storage bucket then we see the files as files, not symlinks.

**Comment by ryandawsonuk** [comment]
The volumeMounts for the initContainer are:
```
    volumeMounts:
    - mountPath: /mnt/pvc
      name: kfserving-pvc-source
      readOnly: true
    - mountPath: /mnt/models
      name: kfserving-provision-location
```
And for the kfserving-container I see:
```
    - mountPath: /mnt/pvc
      name: kfserving-pvc-source
      readOnly: true
    - mountPath: /mnt/models
      name: kfserving-provision-location
      readOnly: true
```
The path that the symlink points to does also contain the files:

![image](https://user-images.githubusercontent.com/22754674/69259791-b7926700-0bb6-11ea-8f54-f79dda31f235.png)

But it seems that the server can't read them in this way.

**Comment by fenglixa** [comment]
I can run sucessfully for the PVC samples.
@ryandawsonuk , From the info you appended,  I don't think you run the mnist job completely, there are no "export" dir under your /mnt/pvc, as the follwing in my ENV, please check. Thanks. 

![image](https://user-images.githubusercontent.com/12505594/69306256-d69a0300-0c61-11ea-88b3-79829eb5dd55.png)

**Comment by ryandawsonuk** [comment]
Ok I actually ran a [different TFJob](https://github.com/SeldonIO/seldon-core/issues/1106#issuecomment-555059204) and put my model directly in `/mnt/pvc/`. So the problem could be something about my TFJob (perhaps tensorflow version) or my path. Will try with the reference sample.

**Comment by ryandawsonuk** [comment]
Which version of kustomize are you using? I'm hitting `no matches for OriginalId kubeflow.org_v1beta2_TFJob|~X|$(trainingName); no matches for CurrentId kubeflow.org_v1beta2_TFJob|~X|$(trainingName); failed to find unique target for patch kubeflow.org_v1beta2_TFJob|$(trainingName)` when trying to build the TFJob with kustomize

**Comment by fenglixa** [comment]
@ryandawsonuk I am using kustomize 2.0.3, it was required and mentioned in [minist example document](https://github.com/kubeflow/examples/tree/master/mnist)
Seems other version of kustomize has issues on it.

```
# kustomize version
Version: {KustomizeVersion:2.0.3
```

**Comment by animeshsingh** [comment]
/assign @jinchihe 

cc @yuzisun @ellis-bigelow

**Comment by ryandawsonuk** [comment]
FWIW I did eventually get the storage-initializer working with Seldon and [documented what I did](https://github.com/SeldonIO/seldon-core/issues/1106#issuecomment-558225067). It was a bit sensitive about paths. I didn't come back to KFServing but the storage-initalizer code is the same for both projects.

**Comment by yuzisun** [comment]
As @fenglixa pointed out, the pvc path should points to the export dir where contains the exported model for the mnist example.

/close
