### ISSUE TITLE
Unable to hit primary endpoint with gRPC

### ISSUE THREAD

**Issue by jeffgriffith** [kubeflow/kfserving#597]
/kind bug

**What steps did you take and what happened:**

Using kfserving 0.2.2, I have a custom container launching either tfserving or trt-is with gRPC port exposed (both work fine), however i am unable to reach the instance if i use the main virtual service endpoint (overriding the authority header to specify these). for example:

**Both of these work with gRPC:**
mnist-predictor-default.default.svc.cluster.local
mnist-predictor-default.default.example.com

**This fails with gRPC "UNIMPLEMENTED" error**
mnist.default.example.com

**Anything else you would like to add:**
I lose the ability to hit a canary presumably?

**Environment:**

- Istio Version: from Kubeflow install
- Knative Version: from Kubeflow install
- KFServing Version: 0.2.2
- Kubeflow version: 0.7
- Kubernetes version: 1.13 (will retry soon with 1.14)

**Comment by jeffgriffith** [comment]
@yuzisun i created this so we don't lose track of it per our discussion.

**Comment by hougangliu** [comment]
had created same issue https://github.com/kubeflow/kfserving/issues/533

**Comment by yuzisun** [comment]
This is now supported in KFS 0.5.

**Comment by daganida88** [comment]
The example does not work, I get UNIMPLEMENTED
