### ISSUE TITLE
installation instructions need to accommodate the KF0.7 installation of knative-serving 

### ISSUE THREAD

**Issue by amygdala** [kubeflow/kfserving#602]
/kind bug

It looks like the kf0.7 install (at least via the c2d app) includes installation of some version of knative-serving.  So the instructions here: https://github.com/kubeflow/kfserving/blob/master/docs/DEVELOPER_GUIDE.md#install-knative-on-a-kubernetes-cluster  ("For Kubeflow install, you can install Knative Serving v0.8 via the following commands after downloading repository kubeflow/manifests.") would seem to be outdated, as those manifests can not be successfully deployed.

**Comment by animeshsingh** [comment]
@amygdala I will correct some of the verbiage there

/assign @animeshsingh
