### ISSUE TITLE
Add licenses for dependencies in KFServing images for Kubeflow 1.0

### ISSUE THREAD

**Issue by zhenghuiwang** [kubeflow/kfserving#605]
Related to kubeflow/testing#539 https://github.com/kubeflow/kubeflow/issues/4061

Need to add all license content for thrid-party dependencies in KFServing controller images.

For Golang images, you may find these instructions helpful to extract all license files:

https://github.com/kubeflow/metadata/blob/master/third_party_licenses/README.md

**Comment by animeshsingh** [comment]
Thanks @zhenghuiwang .
Letme dig deeper - believe this is targeted for 0.1 release? 

/assign @animeshsingh

**Comment by zhenghuiwang** [comment]
> Letme dig deeper - believe this is targeted for 0.1 release?

Thanks @animeshsingh Yes, this is for Kubeflow 1.0 release.

**Comment by animeshsingh** [comment]
Thanks - meant 1.0

**Comment by ellis-bigelow** [comment]
Picking this up
/assign @ellis-bigelow 

Images:

gcr.io/kfserving/xgbserver:0.2.2
gcr.io/kfserving/sklearnserver:0.2.2
gcr.io/kfserving/pytorchserver:0.2.2
gcr.io/kfserving/alibi-explainer:0.2.2
gcr.io/kfserving/storage-initializer:0.2.2
gcr.io/kfserving/logger:0.2.2
gcr.io/kfserving/kfserving-controller:0.2.2

**Comment by jlewi** [comment]
@ellis-bigelow any update on this?

**Comment by ellis-bigelow** [comment]
This is complete. /close
