### ISSUE TITLE
PVC sample is reported to be failing

### ISSUE THREAD

**Issue by ellistarn** [kubeflow/kfserving#620]
Investigate and fix.

**Comment by jinchihe** [comment]
@Mojokb Would you please append details for the problem here? thanks.

**Comment by mojokb** [comment]
I edited source from https://github.com/kubeflow/kfserving/blob/master/docs/samples/pvc/mnist-pvc.yaml.
I updated the ${PVC_NAME} to the created PVC name in the mnist-pvc.yaml and apply
like this.
```
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "mnist-sample"
  namespace: kubeflow
spec:
  default:
    predictor:
      tensorflow:
        storageUri: "pvc://mnistpipeline-x5ffs-mnist-model/export"
```
but pod got error like this.
```
mnist-sample-predictor-default-gmtvf-deployment-6d59954b5cb6tx6   0/2     Init:Error              2          36s
```

When I checked the log, I got a message like this.
```
amaramusic@instance-2:~$ k logs -f mnist-sample-predictor-default-gmtvf-deployment-6d59954b5cb6tx6 -n kubeflow  -c storage-initializer
[I 200106 07:13:01 initializer-entrypoint:13] Initializing, args: src_uri [/mnt/pvc/export] dest_path[ [/mnt/models]
[I 200106 07:13:01 storage:35] Copying contents of /mnt/pvc/export to local
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 58, in download
    (_GCS_PREFIX, _S3_PREFIX, _LOCAL_PREFIX))
Exception: Cannot recognize storage type for /mnt/pvc/export
'gs://', 's3://', and 'file://' are the current available storage type.
```

**Comment by jinchihe** [comment]
I think that's just message is not good, check the code below:
https://github.com/kubeflow/kfserving/blob/5f8461762f7f94187e89382a20ea6f17907cc5ff/python/kfserving/kfserving/storage.py#L38

I guess the `/mnt/pvc/export` does not exist.
@mojokb Could you please confirm if the `export` exist in the PVC? Could you please share your PVC `mnistpipeline-x5ffs-mnist-model` content? Thanks.

**Comment by mojokb** [comment]
oops. I got a typo. I misunderstood mounted directory.

**Comment by jinchihe** [comment]
> oops. I got a typo. I misunderstood mounted directory.

If so I think we can just enhance the message to clear that.

**Comment by mojokb** [comment]
I also think there should be more explanation for the pvc type in doc.

**Comment by pvgbabu** [comment]
Hi @mojokb , i would like to try this, could you please share your pvc/pv yaml and the process. 
appreciate all your help

**Comment by cornleaf** [comment]
> oops. I got a typo. I misunderstood mounted directory.

So how do you fix this at last ,could u give some clue?

**Comment by cornleaf** [comment]
> oops. I got a typo. I misunderstood mounted directory.

So how do you fix it at last mojokb

**Comment by pvgbabu** [comment]
Is any one know how to run pvc  mnist job whith dynamic volume provisioning using NFS storage of K8s . Getting error in  /mnt/models

**Comment by Bhavesh-Joshi** [comment]
> oops. I got a typo. I misunderstood mounted directory.

Hi @mojokb  How do you fix it at last? I am also facing the same issue.
