### ISSUE TITLE
[help wanted] KFServing webhook cert installation script

### ISSUE THREAD

**Issue by yuzisun** [kubeflow/kfserving#642]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
https://github.com/kubeflow/kfserving/pull/630 added cert manager to provision webhook certs and this is suggested way for production grade installation, however we still need a way for deploying KFServing for development or for users who does not want this dependency. 

**Anything else you would like to add:**
Looks like we can leverage this script(https://github.com/kubeflow/manifests/blob/master/admission-webhook/bootstrap/base/config-map.yaml#L9) in kubeflow manifest to generate self signed cert and patch to the validation/mutating webhook configuration.

**Comment by Tomcli** [comment]
ok I will look into it, kfserving is getting the cert and key in terms of tls.crt and tls.key. Probably we can tweak the above script and covert it as part of the makefile.
