### ISSUE TITLE
KFServing 0.3 Task list for release with Kubeflow 1.1

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/kfserving#648]
1. Cut a release candidate branch
2. Get PyTorch GPU code in  
3. Add cert generation automation
4. Update SDK  
5. Update KF manifest 
6. Update Pipeline Integration
7. Update KFServing docs (if needed)
7. Publish/Include initial performance results

**Comment by yuzisun** [comment]
9. install istio local gateway in kubeflow installation

**Comment by animeshsingh** [comment]
10. Set min default to "1"

**Comment by florian-koenig** [comment]
What's your scheduled release date for 0.3?

**Comment by animeshsingh** [comment]
@florian-koenig this will follow Kubeflow 1.0 launch announcement, so in couple of weeks following March 2nd. Till then there is quite a bit of housekeeping to make the 1.0 integration experience with Kubeflow smoother.

**Comment by katiesandford** [comment]
@florian-koenig I was told that the 0.3 release will be this week here: https://kubeflow.slack.com/archives/CH6E58LNP/p1583854544134400

**Comment by animeshsingh** [comment]
@jinchihe how are we doing with SDK?

**Comment by jinchihe** [comment]
@animeshsingh Once the PR #700 merged, I will refresh that immediately. Thanks.

**Comment by jinchihe** [comment]
@animeshsingh kfserving SDK v0.3.0 has been released, thanks.

**Comment by yuzisun** [comment]
@animeshsingh @jinchihe Do you need to update pipeline & fairing for KFServing 0.3 ? I think we have done all the other tasks.

**Comment by katiesandford** [comment]
Does anyone know when the manifests will be updated and released with 0.3? They still reference 0.2.2

**Comment by yuzisun** [comment]
@katiesandford  updated 0.3 in kubeflow manifests https://github.com/kubeflow/manifests/pull/1156.

/close

**Comment by animeshsingh** [comment]
Reopened this issue to track release of Opening this issue to track releasing kfserving as part of 1.1.
Ref: kubeflow/kubeflow#5022

**Comment by animeshsingh** [comment]
https://github.com/kubeflow/website/pull/1998

website PR

**Comment by animeshsingh** [comment]
Related issue
https://github.com/kubeflow/kfserving/issues/874

@yuzisun @adrian555 lets use this as the umbrella issue for KFS related release issues

**Comment by adrian555** [comment]
@yuzisun I have deployed kfctl_istio_dex.yaml and update `ClusterRbacConfig` as follow 

```
apiVersion: rbac.istio.io/v1alpha1
kind: ClusterRbacConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.istio.io/v1alpha1","kind":"ClusterRbacConfig","metadata":{"annotations":{},"name":"default"},"spec":{"exclusion":{"namespaces":["istio-system"]},"mode":"ON"}}
  creationTimestamp: "2020-06-17T22:34:03Z"
  generation: 2
  name: default
  resourceVersion: "10313"
  selfLink: /apis/rbac.istio.io/v1alpha1/clusterrbacconfigs/default
  uid: c90bed71-93d5-4e48-ad43-6dea9742a6ff
spec:
  exclusion:
    namespaces:
    - istio-system
    - admin
  mode: ON_WITH_EXCLUSION
```

The test in [`kfserving`](https://github.com/kubeflow/kfserving/blob/master/docs/samples/istio-dex/README.md) now succeeds.

**Comment by jlewi** [comment]
@animeshsingh @adrian555 @yuzisun Any update?

**Comment by animeshsingh** [comment]
@jlewi tested on IBM Cloud - with an incoming manifests PR on Istio/DEX as well (will be cherry picked to 1.1 release branch once merged very soon)

@Jeffwan can you sign off from AWS perspective?
@yuzisun we may need to update the docs on Kubeflow/website as well - if you have bandwidth, please tackle it, else I can take a stab

**Comment by yuzisun** [comment]
@animeshsingh the website doc is already done [here](https://github.com/kubeflow/website/pull/1998) right? is there anything else I need to do ?

btw there is [an issue](https://github.com/kubeflow/manifests/issues/1339) which we want to disable the istio sidecar for knative serving deployments, I'd like to cherry pick onto the 1.1 release branch.

**Comment by animeshsingh** [comment]
thanks @yuzisun 
so not reflecting here https://www.kubeflow.org/docs/components/serving/kfserving/ 
should i be hitting the website at a different URL @jlewi for 1.1 ?

**Comment by jlewi** [comment]
@animeshsingh  try https://master.kubeflow.org/docs/components/serving/kfserving/
