### ISSUE TITLE
KFServing Image Transformer example failing with transformer pod not being able to find predict service

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/kfserving#651]
/kind bug

**What steps did you take and what happened:**
While trying the Image Transformer example as documented here: https://github.com/kubeflow/kfserving/tree/master/docs/samples/transformer/image_transformer

And following the documentation for calling Predict API on the transformer, I get the following output after
```
curl -v -H "Host: ${SERVICE_HOSTNAME}" -d $INPUT_PATH http://$CLUSTER_IP/v1/models/$MODEL_NAME:predict
```

OUTPUT

```
*   Trying x.x.x.x..
* TCP_NODELAY set
* Connected to x.x.x.x (x.x.x.x) port 80 (#0)
> POST /v1/models/transformer-cifar10:predict HTTP/1.1
> Host: transformer-cifar10.default.example.com
> POST /v1/models/transformer-cifar10:predict HTTP/1.1
> Accept: */*
> Content-Length: 3422
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
>
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
< HTTP/1.1 500 Internal Server Error
< content-length: 93
< content-type: text/html; charset=UTF-8
< date: Fri, 31 Jan 2020 12:45:03 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 20371
<
* Curl_http_done: called premature == 0
* Connection #0 to host x.x.x.x left intact
<html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>
```

The transformer pod has the following log snippet. Refer attached file for the entire log.

```
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.7/site-packages/kfserving/handlers/http.py", line 51, in post
        response = model.predict(request)
      File "/usr/local/lib/python3.7/site-packages/kfserving/kfmodel.py", line 49, in predict
        json.dumps(request)
      File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 116, in post
        return request('post', url, data=data, json=json, **kwargs)
      File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
        r = adapter.send(request, **kwargs)
      File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
        raise ConnectionError(e, request=request)
    requests.exceptions.ConnectionError: HTTPConnectionPool(host='transformer-cifar10-predictor-default.default', port=80): Max retries exceeded with url: /v1/models/transformer-cifar10:predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4cb90b7fd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[E 200131 12:45:03 web:2246] 500 POST /v1/models/transformer-cifar10:predict (127.0.0.1) 1646.12ms
```

**What did you expect to happen:**
The expectation is that the transformer pod is able to hit the Prediction API of the deployed PyTorch model.

**Anything else you would like to add:**
Log File for the Transformer pod.
[transformer.log](https://github.com/kubeflow/kfserving/files/4139456/transformer.log)

**Environment:**

- Istio Version: v1.17
- Knative Version: v0.11.0
- KFServing Version: v.2.2
- Kubeflow version: None - Independent KFServing deployment
- Minikube version: None
- Kubernetes version: (use `kubectl version`): v1.14.10
- OS (e.g. from `/etc/os-release`): NA

/cc @yuzisun @animeshsingh

**Comment by yuzisun** [comment]
Thanks for reporting! I think It is missing the istio local cluster gateway deployment, for internal service mesh calls they all go through the istio local gateway and for external traffic it hits the istio ingress gateway. You should check if these gateway deployments are there in `istio-system` namespace. 

```
kubectl get pods -n istio-system
NAME                                     READY   STATUS    RESTARTS   AGE
cluster-local-gateway-5b9c8bcd47-6kbdf   1/1     Running   0          39h
istio-ingressgateway-68f45bd889-2rg7g    1/1     Running   0          39h
```

Please see the following instruction here to install the local gateway. I think we should explicitly state this requirement in the example.
https://github.com/kubeflow/kfserving/blob/3489be0ef2229d855f7ccd6619fe2e9fa174b85b/docs/DEVELOPER_GUIDE.md#install-knative-on-a-kubernetes-cluster

**Comment by krishnadurai** [comment]
@yuzisun Thanks for helping promptly! I was able to fix this issue by installing cluster local gateway.

As discussed, #652 will get this in the Kubeflow installation.

/close

**Comment by diazidabagus** [comment]
Hi how did you get the log? what are the commands thanks!
