### ISSUE TITLE
Install istio local gateway in kubeflow installation

### ISSUE THREAD

**Issue by yuzisun** [kubeflow/kfserving#652]
/kind feature

**Describe the solution you'd like**
istio local gateway is required for internal service mesh calls for knative 0.9+, since knative 0.11 is now installed in kubeflow we need to get istio local gateway deployed as well.

https://github.com/kubeflow/kfserving/blob/3489be0ef2229d855f7ccd6619fe2e9fa174b85b/docs/DEVELOPER_GUIDE.md#install-knative-on-a-kubernetes-cluster

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by animeshsingh** [comment]
@krishnadurai @yuzisun anyone tacking this?

**Comment by krishnadurai** [comment]
@animeshsingh I'm going to raise a PR soon.

/assign @krishnadurai
