### ISSUE TITLE
how to access custom image service?

### ISSUE THREAD

**Issue by Iamlovingit** [kubeflow/kfserving#660]
/kind bug
i try testing the custom sample, it can be deploy, but i dont know how to send request. is there having some explaining?

i want to send request to service-custom-sample
```
NAME                    URL                                                                                         READY   DEFAULT TRAFFIC   CANARY TRAFFIC   AGE
pytorch-cifar10         http://pytorch-cifar10.default.10.166.15.200.xip.io/v1/models/pytorch-cifar10               True    100                                33m
service-custom-sample   http://service-custom-sample.default.10.166.15.200.xip.io/v1/models/service-custom-sample   True    100                                19m

```
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:1.3.4
- Knative Version:0.10.0
- KFServing Version:0.21.0
- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):1.15.3
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@Iamlovingit did you use kfserving sdk to build the custom predictor image or that’s totally custom ?

**Comment by Iamlovingit** [comment]
> @Iamlovingit did you use kfserving sdk to build the custom predictor image or that’s totally custom ?

@yuzisun  it is totally custom. the images include a flask http server, set `port=8080`

**Comment by Iamlovingit** [comment]
add more detail in #673

**Comment by MATRIX4284** [comment]
This article i described how to use custom docker image in kfserving pytorch server:

https://medium.com/@kaustavmukherjee_66179/serve-your-pytorch-models-on-cpu-or-nvidia-gpu-leveraging-kubeflow-kfserving-using-pytorch-server-d24725e779a0
