### ISSUE TITLE
kfserving switch payload from body to header

### ISSUE THREAD

**Issue by valentin-stefan-popa** [kubeflow/kfserving#662]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I try to do a preprocessing part starting from this example: https://github.com/kubeflow/kfserving/tree/master/docs/samples/transformer/image_transformer
I create my own container but when I do a post I get this error in log: "http1connection:289] Malformed HTTP message from 127.0.0.1: Content-Length too long" 
I use this command: "curl -v -H "host: kfserving-tensorflow-transformer-default.kfserving.example.com" -d @./dicom.json http://my-domain/v1/models/pancreaspng:predict"
dicom.json is a json file with a dicom image converted to base64 with size of 107MB
I try same thing from Postman and I get same error. 
I sent file in body not in header. max_header_size is 65536 which is fine but in my case I sent json file in body not in header.
To reproduce this just post a bigger json file to transform
Can someone have a look?

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version: 0.8
- KFServing Version: 2.2.1
- Kubeflow version: 0.7..1
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
this sounds like https://github.com/kubeflow/kfserving/issues/633 ?

**Comment by yuzisun** [comment]
according to tornado the max buffer size is 100M
https://www.tornadoweb.org/en/stable/_modules/tornado/iostream.html

**Comment by valentin-stefan-popa** [comment]
Yes look like it is a similar problem. So I am not the only one with this problem :)
Looking in my code in lib/python3.7/site-packages/tornado/http1connection.py line 98 I have this: 
`self.max_header_size = max_header_size or 65536`
but even if is 100M not help me because my json file have 107M and also main problem is not this. 
When I sent json file I put it in body not in header which means that must be no limitation. For example if I sent same file to predict instead transform I don't get any limitation message
So I suspect that somewhere in kfserving code you get my file from body and send it in header
Also is it normal to have size limitation when I sent data to preprocessing?

**Comment by yuzisun** [comment]
The header limit is 65536 bytes, the body limit is 100M, which predictor you are using, pytorch? I think any tornado based kfserving model server currently has this default limit, we need to make it configurable.

**Comment by valentin-stefan-popa** [comment]
I use tensorflow for predict but my problem is with transformer not with predictor. On predictor side I test with same json file 107MB and there is no limit problem

**Comment by yuzisun** [comment]
tensorflow predictor is not tornado based and is using https://www.tensorflow.org/tfx/guide/serving, so it is not subjected to that limit.

**Comment by valentin-stefan-popa** [comment]
This explain why is working for predict :)
Anyway for transform since we use tornado probably we need to do that part configurable

**Comment by yuzisun** [comment]
agreed, we need to set `max_buffere_size` when starting the tornado server.

**Comment by yuzisun** [comment]
@valentin-stefan-popa are you interested in making a fix? should be relatively easy, we can add an argument `--max-buffer-size` which defaults to 100M for the tornado server and set it here
https://github.com/kubeflow/kfserving/blob/master/python/kfserving/kfserving/kfserver.py#L69.

**Comment by valentin-stefan-popa** [comment]
Yes I will do it.

**Comment by valentin-stefan-popa** [comment]
@yuzisun  I made the fix but now I need to know how to do commit and PR. Which one is the procedure for this? Fork kfserving repo -> Create branch and do commit there -> create PR from my fork repo to kfserving master and add you as reviewer?

**Comment by yuzisun** [comment]
@valentin-stefan-popa you are exactly right ! Excited to see you PR!

**Comment by valentin-stefan-popa** [comment]
@yuzisun Please have a look and add your comments when you have some time.
https://github.com/kubeflow/kfserving/pull/665

**Comment by valentin-stefan-popa** [comment]
@yuzisun first thank you for your help and I have two questions.
1) Since this issue is fixed do I have to close this or who will close it?
2) I have other issue regarding kfserving transform preprocessing and postprocessing :)
Lets say that I have an 3D image which I pass it in preprocessing and I preprocess that image and do predict then at post processing I need some informations used in preprocessing because I want to return an image2D and new returned image must have same shape and same size like 3D image passed in preprocess.  
So my question is do we have something to pass parameters between preprocess and postprocess methods?
I know that one option is to change my model to return also informations which I need at postprocessing but I have too many models and also to send some information from postprocess to predict and predict to pass them back to postprocess look like not a good option even if infos are very small.
Looking in code here: https://github.com/kubeflow/kfserving/blob/master/python/kfserving/kfserving/handlers/http.py#L48
we have this:
`      request = model.preprocess(body)
        request = self.validate(request)
        response = model.predict(request)
        response = model.postprocess(response)`
so there we can have one variable for transporting data from preprocess to postprocess something like this:
`      transport, request = model.preprocess(body)
        request = self.validate(request)
        response = model.predict(request)
        response = model.postprocess(transport, response)`

What do you think? I think is a good chance that some time we need things from preprocessing to postprocessing

**Comment by yuzisun** [comment]
You can close this issue with `/close`, for the second problem not sure what's the best way, maybe we can have some way to pass a context object.

**Comment by valentin-stefan-popa** [comment]
Ok. I will close this issue since is fixed and I will open a new one for second case.  Yes context object or simple json or anything else to pass something safe from preprocess to postprocess will fix the problem and I am sure that kfserving need this option

**Comment by valentin-stefan-popa** [comment]
This issue was fixed by this PR https://github.com/kubeflow/kfserving/pull/665 so it will be closed
