### ISSUE TITLE
transform model_name and PVC are not working

### ISSUE THREAD

**Issue by valentin-stefan-popa** [kubeflow/kfserving#664]
Problem 1) 
I try to set transform model name but look like is not implemented
Bellow is my yaml: 
`apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "my-mnist-serving"
  namespace: "kfserving"
spec:
  default:
    predictor:
      minReplicas: 1
      tensorflow:
        storageUri: "pvc://kfserving-pvc/models/mnist"
    transformer:
      minReplicas: 1
      custom:
        container:
          image: my-image
          name: kfserving-container
          args:
          - --model_name
          - mnist
          env:
          - name: STORAGE_URI
            value: pvc://kfserving-pvc/models`

As you can se I specify model_name as mnist but when I look in logfile after container is created I can see this: "kfserver:83] Registering model: my-mnist-serving" 
Looking in your code here: https://github.com/kubeflow/kfserving/blob/66e03f70f8615185015d6380a2d71ba7aa5e5470/pkg/apis/serving/v1alpha2/transformer.go#L43 I can see that model name is inferenceservice name which is fine.
but since I pass  --model_name it must get that instead inferenceservice name or --model_name must override inferenceservice name

Problem 2)
I try to set PVC in my inferenceservice like for predict custom image but is not working
As you can see in up yaml I do it like this:
`env:
    - name: STORAGE_URI
       value: pvc://kfserving-pvc/models``
From some reasons volume is not created. I suspect that is not implemented also.

**Comment by yuzisun** [comment]
I think problem 2 should be fixed by recent PR https://github.com/kubeflow/kfserving/pull/643, please test with master or wait for 0.3 which should be cut soon.

**Comment by yuzisun** [comment]
fixed in v0.3.0
/close
