### ISSUE TITLE
IngressNotConfigured with kubeflow master

### ISSUE THREAD

**Issue by ryandawsonuk** [kubeflow/kfserving#668]
I installed kubeflow using [something close to kfctl_istio_dex.yaml](https://raw.githubusercontent.com/ryandawsonuk/seldon-gitops/068da0ff6cc181650483733e4d242141e6f9ee7a/kfctl_istio_dex_noseldon.yaml). So I get istio 1.1 rather than 1.3 as I [can't currently run 1.3 with DigitalOcean](https://github.com/kubeflow/kfctl/issues/170). I've been using this setup successfully before but with the latest manifests coming from kubeflow master I now find the kservice never becomes available and the reason is given as `IngressNotConfigured`

**Comment by yuzisun** [comment]
@ryandawsonuk that's known issue and we created one upstream https://github.com/knative/serving/issues/6793

**Comment by yuzisun** [comment]
The issue is that knative serving sends probes to istio ingress gateway but got 302 when redirecting to AuthService for Dex, we are looking into how to whitelist all these probes.

**Comment by ryandawsonuk** [comment]
Cool, thanks for the quick response

**Comment by krishnadurai** [comment]
@ryandawsonuk we are looking to provide a way to whitelist as @yuzisun has mentioned.

/assign

**Comment by ryandawsonuk** [comment]
@krishnadurai have you tried using SKIP_AUTH_URI in the [auth service](https://github.com/arrikto/oidc-authservice/blob/d5c29815649889b4f1762bcb81dd138c0d73858d/README.md#L33) or speaking to @yanniszark ? Or is the part of the problem even knowing what to whitelist?

**Comment by krishnadurai** [comment]
@ryandawsonuk The requests go to the path '/'. Whitelisting the path '/' isn't the right idea.
The requests are proxied by the istio-ingressgateway using the 'Host' (virtual host) parameter, which contains the KNative service's domain, for e.g. 'xyz-sample.default.example.com'.

I'm looking for the right method to whitelist such requests from KNative's prober service.

/cc @yanniszark

**Comment by yanniszark** [comment]
Hi @ryandawsonuk @krishnadurai.
Maybe I'm missing something here, but why do the KNative probes need to go through the Istio Gateway?
What is the KNative probe and what does it probe?
Aren't both the probe and the probed deployment in the same cluster?

**Comment by krishnadurai** [comment]
@yanniszark fair point. I had the same questions initially. The probe does go through the istio-ingressgateway though. Here are the istio-ingressgateway pod logs for `helloworld.go` sample KNative service running with the Dex based EnvoyFilter:

```
[2020-02-11T18:16:21.419Z] "GET / HTTP/1.1" 404 NR "-" "-" 0 0 0 - "10.88.0.31" "Go-http-client/1.1" "4a8bd584-2323-4f40-9230-9797d890b9fb" "helloworld-go.default:80" "-" - - 10.88.1.13:80 10.88.0.31:36237 - -
[2020-02-11T18:16:21.419Z] "GET / HTTP/1.1" 404 NR "-" "-" 0 0 0 - "10.88.0.31" "Go-http-client/1.1" "7298dbfc-58bb-430f-92c5-cf39e97f63d7" "helloworld-go.default.svc:80" "-" - - 10.88.1.13:80 10.88.0.31:36239 - -
[2020-02-11T18:16:21.420Z] "GET / HTTP/1.1" 302 UAEX "-" "-" 0 269 21 21 "10.88.0.31" "Go-http-client/1.1" "27aa43fa-ac17-4a71-8ca2-b4d9fb772219" "helloworld-go.default.example.com:80" "-" - - 10.88.1.13:80 10.88.0.31:36249 - -
```

**Comment by krishnadurai** [comment]
> What is the KNative probe and what does it probe?

The pod networking-istio in Knative serving probes the Istio gateway from outside of the service mesh to see if ingress is available for the Knative service.

Looking at the comments here:
https://github.com/knative/serving/blob/master/config/istio-ingress/controller.yaml

> Aren't both the probe and the probed deployment in the same cluster?
Yes they are in the same cluster

/cc @yuzisun

**Comment by yanniszark** [comment]
@yuzisun @krishnadurai can you please elaborate on why the probe needs to hit the gateway and not the deployment directly, to bypass the need for authentication?
How does this work on GCP?
Is the probe given an IAM serviceaccount?

/cc @jlewi

**Comment by yuzisun** [comment]
@yanniszark as @krishnadurai said, the probes hit the gateway to test if the ingress(virtual service) is available for the knative services. GCP has similar problem, the probes are failing with 401, we can whitelist with `excludePaths` on the ingress jwt authentication policy but whitelisting the path '/' isn't good idea.

**Comment by yanniszark** [comment]
@yuzisun thanks a lot for the explanation. Then, my next questions are:
* Is this prober deployment necessary for KFServing to work? Is KFServing usable without it?
* What is the desired solution? Giving the KFServing probe credentials? Whitelisting the health check paths?

**Comment by animeshsingh** [comment]
For further tests, lets all test on this configuration
https://github.com/kubeflow/manifests/pull/886

**Comment by yanniszark** [comment]
My understanding is that because of this issue, KFServing can't function in auth-enabled Kubeflow deployments.
@jlewi do you believe this blocking for Kubeflow v1.0?

**Comment by krishnadurai** [comment]
@yanniszark when we look at KFServing 0.11.1 and KFServing 0.2.1 combination with either of Istio's configs (1.16 or 1.3.1), you are right.

Whereas v1.0 Kubeflow has KFServing v0.8.0 which shipped with v0.7 Kubeflow.

**Comment by JRBANCEL** [comment]
Hi, I implemented the probing in Knative.

> Is this prober deployment necessary for KFServing to work? Is KFServing usable without it?

No, but without it, it is fire and forget when Knative configure Istio, so a Knative Service CRD being ready might not actually be ready if all the Envoy do not have the latest config. That's what probing solves. Currently, it cannot be disabled.

> What is the desired solution? Giving the KFServing probe credentials? Whitelisting the health check paths?

The cleanest solution is probably to allow probing calls without auth (from inside the cluster only would be safer).
Probing calls do not reach the user container, so there is no risk of them actually doing anything.
Filtering for probing calls is implemented here: https://github.com/knative/serving/blob/master/pkg/network/probe_handler.go

**Comment by yuzisun** [comment]
see https://github.com/knative/serving/issues/6829 also.

- In GCP IAP setup Istio policy can block the probes and there is no way to filter probes on header content. 
- For Istio-Dex setup, not sure if there is a way to bypass auth for probes in envoy filter.

**Comment by krishnadurai** [comment]
@JRBANCEL @yuzisun 
>     * For Istio-Dex setup, not sure if there is a way to bypass auth for probes in envoy filter.

Any method to bypass will require the authservice envoy-filter for Dex to read the origin of the request. It is not secure to whitelist requests based on the origin.

We might want to consider using another gateway for KFServing for the time being until knative/serving#6829 is resolved.

This comes with the downsides of having another gateway and as well as not supporting authenticated requests for serving models.

**Comment by krishnadurai** [comment]
@JRBANCEL as an alternative is it a good idea to have the prober be supplied with programmatic credentials for these requests? This approach will not need whitelisting and keep the gateway access secure.

What is your take on this?

**Comment by JRBANCEL** [comment]
How would you provide the credentials?

**Comment by krishnadurai** [comment]
By mounting secrets and allowing to specify them in headers to the probing requests.

**Comment by Jude188** [comment]
Any news or progress on this one with Kubeflow 1.0 out?

**Comment by krishnadurai** [comment]
@Jude188 
I'm looking to solve this issue for kfctl_istio_dex.yaml which uses 1.3.1 istio.

Though it seems downgrading istio to 1.1.6 in kfctl_istio_dex.yaml and using this PR will help:
https://github.com/kubeflow/manifests/pull/949

You could easily change Istio manifests to 1.1.6 by changing the entries in kfdef applications: istio-crds and istio-install.
change istio-crds-1-3-1 in path to istio-crds and likewise for istio-install-1-3-1.

**Comment by krishnadurai** [comment]
@ryandawsonuk you could use the PR mentioned kubeflow/manifests#949 to enable your setup in Digital Ocean.

**Comment by ryandawsonuk** [comment]
Hi @krishnadurai sorry it has taken me so long to test. I've just taken the latest master, which is at https://github.com/kubeflow/manifests/commit/9ec6bb39e9bb76d7a9bdef290628a6c6f36952ce and includes https://github.com/kubeflow/manifests/pull/949. My InferenceServices do now start. But I'm not clear on how I now make calls to them as they're no longer [reachable on the external IP](https://github.com/kubeflow/kfserving/blob/6fa7a4d90ebb0e63ede15021d5c2f63047919034/docs/samples/custom/hello-world/README.md#run-a-prediction) given by `kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}'`. Just get 404s for that now.

**Comment by krishnadurai** [comment]
@ryandawsonuk 
The gateway you should be looking for is `kfserving-ingressgateway` instead of `istio-ingressgateway`. I'll update the docs as soon as the patch is released.

**Comment by ryandawsonuk** [comment]
Hmm, for me that gives `Error from server (NotFound): services "kfserving-ingressgateway" not found`. I am using a[ kfdef based on istio_dex](https://github.com/ryandawsonuk/seldon-gitops/blob/7342e5e92e90620f838b56ab39efbcb5360c84f4/kfctl_istio_dex_noseldon.yaml). Perhaps it is missing something. I'll have to compare against the manifests repo as [that deployment](https://github.com/kubeflow/manifests/blob/3f8c3582a7d18c390e5b691f10a0bee011c809d2/istio/kfserving-gateway/base/deployment.yaml#L4) isn't coming through for me.

**Comment by krishnadurai** [comment]
@ryandawsonuk thanks for sharing your manifests and kfdef.

From what I see, the component istio/kfserving-gateway is missing in your kfdef:

Please refer to the following diff where I've patched it to some other kfdefs.
https://github.com/kubeflow/manifests/pull/949/files#diff-3246bb7e71d05445ff82aeff687b3d34R31-R38

**Comment by ryandawsonuk** [comment]
@krishnadurai I don't see istio/kfserving-gateway in https://github.com/kubeflow/manifests/blob/6abf161dc352018bd5be22d5394120013d7e54e3/kfdef/kfctl_istio_dex.yaml - is it missing for the 1.3.1 configurations?

**Comment by ryandawsonuk** [comment]
I've now switched to a [1.1.6 version of istio with the istio_dex variant kfdef](https://github.com/ryandawsonuk/seldon-gitops/blob/9594833635148540614a26c80e03211cff283915/kfctl_istio_dex_noseldon.yaml). Am again finding that everything deploys correctly except the [kfserving gateway manifests](https://github.com/kubeflow/manifests/tree/master/istio/kfserving-gateway/base), even though that kustomize folder does get generated with the expected content

**Comment by Jeffwan** [comment]
@ryandawsonuk If you switch to kfdef with kfserving-gateway, it is supposed to skip auth since it uses LoadBalancer without auth directly?

**Comment by ryandawsonuk** [comment]
Yes that’s what I see.

**Comment by yuzisun** [comment]
@ryandawsonuk @cliveseldon Can you help test KFServing in Istio/Dex setup with kubeflow manifest master?

**Comment by sachua** [comment]
@yuzisun I tried KFServing's sklearn example with kubeflow manifest master in Istio-Dex, I am getting IngressNotConfigured when deploying the inferenceservice:
```bash
NAMESPACE   NAME                             URL                                                       LATESTCREATED                          LATESTREADY                            READY     REASON
admin       sklearn-iris-predictor-default   http://sklearn-iris-predictor-default.admin.example.com   sklearn-iris-predictor-default-6j628   sklearn-iris-predictor-default-6j628   Unknown   IngressNotConfigured
```
Checking the logs of networking-istio, I am getting 404s and 302s.

**Comment by yuzisun** [comment]
@sachua Can you help get the output of `kubectl get deployment networking-istio -n knative-serving -oyaml | grep image:` ?

**Comment by sachua** [comment]
```bash
$ kubectl get deployment networking-istio -n knative-serving -oyaml | grep image:
        image: gcr.io/knative-releases/knative.dev/serving/cmd/networking/istio@sha256:727a623ccb17676fae8058cb1691207a9658a8d71bc7603d701e23b1a6037e6c
```
hmm weird, i checked my deployment.yaml and the image should have been 
```bash
gcr.io/knative-releases/knative.dev/serving/cmd/networking/istio@sha256:61461fa789e19895d7d1e5ab96d8bb52a63788e0607e1bd2948b9570efeb6a8f
```

Thanks!

**Comment by yuzisun** [comment]
@sachua Let me know if that solves the issue.

**Comment by sachua** [comment]
@yuzisun yes, the inferenceservice can be deployed now:
```bash
NAMESPACE   NAME                             URL                                                       LATESTCREATED                          LATESTREADY                            READY   REASON
admin       sklearn-iris-predictor-default   http://sklearn-iris-predictor-default.admin.example.com   sklearn-iris-predictor-default-6j628   sklearn-iris-predictor-default-6j628   True    
```

When I tried to curl the inferenceservice, I hit error 302

```bash
$ curl -v -H "Host: sklearn-iris.default.example.com" http://localhost:8080/v1/models/sklearn-iris:predict -d @./docs/samples/sklearn/iris-input.json*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /v1/models/sklearn-iris:predict HTTP/1.1
> Host: sklearn-iris.default.example.com
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 76
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 76 out of 76 bytes
< HTTP/1.1 302 Found
< location: /dex/auth?client_id=kubeflow-oidc-authservice&redirect_uri=%2Flogin%2Foidc&response_type=code&scope=profile+email+groups+openid&state=MTU4OTE3NzQ0N3xFd3dBRUhoNllXOHlja1pqV25aelMwdGFXRkE9fKu-zz3CNlwBQ7WwyRgnt1VIE3bpoPBtclkKcuiMn-0Q
< date: Mon, 11 May 2020 06:10:47 GMT
< content-length: 0
< x-envoy-upstream-service-time: 1
< server: istio-envoy
< 
```

so i tried to get the auth token and pass it through the curl, and still got an error

```bash
$ curl -v -H "Host: sklearn-iris.default.example.com" -H 'Cookie: authservice_session=MTU4OTE3Njk5MHxOd3dBTkVKTE1sWllURmsxV2tkSlRsTTBSalpKV1ZWQ1NqVk5VVGRCV0VKYVJUTlhRbGhaV0RaWE5FbFNWa0pMUTBjM1RGYzNRa0U9fLJ0uQXwPz6iSPj_JDhgBlcie2JiVmup39-45j6MSD9L' http://localhost:8080/v1/models/sklearn-iris:predict -d @./docs/samples/sklearn/iris-input.json
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /v1/models/sklearn-iris:predict HTTP/1.1
> Host: sklearn-iris.default.example.com
> User-Agent: curl/7.58.0
> Accept: */*
> Cookie: authservice_session=MTU4OTE3Njk5MHxOd3dBTkVKTE1sWllURmsxV2tkSlRsTTBSalpKV1ZWQ1NqVk5VVGRCV0VKYVJUTlhRbGhaV0RaWE5FbFNWa0pMUTBjM1RGYzNRa0U9fLJ0uQXwPz6iSPj_JDhgBlcie2JiVmup39-45j6MSD9L
> Content-Length: 76
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 76 out of 76 bytes
< HTTP/1.1 404 Not Found
< x-powered-by: Express
< content-security-policy: default-src 'none'
< x-content-type-options: nosniff
< content-type: text/html; charset=utf-8
< content-length: 170
< date: Mon, 11 May 2020 06:11:15 GMT
< x-envoy-upstream-service-time: 9
< server: istio-envoy
< 
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /v1/models/sklearn-iris:predict</pre>
</body>
</html>
* Connection #0 to host localhost left intact
```

Do you know where the issue might be?

**Comment by yuzisun** [comment]
Nice! @sachua Would you be interested in contributing the docs for how KFServing works with Istio/Dex ?

**Comment by sachua** [comment]
@yuzisun sure, how can I contribute?

**Comment by yuzisun** [comment]
@sachua Add Istio/Dex example [here](https://github.com/kubeflow/kfserving/tree/master/docs/samples) and send a PR following [contribution guideline](https://github.com/kubeflow/kfserving/blob/master/CONTRIBUTING.md)?

**Comment by yuzisun** [comment]
Thanks @sachua for the awesome write up !
https://github.com/kubeflow/kfserving/blob/master/docs/samples/istio-dex/README.md

/close
