### ISSUE TITLE
kfserving-controller-manager pod in CrashLoopBackOff

### ISSUE THREAD

**Issue by ljainker** [kubeflow/kfserving#677]
/kind bug

I have installed Kubeflow v0.7.1 on Kubernetes version is 1.15.4.

The kfserving-controller-manager pod is going into CrashLoopBackOff state everytime its getting restarted.

Below are the logs of the pod:

{"level":"error","ts":1581588648.411941,"logger":"kubebuilder.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":{"Group":"serving.knative.dev","Kind":"Service"},"error":"no matches for kind \"Service\" in version \"serving.knative.dev/v1alpha1\"","stacktrace":"github.com/kubeflow/kfserving/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/kubeflow/kfserving/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/kubeflow/kfserving/vendor/sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/go/src/github.com/kubeflow/kfserving/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:89\ngithub.com/kubeflow/kfserving/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Watch\n\t/go/src/github.com/kubeflow/kfserving/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:122\ngithub.com/kubeflow/kfserving/pkg/controller/inferenceservice.add\n\t/go/src/github.com/kubeflow/kfserving/pkg/controller/inferenceservice/controller.go:90\ngithub.com/kubeflow/kfserving/pkg/controller/inferenceservice.Add\n\t/go/src/github.com/kubeflow/kfserving/pkg/controller/inferenceservice/controller.go:57\ngithub.com/kubeflow/kfserving/pkg/controller.AddToManager\n\t/go/src/github.com/kubeflow/kfserving/pkg/controller/controller.go:29\nmain.main\n\t/go/src/github.com/kubeflow/kfserving/cmd/manager/main.go:82\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:198"}
{"level":"error","ts":1581588648.4121358,"logger":"entrypoint","msg":"unable to register controllers to the manager","error":"no matches for kind \"Service\" in version \"serving.knative.dev/v1alpha1\"","stacktrace":"github.com/kubeflow/kfserving/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/kubeflow/kfserving/vendor/github.com/go-logr/zapr/zapr.go:128\nmain.main\n\t/go/src/github.com/kubeflow/kfserving/cmd/manager/main.go:83\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:198"}

**Comment by ljainker** [comment]
The docker used  for kfserving is gcr.io/kfserving/kfserving-controller:0.2.2

**Comment by yuzisun** [comment]
@ljainker which kubeflow setup you are running, looks like knative is not installed there ?

**Comment by ljainker** [comment]
Hi @yuzisun , yes the knative is not getting installed. I followed the deployment from the kubeflow official document - https://v0-7.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/
This ticket may now be closed.
Thank you

**Comment by yuzisun** [comment]
Cool!
/close
