### ISSUE TITLE
KFServing controller often gets OOMKilled during initial reconciliation 

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfserving#681]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
When the KFServing controller restarted with some inferenceservice on the cluster, often time it creates an initial burst of memory during reconcile and created an OOMKilled loops. Here's some initial memory burst I saw when running 2 inferenceservices on my cluster.

```shell
tommyli$ kubectl top pod -n kfserving-system
NAME                             CPU(cores)   MEMORY(bytes)
kfserving-controller-manager-0   661m         1777Mi
```
(After 5 minutes)
```shell
tommyli$ kubectl top pod -n kfserving-system
NAME                             CPU(cores)   MEMORY(bytes)
kfserving-controller-manager-0   10m          882Mi
```

**What did you expect to happen:**
We should have a way to configure the memory limit using parameters or overlays when we deploy KFServing with kustomize or kfctl. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.1.6
- Knative Version: 0.11.1
- KFServing Version: master
- Kubeflow version: 1.0
- Minikube version:
- Kubernetes version: (use `kubectl version`): 1.15.3
- OS (e.g. from `/etc/os-release`):

**Comment by bitscuit** [comment]
I can pick up this issue

/assign @bitscuit
