### ISSUE TITLE
Tensorrt example is not working

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfserving#684]
/kind bug
We are not able to ping the tensorrt server once we deployed the example.
```
tommyli$ curl -H "Host: ${SERVICE_HOSTNAME}" http://${CLUSTER_IP}/api/status -v
*   Trying 169.47.250.204...
* TCP_NODELAY set
* Connected to 169.47.250.204 (169.47.250.204) port 80 (#0)
> GET /api/status HTTP/1.1
> Host:
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< x-powered-by: Express
< content-type: application/json; charset=utf-8
< content-length: 55
< etag: W/"37-6EWWYBSIFc46fYxIBg1qhqmTLDY"
< date: Wed, 19 Feb 2020 01:22:18 GMT
< x-envoy-upstream-service-time: 5
< server: istio-envoy
<
* Connection #0 to host 169.47.250.204 left intact
* Closing connection 0
```

Then we discovered that the host needs to be `tensorrt-simple-string-predictor-default.default.example.com` instead of `tensorrt-simple-string.default.example.com` from the inferenceservice. 

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.1.6
- Knative Version: 0.11.1
- KFServing Version: 0.2.2
- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
This is known issue, we are punting on v2 data plane for tensorrt inference server to work with kfserving because their rest api currently is different. To walk around you can directly hit the predictor bypassing the top level virtual service.

**Comment by Tomcli** [comment]
Thanks Dan.
