### ISSUE TITLE
Serving model from gs:// fails with "'gs://', 's3://', and 'file://' are the current available storage type."

### ISSUE THREAD

**Issue by velascoluis** [kubeflow/kfserving#685]
/kind bug

Train a model with pyTorch operator , deploy the dat file on gs://

(venv) velascoluis@python3venvsandbox:~/pytorch$ gsutil ls gs://kf10rc4
gs://kf10rc4/model_cpu.dat

Luanch the KFServing with the following yaml

apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "pytorch-mnist-serving-01"
spec:
  default:
    predictor:
      pytorch:
        storageUri: "gs://kf10rc4/"
        modelClassName: "Net"

(venv) velascoluis@python3venvsandbox:~/pytorch$ kubectl create -f inference.yaml 
inferenceservice.serving.kubeflow.org/pytorch-mnist-serving-01 created

![image](https://user-images.githubusercontent.com/57447519/74818994-eaf0a900-52ff-11ea-8f39-33ae47ccf784.png)

**What did you expect to happen:**

Deploy the model serving

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version: v1.0
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@velascoluis which namespace the service gets deployed to ? I think you may have deployed the service in a namespace with `control-plane` label, The storage-initializer init container does not get injected for deployments in those namespaces since they do not go through the pod mutating webhook, the error is a bit misleading.

**Comment by yuzisun** [comment]
please check https://github.com/kubeflow/kfserving#kfserving-in-kubeflow-installation, the storage initializer init container is not injected because the service is deployed to namespace with `control-plane` label, model is not mounted to /mnt/models hence the above error.

/close
