### ISSUE TITLE
Get the service endpoint by KFServing SDK client quickly

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/kfserving#686]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Get a user feedback for SDK, user would like get the service endpoint by KFServing SDK client quickly, because from the get(watch=True), the URL is not show completely if the endpiont is long, as below.

```
KFServing.get('wahaha-service', namespace='wahaha', watch=True, timeout_seconds=120)
NAME                 READY      DEFAULT_TRAFFIC CANARY_TRAFFIC  URL                                               
wahaha-service         False                                                                                        
wahaha-service         False                                                                                        
wahaha-service         True       100                             http://wahaha-service.wahaha.example.com/v1/mod...
```

 User would like get the service endpoint by KFServing SDK client, such as
```python
KFServing = KFServingClient()
KFServing.get_url('flower-sample', namespace='default')
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by yuzisun** [comment]
I thought `get` returns the full json response and you can directly access the url there right?

**Comment by jinchihe** [comment]
Yeah, I agree with, that should be easy after get.
/close
