### ISSUE TITLE
Improve custom image sample documentation. 

### ISSUE THREAD

**Issue by rzgry** [kubeflow/kfserving#694]
/kind feature

Add an example using a prebuilt existing container with a model wrapped inside it. 

Add another example that extends the KFServing SDK to create a container compatible with KFServing client format, so that all the functionalities of KFServing can be leveraged

**Comment by animeshsingh** [comment]
As per @yuzisun - 

this can be a good example for kfserving custom https://github.com/SeldonIO/seldon-models/blob/master/pytorch/moviesentiment_roberta/inference/kfserving/model.py
