### ISSUE TITLE
Support  for PySpark 2.4.4 Mllib 

### ISSUE THREAD

**Issue by ace-gabriel** [kubeflow/kfserving#706]
/kind feature

Hi, our current pipeline and models are implemented using PySpark Mllib. After looking at the examples I realize we currently don't support PySpark Mllib. Can we include PySpark model server as additional feature in the next release? Thanks

Link on how MLflow implement Spark: https://www.mlflow.org/docs/latest/python_api/mlflow.spark.html

**Comment by Talador12** [comment]
Who is working on this? Support for Spark ML would be a huge boon for KFServing!
