### ISSUE TITLE
logger spec missing from the V1alpha2PredictorSpec in the python sdk

### ISSUE THREAD

**Issue by katiesandford** [kubeflow/kfserving#725]
/kind bug

**Summary**

The logger spec is missing from the V1alpha2PredictorSpec in the kfserving sdk (v 0.2.2.1).

**What did you expect to happen:**
I would have expected that the sdk would mirror the structure of the custom resource definition.
Since the [spec contains a logger](https://github.com/kubeflow/kfserving/tree/master/docs/samples/logger/knative-eventing) I'd have expected the [predictor spec ](https://github.com/kubeflow/kfserving/blob/master/python/kfserving/kfserving/models/v1alpha2_predictor_spec.py) to include a logger.

**Anything else you would like to add:**
I've found a very hacky workaround in the meantime....
```python
predictor = V1alpha2PredictorSpec(...)

predictor.attribute_map['logger'] = 'logger'

predictor.swagger_types['logger'] = 'dict'

predictor.attribute_map.logger = {
    'mode': 'all',
    'url': 'http://message-dumper.default/'
}
```

**Environment:**

- KFServing Version: 0.2.2.1

**Comment by katiesandford** [comment]
Check out related slack convo here: https://kubeflow.slack.com/archives/CH6E58LNP/p1583854544134400

Sounds like it will be fixed in the 0.3 release

**Comment by jinchihe** [comment]
@katiesandford kfserving SDK v0.3.0 has been released. Would you please check with new version SDK.

**Comment by jinchihe** [comment]
@katiesandford The SDK has been refreshed, Could you please have a check, thanks.
