### ISSUE TITLE
Contribute to kfserving project（pytorchserver related）

### ISSUE THREAD

**Issue by zhangrongguo** [kubeflow/kfserving#727]
Dear Sir or Madam，

We have made some changes to pytorchserver, and want to contribute the code to KFServing project. We have submitted the CLA.

The changes are described as follows:

- Pass class with parameters to pytorchserver
- Auto batching for pytorchserver predict

**Comment by yuzisun** [comment]
Nice! we have some discussions on this issue https://github.com/kubeflow/kfserving/issues/546.
