### ISSUE TITLE
custom image has 2 interfaces, how to access them?

### ISSUE THREAD

**Issue by Iamlovingit** [kubeflow/kfserving#733]
/kind bug
If the custom image has one interface, it can be accessed by set route '/v1/models/{servername}:predict'. But if the custom image has >=2 interfaces, how to access others?
This is a custom flask server example, i can call `hello_world` by `curl http://xxx//v1/models/my-custom-sample:predict`, but i cannot call `hello_world_test`.
```python
import os

from flask import Flask

app = Flask(__name__)

@app.route('/v1/models/my-custom-sample:test')
def hello_world_test():
    target = os.environ.get('TARGET', 'World')
    return 'test Hello {}!\n'.format(target)

@app.route('/v1/models/my-custom-sample:predict')
def hello_world():
    target = os.environ.get('TARGET', 'World')
    return 'Hello {}!\n'.format(target)

if __name__ == "__main__":
    app.run(debug=True,host='0.0.0.0',port=int(os.environ.get('PORT', 8080)))

```

**What did you expect to happen:**
I want to access the 2 inferfaces both.

**Comment by yuzisun** [comment]
As discussed, we can possibly introduce an annotation for the custom endpoint and make the top level virtual service configurable.

**Comment by Iamlovingit** [comment]
> As discussed, we can possibly introduce an annotation for the custom endpoint and make the top level virtual service configurable.

good idea. I will give a try  in next week. do you have some else suggestions?
