### ISSUE TITLE
v1alpha2 Laundry List

### ISSUE THREAD

**Issue by ellistarn** [kubeflow/kfserving#765]
Some recent customer feedback has exposed some deficiencies in our interface.

* Expose PodSpec features (perhaps [revision spec?](https://github.com/knative/serving/blob/master/pkg/apis/serving/v1/revision_types.go#L72))
* Clarify frameworks tensorrt/triton
* Explore alternate Canarying implementations (single resource vs multiple resources)

**Comment by ellis-bigelow** [comment]
Multi Model Serving APIs: https://github.com/kubeflow/kfserving/issues/773

**Comment by ellis-bigelow** [comment]
Another usecase for podspec features #794
