### ISSUE TITLE
"RevisionMissing"  when running custom-prebuilt-image samples 

### ISSUE THREAD

**Issue by mengkai94** [kubeflow/kfserving#770]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**
status is ok

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

$ kubectl describe revision/custom-prebuilt-image-predictor-default-zrmjk
reuslt as flowing.
Name:         custom-prebuilt-image-predictor-default-zrmjk
Namespace:    default
Labels:       component=predictor
              controller-tools.k8s.io=1.0
              endpoint=default
              model=custom-prebuilt-image
              serving.knative.dev/configuration=custom-prebuilt-image-predictor-default
              serving.knative.dev/configurationGeneration=1
              serving.knative.dev/service=custom-prebuilt-image-predictor-default
              serving.kubeflow.org/inferenceservice=custom-prebuilt-image
Annotations:  autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
              autoscaling.knative.dev/minScale: 1
              autoscaling.knative.dev/target: 1
              queue.sidecar.serving.knative.dev/resourcePercentage: 20
              serving.knative.dev/creator: system:serviceaccount:kfserving-system:default
API Version:  serving.knative.dev/v1
Kind:         Revision
Metadata:
  Creation Timestamp:  2020-04-09T12:58:50Z
  Generate Name:       custom-prebuilt-image-predictor-default-
  Generation:          1
  Owner References:
    API Version:           serving.knative.dev/v1alpha1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Configuration
    Name:                  custom-prebuilt-image-predictor-default
    UID:                   dbf711f1-7a61-11ea-9dde-10f6bbe84cff
  Resource Version:        37272
  Self Link:               /apis/serving.knative.dev/v1/namespaces/default/revisions/custom-prebuilt-image-predictor-default-zrmjk
  UID:                     dc02e453-7a61-11ea-9dde-10f6bbe84cff
Spec:
  Container Concurrency:  0
  Containers:
    Image:  codait/max-object-detector
    Name:   user-container
    Ports:
      Container Port:  5000
    Readiness Probe:
      Success Threshold:  1
      Tcp Socket:
        Port:  0
    Resources:
      Limits:
        Cpu:     1
        Memory:  2Gi
      Requests:
        Cpu:        1
        Memory:     2Gi
  Timeout Seconds:  60
Status:
  Conditions:
    Last Transition Time:  2020-04-09T13:01:07Z
    Message:               The target could not be activated.
    Reason:                TimedOut
    Severity:              Info
    Status:                False
    Type:                  Active
    Last Transition Time:  2020-04-09T12:58:57Z
    Reason:                Deploying
    Status:                Unknown
    Type:                  ContainerHealthy
    Last Transition Time:  2020-04-09T12:58:57Z
    Message:               0/1 nodes are available: 1 Insufficient memory.
    Reason:                Unschedulable
    Status:                False
    Type:                  Ready
    Last Transition Time:  2020-04-09T12:58:57Z
    Message:               0/1 nodes are available: 1 Insufficient memory.
    Reason:                Unschedulable
    Status:                False
    Type:                  ResourcesAvailable
  Image Digest:            index.docker.io/codait/max-object-detector@sha256:ca9b10849ac84b21ab3e4b66d92c2c7ff0a3320be5b38b3ec249737465cfb4ec
  Log URL:                 http://localhost:8001/api/v1/namespaces/knative-monitoring/services/kibana-logging/proxy/app/kibana#/discover?_a=(query:(match:(kubernetes.labels.knative-dev%2FrevisionUID:(query:'dc02e453-7a61-11ea-9dde-10f6bbe84cff',type:phrase))))
  Observed Generation:     1
  Service Name:            custom-prebuilt-image-predictor-default-zrmjk
Events:                    <none>

**Environment:**

- Istio Version: 1.3.5
- Knative Version:0.11.1
- KFServing Version:0.3.0
- Kubeflow version:
- Minikube version:1.4.0
- Kubernetes version: (use `kubectl version`):1.14.0
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
I see big error message there

Last Transition Time: 2020-04-09T12:58:57Z
Message: 0/1 nodes are available: 1 Insufficient memory.

**Comment by mengkai94** [comment]
> I see big error message there
> 
> Last Transition Time: 2020-04-09T12:58:57Z
> Message: 0/1 nodes are available: 1 Insufficient memory.

the memory is sufficient
$ free
              total        used        free      shared  buff/cache   available
Mem:        7781060     1639596      249468      475428     5891996     5880668
Swap:             0           0           0

**Comment by mengkai94** [comment]
reset minikube memory to 10000, the problem is solved.
when using minikube run kfserving, the memory must be largger than a threshold?

**Comment by yuzisun** [comment]
Because It installs istio and knative on minikube so I guess not much left for the inference service pod.

**Comment by mengkai94** [comment]
@yuzisun  thanks a lot.

**Comment by Mayurji** [comment]
I was getting an similar error while deploying an inference service, changing the terminationGracePeriodSeconds parameter in the predictorSpec from default 30 seconds to 300 seconds, time depends on the size of the image. I hope, it helps.
