### ISSUE TITLE
KFServing fails to copy models in top-level of a GCS Bucket

### ISSUE THREAD

**Issue by bestowjay** [kubeflow/kfserving#771]
/kind bug

**What steps did you take and what happened:**
1. Create a GCS bucket, call it `model-sample` - you can make it public for this example, or otherwise grant docker access
2. save a tensorflow model using the [keras.save](https://www.tensorflow.org/guide/keras/save_and_serialize#export_to_savedmodel) method to the bucket - `gs://model-sample/model/1`
3. run storage-initializer container in docker `docker run -it gcr.io/kfserving/storage-initializer:0.2.2 gs://model-sample/model /mnt` (if you need bucket permissions, you can use `GOOGLE_APPLICATION_CREDENTIALS` env variable, e.g.) - this also fails in k8s, but i found it simpler to reproduce through the init container alone
4. Notice container error claiming "File Exists: 1" or similar

**What did you expect to happen:**
Model to be successfully downloaded into the `/mnt` directory

**Anything else you would like to add:**
problem seems to be (at time of writing) around storage.py [_download_gcs](https://github.com/kubeflow/kfserving/blob/master/python/kfserving/kfserving/storage.py#L86) method. Where the directory check isn't passing when there's only 1 subdirectory.

**Environment:**

- Istio Version: 
- Knative Version: 0.11.1
- KFServing Version: 0.2.2
- Kubeflow version: 1.0.1
- Minikube version:
- Kubernetes version: (use `kubectl version`): v1.14.10-gke.32
- OS (e.g. from `/etc/os-release`):

**StackTrace:**
```
$ kubectl logs mnist-sample-predictor-default-qxf4m-deployment-7c89d4cbf4cxdjp storage-initializer
[I 200410 19:56:17 initializer-entrypoint:13] Initializing, args: src_uri [gs://models/mnist-sample-tf] dest_path[ [/mnt/models]
[I 200410 19:56:17 storage:35] Copying contents of gs://models/mnist-sample-tf to local
[I 200410 19:56:17 storage:111] Downloading: /mnt/models/1
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 48, in download
    Storage._download_gcs(uri, out_dir)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 108, in _download_gcs
    os.makedirs(local_object_dir, exist_ok=True)
  File "/usr/local/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/mnt/models/1'
```

**Comment by ellis-bigelow** [comment]
Do you have a bigger stacktrace that you can attach?

**Comment by bestowjay** [comment]
updated description with stacktrace, logs from my deployment pod

**Comment by bestowjay** [comment]
I thought this was a problem with top-level copies, but it seems something else is going on as well. This has happened to me after loading a model from a bucket and saving that same model 1 version greater.

```
import tensorflow as tf
from tensorflow import keras

new_model = tf.keras.models.load_model('gs://models/samples/mnist-sample-tf/3')
new_model.save('gs://models/samples/mnist-sample-tf/4')

kfserving.delete('mnist-sample', namespace='default')
kfserving.create(isvc, namespace='default')
```

`isvc` is exactly the sample SDK code from [here](https://github.com/kubeflow/kfserving/blob/master/docs/samples/client/kfserving_sdk_sample.ipynb) except using the bucket path above (the bucket name is changed) and the namespace 'default'.

There are 3 versions of the model in my bucket `1/`, `2/` and `3/` and when I load up version `3` and save it as version `4` using the code above, then delete and recreate the inference service I see the same stacktrace from the storage-initializer
```
$ kubectl logs mnist-sample-predictor-default-c8ffq-deployment-68dfd4459f7wh5r storage-initializer
[I 200420 20:25:03 initializer-entrypoint:13] Initializing, args: src_uri [gs://models/samples/mnist-sample-tf] dest_path[ [/mnt/models]
[I 200420 20:25:03 storage:35] Copying contents of gs://models/samples/mnist-sample-tf to local
[I 200420 20:25:03 storage:111] Downloading: /mnt/models/1/saved_model.pb
[I 200420 20:25:03 storage:111] Downloading: /mnt/models/1/variables/variables.data-00000-of-00001
[I 200420 20:25:03 storage:111] Downloading: /mnt/models/1/variables/variables.index
[I 200420 20:25:03 storage:111] Downloading: /mnt/models/2/saved_model.pb
[I 200420 20:25:03 storage:111] Downloading: /mnt/models/2/variables/variables.data-00000-of-00001
[I 200420 20:25:03 storage:111] Downloading: /mnt/models/2/variables/variables.index
[I 200420 20:25:03 storage:111] Downloading: /mnt/models/3/saved_model.pb
[I 200420 20:25:03 storage:111] Downloading: /mnt/models/3/variables/variables.data-00000-of-00001
[I 200420 20:25:03 storage:111] Downloading: /mnt/models/3/variables/variables.index
[I 200420 20:25:03 storage:111] Downloading: /mnt/models/4
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 48, in download
    Storage._download_gcs(uri, out_dir)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 108, in _download_gcs
    os.makedirs(local_object_dir, exist_ok=True)
  File "/usr/local/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/mnt/models/4'
```

**Comment by bestowjay** [comment]
eehhh, this might actually be a tensorflow bug? something about saving the model with tensorflow is breaking this. If I manually `gsutil cp` the same directory to a new place, it's downloaded just fine...

**Comment by bestowjay** [comment]
I think it most definitely is a Tensorflow model saving issue....I'm able to complete this successfully if I do this...

```
new_model.save('/tmp/mnist-sample/4')
!gsutil cp -r /tmp/mnist-sample/4 gs://models/samples/mnist-sample/
```

sorry for the noise!

**Comment by JakeTheWise** [comment]
Can you explain how this is a tensorflow issue if `tf.keras.models.load_model('gs://models/samples/mnist-sample-tf/3')` works? And if `gsutil cp` works? Seems like it's an issue with `_download_gcs` that needs to be addressed...

**Comment by bestowjay** [comment]
> Can you explain how this is a tensorflow saving issue if `tf.keras.models.load_model('gs://...')`and `gsutil cp -r gs://...` work? Seems like it's an issue with `_download_gcs` that needs to be addressed...

hmm i thought i reopened this elsewhere, but maybe i didn't. i think this might actually be related to how something is iterating over a blob. it looks at a "folder" which doesn't actually exist in GCS, and in my example is `4`, and touches a file on the filesystem, then when we try to move into that path as a directory we can't because it's a file.

**Comment by JakeTheWise** [comment]
Yeah I agree. I made a PR to fix this. https://github.com/kubeflow/kfserving/pull/1205
