### ISSUE TITLE
InferenceService with Kafka Event Source 

### ISSUE THREAD

**Issue by alokumar1** [kubeflow/kfserving#785]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I was trying to use kfserving inferenceservice with kafka-event source  and I have already a kafka cluster running. So i skipped the Deploy Kafka part given on this page   https://github.com/kubeflow/kfserving/tree/master/docs/samples/kafka then I tried to Deploy Kafka Event Source https://github.com/kubeflow/kfserving/tree/master/docs/samples/kafka#deploy-kafka-event-source   with instruction provided there. The first two yamls applied successfully but the last one failed with this mesaage:-

kubectl apply --filename https://github.com/knative/eventing-contrib/releases/download/v0.10.2/release.yaml
error: unable to read URL "https://github.com/knative/eventing-contrib/releases/download/v0.10.2/release.yaml", server reported 404 Not Found, status code=404

It seems that file is not present or removed. Can you update the documentation and tell how to install kafka source ?

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by alokumar1** [comment]
After deploying kafka event source using this https://github.com/yuzisun/kfserving/tree/master/docs/samples/kafka#deploy-kafka-event-source it installed properly but I got another error when creating kafka event source https://github.com/yuzisun/kfserving/tree/master/docs/samples/kafka#create-kafka-event-source

kubectl apply -f kafka-source.yaml
error: unable to recognize "kafka-source.yaml": no matches for kind "KafkaSource" in version "sources.eventing.knative.dev/v1alpha1"

**Comment by yuzisun** [comment]
> After deploying kafka event source using this https://github.com/yuzisun/kfserving/tree/master/docs/samples/kafka#deploy-kafka-event-source it installed properly but I got another error when creating kafka event source https://github.com/yuzisun/kfserving/tree/master/docs/samples/kafka#create-kafka-event-source
> 
> kubectl apply -f kafka-source.yaml
> error: unable to recognize "kafka-source.yaml": no matches for kind "KafkaSource" in version "sources.eventing.knative.dev/v1alpha1"

sorry the api group is changed, let me fix that too.

**Comment by alokumar1** [comment]
After changing the api group it created the event source but got an error saying  address not set for &ObjectReference.
my kafka source yaml :- 
```
apiVersion: sources.knative.dev/v1alpha1 
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: knative-group
  bootstrapServers: ***.***.***.***:9092
  topics: framedata
  sink:
    ref:
      apiVersion: serving.kubeflow.org/v1alpha2
      kind: InferenceService
      name: torch
```
 
I have created a inferenceservice with name torch and it is working fine.
```
NAME    URL                                                READY   DEFAULT TRAFFIC   CANARY TRAFFIC   AGE
torch   http://torch.default.example.com/v1/models/torch   True    100                                61m
```

```
Name:         kafka-source
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"sources.knative.dev/v1alpha1","kind":"KafkaSource","metadata":{"annotations":{},"name":"kafka-source","namespace":"default"...
API Version:  sources.knative.dev/v1alpha1
Kind:         KafkaSource
Metadata:
  Creation Timestamp:  2020-04-18T07:56:05Z
  Generation:          1
  Resource Version:    495892
  Self Link:           /apis/sources.knative.dev/v1alpha1/namespaces/default/kafkasources/kafka-source
  UID:                 27a6b717-92ba-47fd-bc44-2fdcdf5ddd1c
Spec:
  Bootstrap Servers:  ***.***.***.***:9092
  Consumer Group:     knative-group
  Net:
    Sasl:
      Password:
      User:
    Tls:
      Ca Cert:
      Cert:
      Key:
  Resources:
    Limits:
    Requests:
  Sink:
    Ref:
      API Version:  serving.kubeflow.org/v1alpha2
      Kind:         InferenceService
      Name:         torch
  Topics:           framedata
Status:
  Conditions:
    Last Transition Time:  2020-04-18T07:56:05Z
    Status:                Unknown
    Type:                  Deployed
    Last Transition Time:  2020-04-18T07:56:05Z
    Reason:                NotFound
    Status:                False
    Type:                  Ready
    Last Transition Time:  2020-04-18T07:56:05Z
    Reason:                NotFound
    Status:                False
    Type:                  SinkProvided
Events:
  Type     Reason         Age                 From                    Message
  ----     ------         ----                ----                    -------
  Warning  InternalError  63s (x20 over 39m)  kafkasource-controller  getting sink URI: address not set for &ObjectReference{Kind:InferenceService,Namespace:default,Name:torch,UID:,APIVersion:serving.kubeflow.org/v1alpha2,ResourceVersion:,FieldPath:,}
```

**Comment by yuzisun** [comment]
are you on kfserving 0.3?

**Comment by alokumar1** [comment]
I am using kfserving that is installed by kubeflow v1.0.1

**Comment by alokumar1** [comment]
I am  using kfserving==0.3.0.1  SDK

**Comment by yuzisun** [comment]
> I am using kfserving that is installed by kubeflow v1.0.1
> I have not installed it independently.

Kubeflow v1.0.1 is still on KFServing 0.2.2, kafka event source support is added in 0.3.

**Comment by alokumar1** [comment]
is there anyway I can update to 0.3?

**Comment by yuzisun** [comment]
> is there anyway I can update to 0.3?

It is not a straight forward upgrade since KFServing release yaml is slightly from KFServing installation in Kubeflow. If you are just playing around and testing out, you can install KFServing 0.3 standalone and try kafka event source.

**Comment by alokumar1** [comment]
Actually, I was using both kubeflow pipelines for training and kfserving for serving the models and since kubeflow installation has kfserving installed I thought it would be good rather than installing kfserving independently.
Anyway, I will try KFServing 0.3 standalone.
