### ISSUE TITLE
Investigate integration of TorchServe in KFServing

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/kfserving#790]
Investigate the capabilities and fit for integration criteria for TorchServe in KFServing

https://aws.amazon.com/blogs/aws/announcing-torchserve-an-open-source-model-server-for-pytorch/

Good candidate to replace custom PyTorch server

**Comment by animeshsingh** [comment]
[Architecture doc](https://torchserve-docs.s3-us-west-2.amazonaws.com/docs/torchserve_architecture_v0.pdf)

**Comment by animeshsingh** [comment]
@Jeffwan is this something you or anyone else from AWS be interested in taking up and contributing?

**Comment by ellis-bigelow** [comment]
Great topic for discussion in a KFS WG meeting. I'd love to see the AWS folks involved in the multi-model serving discussion tomorrow as well. We need to have a pytorch story around this.

**Comment by Jeffwan** [comment]
@animeshsingh We can take this up. There mighbe some upstream works needs to be done first to support current kfserving v2 protocol. 

/assign @Jeffwan

**Comment by animeshsingh** [comment]
Thats's great. Thanks @Jeffwan! 

The meeting has shifted to a biweekly basis - so we didn't have one today - and would be great to get your inputs in next meeting.

**Comment by animeshsingh** [comment]
@Jeffwan any progress on this side?

**Comment by Jeffwan** [comment]
@animeshsingh Just finish oncall in past two weeks. I will start the work from this week.

**Comment by yuzisun** [comment]
@Jeffwan Let us know your plan to integrate torchserver, we'd really want this to be in our v1beta1 release for 0.5.

**Comment by Jeffwan** [comment]
@yuzisun Working on prototype, we get some feature requests from some cx as well. I will make sure it's released in 0.5. e

**Comment by Jeffwan** [comment]
Talked with KFServing maintainers, I think the expectation is torchserve can support v2 prediction protocol.

**Comment by Jeffwan** [comment]
Have the discussion in the bi-weekly meeting. Here's the summary. 

1. Does torchserve need to keep the consistency with v2? How does v2 protocol support additional features? Any v3, v4 plans? 

v2 protocol is from TFServing and Triton past experiences. It’s pretty stable and community will try to provide back-forward experiences. New features like adding new data types or tensor types can be added through [v2 protocol extension](https://github.com/kubeflow/kfserving/tree/master/docs/predict-api/v2).

2. Can we create an additional layer in KFServing to convert KFServing API to TorchServe API? 

Technically yes, however, the concern is more on performance side. extra deserialization and transmitting will drop inference performance .

**Comment by Jeffwan** [comment]
@ellistarn @animeshsingh @yuzisun 

Trying to pull someone from internal torchserve team, seems they have different opinion on the V2. However, as we discussed, V2 is not necessary.  I am currently busy with test infra support on AWS and not able to catch up on this story. @ellistarn told me someone is interested in the story as well, If there's some one has interest, I would them to take the lead on this story. Seems @yuzisun and @jeffgriffith really like to get this supported asap. Don't want to block this story on my side.

**Comment by Jeffwan** [comment]
@Jagadeesh Are you interested in implementing this feature?

**Comment by yuzisun** [comment]
I have done a bit research on torchserve, our current pytorch spec won't change much, it is more about the implementation change.

Torchserve provides a model archiver which mainly support two model formats

**Eager mode model**
- Serialized model file(.pt): the file presents the state_dict in case of eager mode model
- Model file: the file contains the model class extended from torch.nn.modules representing the model architecture.
- Index_to_name.json: this file contains the mapping of predicted index to class
- Handler: default or custom handler(.py)

This is currently what KFServing pytorchserver supports.

**Torchscript model**
- Serialized model file(.pt): a executable ScriptModule(torchscript)
- Index_to_name.json: this file contains the mapping of predicted index to class
- Handler: default or custom handler(.py)

This approach does not require user providing the python code and the model can be loaded into non python environment, currently KFServing can support torchscript model with triton inference server.

### Data plane
The data plane differences potentially can be solved by url rewrite on virtual service.

Endpoint | KFServing v2 | TorchServe
-- | -- | --
Prediction | POST v2/models/${MODEL_NAME}[/versions/${MODEL_VERSION}]/infer | POST /predictions/{model_name}/{version}
Service Health | v2/health/live | GET ping
Register model | POST v2/repository/models/${MODEL_NAME}/load | POST /models?url=xx&model_name=xx&handler=xx&runtime=PYTHON&response_timeout=120s
Unregister model | POST v2/repository/models/${MODEL_NAME}/unload | DELETE /models/{model_name}/{version}
Describe the model status | GET v2/models/${MODEL_NAME}[/versions/${MODEL_VERSION}]/status | GET /models/{model_name}/{version}
List models | ? | GET /models
