### ISSUE TITLE
kfserving tensorflow flowers-sampleprediction through curl not working in kubeflow-v1.0.2 in GKE

### ISSUE THREAD

**Issue by prem0912** [kubeflow/kfserving#798]
/kind bug

**What steps did you take and what happened:**
Kfserving tensorflow flowers-sample prediction through curl command not working in kubeflow-v1.0 in GKE
Followed steps in https://github.com/kubeflow/kfserving/tree/master/docs/samples/tensorflow 
flowers-sample in kubeflow v1.0

But error got through curl command to predict data
Error :

* Connected to X.X.X.X port 31380 (#0)
> POST /v1/models/flowers-sample:predict HTTP/1.1
> Host: flowers-sample.anonymous.example.com
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 16139
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
< HTTP/1.1 404 Not Found
< x-powered-by: Express
< content-security-policy: default-src 'none'
< x-content-type-options: nosniff
< content-type: text/html; charset=utf-8
< content-length: 172
< date: Sun, 26 Apr 2020 17:04:37 GMT
< x-envoy-upstream-service-time: 0
< server: istio-envoy
< 
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /v1/models/flowers-sample:predict</pre>
</body>
</html>
* Connection #0 to host X.X.X.X1 left intact

**What did you expect to happen:**
flowers-sample curl command to predict the result

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: default version comes with kubeflow 1.0
- Knative Version: default version comes with kubeflow 1.0
- KFServing Version: default version comes with kubeflow 1.0
- Kubeflow version: v1.0
- Kubernetes version: (use `kubectl version`): 1.14.10
- OS (e.g. from `/etc/os-release`): ubuntu

**Comment by yuzisun** [comment]
@prem0912 Can you get the full output of inference service status?

**Comment by prem0912** [comment]
@yuzisun You mean logs of  flowers-sample inference service or kfserving-control-manager or logs of  pods in  knative-serving namespace...
One more update kfserving is working in the installation of kubeflow V1.0,  which I have done before a month. 
But kfserving not working  where kubeflow is installed past a week.

**Comment by apryiomka** [comment]
I have the same issue with sklearn example:

**Comment by apryiomka** [comment]
i ran into similar issue and turned out i used incorrect istio gateway selector for forwarding

**Comment by apryiomka** [comment]
I can reproduce the issue with sklearn example as well:

**Comment by larssuanet** [comment]
I am running into the same problem. I'm on KFServing v0.3.0 and Knative v0.11.2, using Knative with Istio v1.3.1. 

After some digging, I found that the url returned by my inference service routes to the `cluster-local-gateway` and not to the kubernetes service as created by knative: 

Virtual Services:
```
$ kubectl get virtualservices.networking.istio.io -n my-namespace                                                                                                         
NAME                          GATEWAYS                                                                          HOSTS                                                                                                                                                                                                                                                                                                                                     AGE
test                          [knative-ingress-gateway.knative-serving knative-serving/cluster-local-gateway]   [test.my-namespace.example.com test.my-namespace.svc.cluster.local]                                                                                                                                                                                     46m
test-predictor-default        [knative-serving/cluster-local-gateway knative-serving/knative-ingress-gateway]   [test-predictor-default.my-namespace test-predictor-default.my-namespace.example.com test-predictor-default.my-namespace.svc test-predictor-default.my-namespace.svc.cluster.local]   46m
test-predictor-default-mesh   [mesh]                                                                            [test-predictor-default.my-namespace test-predictor-default.my-namespace.svc test-predictor-default.my-namespace.svc.cluster.local]                                                                                                    46m
```
Virtual service:
```
$ k get virtualservices.networking.istio.io -n my-namespace test -o yaml
...
spec:
  gateways:
  - knative-ingress-gateway.knative-serving
  - knative-serving/cluster-local-gateway
  hosts:
  - test.my-namespace.example.com
  - test.my-namespace.svc.cluster.local
...
    route:
    - destination:
        host: cluster-local-gateway.istio-system.svc.cluster.local
        port:
          number: 80
      headers:
        request:
          set:
            Host: test-predictor-default.my-namespace.svc.cluster.local
      weight: 100
```

Since I don't have the `cluster-local-gateway` enabled, my predictions don't return anything. 
However, predictions **do work** on `test-predictor-default.my-namespace.example.com`. Can anyone verify this?

**Comment by yuzisun** [comment]
@larssuanet We currently depend on local gateway, can you get that installed ?

**Comment by bjmrevilla** [comment]
I encountered the same problem as well. I followed the instructions in [setting up](https://www.kubeflow.org/docs/started/workstation/minikube-linux/) Kubeflow in Minikube running on a Linux VM. This is the [KFDef](https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.2.yaml) that I used.
```
$ MODEL_NAME=flowers-sample
$ export INPUT_PATH=@./input.json
$ CLUSTER_IP=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.clusterIP}')
10.103.137.5
$ SERVICE_HOSTNAME=$(sudo -E kubectl get inferenceservice ${MODEL_NAME} -n bjmrevilla -o jsonpath='{.status.url}' | cut -d "/" -f 3)
flowers-sample.bjmrevilla.example.com
```

```
$ curl -v -H "Host: ${SERVICE_HOSTNAME}" http://$CLUSTER_IP/v1/models/$MODEL_NAME:predict -d $INPUT_PATH

*   Trying 10.103.137.5...
* TCP_NODELAY set
* Connected to 10.103.137.5 (10.103.137.5) port 80 (#0)
> POST /v1/models/flowers-sample:predict HTTP/1.1
> Host: flowers-sample.bjmrevilla.example.com
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 16201
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
< HTTP/1.1 404 Not Found
< x-powered-by: Express
< content-security-policy: default-src 'none'
< x-content-type-options: nosniff
< content-type: text/html; charset=utf-8
< content-length: 172
< date: Thu, 14 May 2020 14:57:01 GMT
< x-envoy-upstream-service-time: 0
< server: istio-envoy
< 
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /v1/models/flowers-sample:predict</pre>
</body>
</html>
* Connection #0 to host 10.103.137.5 left intact
```
Virtual Services:
```
$ kubectl get vs -n bjmrevilla
NAME                                    GATEWAYS                                                                          HOSTS                                                                                                                                                                                                                 AGE
flowers-sample                          [knative-ingress-gateway.knative-serving]                                         [flowers-sample.bjmrevilla.example.com]                                                                                                                                                                               67m
flowers-sample-predictor-default        [knative-serving/cluster-local-gateway knative-serving/knative-ingress-gateway]   [flowers-sample-predictor-default.bjmrevilla flowers-sample-predictor-default.bjmrevilla.example.com flowers-sample-predictor-default.bjmrevilla.svc flowers-sample-predictor-default.bjmrevilla.svc.cluster.local]   68m
flowers-sample-predictor-default-mesh   [mesh]                                                                            [flowers-sample-predictor-default.bjmrevilla flowers-sample-predictor-default.bjmrevilla.svc flowers-sample-predictor-default.bjmrevilla.svc.cluster.local]                                                           68m
```

```
$ kubectl get vs flowers-sample -n bjmrevilla -o yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"serving.kubeflow.org/v1alpha2","kind":"InferenceService","metadata":{"annotations":{},"name":"flowers-sample","namespace":"bjmrevilla"},"spec":{"default":{"predictor":{"tensorflow":{"storageUri":"gs://kfserving-samples/models/tensorflow/flowers"}}}}}
  creationTimestamp: "2020-05-14T13:54:37Z"
  generation: 1
  name: flowers-sample
  namespace: bjmrevilla
  ownerReferences:
  - apiVersion: serving.kubeflow.org/v1alpha2
    blockOwnerDeletion: true
    controller: true
    kind: InferenceService
    name: flowers-sample
    uid: ec37509c-d032-4935-bef8-6b0145971ed2
  resourceVersion: "5998"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/bjmrevilla/virtualservices/flowers-sample
  uid: fd9c1d91-fd02-4251-be41-9614712a0ced
spec:
  gateways:
  - knative-ingress-gateway.knative-serving
  hosts:
  - flowers-sample.bjmrevilla.example.com
  http:
  - match:
    - uri:
        prefix: /v1/models/flowers-sample:predict
    route:
    - destination:
        host: kfserving-ingressgateway.istio-system.svc.cluster.local
        port: {}
      headers:
        request:
          set:
            Host: flowers-sample-predictor-default.bjmrevilla.example.com
      weight: 100
```
```
$ kubectl describe inferenceservice flowers-sample -nbjmrevilla
Name:         flowers-sample
Namespace:    bjmrevilla
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"serving.kubeflow.org/v1alpha2","kind":"InferenceService","metadata":{"annotations":{},"name":"flowers-sample","namespace":"...
API Version:  serving.kubeflow.org/v1alpha2
Kind:         InferenceService
Metadata:
  Creation Timestamp:  2020-05-14T13:54:26Z
  Generation:          5
  Resource Version:    5999
  Self Link:           /apis/serving.kubeflow.org/v1alpha2/namespaces/bjmrevilla/inferenceservices/flowers-sample
  UID:                 ec37509c-d032-4935-bef8-6b0145971ed2
Spec:
  Default:
    Predictor:
      Tensorflow:
        Resources:
          Limits:
            Cpu:     1
            Memory:  2Gi
          Requests:
            Cpu:          1
            Memory:       2Gi
        Runtime Version:  1.14.0
        Storage Uri:      gs://kfserving-samples/models/tensorflow/flowers
Status:
  Canary:
  Conditions:
    Last Transition Time:  2020-05-14T13:54:37Z
    Status:                True
    Type:                  DefaultPredictorReady
    Last Transition Time:  2020-05-14T13:54:37Z
    Status:                True
    Type:                  Ready
    Last Transition Time:  2020-05-14T13:54:37Z
    Status:                True
    Type:                  RoutesReady
  Default:
    Predictor:
      Host:  flowers-sample-predictor-default.bjmrevilla.example.com
      Name:  flowers-sample-predictor-default-4wd4q
  Traffic:   100
  URL:       http://flowers-sample.bjmrevilla.example.com/v1/models/flowers-sample
Events:      <none>
```

**Comment by yuzisun** [comment]
@bjmrevilla there is an issue unfortunately in kubeflow manifests v1.0.2 https://github.com/kubeflow/manifests/issues/1142, either you can fall back to v1.0.0 or use manifest from v1.0 branch/master.

**Comment by yuzisun** [comment]
This is fixed in upcoming kubeflow 1.1, however you can still configure to use kubeflow gateway to fix the issue if you are using 1.0.2. There are two places which need to configure:
1) Configure knative [config-istio](https://github.com/kubeflow/manifests/blob/master/knative/knative-serving-install/base/config-map.yaml#L661) to use the `kubeflow gateway`
2) Configure kfserving [inferenceservice-config](https://github.com/kubeflow/manifests/blob/master/kfserving/kfserving-install/base/config-map.yaml#L25) to use the `kubeflow gateway`

**Comment by SachinVarghese** [comment]
Hi, @yuzisun I tried the above configuration as you have mentioned on kubeflow v1.0.2, but now the inference service fails to deploy. I did some debugging and found that the underlying knative route is not ready due to `IngressNotConfigured`. I am posting the status of a kubectl describe on the route below. But I saw that the revisions are ready, any idea what else could be missing?
```
Status:
  Address:
    URL:  http://sk-iris-predictor-default.seldon.svc.cluster.local
  Conditions:
    Last Transition Time:  2020-07-10T11:17:20Z
    Status:                True
    Type:                  AllTrafficAssigned
    Last Transition Time:  2020-07-10T11:17:20Z
    Message:               Ingress has not yet been reconciled.
    Reason:                IngressNotConfigured
    Status:                Unknown
    Type:                  IngressReady
    Last Transition Time:  2020-07-10T11:17:20Z
    Message:               Ingress has not yet been reconciled.
    Reason:                IngressNotConfigured
    Status:                Unknown
    Type:                  Ready
  Observed Generation:     1
  Traffic:
    Latest Revision:  true
    Percent:          100
    Revision Name:    sk-iris-predictor-default-v6fhc
  URL:                http://sk-iris-predictor-default.seldon.example.com
Events:
  Type     Reason         Age   From              Message
  ----     ------         ----  ----              -------
  Normal   Created        11s   route-controller  Created placeholder service "sk-iris-predictor-default"
  Normal   Created        11s   route-controller  Created Ingress "sk-iris-predictor-default"
  Warning  InternalError  11s   route-controller  failed to update Ingress: Operation cannot be fulfilled on ingresses.networking.internal.knative.dev "sk-iris-predictor-default": the object has been modified; please apply your changes to the latest version and try again
```

**Comment by yuzisun** [comment]
@SachinVarghese you want to give a shot with [kubeflow 1.1 RC0](https://github.com/kubeflow/manifests/releases/tag/v1.1-rc.0)?

**Comment by yuzisun** [comment]
this has been fixed in kubeflow 1.1
/close

**Comment by nicozhang** [comment]
> this has been fixed in kubeflow 1.1 /close

this problem still exists in 1.5 and 1.4  

```
[root@dev-master kfserving]# curl -v -H "Host: ${SERVICE_HOSTNAME}" -H "Cookie: authservice_session=${SESSION}" http://${CLUSTER_IP}/v1/models/${MODEL_NAME}:predict -d ${INPUT_PATH}
* About to connect() to 10.101.216.126 port 80 (#0)
*   Trying 10.101.216.126...
* Connected to 10.101.216.126 (10.101.216.126) port 80 (#0)
> POST /v1/models/sklearn-iris:predict HTTP/1.1
> User-Agent: curl/7.29.0
> Accept: */*
> Host: sklearn-iris.kubeflow-user-example-com.example.com
> Cookie: authservice_session=MTY0OTQwNzgyOXxOd3dBTkVaQ1ZqWlpTazFFVlVVMU56TkxWRTQyV0ZkV1ZVTllWMWRCVEZGQldFTXpNamRMUjFoVE56SmFTVmMyVGpWTVMwVk9VRkU9fKa7dC36g3eCJjrZakMOkJOEvoouLi190z06UrDWWjQZ
> Content-Length: 88
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 88 out of 88 bytes
< HTTP/1.1 404 Not Found
< x-powered-by: Express
< content-security-policy: default-src 'none'
< x-content-type-options: nosniff
< content-type: text/html; charset=utf-8
< content-length: 170
< date: Fri, 08 Apr 2022 08:55:50 GMT
< x-envoy-upstream-service-time: 2
< server: istio-envoy
<
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /v1/models/sklearn-iris:predict</pre>
</body>
</html>
* Connection #0 to host 10.101.216.126 left intact
```

**Comment by namlh16** [comment]
> > this has been fixed in kubeflow 1.1 /close
> 
> this problem still exists in 1.5 and 1.4
> 
> ```
> [root@dev-master kfserving]# curl -v -H "Host: ${SERVICE_HOSTNAME}" -H "Cookie: authservice_session=${SESSION}" http://${CLUSTER_IP}/v1/models/${MODEL_NAME}:predict -d ${INPUT_PATH}
> * About to connect() to 10.101.216.126 port 80 (#0)
> *   Trying 10.101.216.126...
> * Connected to 10.101.216.126 (10.101.216.126) port 80 (#0)
> > POST /v1/models/sklearn-iris:predict HTTP/1.1
> > User-Agent: curl/7.29.0
> > Accept: */*
> > Host: sklearn-iris.kubeflow-user-example-com.example.com
> > Cookie: authservice_session=MTY0OTQwNzgyOXxOd3dBTkVaQ1ZqWlpTazFFVlVVMU56TkxWRTQyV0ZkV1ZVTllWMWRCVEZGQldFTXpNamRMUjFoVE56SmFTVmMyVGpWTVMwVk9VRkU9fKa7dC36g3eCJjrZakMOkJOEvoouLi190z06UrDWWjQZ
> > Content-Length: 88
> > Content-Type: application/x-www-form-urlencoded
> >
> * upload completely sent off: 88 out of 88 bytes
> < HTTP/1.1 404 Not Found
> < x-powered-by: Express
> < content-security-policy: default-src 'none'
> < x-content-type-options: nosniff
> < content-type: text/html; charset=utf-8
> < content-length: 170
> < date: Fri, 08 Apr 2022 08:55:50 GMT
> < x-envoy-upstream-service-time: 2
> < server: istio-envoy
> <
> <!DOCTYPE html>
> <html lang="en">
> <head>
> <meta charset="utf-8">
> <title>Error</title>
> </head>
> <body>
> <pre>Cannot POST /v1/models/sklearn-iris:predict</pre>
> </body>
> </html>
> * Connection #0 to host 10.101.216.126 left intact
> ```

I face to same issue with kubeflow 1.3 , have you solve this problem ? @nicozhang

**Comment by nicozhang** [comment]
> > > this has been fixed in kubeflow 1.1 /close
> > 
> > 
> > this problem still exists in 1.5 and 1.4
> > ```
> > [root@dev-master kfserving]# curl -v -H "Host: ${SERVICE_HOSTNAME}" -H "Cookie: authservice_session=${SESSION}" http://${CLUSTER_IP}/v1/models/${MODEL_NAME}:predict -d ${INPUT_PATH}
> > * About to connect() to 10.101.216.126 port 80 (#0)
> > *   Trying 10.101.216.126...
> > * Connected to 10.101.216.126 (10.101.216.126) port 80 (#0)
> > > POST /v1/models/sklearn-iris:predict HTTP/1.1
> > > User-Agent: curl/7.29.0
> > > Accept: */*
> > > Host: sklearn-iris.kubeflow-user-example-com.example.com
> > > Cookie: authservice_session=MTY0OTQwNzgyOXxOd3dBTkVaQ1ZqWlpTazFFVlVVMU56TkxWRTQyV0ZkV1ZVTllWMWRCVEZGQldFTXpNamRMUjFoVE56SmFTVmMyVGpWTVMwVk9VRkU9fKa7dC36g3eCJjrZakMOkJOEvoouLi190z06UrDWWjQZ
> > > Content-Length: 88
> > > Content-Type: application/x-www-form-urlencoded
> > >
> > * upload completely sent off: 88 out of 88 bytes
> > < HTTP/1.1 404 Not Found
> > < x-powered-by: Express
> > < content-security-policy: default-src 'none'
> > < x-content-type-options: nosniff
> > < content-type: text/html; charset=utf-8
> > < content-length: 170
> > < date: Fri, 08 Apr 2022 08:55:50 GMT
> > < x-envoy-upstream-service-time: 2
> > < server: istio-envoy
> > <
> > <!DOCTYPE html>
> > <html lang="en">
> > <head>
> > <meta charset="utf-8">
> > <title>Error</title>
> > </head>
> > <body>
> > <pre>Cannot POST /v1/models/sklearn-iris:predict</pre>
> > </body>
> > </html>
> > * Connection #0 to host 10.101.216.126 left intact
> > ```
> 
> I face to same issue with kubeflow 1.3 , have you solve this problem ? @nicozhang



> > > this has been fixed in kubeflow 1.1 /close
> > 
> > 
> > this problem still exists in 1.5 and 1.4
> > ```
> > [root@dev-master kfserving]# curl -v -H "Host: ${SERVICE_HOSTNAME}" -H "Cookie: authservice_session=${SESSION}" http://${CLUSTER_IP}/v1/models/${MODEL_NAME}:predict -d ${INPUT_PATH}
> > * About to connect() to 10.101.216.126 port 80 (#0)
> > *   Trying 10.101.216.126...
> > * Connected to 10.101.216.126 (10.101.216.126) port 80 (#0)
> > > POST /v1/models/sklearn-iris:predict HTTP/1.1
> > > User-Agent: curl/7.29.0
> > > Accept: */*
> > > Host: sklearn-iris.kubeflow-user-example-com.example.com
> > > Cookie: authservice_session=MTY0OTQwNzgyOXxOd3dBTkVaQ1ZqWlpTazFFVlVVMU56TkxWRTQyV0ZkV1ZVTllWMWRCVEZGQldFTXpNamRMUjFoVE56SmFTVmMyVGpWTVMwVk9VRkU9fKa7dC36g3eCJjrZakMOkJOEvoouLi190z06UrDWWjQZ
> > > Content-Length: 88
> > > Content-Type: application/x-www-form-urlencoded
> > >
> > * upload completely sent off: 88 out of 88 bytes
> > < HTTP/1.1 404 Not Found
> > < x-powered-by: Express
> > < content-security-policy: default-src 'none'
> > < x-content-type-options: nosniff
> > < content-type: text/html; charset=utf-8
> > < content-length: 170
> > < date: Fri, 08 Apr 2022 08:55:50 GMT
> > < x-envoy-upstream-service-time: 2
> > < server: istio-envoy
> > <
> > <!DOCTYPE html>
> > <html lang="en">
> > <head>
> > <meta charset="utf-8">
> > <title>Error</title>
> > </head>
> > <body>
> > <pre>Cannot POST /v1/models/sklearn-iris:predict</pre>
> > </body>
> > </html>
> > * Connection #0 to host 10.101.216.126 left intact
> > ```
> 
> I face to same issue with kubeflow 1.3 , have you solve this problem ? @nicozhang

check this https://github.com/kserve/kserve/issues/2138#issuecomment-1117426374 ,may be helpful

**Comment by ajithkj** [comment]
Hi @nicozhang , @namlh16, @yuzliu 
I'm also facing same issue and not able to resolve.

*   Trying <url>:8080...
* TCP_NODELAY set
* Connected to <url> (<url>) port 8080 (#0)
> POST /v1/models/iris-kf-auth-project:predict HTTP/1.1
> Host: iris-kf-auth-project.ajkj.example.com
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Length: 76
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 76 out of 76 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< content-type: text/html; charset=UTF-8
< referrer-policy: no-referrer
< content-length: 315
< date: Thu, 23 Jun 2022 13:50:32 GMT
< x-envoy-upstream-service-time: 62
< server: envoy
< 

<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>404 Not Found</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Not Found</h1>
<h2>The requested URL <code>/v1/models/iris-kf-auth-project:predict</code> was not found on this server.</h2>
<h2></h2>
</body></html>
* Connection #0 to host <url> left intact


Are you guys able to resolve?

**Comment by nicozhang** [comment]
> Hi @nicozhang , @namlh16, @yuzliu I'm also facing same issue and not able to resolve.
> 
> * Trying :8080...
> * TCP_NODELAY set
> * Connected to  () port 8080 (#0)
> 
> > POST /v1/models/iris-kf-auth-project:predict HTTP/1.1
> > Host: iris-kf-auth-project.ajkj.example.com
> > User-Agent: curl/7.68.0
> > Accept: _/_
> > Content-Length: 76
> > Content-Type: application/x-www-form-urlencoded
> 
> * upload completely sent off: 76 out of 76 bytes
> * Mark bundle as not supporting multiuse
>   < HTTP/1.1 404 Not Found
>   < content-type: text/html; charset=UTF-8
>   < referrer-policy: no-referrer
>   < content-length: 315
>   < date: Thu, 23 Jun 2022 13:50:32 GMT
>   < x-envoy-upstream-service-time: 62
>   < server: envoy
>   <
> 
> <title>404 Not Found</title>
> # Error: Not Found
> ## The requested URL `/v1/models/iris-kf-auth-project:predict` was not found on this server.
> * Connection #0 to host left intact
> Are you guys able to resolve?

The problem is caused by the sklearn version.  The version of training model is diff from the version in kfserving image, so the model can not be load correctly. Try the same version sklearn .
