### ISSUE TITLE
kubernetes probes using HealthHandler endpoint succeed when models are not ready

### ISSUE THREAD

**Issue by dshen51** [kubeflow/kfserving#799]
/kind bug

**What steps did you take and what happened:**
Used the [HealthHandler endpoint](https://github.com/kubeflow/kfserving/blob/92c5f3c9df662c853beef86bddf7f30ab5d8b996/python/kfserving/kfserving/kfserver.py#L62-L63) to set up a Kubernetes readiness probe. The probe succeeded even though the model was not ready. 

**What did you expect to happen:**
Readiness probe failure when model is not ready. 

**Anything else you would like to add:**
[Kubernetes probe documentation](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) says `Any code greater than or equal to 200 and less than 400 indicates success. Any other code indicates failure`, which seems to imply that the [response contents](https://github.com/kubeflow/kfserving/blob/92c5f3c9df662c853beef86bddf7f30ab5d8b996/python/kfserving/kfserving/kfserver.py#L108-L111) (which include the model's `.ready` property) are ignored. 

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by kolasanichaitanya** [comment]
I can make a PR for this. should the error code when the model is not ready be 404 or a custom one ?

**Comment by ellis-bigelow** [comment]
Wait we're returning 200 before the model is loaded? 400 or 503 (service unavailable) is fine to start. Happy to hear suggestions if you have other ideas.

**Comment by dshen51** [comment]
i was thinking 503, but i don't feel too strongly about the particular code that's used.
