### ISSUE TITLE
Disable retries in Istio VirtualService 

### ISSUE THREAD

**Issue by salanki** [kubeflow/kfserving#808]
/kind feature

**Describe the solution you'd like**
Currently, the retires in the VirtualService are setup to retry three times on all errors. KNative will also currently retry three times on all errors between a Transformer and Predictor. These settings, combined with default high timeouts can easily lead to a self-DoS in an overload condition. See screenshot.

![Screen Shot 2020-04-30 at 16 35 04](https://user-images.githubusercontent.com/192223/81032842-5e19ae00-8e5f-11ea-9293-80b15a8316a9.png)

KNative has now removed the retries in their VirtualServices: https://github.com/knative/serving/issues/6549 https://github.com/knative/serving/pull/7842

KFserving should do one of the following:

1) Disable retries completely (Implemented in PR #807)
2) Allow retries, but not on the 502/504 that are thrown on timeouts. Retrying on connect-failure should be safe.
3) Make the behavior configurable, as users might have different requirements for if they want KFServing to handle retrying or they already have a mechanism to do that higher up in the stack.

**Comment by yuzisun** [comment]
disabled the top level virtual service retries in https://github.com/kubeflow/kfserving/pull/807 and releasing with 0.4.
