### ISSUE TITLE
Inference service is not ready while knative service is

### ISSUE THREAD

**Issue by larssuanet** [kubeflow/kfserving#812]
/kind bug

**What steps did you take and what happened:**

I deployed the sklearn-iris example with the `cluster-local-gateway` configured in Knative (using Ambassador, not Istio). The `services.serving.knative.dev` enters the ready state, while the `inferenceservices.serving.kubeflow.org` does not.

**What did you expect to happen:**

I expect the `inferenceservices.serving.kubeflow.org` to become ready after the `services.serving.knative.dev` is ready.

**Anything else you would like to add:**

`services.serving.knative.dev` is ready:
```
$ kubectl get ksvc -n default
NAME                                  URL                                                                                        LATESTCREATED                                                   LATESTREADY                                                     READY   REASON
sklearn-iris-predictor-default        http://sklearn-iris-predictor-default.default.svc.cluster.local                            sklearn-iris-predictor-default-79z6p                            sklearn-iris-predictor-default-79z6p                            True
```

`inferenceservices.serving.kubeflow.org` is not ready:
```
$ kubectl get inferenceservices.serving.kubeflow.org -n default
NAME                                    URL   READY   DEFAULT TRAFFIC   CANARY TRAFFIC   AGE
sklearn-iris                                  False                                      84m
```

Using `kubectl port-forward` on ambassador to test predictions works:
```
POST http://localhost:3000/v1/models/sklearn-iris:predict
200
75 ms
POST /v1/models/sklearn-iris:predict HTTP/1.1
Host: sklearn-iris-predictor-default.default.svc.cluster.local
Content-Type: application/json
User-Agent: PostmanRuntime/7.24.1
Accept: */*
Cache-Control: no-cache
Postman-Token: 5790a480-ecd7-4213-80c9-9536d6c077c0
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 81
{
  "instances": [
    [6.8,  2.8,  4.8,  1.4],
    [6.0,  3.4,  4.5,  1.6]
  ]
}
HTTP/1.1 200 OK
content-length: 23
content-type: application/json; charset=UTF-8
date: Wed, 06 May 2020 16:50:11 GMT
server: envoy
x-envoy-upstream-service-time: 6
{"predictions": [1, 1]}
```

**Environment:**

- Ambassador Version: 1.4.2
- Knative Version: 0.14.0
- KFServing Version: 0.3.0
- Kubernetes version: 1.15.11 (AWS EKS)

**Comment by yuzisun** [comment]
@larssuanet we have a top level virtual service which does canary traffic split as well as routing between KFServing transformer, explainer and predictor, currently it is depending on Istio so the inference service status stays false because it wasn't able to create Istio virtual service. Yes the underlying knative service can still work.. but you won't be able to do canary rollout.

**Comment by larssuanet** [comment]
@yuzisun alright, thanks for sharing. 

I tried Ambassador because I couldn't get the `cluster-local-gateway` to work with Istio (Knative 0.11.2 & Istio 1.3.1), but that is more of a Knative issue. Seems like I'll be switching back to Istio anyway. Will close the issue. Thanks again!
