### ISSUE TITLE
TFServing takes forever to shutdown

### ISSUE THREAD

**Issue by ellistarn** [kubeflow/kfserving#82]
Tensorflow deployed pods take forever to die. This is probably due to signal mishandling for TFserving. Perhaps we should be more aggressive with shutdown logic on our pods.

**Comment by yuzisun** [comment]
Knative configuration has a timeout field which by default sets to 5 mins, so kubernetes will wait that long to terminate the pod to give the requests grace period to finish processing .

**Comment by yuzisun** [comment]
I think we can surface this field onto our spec, timeout should be tunable.

**Comment by ellis-bigelow** [comment]
Agreed. We need to figure out a clean way to organize all these fields. I
want to avoid a messy spec.

*From: *Dan Sun <notifications@github.com>
*Date: *Fri, May 10, 2019, 5:25 PM
*To: *kubeflow/kfserving
*Cc: *Ellis Bigelow, Author

I think we can surface this field onto our spec, timeout should be tunable.

**Comment by yuzisun** [comment]
this will be configurable in 0.6, https://github.com/knative/serving/issues/3342.
