### ISSUE TITLE
s3 Model Serving Example has wrong yaml fields for AWS credentials

### ISSUE THREAD

**Issue by jpatanooga** [kubeflow/kfserving#827]
/kind bug

**What steps did you take and what happened:**
https://github.com/kubeflow/kfserving/blob/master/docs/samples/s3/s3_secret.yaml

Container fails to download files from s3 for InferenceService deployment

If you view the deployment pod, 

kubectl describe pod aws-sklearn-model-predictor-default-pff27-deployment-55978gslb6

you see:

      Message:      OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"setenv: invalid argument\"": unknown

**What did you expect to happen:**

It should pull the data, and then load the model locally in the image

**Anything else you would like to add:**

has fields:

...
data:
  awsAccessKeyID: bWluaW8=
  awsSecretAccessKey: bWluaW8xMjM=

The fields should be:

stringData:
  awsAccessKeyID: foo
  awsSecretAccessKey: bar

as explained:

https://kubernetes.io/docs/concepts/configuration/secret

for string data being passed as a secret

**Environment:**

From:
https://github.com/kubeflow/kfserving/blob/v0.3.0/hack/quick_install.sh

- Istio Version: 1.3.6
- Knative Version: 0.12.0
- KFServing Version: 0.2.2
- Kubeflow version: [none]
- Minikube version: v1.9.2
- Kubernetes version: (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`):

OSX 10.15.3

**Comment by yuzisun** [comment]
fixed in #843
/close
