### ISSUE TITLE
Missing requirements.txt in the Pypi source code

### ISSUE THREAD

**Issue by nphilou** [kubeflow/kfserving#860]
**What steps did you take and what happened:**
The requirements.txt file is missing in the source code on Pypi so setuptools will not work.

```
Executing setuptoolsBuildPhase
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 23, in <module>
    with open('requirements.txt') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
builder for '/nix/store/z8sh0v4cji9aq9v02865273xvmhcwzgh-python3.8-kfserving-0.3.0.1.drv' failed with exit code 1
cannot build derivation '/nix/store/75ihn4avq52qdpavs0s8c1y0nj0wjfdx-python3-3.8.2-env.drv': 1 dependencies couldn't be built
```

**What did you expect to happen:**
requirements.txt in the tar.gz archive

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version: 0.3.0.1
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`): NixOS 20.03 (Markhor) x86_64

**Comment by jinchihe** [comment]
@nphilou what were you doing when this problem occurred? install kfserving sdk from pypi? Thanks.

**Comment by nphilou** [comment]
@jinchihe I was installing kfserving from Pypi sources (kfserving-0.3.0.1.tar.gz) and more precisely, `nix-build` of https://gist.github.com/nphilou/5c9fe0715c94b51f8d1f24e557d3c90a.

It should be equivalent to `python setup.py install` of kfserving-0.3.0.1.tar.gz (https://pypi.org/project/kfserving/#files).

**Comment by jinchihe** [comment]
OK, got that, thanks. @nphilou 

/assign
