### ISSUE TITLE
supervisor server in custom image run failed

### ISSUE THREAD

**Issue by Iamlovingit** [kubeflow/kfserving#869]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
custom image include the supervisor service,  when deploy this image, this error is occured:
```
Error: The directory named as part of the path /var/log/supervisor/supervisord.log does not exist.
For help, use /usr/bin/supervisord -h
```

I found that the `user-container`  mount the `/var/log` from knative
```
Mounts:
      /var/log from knative-var-log (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-q7dh2 (ro)
```

how to fix it?

**Comment by yuzisun** [comment]
looks like it is related to this issue https://github.com/knative/serving/issues/3809.

**Comment by yuzisun** [comment]
This is not KFServing issue, better to follow up with knative/serving#3809.
/close
