### ISSUE TITLE
Inferenceservice status is 'Unknown' with 'IngressNotConfigured'

### ISSUE THREAD

**Issue by songm28** [kubeflow/kfserving#870]
/kind bug

**What steps did you take and what happened:**
My kubeflow and kfserving are installed in k8s, I tried the solution of the issue [https://github.com/kubeflow/kfserving/issues/668](https://github.com/kubeflow/kfserving/blob/master/docs/samples/istio-dex/README.md), but my Inferenceservice is still 'Unknown' with 'IngressNotConfigured', is there anything missed?

**What did you expect to happen:**
I expect the inferenceservice status is 'Ready'.

**Anything else you would like to add:**
the inferenceservice revision and configuration are ready, but the route and the service is not ready.
Here is ![inferenceservice related status snapshot](https://github.com/songm28/error-snapshots/blob/master/kubeflow-kfserving-ingressnotconfigured.png)

Here is the ![network-istio log snapshot](https://github.com/songm28/error-snapshots/blob/master/network-istio.png)

And here is the ![snapshot of the inferenceservice related virtualservice](https://github.com/songm28/error-snapshots/blob/master/kubeflow-kfserving-vs.png)
Does is error is complain the virtualservice owner Ingress is missed? actully, there is not the specified Ingress in the same namespace or knative-serving or istio namespace, if the answer is YES, which component should create the ingress?

**Environment:**

- Istio Version:
- Knative Version: v0.11.1
- KFServing Version: 0.2.2
- Kubeflow version: 1.0.2
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@songm28 do not deploy the inference service in kubeflow namespace ! we have a warning here 
https://github.com/kubeflow/kfserving/#kfserving-in-kubeflow-installation

**Comment by songm28** [comment]
@yuzisun Okay, Let me create the inference service in other test namespace.

**Comment by yuzisun** [comment]
@songm28 oh maybe you are deploying a custom inference service, looks like your pod is actually up running. The out of the box inference services like sklearn does not work in kubeflow namespace because it needs to go through the kfserving pod mutator to inject a storage initializer. The picture you sent for the networking istio log looks like is truncating the error stack, I can not see the entire error message.

**Comment by songm28** [comment]
@yuzisun the inference service is a very simple sample here: https://github.com/kubeflow/kfserving/tree/master/docs/samples/custom/hello-world.
I had deployed the inference service in my test namespace, everything seems to be the same. the above snapshots are updated.

**Comment by yuzisun** [comment]
@songm28 I am not sure why it is getting 404 when probing `http://kfserving-hello-world-predictor-default.test.svc:80` , can you test if that endpoint works in cluster?

**Comment by songm28** [comment]
@yuzisun I test the link in the k8s pods in another namespace, it did not work. 
The network between the pods are ok as I tested a normal service and deployment. Please checkout the ![snapshot](https://github.com/songm28/error-snapshots/blob/master/svc-network.png)

**Comment by yuzisun** [comment]
@songm28 it won't work outside the kube cluster, this is the cluster local service host so you would need to `kubectl exec` into some of the pods(like istio ingress gateway pods) and then test this url.

**Comment by yuzisun** [comment]
btw, do you have istio cluster local gateway installed?

**Comment by songm28** [comment]
> @songm28 it won't work outside the kube cluster, this is the cluster local service host so you would need to `kubectl exec` into some of the pods(like istio ingress gateway pods) and then test this url.

yes, the test is done when I 'kubectl exec' into another pod in namespace testB.
it seems that the knative code build out the service endpoint not complete, it should be `kfserving-hello-world-predictor-default.test.svc.cluster.local` rather than `kfserving-hello-world-predictor-default.test.svc` as the host.
and from the test output, it seems once the endpoint is reachable, there will be another error about revision '' not found, but the revision name is blank we get in the knative code, is there anything missing in the k8s made the revision name get as blank?

In my understanding, with knative 1.0.2, we used the kfserving-ingressgateway instead of istio cluster local gateway, is it?
Here is my **SVC** for gateway in istio:
istio-egressgateway        ClusterIP      10.43.62.130    <none>         80/TCP,443/TCP                                                                                                                                                                            425d
istio-ingressgateway       LoadBalancer   10.43.231.163   x.x.x.x   80:31380/TCP,443:31390/TCP,31400:31400/TCP,15011:31700/TCP,8060:31068/TCP,853:30088/TCP,15030:32450/TCP,15031:31272/TCP                                                                   425d
kfserving-ingressgateway   LoadBalancer   10.43.139.50    x.x.x.x    15020:30527/TCP,80:32380/TCP,443:32390/TCP,31400:32400/TCP,15011:31650/TCP,8060:32718/TCP,853:31119/TCP,15029:30047/TCP,15030:31542/TCP,15031:31164/TCP,15032:32014/TCP,15443:32125/TCP   19h

Here is my **gateway** in **istio**:
kubectl -n istio get gateway
NAME                              AGE
istio-autogenerated-k8s-ingress   1y

Here is my **gateway** in **knative-serving** namespace:
kubectl -n knative-serving get gateway
NAME                      AGE
cluster-local-gateway     48d
knative-ingress-gateway   19h

and one more thing, my k8s version is below 1.15, will it make knative and kfserving not work?

**Comment by yuzisun** [comment]
@songm28 oh I see, we have deprecated `kfserving-ingressgateway` since it exposes the servics publicly. If you try the kubeflow manifests on master it should work with `istio-ingressgateway`, we are releasing kubeflow 1.1 soon.

**Comment by songm28** [comment]
@yuzisun ok, I will try after the kubeflow 1.1 released.

**Comment by yuzisun** [comment]
consolidate to https://github.com/kubeflow/kfserving/issues/798
/close
