### ISSUE TITLE
KFServing on Kubeflow with Istio-Dex - Access Denied

### ISSUE THREAD

**Issue by mumarniaz** [kubeflow/kfserving#874]
/kind bug

**What steps did you take and what happened:**
I'm following [this](https://github.com/kubeflow/kfserving/tree/master/docs/samples/istio-dex) sample to send a prediction request to the InferenceService in an Istio-Dex environment. I have followed steps as mentioned in the readme of the sample but in response of my curl request instead of getting prediction result, i'm getting `Access Denied` error.

**What did you expect to happen:**
It should return the prediction result

**Anything else you would like to add:**
I'm able to get the session token by following the method explain in the sample but when i make the curl request to my inference, i got error. I have deployed my inference service in admin namespace with injection enabled. My inference service is working fine and pods are up. Only issue is i'm unable to make it work with curl.

**Environment:**

- Istio Version:
- Knative Version: 0.11.2
- KFServing Version: 0.2.2
- Kubeflow version: It is using the menifest pointed to master as describe in the sample readme
- Kfdef: [kfctl_istio_dex.v1.0.2.yaml](https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.2.yaml)

**Comment by yuzisun** [comment]
@sachua Can you help @mukulikak ? thanks!

**Comment by sachua** [comment]
@mumarniaz can you try using the master branch of the kfdef? v1.0.2 does not have the istio probe fix

**Comment by sachua** [comment]
I think you would have to disable sidecar injection also since the istio rbac rules will block it

**Comment by mumarniaz** [comment]
@sachua I'm using the master branch for the kfdef as mentioned in the sample read me.

**Comment by talhairfanbentley** [comment]
I'm having the same issues, is there any fix or a workaround?
Followed the doc [here](https://github.com/kubeflow/kfserving/tree/master/docs/samples/istio-dex).
@sachua

**Comment by SachinVarghese** [comment]
@mumarniaz @talhairfanbentley Have you guys tried getting the session cookie from the browser to make a prediction using curl? This test can confirm if there is an issue with the OAuth authorization code flow on the command line.

**Comment by mumarniaz** [comment]
@SachinVarghese Yes i have used the session token both from cmd as well as from browser but still i  got the same `RBAC: Access denied` error.

**Comment by SachinVarghese** [comment]
@mumarniaz Okay `RBAC: Access denied` error seems to be from Istio RBAC rules or [policies](https://istio.io/latest/docs/reference/config/security/authorization-policy/) set up on your cluster as @sachua mentioned. You could list these Istio auth custom resources in all relevant namespaces and check if any of the existing policies deny your prediction request. Would be good to know if this is an issue with the latest kubeflow installation

**Comment by yuzisun** [comment]
@mumarniaz Can you help try the following to see if this fixes it ? 
`kubectl edit clusterrbacconfig default` and exclude `knative-serving`

**Comment by mumarniaz** [comment]
@yuzisun I have added the `knative-serving` in exclusion list but still getting the same error : `RBAC: Access denied`
![image](https://user-images.githubusercontent.com/23311468/84627787-f09e7a00-af00-11ea-9d5c-2085af49dabc.png)


![image](https://user-images.githubusercontent.com/23311468/84627878-1d529180-af01-11ea-85c6-765eb4e43bcf.png)

**Comment by yuzisun** [comment]
@mumarniaz Can you turn off istio rbac `mode: OFF` to verify if 403 is actually from Istio RBAC check? If it is from istio RBAC you can refer to [this slide](https://www.slideshare.net/mt165/debugging-an-rbac-problem-in-istio) to debug where it is blocking it.

**Comment by mumarniaz** [comment]
@yuzisun Turning istio RBAC mode `OFF` make it work. Now the curl request is returning prediction result instead of `RBAC: Access denied` error

**Comment by yuzisun** [comment]
@mumarniaz looks you already turned off sidecar for the inference service, wondering where else is possibly checking the rbac.

**Comment by mumarniaz** [comment]
@yuzisun You are right. Istio injection is disabled in my namespace where inference pod is running. But still if i disable the RBAC mode off it works fine but when i turn it on, i got the RBAC issue. Any pointers where else this RBAC check is happening ?

**Comment by SachinVarghese** [comment]
@mumarniaz In this case, it is possible that RBAC check could be happening at the Istio gateway service workload. All the predict requests are routed through that load-balancer service created by the `istio-ingressgateway` in `istio-system` namespace.

**Comment by yuzisun** [comment]
@mumarniaz I think kubeflow has `istio-system` whitelisted for the rbac check, is that correct?

**Comment by SachinVarghese** [comment]
Hey, @yuzisun I think it is meant to be whitelisted as mentioned in the comment [here](https://github.com/kubeflow/manifests/blob/master/istio/istio/base/kf-istio-resources.yaml#L113), but as per the [KfDef](https://github.com/kubeflow/manifests/blob/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.2.yaml#L45) used in this case, the ClusterRbacConfig mode is set to `ON`.

As per the istio auth [doc](https://archive.istio.io/v1.3/docs/concepts/security/#enabling-authorization), we should probably set it to `ON_WITH_EXCLUSION`  to exclude rbac check on `istio-system` namespace. What are your thoughts?

**Comment by yuzisun** [comment]
@SachinVarghese that seems like a bug to me
