### ISSUE TITLE
Support MXNet

### ISSUE THREAD

**Issue by ianhellstrom** [kubeflow/kfserving#883]
/kind feature

**Support MXNet in KFServing**
Since Kubeflow has an [MXNet operator](https://www.kubeflow.org/docs/components/training/mxnet/), it would be great if MXNet models could also be served with KFServing, as otherwise there is little use for it except in research.

**Comment by yuzisun** [comment]
I believe MXNet is deprecated at this point and joins the pytorch community.. so we do not have plan to support and maintain MXNet, you can always build custom model server to serve MXNet model, thanks.

**Comment by ianhellstrom** [comment]
@yuzisun Do you have a link to the deprecation notice because MXNet looks alive: https://github.com/apache/incubator-mxnet

Some APIs (Symbol, Model) have been deprecated.
