### ISSUE TITLE
SDK can't create and watch inferenceservice at the same time

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfserving#884]
/kind bug

**What steps did you take and what happened:**
Running the below python SDK code to create and watch the inferenceservice occasionally have race condition on getting the status.
```python
KFServing.create(isvc, watch=True, timeout_seconds=120)
```

```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-4-06b315a74aac> in <module>
      1 KFServing = KFServingClient()
----> 2 KFServing.create(isvc, watch=True, timeout_seconds=120)

~/.local/lib/python3.6/site-packages/kfserving/api/kf_serving_client.py in create(self, inferenceservice, namespace, watch, timeout_seconds)
    114                 name=outputs['metadata']['name'],
    115                 namespace=namespace,
--> 116                 timeout_seconds=timeout_seconds)
    117         else:
    118             return outputs

~/.local/lib/python3.6/site-packages/kfserving/api/kf_serving_watch.py in watch(name, namespace, timeout_seconds)
     46             continue
     47         else:
---> 48             url = isvc['status'].get('url', '')
     49             default_traffic = isvc['status'].get('traffic', '')
     50             canary_traffic = isvc['status'].get('canaryTraffic', '')

KeyError: 'status'
```
**What did you expect to happen:**
it should watch the inferenceservice without error out on race condition.

**Anything else you would like to add:**
This error happens way more often on kfserving SDK 0.3.0+

**Environment:**

- Istio Version: 1.1.6
- Knative Version: 1.11.2
- KFServing Version: 0.3.0
- Kubeflow version: 1.0.2
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`): 1.15
- OS (e.g. from `/etc/os-release`):

**Comment by jinchihe** [comment]
/assign

I will take a look asap. Thanks.

**Comment by jinchihe** [comment]
I did not reproduce the problem. But I think this is caused by env issue such as machine is slow so that the `status` of isvc is not generated. We can enhance here to ensure the status section is generated and then go on. Thanks.
