### ISSUE TITLE
Use klog for kfserving

### ISSUE THREAD

**Issue by gyliu513** [kubeflow/kfserving#89]
/kind feature

Describe the solution you'd like
[A clear and concise description of what you want to happen.]

Use the permanent forked version of glog for kubernetes instead of log.

ref:
kubernetes/kubernetes#70264
https://github.com/kubernetes/klog/blob/master/README.md

Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/cc @ellis-bigelow

**Comment by ellis-bigelow** [comment]
Do we know other projects have done this migration already?

**Comment by gyliu513** [comment]
I was working for katib at https://github.com/kubeflow/katib/issues/506 . Besides, most of the Kubernetes projects are using `klog`, and it is better for kfserving migrate to this as well.

**Comment by ellis-bigelow** [comment]
SGTM!
