### ISSUE TITLE
Scale to Zero example

### ISSUE THREAD

**Issue by Sliceco** [kubeflow/kfserving#898]
/kind feature

**Describe the solution you'd like**
An example of an InferenceService that scales to zero.

**Anything else you would like to add:**
I'm not sure the best way to do this. I was able to get an InferenceService to scale to zero but I had to manually set the minScale to 0 on the KPA and update the config-autoscaler to enable-scale-to-zero in order to do so. Is there a better way to do this?

**Comment by yuzisun** [comment]
@Tomcli Do we have an example to scaling to zero still? We change to [default to minReplica 1](https://github.com/kubeflow/kfserving/pull/655) since 0.3

**Comment by Tomcli** [comment]
The best way to scale from 0 for a particular inferenceservice is to set the minReplica field. We don't have a specific example for this but you can refer to the logger example for reference https://github.com/kubeflow/kfserving/blob/master/docs/samples/logger/basic/sklearn-logging.yaml#L8

**Comment by Sliceco** [comment]
Thank you - setting the minReplica field to 0 did scale to zero as expected

**Comment by larssuanet** [comment]
I found the SDK documentation to be a little bit confusing on the topic of minReplicas:

> Minimum number of replicas, pods won't scale down to 0 in case of no traffic

https://github.com/kubeflow/kfserving/blob/master/python/kfserving/docs/V1alpha2PredictorSpec.md#properties

But setting this to 0 does actually scale it down as expected.

**Comment by yuzisun** [comment]
@larssuanet we used to default to scale down to 0 in 0.2, since 0.3 we have changed to `minReplicas` 1. Thanks for pointing out the sdk doc issue, we have already updated the api doc [here](https://github.com/kubeflow/kfserving/tree/master/docs/apis#deploymentspec) and will regenerate the sdk doc.

**Comment by edenbuaa** [comment]
@yuzisun Can we set the inactivity time to scale down to 0 ?

**Comment by yuzisun** [comment]
> @yuzisun Can we set the inactivity time to scale down to 0 ?

Yes this should be configurable in knative https://knative.dev/docs/serving/autoscaling/scale-to-zero/#scale-to-zero-last-pod-retention-period

**Comment by yuzisun** [comment]
this is now documented in https://knative.dev/docs/serving/autoscaling/scale-to-zero/#scale-to-zero-last-pod-retention-period

**Comment by danielmhair** [comment]
The documentation is great, however, we are starting to ask this type of question, because if you have pods in your GPU node, how can it properly scale down even if we have knative configured right? For reference, see our question here in stackoverflow: https://stackoverflow.com/questions/66388294/how-do-we-assign-pods-properly-so-that-kfserving-can-scale-down-gpu-instances-to
