### ISSUE TITLE
Can anyone share an example of nginx sidecar implementation?

### ISSUE THREAD

**Issue by rtrobin** [kubeflow/kfserving#919]
I have a pre-build image which implements a custom REST API for prediction, _/custom-prediction_ for example. I want to put this image into Kfserving without changing code or image at all. I think I could put an nginx image which forward _/v1/models/custom-sample:predict_ to _/custom-prediction_ to make it work.

Can anyone share an example yaml file for my case? Thanks in advance.

**Comment by yuzisun** [comment]
@rtrobin Currently we only support Istio as ingress, we are working towards v1beta1 which is going to make istio optional.

**Comment by ellistarn** [comment]
@rtrobin, we also don't enforce the API. If you want to run your container as-is and call it at /custom-prediction, it should work just fine.

**Comment by rtrobin** [comment]
It is not a problem in v0.4 now. I'm closing the issue.

**Comment by HassanOuda** [comment]
@rtrobin how did you implement to use nginx in v0.4? Thanks

**Comment by rtrobin** [comment]
@HassanOuda KFServing v0.4 already supports custom prediction route. So for my case, nginx is not needed anymore. What's your case for using nginx?

**Comment by HassanOuda** [comment]
Our production environment uses an external F5 loadbalancer that links to our nginx in kubernetes. so only ingress resources with a dns recognized by our loadbalancer can be used to expose a service in kubernetes. So how would that work with KFServing that purely uses Istio? 

PS. I have Istio installed as part of the kubeflow installation and i created a nginx ingress resource that points the istio-ingressgateway:80 for path '/' on a specific DNS we created for our loadbalancer.
