### ISSUE TITLE
What if a pre-build custom image have more than one prediction APIs?

### ISSUE THREAD

**Issue by rtrobin** [kubeflow/kfserving#920]
I have a pre-build image which have more than one prediction APIs, _/prediction1_ and _/prediction2_ for example. I want to put this image into Kfserving which bind two prediction APIs with my custom APIs. 

Can anyone share an example for my case? Thanks in advance.

**Comment by Iamlovingit** [comment]
@rtrobin Hi, we just added this new feature. You can look at this [sample](https://github.com/kubeflow/kfserving/blob/master/docs/samples/custom/customized-urls/Readme.md).

**Comment by rtrobin** [comment]
Hi @Iamlovingit . Perfect! It is just what I expected. I will try it soon and give you feedback. 

Btw, I raised another [question](https://github.com/kubeflow/kfserving/issues/919) about custom url. I think the sample you mentioned in this post, should fix my problem too. Right?

**Comment by Iamlovingit** [comment]
@rtrobin yes, we relax the standard of url format, you can use your customized urls now.

**Comment by rtrobin** [comment]
@Iamlovingit I have tried your sample, but met some issues.

By running `kubectl get inferenceservice customized-sample`, it shows below. Which is not like the `http://customized-urls-sample.default.10.166.15.200.xip.io` in sample doc. Is the sample running on specific version? 

| NAME | URL | READY | DEFAULT | TRAFFIC | CANARY | TERAFFIC | AGE |
|  ----  | ----  |  ----  | ----  |  ----  | ----  |  ----  | ----  
| customized-sample | http://customized-sample.test-serving.example.com/v1/models/customized-sample | True | 100 | . | . | .  | 10m |

Also, running `curl http://customized-sample.test-serving.example.com/v1/models/customized-sample:predict` script, it shows `curl: (6) Could not resolve host: customized-sample.test-serving.example.com`.

**Comment by Iamlovingit** [comment]
It looks like you have not use the right version. You should update your code to latest, and build the KFServing, you can look at thsi [section](https://github.com/kubeflow/kfserving/blob/master/docs/DEVELOPER_GUIDE.md#deploy-kfserving-with-your-own-version).

**Comment by rtrobin** [comment]
@Iamlovingit Hi, do you know which version could support this sample case? We are using the [release version 0.3.0](https://github.com/kubeflow/kfserving/releases/tag/v0.3.0) right now. Do you know when to release next version? Or maybe which commit is about this feature? We could merge the commit in our build. Thanks.

**Comment by Iamlovingit** [comment]
The latest master branch is supoort this feature, you can pull the latest commit. Next week KFServing will cut the 0.4 release version. This feature will be included.

**Comment by rtrobin** [comment]
Thanks. I would wait to check it in next release.

**Comment by yuzisun** [comment]
/close
this feature is released in 0.4.
