### ISSUE TITLE
alibi's version is  incompatible in gcr.io/kfserving/alibi-explainer:v0.3.0

### ISSUE THREAD

**Issue by quanguachong** [kubeflow/kfserving#927]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I deploy kfserving v0.3.0 in my k8s cluster and run test [explanation/alibi/imagenet](https://github.com/kubeflow/kfserving/tree/v0.3.0/docs/samples/explanation/alibi/imagenet). After execute [test_imagenet.py](https://github.com/kubeflow/kfserving/blob/v0.3.0/docs/samples/explanation/alibi/imagenet/test_imagenet.py), I get response_code 500.

explainer server pod logs is:
```bash
[I 200707 20:36:08 __main__:116] Extra args: {'batch_size': 25}
[I 200707 20:36:08 storage:35] Copying contents of /mnt/models to local
[I 200707 20:36:08 __main__:125] Loading Alibi model
[I 200707 20:36:08 explainer:47] Predict URL set to imagenet-predictor-default.kfserving-test
[I 200707 20:36:08 kfserver:88] Registering model: imagenet
[I 200707 20:36:08 kfserver:77] Listening on port 8080
[I 200707 20:36:08 kfserver:79] Will fork 0 workers
[I 200707 20:36:08 process:126] Starting 32 processes
[I 200708 05:00:10 anchor_images:35] Calling explain on image of shape ((1, 299, 299, 3),)
[E 200708 05:00:13 web:1792] Uncaught exception POST /v1/models/imagenet:explain (127.0.0.1)
    HTTPServerRequest(protocol='http', host='imagenet-explainer-default.kfserving-test.svc.cluster.local', method='POST', uri='/v1/models/imagenet:explain', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 1701, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/kfserving/kfserving/handlers/http.py", line 61, in post
        response = model.explain(request)
      File "/alibiexplainer/alibiexplainer/explainer.py", line 74, in explain
        explanation = self.wrapper.explain(request["instances"])
      File "/alibiexplainer/alibiexplainer/anchor_images.py", line 45, in explain
        anchor_exp = self.anchors_image.explain(arr[0], **self.kwargs)
      File "/usr/local/lib/python3.7/site-packages/alibi/explainers/anchor_image.py", line 365, in explain
        self.instance_label = self.predictor(image[np.newaxis, ...])[0]
    AttributeError: 'AnchorImage' object has no attribute 'predictor'
[E 200708 05:00:13 web:2250] 500 POST /v1/models/imagenet:explain (127.0.0.1) 3161.48ms
```

**What did you expect to happen:**

Get correct result of explainer

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I found alibi verion is 0.3.3.dev0 in gcr.io/kfserving/alibi-explainer:v0.3.0.

In alibi-0.3.3.dev0, AnchorImage object has attribute predictor instead of predict_fn, while [kfserving alibi explainer use predict_fn](https://github.com/kubeflow/kfserving/blob/v0.3.0/python/alibiexplainer/alibiexplainer/anchor_images.py#L40).

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@quanguachong how did you install 0.3? Looks it is using the wrong image, should be using https://github.com/kubeflow/kfserving/blob/master/install/v0.3.0/kfserving.yaml#L6874

**Comment by quanguachong** [comment]
@yuzisun You're right, thank you. I install 0.3 with master's [./install/v0.3.0](https://github.com/kubeflow/kfserving/tree/master/install/v0.3.0) . As the version name is v0.3.0, I thought they are the same.

**Comment by quanguachong** [comment]
@yuzisun Thank you, you're right. I install kfserinvg with branch v0.3.0: https://github.com/kubeflow/kfserving/blob/v0.3.0/install/v0.3.0/kfserving.yaml#L6923 whose explainer image is not compatible with alibi-explainer-sample in branch v0.3.0: https://github.com/kubeflow/kfserving/tree/v0.3.0/python/alibiexplainer.
