### ISSUE TITLE
Make the Tensorflow serving version configurable

### ISSUE THREAD

**Issue by Svendegroote91** [kubeflow/kfserving#943]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Is it possible to make the Tensorflow Serving runtime version configurable? Now it defaults to 1.14 but a lot of models are in TensorFlow 2.0. Or is this feature already available?

I tried playing with the runtimeVersion variable by putting it to "2.1.0" but got the following error:
```admission webhook "inferenceservice.kfserving-webhook-server.validator" denied the request: Tensorflow RuntimeVersion must be one of 1.11.0, 1.11.0-gpu, 1.12.0, 1.12.0-gpu, 1.13.0, 1.13.0-gpu, 1.14.0, 1.14.0-gpu```
Is there a way to control the list of allowed images? I noticed this was recently removed by #917

**Comment by yuzisun** [comment]
@Svendegroote91 all the versions can be configured in inference service configmap https://github.com/kubeflow/kfserving/blob/master/install/v0.3.0/kfserving.yaml#L6900, you can add tensorflow 2.0 in the allowed version list and on the inference service yaml you can specify runtimeVersion field to use a specific version if you do not like the default one. Also as you can see the upcoming KFServing 0.4 release is no longer going to maintain this allowed version list so you can specify the version you want to use.

**Comment by Svendegroote91** [comment]
@yuzisun Awesome, thanks for clarifying. Closing the issue.
