### ISSUE TITLE
tensorflow.yaml created but inferenceservice not ready

### ISSUE THREAD

**Issue by zhou-harry** [kubeflow/kfserving#971]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I install kfserving with kubflow-1.0_kfctl-1.0.2 and run the sample of tensorflow.yaml and get :inferenceservice.serving.kubeflow.org/flowers-sample created but when I check the inferenceservice status I get:
kubectl get inferenceservice -A
NAMESPACE   NAME                 URL   READY   DEFAULT TRAFFIC   CANARY TRAFFIC   AGE
anonymous   flowers-sample                                                        29s

[root@Test ~]# kubectl describe inferenceservice flowers-sample -n anonymous
Name:         flowers-sample
Namespace:    anonymous
Labels:       <none>
Annotations:  API Version:  serving.kubeflow.org/v1alpha2
Kind:         InferenceService
Metadata:
  Creation Timestamp:  2020-07-25T03:07:23Z
  Generation:          1
  Resource Version:    156911
  Self Link:           /apis/serving.kubeflow.org/v1alpha2/namespaces/anonymous/inferenceservices/flowers-sample
  UID:                 05706bfc-b88d-4f01-9c22-3cd82eefaa0c
Spec:
  Default:
    Predictor:
      Tensorflow:
        Resources:
          Limits:
            Cpu:     1
            Memory:  2Gi
          Requests:
            Cpu:          1
            Memory:       2Gi
        Runtime Version:  1.14.0
        Storage Uri:      pvc://mnist-e2e-pvc/export
Status:
Events:  <none>

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: v1.1.6
- Knative Version: v0.11.1
- KFServing Version: 0.2.2
- Kubeflow version: 1.0
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by ofaz** [comment]
Hi @zhou-harry - have you had a look through the [debugging guide?](https://github.com/kubeflow/kfserving/blob/master/docs/KFSERVING_DEBUG_GUIDE.md) 

Is this the first `inferenceservice` being deployed in your installation (i.e. do you have other KFserving models coming up healthy?)
