### ISSUE TITLE
make deploy fails with  The CustomResourceDefinition "inferenceservices.serving.kubeflow.org" is invalid:

### ISSUE THREAD

**Issue by navneet1075** [kubeflow/kfserving#977]
/kind bug

**What steps did you take and what happened:**
1. installed the kf serving using the developer guide from this  location: [developer guide](https://github.com/kubeflow/kfserving/blob/master/docs/DEVELOPER_GUIDE.md)
[A clear and concise description of what the bug is.
while running the make deploy step i am getting below errors : 
 **The CustomResourceDefinition "inferenceservices.serving.kubeflow.org" is invalid:
 spec.validation.openAPIV3Schema.properties[status].properties[address].properties[url].$ref: Forbidden: $ref is not supported
 spec.validation.openAPIV3Schema.properties[status].properties[conditions].$ref: Forbidden: $ref is not supported**

**What did you expect to happen:**
crds properly getting installed. 

**Anything else you would like to add:**
I am using the certificate manager as recommended in the developer guide.

[Miscellaneous information that will assist in solving the issue.]
Full logs of the make deploy command :   

make deploy

/Users/i318056/go/bin/controller-gen "crd:maxDescLen=0" paths=./pkg/apis/... output:crd:dir=config/crd
/Users/i318056/go/bin/controller-gen rbac:roleName=kfserving-manager-role paths=./pkg/controller/inferenceservice/... output:rbac:artifacts:config=config/rbac
/Users/i318056/go/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths=./pkg/apis/serving/v1alpha2
#TODO Remove this until new controller-tools is released
perl -pi -e 's/storedVersions: null/storedVersions: []/g' config/crd/serving.kubeflow.org_inferenceservices.yaml
perl -pi -e 's/conditions: null/conditions: []/g' config/crd/serving.kubeflow.org_inferenceservices.yaml
perl -pi -e 's/Any/string/g' config/crd/serving.kubeflow.org_inferenceservices.yaml
# Remove the certmanager certificate if KFSERVING_ENABLE_SELF_SIGNED_CA is not false
cd config/default && if [ true != false ]; then \
kustomize edit remove resource certmanager/certificate.yaml; \
else kustomize edit add resource certmanager/certificate.yaml; fi;
kustomize build config/default | kubectl apply --validate=false -f -
BATCHER_IMG ?= batcher:latest
namespace/kfserving-system unchanged
role.rbac.authorization.k8s.io/leader-election-role unchanged
clusterrole.rbac.authorization.k8s.io/kfserving-manager-role configured
clusterrole.rbac.authorization.k8s.io/kfserving-proxy-role unchanged
rolebinding.rbac.authorization.k8s.io/leader-election-rolebinding unchanged
clusterrolebinding.rbac.authorization.k8s.io/kfserving-manager-rolebinding unchanged
clusterrolebinding.rbac.authorization.k8s.io/kfserving-proxy-rolebinding unchanged
configmap/inferenceservice-config unchanged
secret/kfserving-webhook-server-secret unchanged
service/kfserving-controller-manager-metrics-service unchanged
service/kfserving-controller-manager-service unchanged
service/kfserving-webhook-server-service unchanged
statefulset.apps/kfserving-controller-manager unchanged
certificate.cert-manager.io/serving-cert unchanged
issuer.cert-manager.io/selfsigned-issuer unchanged
mutatingwebhookconfiguration.admissionregistration.k8s.io/inferenceservice.serving.kubeflow.org configured
validatingwebhookconfiguration.admissionregistration.k8s.io/inferenceservice.serving.kubeflow.org configured
The CustomResourceDefinition "inferenceservices.serving.kubeflow.org" is invalid:
* spec.validation.openAPIV3Schema.properties[status].properties[address].properties[url].$ref: Forbidden: $ref is not supported
* spec.validation.openAPIV3Schema.properties[status].properties[conditions].$ref: Forbidden: $ref is not supported
make: *** [Makefile:47: deploy] Error 1

**Environment:**

- Istio Version: istio 1.6.5
- Knative Version: v0.16.0
- KFServing Version: latest master  (using the fork from the latest master)
- Kubeflow version: latest master (using the fork from the latest master)
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]

- Minikube version: Using docker for desktop version 2.3.0.3

- Kubernetes version: (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`): Mac os Catalina 10.15.6.

**Comment by yuzisun** [comment]
@navneet1075 you are likely having an older version of `controller-gen` binary under your $GOPATH/bin, delete that and rerun `make deploy` should solve the problem.

**Comment by navneet1075** [comment]
@yuzisun thanks a lot . it works fine after the update.
