### ISSUE TITLE
[Error] The kfserving image is missing

### ISSUE THREAD

**Issue by edenbuaa** [kubeflow/kfserving#984]
It's seems that the docker image `gcr.io/kfserving/batcher:v0.4.0` in v0.4.0 cloud not be found. Is it missing?
![image](https://user-images.githubusercontent.com/16248697/88993282-0da7d480-d318-11ea-988d-c3924918c8e7.png)

**Comment by yuzisun** [comment]
@edenbuaa yes there is a permission issue for publishing this new image https://github.com/kubeflow/kfserving/issues/975

**Comment by yuzisun** [comment]
consolidate to https://github.com/kubeflow/kfserving/issues/975

**Comment by edenbuaa** [comment]
@yuzisun Cloud we push this image to other docker hub (e.g docker.io ) temporarily?

**Comment by yuzisun** [comment]
@edenbuaa if you just want to try, you can change the config [here](https://github.com/kubeflow/kfserving/blob/master/config/configmap/inferenceservice.yaml#L80) to use the latest tag `gcr.io/kfserving/batcher:latest`

**Comment by edenbuaa** [comment]
@yuzisun  the `latest` tag seems also not found.
![image](https://user-images.githubusercontent.com/16248697/89138025-ba7a8f80-d56c-11ea-8a39-09472286e949.png)
