### ISSUE TITLE
[Failed] created revision failed

### ISSUE THREAD

**Issue by edenbuaa** [kubeflow/kfserving#993]
**Environment:**

- Istio Version: v1.3.6
- Knative Version: v0.15.0
- KFServing Version: v0.4.0
- Kubernetes version: (use `kubectl version`): 1.15.11
- OS (e.g. from `/etc/os-release`):

kfserving v0.4 report `revision failed` error when I try to deploy the sklearn inferenceservice demo
`
Message:  Revision "sklearn-iris-predictor-default-tclgg" failed with message: Unable to fecth image "10.10.47.1/myhub/sklearnserver:v0.4.0": failed to resolve image to digest: failed to fech image information: Get "https://10.10.47.1/v2/": dail tcp 10.10.47.1:443:  connect: connection refused.`

It seems a docker issue, but I can pull image on every node with `docker pull` .  
Could you help me to check it ? @yuzisun  thanks.

**Comment by Iamlovingit** [comment]
It looks like the knative [Skipping tag resolution](https://knative.dev/docs/serving/tag-resolution/), you can add your repo address

**Comment by edenbuaa** [comment]
It works. thanks @Iamlovingit
