### ISSUE TITLE
Flowers-sample still broken for KF 1.1 (including potential reason)

### ISSUE THREAD

**Issue by d123456temp** [kubeflow/kfserving#994]
/kind bug

**What steps did you take and what happened:**
Kubeflow in EKS installed using:
https://github.com/kubeflow/manifests/blob/v1.1-branch/kfdef/kfctl_istio_dex.yaml

flowers-sample deployed exactly as described here:
https://github.com/kubeflow/kfserving/tree/master/docs/samples/tensorflow

**What did you expect to happen:**
I would be able to use flowers-sample and kfserving in general

**Anything else you would like to add:**
Just after applying https://github.com/kubeflow/kfserving/tree/master/docs/samples/tensorflow

1. istioctl analyze
```
Error [IST0101] (VirtualService flowers-sample.default) Referenced gateway not found: "kubeflow-gateway.kubeflow"
Error [IST0101] (VirtualService flowers-sample.default) Referenced host not found: "cluster-local-gateway.istio-system.svc.cluster.local"
Info [IST0118] (Service flowers-sample-predictor-default-6dz95-private.default) Port name queue-metrics (port: 9090, targetPort: queue-metrics) doesn't follow the naming convention of Istio port.
Error: Analyzers found issues when analyzing namespace: default.
See https://istio.io/docs/reference/config/analysis for more information about causes and resolutions.
```

2. Broken virtualservice configuration - notice the section "gateways: - kubeflow-gateway.kubeflow" shouldn't it be "gateways: - kubeflow/kubeflow-gateway" ???

```
kubectl get virtualservices flowers-sample -o yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"serving.kubeflow.org/v1alpha2","kind":"InferenceService","metadata":{"annotations":{},"name":"flowers-sample","namespace":"default"},"spec":{"default":{"predictor":{"tensorflow":{"storageUri":"gs://kfserving-samples/models/tensorflow/flowers"}}}}}
  creationTimestamp: "2020-08-04T15:31:34Z"
  generation: 1
  name: flowers-sample
  namespace: default
  ownerReferences:
  - apiVersion: serving.kubeflow.org/v1alpha2
    blockOwnerDeletion: true
    controller: true
    kind: InferenceService
    name: flowers-sample
    uid: 9a2208ed-4c9c-4763-8467-d1f747577acf
  resourceVersion: "62233107"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/default/virtualservices/flowers-sample
  uid: 3ea1c2e6-0bef-4d79-910e-f26d2642d3b2
spec:
  gateways:
  - kubeflow-gateway.kubeflow
  - knative-serving/cluster-local-gateway
  hosts:
  - flowers-sample.default.example.com
  - flowers-sample.default.svc.cluster.local
  http:
  - match:
    - authority:
        regex: ^flowers-sample\.default\.example\.com(?::\d{1,5})?$
      gateways:
      - kubeflow-gateway.kubeflow
      uri:
        prefix: /v1/models/flowers-sample:predict
    - authority:
        regex: ^flowers-sample\.default(\.svc(\.cluster\.local)?)?(?::\d{1,5})?$
      gateways:
      - knative-serving/cluster-local-gateway
      uri:
        prefix: /v1/models/flowers-sample:predict
    retries:
      attempts: 3
      perTryTimeout: 600s
    route:
    - destination:
        host: cluster-local-gateway.istio-system.svc.cluster.local
        port:
          number: 80
      headers:
        request:
          set:
            Host: flowers-sample-predictor-default.default.svc.cluster.local
      weight: 100
```

3. How can I modify the virtualservice descriptor? I wanted to change the gateway section so tried to dump vs yaml and then apply it after modification:

```
kubectl get virtualservices flowers-sample -o yaml /tmp/x.yaml
(modify gateway)
kubectl apply -f /tmp/x.yaml
```

4. Side note, getting 404 (I guess as expected taking into consideration missconfiguration above):

```
curl -v -H "Host:flowers-sample.default.example.com" http://cluster-local-gateway.istio-system.svc.cluster.local/v1/models/flowers-sample
> GET /v1/models/flowers-sample HTTP/1.1
> User-Agent: curl/7.35.0
> Accept: */*
> Host:flowers-sample.default.example.com
> 
< HTTP/1.1 404 Not Found
< date: Tue, 04 Aug 2020 14:06:34 GMT
< server: envoy
< content-length: 0
< x-envoy-upstream-service-time: 0

```

But my changes are ignored and "kubectl get virtualservices flowers-sample -o yaml" still returns "old" version.

**Environment:**

Default unaltered KF 1.1 installation

- Istio Version: 1.3 (KF 1.1 default)
- Knative Version: 0.11.2
- KFServing Version: 0.3.0
- Kubeflow version: 1.1
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`): 17 (v1.17.6-eks)
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@d123456temp the gateway is not an issue, the problem is with your host header is the curl command
you are using the local gateway so the host header should be `flowers-sample.default.svc.cluster.local`

**Comment by d123456temp** [comment]
@yuzisun I've tried already other combinations of host/gateway pairs, including flowers-sample.default.svc.cluster.local to no avail. Changing to flowers-sample.default.svc.cluster.local did not help:

```
curl -v -H "Host:flowers-sample.default.svc.cluster.local" http://cluster-local-gateway.istio-system.svc.cluster.local/v1/models/flowers-sample
> GET /v1/models/flowers-sample HTTP/1.1
> User-Agent: curl/7.35.0
> Accept: */*
> Host:flowers-sample.default.svc.cluster.local
> 
< HTTP/1.1 404 Not Found
< date: Tue, 04 Aug 2020 21:57:01 GMT
< server: envoy
< content-length: 0
< x-envoy-upstream-service-time: 0
```

Besides, what about istioctl analyze output above?

NOTE that "istioctl analyze" does not report error for the "flowers-sample-predictor-default" vs which uses "kubeflow/kubeflow-gateway" in it's gateway section...:
```
kubectl get vs --all-namespaces
NAMESPACE   NAME                                    GATEWAYS                                                            HOSTS                                                                                                                                                                                                     AGE
auth        dex                                     [kubeflow/kubeflow-gateway]                                         [*]                                                                                                                                                                                                       8h
default     flowers-sample                          [kubeflow-gateway.kubeflow knative-serving/cluster-local-gateway]   [flowers-sample.default.example.com flowers-sample.default.svc.cluster.local]                                                                                                                             6h29m
default     flowers-sample-predictor-default        [knative-serving/cluster-local-gateway kubeflow/kubeflow-gateway]   [flowers-sample-predictor-default.default flowers-sample-predictor-default.default.example.com flowers-sample-predictor-default.default.svc flowers-sample-predictor-default.default.svc.cluster.local]   8h                                      
default     flowers-sample-predictor-default-mesh   [mesh]                                                              [flowers-sample-predictor-default.default flowers-sample-predictor-default.default.svc flowers-sample-predictor-default.default.svc.cluster.local]                                                        8h                                      
kubeflow    argo-ui                                 [kubeflow-gateway]                                                  [*]                                                                                                                                                                                                       8h                                      
kubeflow    centraldashboard                        [kubeflow-gateway]                                                  [*]                                                                                                                                                                                                       8h                                      
kubeflow    google-api-vs                                                                                               [www.googleapis.com]                                                                                                                                                                                      8h                                      
kubeflow    google-storage-api-vs                                                                                       [storage.googleapis.com]                                                                                                                                                                                  8h                                      
kubeflow    grafana-vs                              [kubeflow-gateway]                                                  [*]                                                                                                                                                                                                       8h                                      
kubeflow    jupyter-web-app                         [kubeflow-gateway]                                                  [*]                                                                                                                                                                                                       8h                                      
kubeflow    katib-ui                                [kubeflow-gateway]                                                  [*]                                                                                                                                                                                                       8h                                      
kubeflow    kfam                                    [kubeflow-gateway]                                                  [*]                                                                                                                                                                                                       8h                                      
kubeflow    metadata-grpc                           [kubeflow-gateway]                                                  [*]                                                                                                                                                                                                       8h                                      
kubeflow    metadata-ui                             [kubeflow-gateway]                                                  [*]                                                                                                                                                                                                       8h                                      
kubeflow    ml-pipeline-tensorboard-ui              [kubeflow-gateway]                                                  [*]                                                                                                                                                                                                       8h                                      
kubeflow    ml-pipeline-ui                          [kubeflow-gateway]                                                  [*]                                                                                                                                                                                                       8h                                      
kubeflow    tensorboard                             [kubeflow-gateway]                                                  [*]                                                                                                                                                                                                       8h  
```

**Comment by yuzisun** [comment]
@d123456temp your command should really be
`curl -v -H "Host:flowers-sample.default.svc.cluster.local" http://cluster-local-gateway.istio-system.svc.cluster.local` as we are not doing path based routing. Also this is unnecessary you could directly do `curl flowers-sample.default.svc.cluster.local`

**Comment by yuzisun** [comment]
@d123456temp if you do `curl -v flowers-sample.default.svc.cluster.local/v1/models/flowers-sample` that should work, actually in theory your way should work too but looks like it does not work the same way as ingress gateway.

**Comment by d123456temp** [comment]
@yuzisun thank you for your answer. Unfortunately none of your suggestions work and I actually tested all of them before posting. What works for me is querying the flowers-sample-predictor virtualservice directly. This is true for other example, sklearn, too. From my point of view it looks like the main inference services like flowers-sample vs has issues with the default KF installation. The only difference I can see in configs is suspiciously looking gateway declaration as mentioned above.

**Comment by yuzisun** [comment]
@d123456temp sorry I missed your istioctl analyze output, this error looks like the root cause
`Error [IST0101] (VirtualService flowers-sample.default) Referenced host not found: "cluster-local-gateway.istio-system.svc.cluster.local"
`

**Comment by d123456temp** [comment]
Yest it does exist:

```
kubectl get services --all-namespaces | grep local-gateway
default                flowers-sample                                   ExternalName   <none>           cluster-local-gateway.istio-system.svc.cluster.local   <none>                                                                                                                                       2d17h
default                flowers-sample-predictor-default                 ExternalName   <none>           cluster-local-gateway.istio-system.svc.cluster.local   <none>                                                                                                                                       2d17h
default                sklearn-iris                                     ExternalName   <none>           cluster-local-gateway.istio-system.svc.cluster.local   <none>                                                                                                                                       19h
default                sklearn-iris-predictor-default                   ExternalName   <none>           cluster-local-gateway.istio-system.svc.cluster.local   <none>                                                                                                                                       19h
istio-system           cluster-local-gateway                            ClusterIP      10.100.137.178   <none>                                                 80/TCP,443/TCP,31400/TCP,15011/TCP,8060/TCP,15029/TCP,15030/TCP,15031/TCP,15032/TCP
```

@yuzisun Can you please kindly answer my other related question: How can I modify existing virtual service in KF/KFServing setup? It looks like every time I try to edit  (kubectl edit sv....) my changes get somehow overriden/ignored. I spent significant amount of time looking for answer in Istio manuals etc but nothing came out. Is my change getting overriden by some hook and autogeneration or there is another proper way to edit vss?

**Comment by yuzisun** [comment]
@d123456temp Every time you make a manual change KFServing controller detects that and overwrite with the desired virtual service it thinks should be. All InferenceService sub resources are reconciled this way so you won't be able to change the underlying resources KFServing creates except the high level crd like InferenceService, this is how all the kubernetes custom resource controller works.

**Comment by yuzisun** [comment]
@d123456temp,  @adrian555 and I finally tracked down the issue, the problem is that the virtual service only matches for the verb `:predict`, so when you query the status endpoint `curl -v flowers-sample.default.svc.cluster.local/v1/models/flowers-sample` it does not work, but it does work if you try the actual predict endpoint. This issue was fixed in KFS 0.4 release while KF 1.1 installation installs KFS 0.3.

**Comment by d123456temp** [comment]
@yuzisun that's great news, thank you for investigating this. Will try to install KFS 0.4 on KF 1.1 - I hope there are no compatibility issues that you are aware of?

**Comment by yuzisun** [comment]
@d123456temp Looks like you are on Kubernetes 1.17, so I think no compatibility issue.

**Comment by d123456temp** [comment]
@yuzisun I can confirm that this is the case for 0.3.0 and your workaround works for 0.3.0. I could not upgrade the environment to 0.4.0 at this moment, but it's great this was adressed.

**Comment by jal06** [comment]
@yuzisun,
I see the same error as @d123456temp when executing istio analyze with kubeflow 1.2 (KFS 0.4)
`Error [IST0101] (VirtualService sklearn-iap.jal) Referenced gateway not found: "kubeflow-gateway.kubeflow"`

The gateway kubeflow-gateway exists in the namespace kubeflow
```
kubectl get gateway -n kubeflow 
NAME               AGE
kubeflow-gateway   2d23h
```

According the [istio documentation](https://istio.io/latest/docs/reference/config/networking/virtual-service/)

`gateways in other namespaces may be referred to by <gateway namespace>/<gateway name> .`

Maybe this could explain why we see the error message above  ?

**Comment by gringParis** [comment]
It's not only the flower sample that is broken. i tried with the sklearn iris example as well as custom models and it results in the same error:
Error [IST0101] (VirtualService sklearn-iris.kubeflow-staging) Referenced gateway not found: "kubeflow-gateway.kubeflow"

kubeflow-gateway.kubeflow is a legacy gatewayName format. 
most of the example on kfserving github of inference 
(for example https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/lightgbm, https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/xgboost,
https://github.com/kubeflow/kfserving/tree/master/docs/samples/istio-dex)

use this command to determine the service host to use to access the predtiction:
SERVICE_HOSTNAME=$(kubectl get inferenceservice xgboost-iris -o jsonpath='{.status.url}' | cut -d "/" -f 3)
where .status.url uses the kubeflow/kubeflow-gateway. 

If we are supposed to use the cluster-local-gateway, could you plz explain how we are supposed to use the prediction servic from outside the kubernetes cluster ?

Best regards
