### ISSUE TITLE
Access to inference service within cluster using cluster-local-gateway

### ISSUE THREAD

**Issue by decewei** [kubeflow/kfserving#995]
This is a question for accessing inference service within cluster. The kfaka example is great but we don't need that in between our services to inference service.

Is it correct if I access the service like this? "default" is the namespace. Example in curl call. It'd be great if we have some documentations on this. 

```shell
curl -H "Host: model-name-predictor-default.default.svc.cluster.local" \
http://cluster-local-gateway.istio-system.svc.cluster.local/v1/models/model-name:predict -v
```

**Comment by yuzisun** [comment]
@decewei you could directly call like this
```
curl http://model-name.default.svc.cluster.local/v1/models/model-name:predict
```

**Comment by decewei** [comment]
> @decewei you could directly call like this
> 
> ```
> curl http://model-name.default.svc.cluster.local/v1/models/model-name:predict
> ```

Thanks!
